### ISSUE TITLE
"This string has been translated in the past" is not helpful

### ISSUE THREAD

**Issue by okainov** [WeblateOrg/weblate#4084] opened 2020-06-23 20:34 UTC
**Describe the bug**
"This string has been translated in the past"... And what? Can you show me the translation from the past so I don't need to translate it again? Without this it's completely useless warning...

**To Reproduce**
1. Do whatever needed to get this warning "This string has been translated in the past"
2. Check the UI

**Expected behavior**
I expect to see the "translation from the past"

**Comment by nijel** [comment] 2020-06-24 07:55
You can see it in the history, but it could be indeed shown more prominently.

**Comment by 55abhilash** [comment] 2020-06-24 10:30
Can you assign this to me? I will send a PR shortly.

**Comment by nijel** [comment] 2020-06-24 11:14
Thanks, I've assigned you.

**Comment by 55abhilash** [comment] 2020-06-25 12:02
@okainov Can you tell me steps to reproduce the warning?

**Comment by okainov** [comment] 2020-06-25 12:45
@55abhilash  that's complicated :)

What I did:
- Translated some strings, do not commit
- Go to settings, put checkmark "Allow to edit base language"
- Everything apparently got reindexed and all the translations were lost, here you see this message

Maybe also "reset changes" on the repo tab would lead to the same effect...

**Comment by 55abhilash** [comment] 2020-06-26 09:44
I am unable to reproduce it with these steps.
@nijel When is this warning triggered? In my setup, the code in class TranslatedCheck : 
```
   def check_target_unit(self, sources, targets, unit):
        if unit.translated:
            return False
...
...
```
This always returns false in my case, because unit.translated is always True for me! Even though string is being translated for the first time.

@okainov : Did you reset or remove the translation from the VCS from outside weblate?

**Comment by nijel** [comment] 2020-06-26 12:40
The easiest way to trigger this should be:

* Have a component without push enabled
* Edit string which is currently not translated
* Go to repository maintenance, commit changes and once that is done, reset the repository to upstream

This way Weblate will have history that the string was translated, but the translation is gone from the repository.

**Comment by nijel** [comment] 2020-06-26 12:52
> Everything apparently got reindexed and all the translations were lost, here you see this message

This should be fixed by 75564435febc8d680143130977a51f09c7404d0a

**Comment by 55abhilash** [comment] 2020-06-29 11:57
Related issue: #4105

**Comment by 55abhilash** [comment] 2020-06-30 08:34
#4112

**Closed** 2020-07-03 08:34 UTC
Labels: enhancement
