### ISSUE TITLE
Allow mark 'review' for string of second languages in translate interface

### ISSUE THREAD

**Issue by yfdyh000** [WeblateOrg/weblate#1033] opened 2016-03-19 18:09 UTC
### Steps to reproduce
1. I am translating my language for a project.
2. I see a string of second language there is an incorrect translation.
### Expected behaviour
1. I can mark the translation to 'review' to alert this translation needs to be corrected.
### Actual behaviour
1. I can't seem to go to the string in the second language, it is just a translation text shown.
### Additional comments
1. I can not directly correct the translation because I just understand the meaning but are not familiar the wording with a second language.
2. I might be able to search in the second language and check 'reivew' for the translation. But this workflow is cumbersome and time-consuming, I don't like the current search interface, I feel like I did not understand the "Search type".
3. Perhaps this should support view a string in all languages, check (not checked by default) and mark these defective strings to 'reivew' with comment.
##

**Comment by nijel** [comment] 2017-07-19 14:36
Duplicate of #1509

Fixed in 7dff120dd58a39cb58c4b67d977045c80ba21344 (there is now link to edit secondary language).

**Closed by nijel** 2017-07-19 14:36 UTC
Labels: enhancement, undecided
