### ISSUE TITLE
Mobile interface is broken

### ISSUE THREAD

**Issue by Badiboy** [WeblateOrg/weblate#3832] opened 2020-05-07 18:15 UTC
**Describe the bug**
Up-right menu button is not clickable. So no chance to use anything in mobile interface

**To Reproduce**
1. Use incognito mode in mobile or desktop Crome
2. In desktop Chrome make the mobile-like proportions (see screenshot)
3. Try to click top-right button

**Screenshots**
![image](https://user-images.githubusercontent.com/5613421/81329891-e5596280-90a7-11ea-9e32-07feb5615d25.png)

**Server configuration and status**
Weblate 4.0.3 from pip on Ubuntu.
In DEBUG mode.

**Comment by nijel** [comment] 2020-05-07 18:34
Caused by regression in jQuery 3.5.0, the fix is already in master branch and will be released soon.

**Closed by nijel** 2020-05-07 18:34 UTC
Labels: bug
