### ISSUE TITLE
Commit not used when build fails

### ISSUE THREAD

**Issue by niccokunzmann** [WeblateOrg/weblate#12401] opened 2024-09-02 16:41 UTC
### Describe the issue

I use hosted Weblate with web hook and Weblate Org installed, the project is Open-Web-Calendar.

When the build failed, the source strings were not updated.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Configure a component so that source files automatically get pulled from the repository into weblate
2. Make the build fail
3. change the source file by adding a translation string
4. Go to weblate -> manage -> pull the repository
5. notice that the source language translation does not update

### Expected behavior

I expected the source string to update
I did not know that weblate checks the build status
However - this being a feature, it would be nice to have a message when I pulled the repository here:

Saying: The source repository contains build errors. Translations are not used unless the build errors are removed.

### Screenshots

![grafik](https://github.com/user-attachments/assets/092e1806-2821-46f3-81b6-9f92d2aecbc6)

### How do you run Weblate?

weblate.org service

### Additional context

- https://github.com/niccokunzmann/open-web-calendar/issues/458
- Search: https://docs.weblate.org/en/latest/search.html?q=failed+build&check_keywords=yes&area=default

**Comment by nijel** [comment] 2024-09-03 06:56
How is the build related to Weblate? Weblate just follows whatever is in the repository, it is not connected to your CI.

**Comment by niccokunzmann** [comment] 2024-09-03 09:57
Hi, I agree that I understood that. And what seemed to happen is what I described.

**Comment by nijel** [comment] 2024-09-04 09:24
Sorry, but I have no clue what happens when "Make the build fail" and how that is supposed to be related to Weblate. Most likely, this is a duplicate of #12365 and not related to whatever happens inside your build.

**Comment by nijel** [comment] 2024-09-04 09:25
Duplicate of #12365

**Closed by nijel** 2024-09-04 09:25 UTC
Labels: bug, duplicate

**Comment by niccokunzmann** [comment] 2024-09-04 13:29
Hm. I am not sure this is a duplicate of https://github.com/WeblateOrg/weblate/issues/12365. However, the timing of the fix roll-out could have matched exactly with me configuring the Weblate project: As soon as I corrected the build (green GitHub Actions), the string appeared in Weblate.

A testable "Make the build fail" would be the GitHub Action below.

```yaml
name: "build"

on: [push, pull_request]

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    steps:
    - run: true # switch this to false to make the build fail
```
