### ISSUE TITLE
Add possibility to revert all actions done by specific users

### ISSUE THREAD

**Issue by erciccione** [WeblateOrg/weblate#4951] opened 2020-12-01 10:50 UTC
**Is your feature request related to a problem? If so, please describe.**
There deosn't seem to be a way to revert the actions of users. I'm having issues with rogue users who are confirming and overwriting suggestions. They are also confirming legit translations, so simply rolling back would make us lose that work. The only reliable way to fix the problem would be to revert all the actions of some specific users, but that doesn't seem to be possible.

**Describe the solution you'd like**
Would be very useful to have the ability to revert all the actions of a user.

**Comment by nijel** [comment] 2020-12-01 11:58
Duplicate of #3040

**Closed by nijel** 2020-12-01 11:58 UTC
Labels: enhancement, duplicate
