### ISSUE TITLE
Mercurial problems

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2722] opened 2019-05-02 11:04 UTC
**Describe the bug**
The rebase is not working properly in Mercurial, observed on Kallithea on the Hosted Weblate service.

The code already seems to be setting the correct settings in the .hgrc file like
phases.publish = False
experimental.evolution = all

In order to get correct rebase behavior, I think the commits Weblate
is making should remain in 'draft' phase. Then, when they are rebased,
the old ones will automatically be obsoleted thanks to the
experimental.evolution = all setting.

Could you perhaps check in the actual weblate repo (not in a clone or
something) what the state of commits is, e.g. via

hg log --template phases

Other things that could be checked:
- are the settings correctly written to the weblate repo's .hg/hgrc file?
- which version of Mercurial is used by Weblate, is it recent enough
to understand 'experimental.evolution=all' ?

For weblate projects where weblate has push rights to the project
repo, it would be normal that the commits in the weblate repo become
'public' at the time of the push.
But in the case of Kallithea, weblate cannot push to the project repo.
Is Weblate doing pushes to any other repo as part of its operation?
Like for backup, or other purposes?

**Comment by patrickdepinguin** [comment] 2019-05-04 19:03
I have another interesting observation. Today the situation on kallithea-stable was:

```
o  7768 e30036e623ba tip stable   2019-04-30 Allan Nordhøy i18n: updated translation for Norwegian Bokmål
|
o  7767 3e0455e2f68c stable   2019-04-29 Allan Nordhøy i18n: updated translation for Norwegian Bokmål
|
| o  7766 387badb5c19e stable   2019-04-30 Allan Nordhøy i18n: updated translation for Norwegian Bokmål
| |
o |  7765 7135fd2db7c9 stable   2019-04-30 Mads Kiilerich files: fix ignored navigation back to initial page
| |
o |  7764 b1e2ae0dd6e1 stable   2019-04-30 Mads Kiilerich files: drop extra history push on source pages that trapped the user without option for going back (Issue #343)
| |
o |  7763 6b7a0cd02857 stable   2019-04-30 Mads Kiilerich files: avoid duplicated "Select changeset" select2 controls on file source pages (Issue #343)
| |
o |  7762 fa2f02020cc8 stable   2019-04-30 Mads Kiilerich files: fix State typo after d66201a7ce6 (Issue #343)
| |
| o  7761 281ce0760944 stable   2019-04-29 Allan Nordhøy i18n: updated translation for Norwegian Bokmål
|/
o  7760 535f8d26ed31 stable   2019-04-17 Thomas De Schampheleire gists: fix typo in translatable string
|
```
so there were two commits for Norwegian on the tip of the branch, but also two commits for Norwegian with another base.

Because I wanted to rebase manually, I forced these 4 commits from public phase to draft phase, using:
```
hg phase -f -d 281ce0760944 387badb5c19e 3e0455e2f68c e30036e623ba
```
but automatically, the tree became:
```
o  7768 e30036e623ba tip stable   2019-04-30 Allan Nordhøy i18n: updated translation for Norwegian Bokmål
|
o  7767 3e0455e2f68c stable   2019-04-29 Allan Nordhøy i18n: updated translation for Norwegian Bokmål
|
o  7765 7135fd2db7c9 stable   2019-04-30 Mads Kiilerich files: fix ignored navigation back to initial page
```
The two Norwegian commits with the older base have disappeared, because they were already marked as predecessors for the commits on the newer base, thanks to rebase with the evolution setting enabled. I.e. the obsolescence markers are correctly exchanged between Weblate server and clients.

```
$ hg log -r 387badb5c19e -r 281ce0760944                
abort: hidden revision '387badb5c19e' was rewritten as: e30036e623ba!
(use --hidden to access hidden revisions)
$ hg log  -r 281ce0760944                               
abort: hidden revision '281ce0760944' was rewritten as: 3e0455e2f68c!
(use --hidden to access hidden revisions)
```

So, it seems to me that the only problem is that commits are marked 'public' in the weblate repository or when pulling from it. There are two possible problems:

1. The commits are already public on the weblate server. In this case there is something wrong during the operations weblate performs.
2. The commits are effectively draft on the weblate server, meaning the conversion to public happens when a client pulls. This would indicate that the setting 'phases.publish = False' is not set on the weblate server repository, or that the server software somehow ignores it.

**Comment by nijel** [comment] 2019-05-05 08:05
Bot `phases.publish = False` and `experimental.evolution = all` are set on the repository.

The commits seem to be marked as draft (on kallithea repo):

```console
$ hg outgoing --template phases 
comparing with https://kallithea-scm.org/repos/kallithea
searching for changes
changeset:   7580:d6e5cce0a292
phase:       draft
user:        Allan Nordhøy <epost@anotheragency.no>
date:        Wed Mar 13 00:35:45 2019 +0000
summary:     i18n: updated translation for Danish

changeset:   7581:e66dc7a3abeb
phase:       draft
user:        Allan Nordhøy <epost@anotheragency.no>
date:        Wed Mar 13 00:38:58 2019 +0000
summary:     i18n: updated translation for German

changeset:   7582:1b8f26dfad45
phase:       draft
user:        Allan Nordhøy <epost@anotheragency.no>
date:        Wed Mar 13 00:34:28 2019 +0000
summary:     i18n: updated translation for Norwegian Bokmål

changeset:   7585:ed2379c34bb1
phase:       draft
parent:      7583:927b7934b867
user:        Étienne Gilli <etienne.gilli@gmail.com>
date:        Mon Mar 18 16:19:27 2019 +0000
summary:     i18n: updated translation for French

changeset:   7596:2bff20c89328
phase:       draft
user:        Étienne Gilli <etienne.gilli@gmail.com>
date:        Tue Mar 19 08:20:36 2019 +0000
summary:     i18n: updated translation for French

```

**Comment by patrickdepinguin** [comment] 2019-05-05 08:17
How are the repositories served? Are you using hgweb, hg serve, or something else?

Could you confirm that if you clone the repository via its url, that you also see these draft commits turning to public phase, ie that the problem is not specific to me?

**Comment by nijel** [comment] 2019-05-05 09:30
It's using static http, that might be reason of the problems...

**Comment by patrickdepinguin** [comment] 2019-05-05 09:34
Perhaps as a test to confirm that hypothesis, you could serve the repository in another way, for example by running 'hg serve' in the repo itself, which would expose the repo on a TCP port (8000 by default, configurable with '-p PORT'). Then you can check if the cloning from that URL does preserve the draft attribute correctly.

**Comment by nijel** [comment] 2019-05-10 07:06
I've switched the server to use `hg serve` (something I had long in my todo list). Can you check if that improves the situation?

**Comment by patrickdepinguin** [comment] 2019-05-12 20:32
Yes, it looks like this is better!
I cloned the repo, both 'kallithea' as 'kallithea-stable', and in both cases I now see draft commits with translation updates. I think this will improve the situation a lot. I'll report back if there are remaining issues.

Partially related question: we now still have multiple heads on 'kallithea', probably caused by me squashing the commits before applying them. Is there a way for me to remove these heads via the weblate interface? There is a 'Reset' button that says "Reset all changes in the local repository" but it's unclear to me what it will do.

**Comment by nijel** [comment] 2019-05-13 05:08
It does:

```
hg update --clean remote(.)
hg strip roots(outgoing())
```

**Comment by nijel** [comment] 2019-06-18 14:14
Is there still something to address on this issue?

**Comment by patrickdepinguin** [comment] 2019-06-18 18:51
No, things seem fine. Thanks for your help!

**Closed** 2019-06-18 20:01 UTC
Labels: bug, hosted
