### ISSUE TITLE
CDATA does not export properly in Android strings file

### ISSUE THREAD

**Issue by eakkas** [WeblateOrg/weblate#1211] opened 2016-08-31 16:07 UTC
### Steps to reproduce
1. Import an XML file that contains CDATA
2. Translate in Weblate
3. Push translated files
### Actual behaviour

CDATA gets lost. See screenshot https://goo.gl/njjILy
### Expected behaviour

CDATA structure should match the source
### Server configuration

Please paste the output of command `./manage.py list_versions` over here
##

**Comment by nijel** [comment] 2016-09-02 09:12
This is something what needs to be handled at translate-toolkit level. Does this cause any real problems? AFAIK both ways should be valid in this case...

**Comment by nijel** [comment] 2017-07-19 14:03
Closing as there should not be any problems in using either of way. Please reopen if you see some.

**Closed by nijel** 2017-07-19 14:03 UTC
Labels: bug, translate-toolkit

**Comment by pstorch** [comment] 2021-04-17 11:13
I have a bigger string "About info" text of my app using a cdata section with line brakes and HTML tags. Weblate still removes the cdata section and puts everything in one long line. This is then hard to maintain in other text editors in source repository. 
Also HTML attributes like links get corrupted.

**Comment by nijel** [comment] 2021-04-17 13:51
HTML attributes get corrupted? Is this caused by Weblate or person doing the translation?

**Comment by pstorch** [comment] 2021-04-18 06:08
To explain a bit more, here some screenshots:

This is the source language string in the source file, as you can see it contains html + linebreaks:
![image](https://user-images.githubusercontent.com/5598124/115135891-3bef5080-a01c-11eb-9d42-07f414c6723b.png)

This is how it looks in weblate. No linebreaks anymore and the HTML is corrupted (quotes removed from `<a href` attribute):
![image](https://user-images.githubusercontent.com/5598124/115135942-a56f5f00-a01c-11eb-8113-a9ad91e8d902.png)

And finally the translation coming back from weblate viewed in the source file. All in one line, CDATA section removed, `<` and `>` escaped as needed and the quotes for the `href` attribute missing:

![image](https://user-images.githubusercontent.com/5598124/115136019-334b4a00-a01d-11eb-8519-e3529310e374.png)

**Comment by nijel** [comment] 2021-04-18 15:15
Okay, I've created https://github.com/translate/translate/issues/4320 to track this.
