### ISSUE TITLE
Show green-red diff on Automatic suggestions tab source strings

### ISSUE THREAD

**Issue by emmapeel2** [WeblateOrg/weblate#8641] opened 2023-01-20 10:08 UTC
### Describe the problem

When trying to use our translation memory to recover strings with small changes, the results from the 'Automatic tab' give a similarity percent, which is good:

![current cleaned](https://user-images.githubusercontent.com/11485015/213668790-5d606168-6634-4b44-aaf9-95ea392945e0.png)

### Describe the solution you'd like

But it will be even better if the source string showed the diff with the current source string, 
As it is done for example with the suggestions, although in this case it is done for the target string:

![suggestions-diff cleaned](https://user-images.githubusercontent.com/11485015/213669466-2061cf00-efb8-4f7c-b92a-fc6ef60d709f.png)

This will make the evaluation of the suggestion much quicker and easier to reuse.

**Comment by Geeyun-JY3** [comment] 2023-01-20 13:16
Duplicate of #4368

**Closed** 2023-01-20 13:51 UTC
Labels: enhancement, duplicate
