### ISSUE TITLE
Weblate should show the old context change for fuzzy strings (gettext)

### ISSUE THREAD

**Issue by alvinhochun** [WeblateOrg/weblate#6436] opened 2021-08-18 11:13 UTC
**Is your feature request related to a problem? If so, please describe.**

After updating PO files with `msgmerge --previous`, some translations may be copied from another message with a different context, e.g.:

```po
#: plugins/extensions/metadataeditor/kis_meta_data_editor.cc:95
#, fuzzy, kde-format
#| msgctxt "metadata editor page"
#| msgid "Dublin Core"
msgid "Dublin Core"
msgstr "都柏林核心"
```

Weblate does not show the difference in context on the UI:

![圖片](https://user-images.githubusercontent.com/2397650/129887747-24320737-74f4-4a24-823a-491bfbcdd981.png)

**Describe the solution you'd like**

Weblate should show the context change in some form.

This is what Lokalize does (not ideal, but it does the job):
![圖片](https://user-images.githubusercontent.com/2397650/129888143-29a24138-e216-46b3-b3cf-ee1cf5e4d94c.png)

**Describe alternatives you've considered**

None

**Comment by nijel** [comment] 2021-08-18 11:27
Duplicate of #1477

**Closed by nijel** 2021-08-18 11:27 UTC
Labels: enhancement, duplicate
