### ISSUE TITLE
Invalid PHP array

### ISSUE THREAD

**Issue by pc-jedi** [WeblateOrg/weblate#910] opened 2015-10-29 15:31 UTC
I'm using weblate 2.4 and try to configure it for my PHP language arrays.

This is the source file `en.php`

``` php
<?php
$lang = array(
'login'=>'Login',
'imprint'=>'Imprint',
'contact'=>'Contakt',
);
```

When I add a tranlation e.g. German, then I get the following `de.php`. The opening tag is missing and it is not valid php.

``` php
$lang->'login'='Login';
$lang->'imprint'='Impressum';
$lang->'contact'='Kontakt';
```

Did I miss something in the configuration?
##

**Comment by nijel** [comment] 2015-10-29 15:48
What version of translate-toolkit are you using? The PHP support is not always working there...

**Comment by pc-jedi** [comment] 2015-10-29 15:49
1.13.0
I'm using your docker script.

**Comment by pc-jedi** [comment] 2015-10-29 18:54
Is there a way I can help you figuring out where this issue comes from?

**Comment by nijel** [comment] 2015-11-03 06:58
It definitely comes from translate-tookit - it somehow doesn't deal with this style of file...

**Comment by pc-jedi** [comment] 2015-11-03 08:39
I tried to reprudce the error by manual using translation-toolkit according to this manual.
[php2po Example](http://docs.translatehouse.org/projects/translate-toolkit/en/stable-1.13.0/commands/php2po.html#examples)

en.php
```php
<?php
$lang = array(
'login'=>'Login',
'imprint'=>'Imprint',
'contact'=>'Contact',
);
```
Creating `template.pot` and create a copy of it:
```bash
php2po -P en.php template.pot
cp template.pot de.po
```

Filled `de.po` with german translations:
```po
#. extracted from en.php
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-11-03 09:20+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Translate Toolkit 1.13.0\n"

#: $lang->'login'
msgid "Login"
msgstr "Login"

#: $lang->'imprint'
msgid "Imprint"
msgstr "Impressum"

#: $lang->'contact'
msgid "Contakt"
msgstr "Kontakt"
```

Convert `de.po` to `de.php` with `en.php` as template:
```bash
po2php -t en.php de.po de.php
```

Result:
```php
<?php
$lang = array(
'login'=>'Login',
'imprint'=>'Impressum',
'contact'=>'Kontakt',
);
```

This way I get the expected result.
Hope this will help you.

**Comment by nijel** [comment] 2015-11-03 08:48
But the problem is once you start to change the file:

```php
<?php
$lang = array(
'login'=>'Login',
'imprint'=>'Imprint',
'contact'=>'Contact',
);
```

Do a simple modification:

```python
from translate.storage.php import phpfile
store = phpfile.parsefile('/tmp/en.php')
store.units[0].source = 'XXX'
store.save()
```

And you get:

```php
$lang->'login'='XXX';
$lang->'imprint'='Imprint';
$lang->'contact'='Contact';
```

The po2php script in translate-toolkit doesn't use at all the php storage, it just manually generates the PHP code.

**Comment by pc-jedi** [comment] 2015-11-03 09:29
I'm not so into python, but after looking to to documentation it seems to that `.save()` is the wrong function, because it does not use the input file as template.

The php2po and po2php command use the following function:
[php2po](https://github.com/translate/translate/blob/da1b437d05c5636d6142cc86a96dff73e017c0fd/translate/convert/php2po.py#L96-L112)
[po2php](https://github.com/translate/translate/blob/da1b437d05c5636d6142cc86a96dff73e017c0fd/translate/convert/po2php.py#L164-L177)

If I understand that right, the following should work.
```python
from translate.storage.php import phpfile
store = phpfile.parsefile('/tmp/en.php')
store.units[0].source = 'XXX'
convertor = rephp('/tmp/en.php', store)
outputphplines = convertor.convertstore(includefuzzy)
outputfile.writelines('/tmp/en.php')
```

**Comment by nijel** [comment] 2015-11-03 10:17
The ``.save()`` method works for all other formats, it's just the php format implementation in translate-toolkit which doesn't properly handle this. The code you've posted is for converting ``.po`` files to ``.php`` ones. It might be possible to use something like that as workaround, but it fails to work directly (it expect ``.po`` units as input, not the ones created by parsing ``.php`` file).

**Comment by pc-jedi** [comment] 2015-11-03 11:12
I experimented a bit with python and the following code worked perfectly for me.

```python
from translate.storage import php
from translate.convert import po2php, convert

# read file into store
inputstore = php.phpfile(open('en.php', 'rw'))

# modify first unit
inputstore. units[0].source = 'xxx'

convertor = po2php.rephp(open('en.php', 'r'), inputstore)

includefuzzy = False

# generate php
outputphplines = convertor.convertstore(includefuzzy)

# write file
open('de.php', 'w+').writelines(outputphplines)
```

**Comment by nijel** [comment] 2015-11-03 14:32
Thanks for testing, I've implemented workaround based on your code. Not sure why it has failed for me before...

**Comment by pc-jedi** [comment] 2015-11-08 17:53
I'm sorry, but now I had the change to test it.
And I found an issue. 
```python
with open(self.store.filename, 'r') as handle:
    convertor = po2php.rephp(handle, self.store)
```
`handle` had to be the the filehandle to the "Monolingual base language file", because this works as template.

**Comment by pc-jedi** [comment] 2015-11-09 09:09
Additional:
`rephp` will fill up missing translations with the source string. I don't know if weblate could handle this, but maybe it would be better to save the .PO files.
translate/translate#3366

**Comment by nijel** [comment] 2016-06-21 11:52
The workaround from @pc-jedi was confirmed here: https://github.com/nijel/weblate/issues/1149#issuecomment-225661891

**Comment by jekkos** [comment] 2016-09-14 15:55
So then the fix is to manually patch this php2po or po2php file? I'm facing similar issues and will give it a go (I do have these files stored in a docker container however)

**Comment by jekkos** [comment] 2016-09-15 14:22
Ok I fixed the issue as follows, adding an extra check for lookupkey value (see if it's not None). This seems to work so far.

```
root@a2af6408d946:/usr/local/lib/python2.7/dist-packages/translate/convert# cat po2php.py | sed -n 119,125p
                if lookupkey in self.inputstore.locationindex and self.inputstore.locationindex[lookupkey] is not None:
                    unit = self.inputstore.locationindex[lookupkey]
                    if ((unit.isfuzzy() and not self.includefuzzy) or
                        len(unit.target) == 0):
                        value = unit.source
                    else:
                        value = unit.target
```

**Comment by nijel** [comment] 2017-10-04 09:44
Should be fixed for real in https://github.com/translate/translate/pull/3697

**Closed by nijel** 2017-10-04 09:44 UTC
Labels: bug, translate-toolkit
