### ISSUE TITLE
License tag: "GNU General Public License 2 or later" (settings) is tagged as "GPL-2.0" in language list

### ISSUE THREAD

**Issue by buhtz** [WeblateOrg/weblate#12833] opened 2024-10-21 18:20 UTC
### Describe the issue

Project/component settings indicate "GNU General Public License 2 or later"
But in the list of existing languages, each is tagged with "GPL-2.0" which is wrong.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

See description of issue.

### Expected behavior

Minimal use a correct tag "GPL 2.0 or later".
Better use SPDX license identifiers only. In this case it would be "GPL-2.0-or-later"

Regarding SPDX a license like "GPL-2.0" does not exist. It is "GPL-2.0-only" or "GPL-2.0-or-later".

### Screenshots

![image](https://github.com/user-attachments/assets/45ed3d54-a5bb-4a2d-8542-44f95f5a0b4c)

### How do you run Weblate?

Other

### Weblate versions

It is Weblate 5.7.2 hosted on translate.codeberg.org.
Project is https://translate.codeberg.org/projects/backintime/common/

**Comment by nijel** [comment] 2024-10-22 05:56
Duplicate of #8789

**Closed by nijel** 2024-10-22 05:56 UTC
Labels: duplicate
