### ISSUE TITLE
String flag description does not link to documentation

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3486] opened 2020-02-16 13:35 UTC
I remember the flags as a dropdown list…?

Now it links to https://hosted.weblate.org/translate/remmina/remmina/nb_NO/?q=check:same#
(which is the same link for flags, labels and context)

![bilde](https://user-images.githubusercontent.com/13802408/74605547-51d84d00-50c9-11ea-86df-adffcff53394.png)

https://hosted.weblate.org/translate/weblate/master/en/?checksum=d60e03450101274f

**Comment by nijel** [comment] 2020-02-16 18:25
Duplicate of #1567

**Closed by nijel** 2020-02-16 18:25 UTC
Labels: enhancement, duplicate
