### ISSUE TITLE
Suggestable flags

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#9670] opened 2023-08-02 06:40 UTC
### Describe the problem

Not all users are mods, and not all mods know to use the flags.

### Describe the solution you'd like

Dropdown to suggest where the functionality is already, and/or text input ala "!s ignore-java-format"

### Describe alternatives you've considered

!s is maybe not the best idea as strings could start with "!s", but the idea was to have regular and flag suggestions available from the Zen editor.

I don't find the idea of a separate button to only suggest flags compelling.

_No response_

**Comment by nijel** [comment] 2023-08-02 06:47
Duplicate of #1567

**Closed by nijel** 2023-08-02 06:47 UTC
Labels: enhancement, duplicate
