### ISSUE TITLE
useless trailing whitespace on po files update (when pot changes)

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#3608] opened 2020-03-18 21:48 UTC
When weblate detect a POT update, it adds useless trailing whitespace.
There is no trailing whitespace when a translator does contribution a file.

Some project have strick coding style rules that prevents the inclusion of update commits.

Here is an example: https://github.com/linux-pam/linux-pam/issues/165

**Comment by nijel** [comment] 2020-03-19 11:45
Can you please clarify where the whitespace is being added? https://github.com/linux-pam/linux-pam/issues/165#issuecomment-600570151 seems to describe opposite case than you do.

It might be already addressed by https://github.com/translate/translate/pull/3947, but it's hard to guess until exact case where this happens is shown.

**Comment by ldv-alt** [comment] 2020-03-28 14:38
Trailing whitespace is added right in the header:

```
diff --git a/po/cs.po b/po/cs.po
index dd3d1e41..e2a05a0d 100644
--- a/po/cs.po
+++ b/po/cs.po
@@ -1,7 +1,7 @@
 # SOME DESCRIPTIVE TITLE.
 # Copyright (C) YEAR Linux-PAM Project
 # This file is distributed under the same license as the PACKAGE package.
-#
+# 
 # Translators:
 # Klara Cihlarova <koty@seznam.cz>, 2005, 2006.
 # <tmraz@fedoraproject.org>, 2011.
```

**Comment by nijel** [comment] 2020-03-28 19:40
Duplicate of https://github.com/translate/translate/pull/3947

**Closed by nijel** 2020-03-28 19:40 UTC
Labels: bug, duplicate
