### ISSUE TITLE
Search tool | Full accessibility needed in all interfaces

### ISSUE THREAD

**Issue by Ricky-Tigg** [WeblateOrg/weblate#5751] opened 2021-03-26 10:32 UTC
**Weblate version:** 4.5.1; **Organisation:** Fedora Weblate

**Description:** As noticeable, a "_Search_" option aimed to invoke the already existing search tool, is not present in the interface whose context is _All main projects are displayed for a given language_.

![weblate_4 5 1_one_language_all_main_projects](https://user-images.githubusercontent.com/26058215/112606041-9a138400-8e20-11eb-923b-4fce6319cab8.png)

If even needed, a common **use-case** such as the one that follows does illustrate alone the need to have full accessibility to a search tool:

_A string or term to be searched within a given language, exits or may exist inside several main projects._

**As a result of that non-accessibility:** 
- Searches covering all main projects for a given language are not enabled.
- Translators have to iterate their search as many times as there are main projects to search inside. Such a major restriction lowers instantaneously and dramatically the capacities of those who translate to operate efficiently on this translation platform.

**Expected:** 
Though the accessibility to that tool is enabled in the interface whose context is _A given main project is displayed for a given language_, despite the priority for its accessibility there has proven to be lower than the priority for its accessibility in the interface i depicted as context of this non-conventional issue.

![weblate_4 5 1_one_language_one_main_project](https://user-images.githubusercontent.com/26058215/112606265-d646e480-8e20-11eb-83c9-1e1340764b26.png)

**Comment by nijel** [comment] 2021-03-26 11:12
Duplicate of #3701

**Closed by nijel** 2021-03-26 11:12 UTC
Labels: enhancement, Area: UX, duplicate
