### ISSUE TITLE
"_QQ_"

### ISSUE THREAD

**Issue by emresaracoglu** [WeblateOrg/weblate#2047] opened 2018-05-24 22:52 UTC
Hello,

It adds `"_QQ_"` to the beginning and end of the translations.
What could be the reason for this?

Format type: INI file

Sample export:
```
FAVORIYEEKLE=""_QQ_"Favoriye Ekle"_QQ_""
HOME=""_QQ_"Anasayfa"_QQ_""
TUMKATEGORILER=""_QQ_"Tüm Kategoriler"_QQ_""
URUNLER=""_QQ_"Kategori"_QQ_""
```

**Comment by nijel** [comment] 2018-05-25 06:33
Duplicate of #1716

Was fixed in the translate-toolkit, see https://github.com/translate/translate/commit/c4f78dd93de0b6233be400b67701a7314119a314

**Closed by nijel** 2018-05-25 06:33 UTC
Labels: bug
