### ISSUE TITLE
InternalError "regular expression is too complex"

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#1834] opened 2018-02-07 17:55 UTC
During the translation work and suggestion processing, we experience a bug that blocks our work.

### Steps to reproduce
1. https://l10n.opensuse.org/translate/yast-iplb/master/cs/?type=suggestions
2. Edit suggestions (if you have permissions)

### Actual behaviour
504 error on every 2 or 3 strings

context | Error in formatting: DataError: invalid regular expression: regular expression is too complex
-- | --
request | <WSGIRequest: GET '/translate/yast-iplb/master/cs/?type=suggestions'>
status | None
template | u'translate.html'

### Expected behaviour
No errors.

### Server configuration
 * Weblate 2.18
 * Python 2.7.13
 * Django 1.11.8
 * six 1.9.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.1
 * Translate Toolkit 2.2.4
 * Whoosh 2.7.0
 * defusedxml 0.5.0
 * Git 2.13.6
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.6.1
 * django-crispy-forms 1.7.0
 * compressor 2.1.1
 * djangorestframework 3.7.3
 * pytz 2016.10
 * PyYAML 3.12
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by stanislav-brabec** [comment] 2018-02-07 18:10
Full backtrace was sent by e-mail.

**Comment by nijel** [comment] 2018-02-07 18:18
Duplicate of #1773

**Closed by nijel** 2018-02-07 18:18 UTC
Labels: bug
