### ISSUE TITLE
String status in all views

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3061] opened 2019-09-27 23:25 UTC
![bilde](https://user-images.githubusercontent.com/13802408/65807545-46729c80-e18f-11e9-9a2f-572d693adfcd.png)
**It is currently cumbersome to navigate to fuzzy strings for (especially) a whole project, because it means clicking every component.**

It would mean opening the editor of two or more components, (similar to editing helper-languages directly) but since Weblate doesn't load all strings at once, I don't think it would be that bad on ram. Unless maybe doing it (per language) for all projects on the instance, but that would be very useful.

**Comment by nijel** [comment] 2019-09-28 04:36
Duplicate of #49

**Closed by nijel** 2019-09-28 04:36 UTC
