### ISSUE TITLE
XLIFF file structure not preserved after new translations added

### ISSUE THREAD

**Issue by jcolladosp** [WeblateOrg/weblate#7652] opened 2022-05-17 10:30 UTC
### Describe the issue

Hi,
I have a weblate project with a component connected to a gitlab repository.
If I upload a source xlif file (messages.xlf) like the one below:
```xml
<?xml version="1.0" encoding="utf-8"?>
<xliff version="1.2"
	xmlns="urn:oasis:names:tc:xliff:document:1.2">
	<file original="/.a.ts" source-language="en" target-language="es" datatype="plaintext">
		<body>
			<trans-unit id="a">
				<source xml:lang="en">Hi</source>
			</trans-unit>
		</body>
	</file>
	<file original="./b.ts" source-language="en" target-language="es" datatype="plaintext">
		<body>
			<trans-unit id="b">
				<source xml:lang="en">Bye</source>
			</trans-unit>
		</body>
	</file>
</xliff>
```
And I apply the translations from weblate, I get the following correct output in messages_en.xlf:
```xml
<?xml version="1.0" encoding="utf-8"?>
<xliff version="1.2"
	xmlns="urn:oasis:names:tc:xliff:document:1.2">
	<file original="/.a.ts" source-language="en" target-language="es" datatype="plaintext">
		<body>
			<trans-unit id="a">
				<source xml:lang="en">Hi</source>
				<target state="translated">Hola</target>
			</trans-unit>
		</body>
	</file>
	<file original="./b.ts" source-language="en" target-language="es" datatype="plaintext">
		<body>
			<trans-unit id="b">
				<source xml:lang="en">Bye</source>
				<target state="translated">Adios</target>
			</trans-unit>
		</body>
	</file>
</xliff>

```

But If I add a new `<trans-unit>` in the second `<file>` node in the source xlf file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<xliff version="1.2"
	xmlns="urn:oasis:names:tc:xliff:document:1.2">
	<file original="/.a.ts" source-language="en" target-language="es" datatype="plaintext">
		<body>
			<trans-unit id="a">
				<source xml:lang="en">Hi</source>
			</trans-unit>
		</body>
	</file>
	<file original="./b.ts" source-language="en" target-language="es" datatype="plaintext">
		<body>
			<trans-unit id="b">
				<source xml:lang="en">Bye</source>
			</trans-unit>
			<trans-unit id="c">
				<source xml:lang="en">Thanks</source>
			</trans-unit>
		</body>
	</file>
</xliff>

```
When I apply the translation in weblate, that's the resulting xlf:

```xml
<?xml version="1.0" encoding="utf-8"?>
<xliff version="1.2"
	xmlns="urn:oasis:names:tc:xliff:document:1.2">
	<file original="/.a.ts" source-language="en" target-language="es" datatype="plaintext">
		<body>
			<trans-unit id="a">
				<source xml:lang="en">Hi</source>
				<target state="translated">Hola</target>
			</trans-unit>
			<trans-unit id="c">
				<source xml:lang="en">Thanks</source>
				<target state="translated">Gracias</target>
			</trans-unit>
		</body>
	</file>
	<file original="./b.ts" source-language="en" target-language="es" datatype="plaintext">
		<body>
			<trans-unit id="b">
				<source xml:lang="en">Bye</source>
				<target state="translated">Adios</target>
			</trans-unit>
		</body>
	</file>
</xliff>

```
As you can see, weblate does not respect the `<file>` where the trans-unit was located originally. 
I think it can be related with this issue: https://github.com/WeblateOrg/weblate/issues/4953

Thanks in advance

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Expected behavior

```xml
<?xml version="1.0" encoding="utf-8"?>
<xliff version="1.2"
	xmlns="urn:oasis:names:tc:xliff:document:1.2">
	<file original="/.a.ts" source-language="en" target-language="es" datatype="plaintext">
		<body>
			<trans-unit id="a">
				<source xml:lang="en">Hi</source>
				<target state="translated">Hola</target>
			</trans-unit>
		</body>
	</file>
	<file original="./b.ts" source-language="en" target-language="es" datatype="plaintext">
		<body>
			<trans-unit id="b">
				<source xml:lang="en">Bye</source>
				<target state="translated">Adios</target>
			</trans-unit>
			<trans-unit id="c">
				<source xml:lang="en">Thanks</source>
				<target state="translated">Gracias</target>
			</trans-unit>
		</body>
	</file>
</xliff>

```

### How do you run Weblate?

Other

### Weblate versions

Weblate 3.9.1

**Comment by nijel** [comment] 2022-05-17 10:36
Duplicate of #4953

**Closed by nijel** 2022-05-17 10:36 UTC
Labels: duplicate
