### ISSUE TITLE
De-listing flag

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#5510] opened 2021-02-23 22:33 UTC
With changelogs piling up and old ones often not included or worthwile to translate, it would be nice to flag them "delist" to remove them from the translation bars and tallies.

Isn't there something like that for read-only already?

I see two not-completed projects and I have to remember whether I translated the recent one, and also know whether a version has been released afterwards.
If it was all full if done and not-full if not done, I could spend more time translating current changelogs.

I thought about "current-changelog", but that is a bit iffy since there might be more versions released, and there are also short-desc and long-desc type strings in the same Fastlane components. Similar for SailfishOS.

**Comment by nijel** [comment] 2021-02-24 06:19
See https://docs.weblate.org/en/latest/formats.html#app-store-metadata-files and https://docs.weblate.org/en/latest/admin/addons.html#addon-weblate-flags-bulk for info how to skip certain strings from translation.

**Comment by comradekingu** [comment] 2021-02-24 06:45
So unless I am as stupid as I thought I was, that only describes "read-only"?

I actually want to allow translation, I just don't want those strings to count towards the totals (as if it was read-only). If I translate everything that isn't delisted, I want full bars.

So all of read-only, without the actual read-only.

Bonus for also applying a low priority: to any string that is flagged "delisted".

Other than metadata,

say you want to delete some of your strings. A part of the program got deprecated for example. Now instead of losing the translation memory of it, you can de-list those strings. It helps people look up translations, it helps populate new strings. All that good stuff.

None of the "throw new strings in with the old ones and have everyone translate everything", and especially no "lets have to identical components for two versions and forget to set up linking". Just de-list whatever isn't new, and everyone wins.

And I am somewhat thinking it can help formats that don't support fuzzy strings by just updating the string(?).

**Comment by nijel** [comment] 2021-02-25 07:17
Now it sounds like a duplicate of #1993

**Comment by comradekingu** [comment] 2021-02-25 22:34
Yes, only now more relevant since changelogs are very ephemeral.
There is no use losing the data, and currently translating the latest one is hard because of old ones being kept as is.

**Comment by nijel** [comment] 2021-02-27 06:56
The strings should be ordered correctly, so the first one to translate should be the latest one.

**Closed** 2021-03-15 04:38 UTC
Labels: wontfix

**Comment by comradekingu** [comment] 2021-03-18 14:56
Don't see any other way of solving this

**Comment by nijel** [comment] 2021-03-18 15:45
I don't see other way of solving this than #1993 (besides what is already in place).
