### ISSUE TITLE
Migrate client 3d party libraries to the new build workflow in client/

### ISSUE THREAD

**Issue by meel-hd** [WeblateOrg/weblate#12490] opened 2024-09-13 10:16 UTC
### Describe the issue

Dependency management was done using custom tooling in `scripts/yarn/*`. Now with the introduction of the `client/` folder for managing client libraries using the standard  and simple yarn workflow (`package.json`, `yarn install`, etc) see [Dependency Management](https://docs.weblate.org/en/latest/contributing/frontend.html#dependency-management). But only `sentry` is managed using this new workflow now.

Other libraries are  still using the older workflow?  which should start using the new workflow.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

-

### How do you run Weblate?

Other

**Comment by nijel** [comment] 2024-09-20 09:33
Duplicate of #12172

**Closed by nijel** 2024-09-20 09:33 UTC
Labels: enhancement, duplicate
