### ISSUE TITLE
Mercurial: Amount of closed namesake branches prevents me to rebase commits

### ISSUE THREAD

**Issue by Wohlstand** [WeblateOrg/weblate#3181] opened 2019-11-06 08:19 UTC
**Describe the bug**
I having the mercurial repository where are heads with the "default" name and one of them is closed (Made a dummy public sample here https://bitbucket.org/Wohlstand/weblate-bug/) and here is no way to merge/rebase and no way to push: it says "nothing to push" on every attempt, and "nothing to rebase" on attempt to rebase.

**To Reproduce**
1. Add my mercurial repo into WebLate as translatable component
2. Open Settings / Repository management
3. See "Remote repository needs for a merge" will be always shown: no matter: do you have commits, etc.

**Expected behavior**
Rebase works, merge works, push works.

**Screenshots**
![Снимок экрана от 2019-11-06 11-14-37](https://user-images.githubusercontent.com/6751442/68280547-cc371100-0086-11ea-94f4-25323618caa6.png)

**Server configuration and status**
[root@localhost weblate]# docker-compose exec weblate weblate list_versions
```
 * Weblate 3.9.1
 * Python 3.7.3
 * Django 2.2.6
 * Celery 4.3.0
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.2.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.4.0
 * translation-finder 1.7
 * Whoosh 2.7.4
 * defusedxml 0.6.0
 * Git 2.20.1
 * Pillow 6.2.1
 * python-dateutil 2.8.0
 * lxml 4.3.2
 * django-crispy-forms 1.7.2
 * django_compressor 2.3
 * djangorestframework 3.10.3
 * user-agents 2.0
 * jellyfish 0.7.2
 * diff-match-patch 20181111
 * ruamel.yaml 0.16.5
 * tesserocr 2.4.1
 * Mercurial 4.8.2
 * git-svn 2.20.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mail.dssl.ru
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 3.10.0-1062.1.2.el7.x86_64 (x86_64)
```

[root@localhost weblate]# docker-compose exec --user weblate weblate weblate check --deploy
```
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-3.9.1/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-3.9.1/admin/backup.html

System check identified 6 issues (1 silenced).
```

**Comment by Wohlstand** [comment] 2019-11-06 08:56
Some additional information, what happens under "guts":
(I have captured this trace by injecting into `hg` the python code that dumps all incoming arguments and output into the text file)

When opening repo management:
```
/usr/bin/hg log --limit 1 --template "{node}" --branch .

7099e8d86ee17d78d92c925de715eb7f3b735a9f

/usr/bin/hg log --template '{node}\n' --rev "heads(branch(.))" - .

ec84d1caf743ed590691514da1d443272877aec4
6312a449350d40f91b29fb05bf043ba928608f66
7099e8d86ee17d78d92c925de715eb7f3b735a9f
```

When hit "Rebase" button, having one commit made locally
```
/usr/bin/hg log --template "{node}\n" --rev "outgoing()"

7099e8d86ee17d78d92c925de715eb7f3b735a9f


/usr/bin/hg log --template "{node}\n" --rev "heads(branch(.))" - .

ec84d1caf743ed590691514da1d443272877aec4
6312a449350d40f91b29fb05bf043ba928608f66
7099e8d86ee17d78d92c925de715eb7f3b735a9f


/usr/bin/hg log --limit 1 --template "{node}" --branch .

7099e8d86ee17d78d92c925de715eb7f3b735a9f

/usr/bin/hg status



/usr/bin/hg pull --branch default

pulling from https://Wohlstand@bitbucket.org/Wohlstand/weblate-bug
no changes found
abort: HTTP Error 410: Gone


/usr/bin/hg status



/usr/bin/hg log --limit 1 --template "{node}Э --branch .

7099e8d86ee17d78d92c925de715eb7f3b735a9f

/usr/bin/hg log --template "{node}\n" --rev "heads(branch(.))" - .

ec84d1caf743ed590691514da1d443272877aec4
6312a449350d40f91b29fb05bf043ba928608f66
7099e8d86ee17d78d92c925de715eb7f3b735a9f


/usr/bin/hg log --template "{node}\n" --rev "outgoing()"

7099e8d86ee17d78d92c925de715eb7f3b735a9f


/usr/bin/hg log --template "{node}\n" --rev heads(branch(.)) - .

ec84d1caf743ed590691514da1d443272877aec4
6312a449350d40f91b29fb05bf043ba928608f66
7099e8d86ee17d78d92c925de715eb7f3b735a9f


/usr/bin/hg log --limit 1 --template "{node}\n" --branch .

7099e8d86ee17d78d92c925de715eb7f3b735a9f

/usr/bin/hg status
```

And, when trying to push:
```
/usr/bin/hg log --template "{node}\n" --rev "outgoing()"

7099e8d86ee17d78d92c925de715eb7f3b735a9f


/usr/bin/hg pull --branch default

pulling from https://Wohlstand@bitbucket.org/Wohlstand/weblate-bug
no changes found


/usr/bin/hg branch

default


/usr/bin/hg log --template "{node}\n" --rev "heads(branch(.))" - .

ec84d1caf743ed590691514da1d443272877aec4
6312a449350d40f91b29fb05bf043ba928608f66
7099e8d86ee17d78d92c925de715eb7f3b735a9f


/usr/bin/hg status --rev "heads(branch(.))" - .

M opl3bankeditor_ru_RU.ts


/usr/bin/hg log --limit 1 --template "{node}"

7099e8d86ee17d78d92c925de715eb7f3b735a9f

/usr/bin/hg log --template "{node}\n" --rev "heads(branch(.))" - .

ec84d1caf743ed590691514da1d443272877aec4
6312a449350d40f91b29fb05bf043ba928608f66
7099e8d86ee17d78d92c925de715eb7f3b735a9f


/usr/bin/hg log --template "{node}\n" --rev ".::remote(.)" - .



/usr/bin/hg rebase -d "remote(.)"

nothing to rebase - working directory parent is also destination


/usr/bin/hg status



/usr/bin/hg update --clean "remote(.)"

0 files updated, 0 files merged, 0 files removed, 0 files unresolved


/usr/bin/hg log --template "{node}\n" --rev "outgoing()"

7099e8d86ee17d78d92c925de715eb7f3b735a9f


/usr/bin/hg log --template "{node}\n" --rev "heads(branch(.))" - .

ec84d1caf743ed590691514da1d443272877aec4
6312a449350d40f91b29fb05bf043ba928608f66
7099e8d86ee17d78d92c925de715eb7f3b735a9f


/usr/bin/hg log --limit 1 --template "{node}" --branch .

7099e8d86ee17d78d92c925de715eb7f3b735a9f

/usr/bin/hg log --template "{node}\n" --rev "heads(branch(.))" - .

ec84d1caf743ed590691514da1d443272877aec4
6312a449350d40f91b29fb05bf043ba928608f66
7099e8d86ee17d78d92c925de715eb7f3b735a9f


/usr/bin/hg log --template "{node}\n" --rev "outgoing()"

7099e8d86ee17d78d92c925de715eb7f3b735a9f


/usr/bin/hg log --template "{node}\n" --rev "heads(branch(.))" - .

ec84d1caf743ed590691514da1d443272877aec4
6312a449350d40f91b29fb05bf043ba928608f66
7099e8d86ee17d78d92c925de715eb7f3b735a9f


/usr/bin/hg log --limit 1 --template "{node}" --branch .

7099e8d86ee17d78d92c925de715eb7f3b735a9f

/usr/bin/hg status

```

**Comment by nijel** [comment] 2019-11-06 09:00
Looks like the Mercurial integration needs some review.  Recently there were some changes because of #3022, maybe that broke something else.

**Comment by Wohlstand** [comment] 2019-11-06 10:17
I don't think, the bug is exist on WebLate 3.2 also

**Comment by nijel** [comment] 2019-11-06 10:20
Good, at least it's not a regression.

**Comment by Wohlstand** [comment] 2019-11-06 10:21
So, I think, to solve this we should exclude any closed branches and heads from searches :thinking:

**Comment by Wohlstand** [comment] 2019-11-06 10:34
Maybe try to attach the " not closed()" into --rev?

**Comment by Wohlstand** [comment] 2019-11-06 10:39
Oh!!!!!
I see something:
```
$ hg log --template '{node}\n' --rev "heads(branch(.)) - ."
ec84d1caf743ed590691514da1d443272877aec4
6312a449350d40f91b29fb05bf043ba928608f66
```
And:
```
hg log --template '{node}\n' --rev "heads(branch(.))" - .
```

Pay attention to the position of last quote! `heads(branch(.))` should be a separated argument! However, It's passed with " - ." tail as one single argument `heads(branch(.)) - .` which IS a sounrce of the bug I guess! :eyes:

**Comment by Wohlstand** [comment] 2019-11-06 10:40
Will try to make the change and if it will work, will submit as a pull-request :thinking:

**Comment by Wohlstand** [comment] 2019-11-06 12:04
Also, why `hg push -r .`? It won't work :thinking: 
However, `hg push` works as is...

**Comment by Wohlstand** [comment] 2019-11-06 12:14
Okay, locally I have resolved the rebasing and pushing problems, however, the "Remote repository needs a merge" still not fixed :thinking: 
Can you hint me which call does detecting of this case? I mean, which call does check of the remote repository and which condition is to say: is it needs a merge or not?

**Comment by Wohlstand** [comment] 2019-11-06 12:17
My fixes are:
this:
```
ref_to_remote = 'heads(branch(.)) - .'
```
replaced with:
```
ref_to_remote = 'head() and branch(.) and not closed()'
```

and
```
self.execute(['push', '-r', '.'])
```
replaced with:
```
self.execute(['push'])
```

Still thinking about how to solve the "Remote repository needs a merge" false positive :thinking:

**Comment by Wohlstand** [comment] 2019-11-06 12:36
P.S. Note that as "heads" with "heads(branch(.))" may appear some odd parent branches:

what will happen with `heads(branch(.)) - .`:
![Снимок экрана от 2019-11-06 15-32-46](https://user-images.githubusercontent.com/6751442/68298619-e256c880-00aa-11ea-890d-8ac400f5a017.png)
here are lots of closed and junk heads

Then, what will happen with `heads(branch(.)) and not closed() and not secret()`:
![Снимок экрана от 2019-11-06 15-33-24](https://user-images.githubusercontent.com/6751442/68298647-f0a4e480-00aa-11ea-8ecf-b7c9bc9a719b.png)
Closed heads are no more here, however, odd "heads" have appeared here

And only with `heads(branch(.)) and not closed()` there are true heads:
![Снимок экрана от 2019-11-06 15-33-51](https://user-images.githubusercontent.com/6751442/68298693-074b3b80-00ab-11ea-9020-e200e6537bbc.png)
(both heads you see here are two independent drafts)

**Comment by Wohlstand** [comment] 2019-11-06 12:57
Okay, okay, after a small check I have found the source of "Remote repository needs a merge":
Original `heads(branch(.)) - .` meant heads are on top of current, but not just "most top" head
So, the solution should be:
```
head() and branch(.) and not closed() - .
```
and it will work as intended :fox_face:

**Comment by nijel** [comment] 2019-11-07 09:59
Fixed by https://github.com/WeblateOrg/weblate/pull/3185

**Closed by nijel** 2019-11-07 09:59 UTC
Labels: bug, help wanted
