### ISSUE TITLE
Skipping too many strings in Zen mode for dictionary components

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#6530] opened 2021-09-08 17:34 UTC
Try clicking tab from one field to the next here.
https://hosted.weblate.org/zen/liberaforms/server-liberaforms/nb_NO/?offset=1&q=state%3Aempty

It skips somewhat at random.

**Comment by nijel** [comment] 2021-09-08 19:20
Duplicate of #6236

**Closed by nijel** 2021-09-08 19:20 UTC
Labels: bug, duplicate
