### ISSUE TITLE
punctuation-spacing autofix shouldn't add spaces to URLs / only trigger when punctuation is followed by whitespace or at end of string

### ISSUE THREAD

**Issue by cloph** [WeblateOrg/weblate#10881] opened 2024-01-29 12:23 UTC
### Describe the issue

somewhat related to https://github.com/WeblateOrg/weblate/issues/10880 - given a string `<a href="org.libreoffice.impressremote://requirements/">Learn more</a>` the autofix for French and Breton to add space before punctuation also adds a space in the value for the href attribute of the link.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. try to translate the string not touching the link in French
2. it still gets the auto-fix applied

### Expected behavior

autofix should not touch href attribute - but given that's a pretty specific/limited case, I'd go further and say expected behavior would be to only do the autofix when the punctuation is followed by whitespace/newline/the end of the string. 

### How do you run Weblate?

Git checkout

### Weblate versions

* Weblate: weblate-5.3.1

### Additional context

The problem is not limited to xm/html, but also for strings containing examples like "oracle:thin:@hostname:port:database_name" or "mysql://hostname:port/database_name" or "Display a time using the 24-hour format (hh:mm)." that shouldn't have an auto-fix applied.

**Comment by nijel** [comment] 2024-01-29 13:10
Duplicate of #10779

**Closed by nijel** 2024-01-29 13:10 UTC
Labels: bug, duplicate
