### ISSUE TITLE
SMTP w/ Docker not sending emails.

### ISSUE THREAD

**Issue by STRATZ-Ken** [WeblateOrg/weblate#2938] opened 2019-08-07 04:22 UTC
Report two different bugs here.

A) When using Exchange 2016 with Docker build, I override the settings with TLS and I get `SSL: WRONG_VERSION_NUMBER`.  If I use SSL, I get `ERRNO0` Error.  If I use basic (port 25) I get SMTP Authentication error.  I use `domain\\user` as my login and my normal password.  I use Exchange relaying on all my applications, and have no issues with no other program. I use the same credentials on all those internal applications.

B) When I setup sendgrid to relay, everything works fine with `sendemailtest`.  Though when a new user registers, they never get the email.  When I `report a bug` feature, I see the email going through sendgrid and the email is delivered.

Both on Ubuntu 18.04.  Docker installation method.  Latest build as of 8/7/2019.

**Comment by nijel** [comment] 2019-08-07 06:14
A) Maybe the server is using insecure SSL version? The Docker container is based on quite recent components and might be stricter in this than older tools.

B) Check logs, do you see Weblate sending out these emails?

**Comment by STRATZ-Ken** [comment] 2019-08-07 12:42
A) You are probably right, but I do know that just turning on SSL on other applications and it just works (465) or TLS for (587).  

B) I do see it saying in the docker log `email task received to someone@someone.com` but checking SendGrid's logs, I don't ever see it hitting the SMTP server.  I see the same error when I `report a bug` as well, but that one actually is sent.

**Comment by nijel** [comment] 2019-08-07 12:47
Under some circumstances the errors from sending are not properly logged, this will be addressed by upcoming 3.8 release, so it's possible there is problem in sending on Weblate side. If you can configure error collection (see https://docs.weblate.org/en/latest/admin/install.html#collecting-error-reports), it should give more insights, otherwise it's probably easiest to wait for the next release as backporting those fixes is not trivial.

**Comment by STRATZ-Ken** [comment] 2019-08-07 12:50
I have no problem waiting, I just figured I would shoot over some bugs, as I debugged for about 4-5 hours and gave up.

Sidenote, your installation instructions, while there is a lot of documentation, needs to be better organized.  I jumped around for a while from the 3 pages for OS level install, before failing and giving up and decided to use Docker.

Otherwise, great job on the product!

**Closed** 2019-08-07 12:50 UTC
Labels: question

**Comment by nijel** [comment] 2019-08-08 06:46
I know the documentation needs improvements, we just don't have capacity to do full review of it, so if you could point out actual problems you've found that, it would be great.

**Comment by STRATZ-Ken** [comment] 2019-08-08 13:56
I think there is two pages for OS installs.  The first describes how to do the installation and the other talks about the software required.  Then you have multiple OS formats.  I think it would be easier if you merged both pages into one since they are technically the same thing.  Then do a sort of 1-100 steps from top to bottom. I found myself missing packages throughout as well, and I had to google the import then manually install them as well.

**Comment by nijel** [comment] 2019-08-09 11:40
You're right on that, I have some changes ready and I should work on pushing them out...

**Comment by nijel** [comment] 2019-08-09 12:30
Thanks for pushing me to this long pending task, for now I've at least completed the things I had already prepared, see https://docs.weblate.org/en/latest/admin/quick.html

**Comment by apgrucza** [comment] 2019-08-15 23:56
> Under some circumstances the errors from sending are not properly logged, this will be addressed by upcoming 3.8 release, so it's possible there is problem in sending on Weblate side. If you can configure error collection (see https://docs.weblate.org/en/latest/admin/install.html#collecting-error-reports), it should give more insights, otherwise it's probably easiest to wait for the next release as backporting those fixes is not trivial.

After upgrading to Weblate 3.8, the logs now show an error during account registration:

```
weblate_1   | uwsgi stderr | INFO Passed captcha for *******@************ (7 * 3 = 21)
weblate_1   | uwsgi stderr | INFO sending notification activation on /accounts/complete/email/?verification_code=032e658c3f644428b87078ae4f993b17&partial_token=0c9d1083c2dc48f7832a0475d1a3c212 to *******@************
weblate_1   | celery-notify stderr | [2019-08-15 23:43:24,409: INFO/MainProcess] Received task: weblate.accounts.tasks.send_mails[7d66d7cd-0674-435c-a627-3e8b04e6b62c]
weblate_1   | nginx stdout | 172.25.200.103 - - [15/Aug/2019:23:43:24 +0000] "POST /accounts/register/ HTTP/1.1" 302 0 "http://**********************************************" "Mozilla/5.0
(Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
weblate_1   | uwsgi stderr | [pid: 186|app: 0|req: 2/4] 172.25.200.103 () {52 vars in 1162 bytes} [Thu Aug 15 23:43:24 2019] POST /accounts/register/ => generated 0 bytes in 66 msecs (HTTP/1.1 302) 12 headers in 713 bytes (1 switches on core 0)
weblate_1   | uwsgi stderr | [pid: 185|app: 0|req: 3/5] 172.25.200.103 () {46 vars in 982 bytes} [Thu Aug 15 23:43:24 2019] GET /accounts/email-sent/ => generated 6894 bytes in 31 msecs (HTTP/1.1 200) 9 headers in 580 bytes (1 switches on core 0)
weblate_1   | nginx stdout | 172.25.200.103 - - [15/Aug/2019:23:43:24 +0000] "GET /accounts/email-sent/ HTTP/1.1" 200 2624 "http://**********************************************" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142
Safari/537.36"
weblate_1   | celery-notify stderr | ERROR Failure while executing task: SMTPSenderRefused: (530, b'5.5.1 Authentication Required. Learn more at\n5.5.1  https://support.google.com/mail/?p=WantAuthError a21sm5536291ioe.27 - gsmtp', '*******@*********')
weblate_1   | celery-notify stderr | [2019-08-15 23:43:24,738: ERROR/ForkPoolWorker-1] Failure while executing task: SMTPSenderRefused: (530, b'5.5.1 Authentication Required. Learn more at\n5.5.1  https://support.google.com/mail/?p=WantAuthError a21sm5536291ioe.27 - gsmtp', '*******@*********')
weblate_1   | ERROR Failure while executing task
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/celery/app/trace.py", line 385, in trace_task
weblate_1   |     R = retval = fun(*args, **kwargs)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/celery/app/trace.py", line 648, in __protected_call__

```

So for account registration it looks like the email credentials may not get passed through anymore (`sendtestemail` works fine).

**Comment by nijel** [comment] 2019-08-16 06:12
Can you please be more specific what kind of error was there? Is there something what can be fixed on Weblate container side?

**Comment by apgrucza** [comment] 2019-08-16 13:13
No the error was solely in my script, and the better logging in 3.8 certainly helped me to track this down.


Adrian Grucza  
Technical Lead
Tel: +61390185847
Mobile: +61432755054
adrian.grucza@iress.com
www.iress.com
Level 16, 385 Bourke Street,
 Melbourne, Victoria, 3000
The contents of this email originated from Iress. For this purpose Iress includes Iress Limited and/or any of its subsidiaries, holding companies and trading entities. 
​If you have received this email in error please notify the sender immediately and delete this email. 
nosig

**Comment by romanr** [comment] 2019-09-08 07:21
I can confirm. Had this problem in 3.7.1. Upgrading to 3.8 fixed sending email issue
