### ISSUE TITLE
Gettext newlines get entirely removed sometimes

### ISSUE THREAD

**Issue by hhyyrylainen** [WeblateOrg/weblate#11032] opened 2024-02-18 17:16 UTC
### Describe the issue

I've been noticing the past few weeks that the headers in my .po files get sometimes mangled by Weblate. And also in some translated text.

I just updated to 5.4 and Weblate just made its first PR that shows all modified .po files have the newlines in their headers removed: https://github.com/Revolutionary-Games/Thrive/pull/4892/files

This seems to maybe trigger when a certain kind of update happens? I wrote some more about this in the extra details section.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Have the gettext output customization plugin enabled with only explicit newlines as breaking
2. Wait for Weblate to make a PR

### Expected behavior

I expect the gettext file header to stay intact with line breaks. And the other texts following the customization plugin option.

### How do you run Weblate?

PyPI module

### Weblate versions

 * Weblate: 5.4
 * Django: 4.2.9
 * siphashc: 2.3
 * translate-toolkit: 3.12.2
 * lxml: 5.1.0
 * Pillow: 10.1.0
 * nh3: 0.2.15
 * python-dateutil: 2.8.2
 * social-auth-core: 4.5.1
 * social-auth-app-django: 5.4.0
 * django-crispy-forms: 2.1
 * oauthlib: 3.2.2
 * django-compressor: 4.4
 * djangorestframework: 3.14.0
 * django-filter: 23.5
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.13.1
 * rapidfuzz: 3.5.2
 * openpyxl: 3.1.2
 * celery: 5.3.6
 * django-celery-beat: 2.5.0
 * kombu: 5.3.4
 * translation-finder: 2.16
 * weblate-language-data: 2023.9
 * html2text: 2020.1.16
 * pycairo: 1.25.1
 * PyGObject: 3.46.0
 * diff-match-patch: 20230430
 * requests: 2.31.0
 * django-redis: 5.4.0
 * hiredis: 2.2.3
 * sentry-sdk: 1.39.1
 * Cython: 3.0.7
 * misaka: 2.1.1
 * GitPython: 3.1.40
 * borgbackup: 1.2.7
 * pyparsing: 3.1.1
 * ahocorasick_rs: 0.20.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.2
 * Python: 3.12.1
 * Git: 2.43.0
 * psycopg: 3.1.16
 * psycopg-binary: 3.1.16
 * phply: 1.2.6
 * ruamel.yaml: 0.18.5
 * tesserocr: 2.6.2
 * boto3: 1.34.11
 * aeidon: 1.13
 * iniparse: 0.5
 * Mercurial: 6.6.1
 * git-svn: 2.43.0
 * PostgreSQL server: 15.4
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mail.revolutionarygamesstudio.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 6.6.14-200.fc39.x86_64 (x86_64)

### Weblate deploy checks

```shell
System check identified some issues:

WARNINGS:
?: (weblate.W033.Gerrit) Failure in loading VCS module for Gerrit: Traceback (most recent call last):
  File "/home/weblate/weblate-env/bin/git-review", line 5, in <module>
    from git_review.cmd import main
  File "/home/weblate/weblate-env/lib/python3.12/site-packages/git_review/cmd.py", line 34, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
 (1)
        HINT: https://docs.weblate.org/en/weblate-5.4/vcs.html

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.4/admin/install.html#collecting-errors

System check identified 2 issues (1 silenced).
```

### Additional context

This seems to have started after the previous gettext bug was fixed that I was experiencing, which maybe caused this new problem or uncovered an underlying bug.

**Comment by nijel** [comment] 2024-02-19 10:42
This is typically done by add-on, see https://docs.weblate.org/en/latest/admin/addons.html#customize-gettext-output

**Comment by hhyyrylainen** [comment] 2024-02-19 10:46
Yes, that's an addon that I've enabled and configured to only add line breaks on the line break character. It's just that recently it has started to act incorrectly again. Before it would use incorrect settings for an entire file, but now it seems to only break the gettext header info and sometimes the changed translations. So it is better than it was before but there is still some bug. I've just tried to reinstall the plugin again and set it to the right option.

**Comment by nijel** [comment] 2024-02-19 10:56
There was a change in 5.4 that should make the add-on behavior more consistent, see 9aef095a0b172a487b3bfec1f0b81b7f3dde597c or 00268c56f7e458d0420af6eec1f849e6028af6f1.

**Comment by hhyyrylainen** [comment] 2024-02-19 10:57
I was hoping that that would be the case, but less than 10 minutes after updating to 5.4 that PR with the bad changes in it got opened. That's why I opened this issue as it seems the problem is not fully solved. I can try merging and fixing that one PR now to see if there were some old changes or something that got committed and a fully clean 5.4 generated PR would be fine.

**Comment by hhyyrylainen** [comment] 2024-02-19 15:35
My addon setting is this, and has been at least for the past year:

![image](https://github.com/WeblateOrg/weblate/assets/3796411/c737f28e-7af9-4d9d-838a-009ea3aaf18f)

(sorry for the localized website, but it is the wrap only on new lines option)

So the header part of the gettext file is the most obvious part that gets formatted not following the selected addon setting.

**Comment by hhyyrylainen** [comment] 2024-02-24 10:02
I just saw the bug trigger again: https://github.com/Revolutionary-Games/Thrive/pull/4910/files#diff-de4a0c9801d4c8c5874d42d1762824807c47062345173729e6b424474626b6cb (and this is after re-installing the plugin). That PR was opened a little bit after the latest changes to the English text.

**Comment by nijel** [comment] 2024-03-12 12:32
https://github.com/Revolutionary-Games/Thrive/pull/4925/files looks correct, it wraps on the newlines.

In the previous one, there are definitely strings which are not wrapped correctly:
https://github.com/Revolutionary-Games/Thrive/pull/4910/files#diff-de4a0c9801d4c8c5874d42d1762824807c47062345173729e6b424474626b6cbR6984

For example, it turns:

```po
msgid "WIKI_PROTOPLASM_STRATEGY"
msgstr ""
"在常規遊戲中不可能使用[b]原生質[/b]。玩家只有在自由建構模式下開啟在先前的遊戲中化石化的非玩家物種時才能使用它，且該物種恰好演化了這種細胞器。\n"
"\n"
"當它確實出現時，[b]原生質[/b]在策略上等同於[b][color=#3796e1][url=thriveopedia:cytoplasm]細胞質[/url][/color][/b]，但顯著增加儲存和較慢的[thrive:compound type=\"atp\"][/thrive:compound] 生產。具有[b]原生質[/b]的細胞通常可以存活更長時間，而無需尋找化合物雲或消化獵物。"
```
into:

```po
msgid "WIKI_PROTOPLASM_STRATEGY"
msgstr ""
"在常規遊戲中不可能使用[b]原生質[/b]。玩家只有在自由建構模式下開啟在先前的遊戲"
"中化石化的非玩家物種時才能使用它，且該物種恰好演化了這種細胞器。\n"
"\n"
"當它確實出現時，[b]原生質[/b]在策略上等同於[b][color=#3796e1]"
"[url=thriveopedia:cytoplasm]細胞質[/url][/color][/b]，但顯著增加儲存和較慢的"
"[thrive:compound type=\"atp\"][/thrive:compound] 生產。具有[b]原生質[/b]的細"
"胞通常可以存活更長時間，而無需尋找化合物雲或消化獵物。"
```

Have you seen this on latin languages as well? Maybe this is an issue with CJK wrapping implementation in https://github.com/translate/translate/blob/e98250d1d68007889d63f961cbf3fb688658fbe5/translate/storage/pypo.py#L106-L222

**Comment by hhyyrylainen** [comment] 2024-03-12 14:04
> Have you seen this on latin languages as well? 

I can't say I have seen that after the latest Weblate update. In the past it has happened to latin alphabet based languages (languages like Swedish and Polish I'm pretty sure I remember it happening to but I think all of the regularly updated translations for Thrive have at some point been hit by this), but that was before the latest Weblate updates.

**Comment by hhyyrylainen** [comment] 2024-03-27 07:04
I see that Turkish has also been affected by this problem now: https://github.com/Revolutionary-Games/Thrive/pull/4955/files

**Comment by nijel** [comment] 2024-04-20 12:17
I still fail to reproduce this issue. It might have been caused by wrong merging of PO files, which got fixed in https://github.com/WeblateOrg/weblate/pull/11280, but I don't see this cause as much likely.

**Comment by nijel** [comment] 2024-04-24 12:05
I've identified some issues in wrapping, but these should affect individual units being added, not whole file being rewrapped: 

* https://github.com/WeblateOrg/weblate/pull/11477 
* https://github.com/translate/translate/pull/5241

**Comment by nijel** [comment] 2024-04-26 06:31
I think I've reproduced the issue now and above fixes make the issue disappear for me. So let's assume they will fix it for you as well once you upgrade to Weblate 5.5.1 and translate-toolkit 3.13.1 (neither of these are released yet).

**Closed** 2024-04-26 06:31 UTC
Labels: bug
