### ISSUE TITLE
Keyboard accelerator mark check

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#6142] opened 2021-06-05 05:40 UTC
If the source has underlines for strings, the translation should too

msgfmt -c --check-accelerators="_" --statistics po/<languagecode>.po
gives a list of missing entries, but in Weblate this goes unnoticed.

**Comment by nijel** [comment] 2021-06-11 07:44
Duplicate of #5962

**Closed by nijel** 2021-06-11 07:44 UTC
Labels: duplicate, enhancement
