### ISSUE TITLE
Can't type polish special characters with diacritics

### ISSUE THREAD

**Issue by Buszmen** [WeblateOrg/weblate#1648] opened 2017-10-04 10:20 UTC
### Steps to reproduce
1. Use Mac/OSX with polish keyboard settings
2. Open translation windows
3. Start writing polish special characters with diacritics

### Actual behaviour
I can't type characters like ę, ć, ń, ś. In standard polish keyboard setting those can be achieved with Alt + e, Alt + c, Alt + n, Alt + s, but those are reserved for Weblate keyboard shortcuts. It works on Windows because left Alt is different than right Alt, but not on OSX.

### Expected behaviour
I can type all polish special characters with diacritics

### Server configuration
Weblate online demo

**Comment by nijel** [comment] 2017-10-04 10:37
Duplicate of #1574

**Comment by nijel** [comment] 2017-10-04 10:37
Yes, some of the shortcuts collide with system ones. Suggestions how to deal with this are welcome in #1574

**Closed by nijel** 2017-10-04 10:37 UTC
