### ISSUE TITLE
Crash when changing review state to Approved

### ISSUE THREAD

**Issue by dngduy132** [WeblateOrg/weblate#11420] opened 2024-04-17 15:47 UTC
### Describe the issue

Hello. When trying to change the review state to Approved, we get hit by a server error like the one uploaded at the screen shot and the state not being updated 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Go to the component that needs to change the state
2. Change the review state to "Approved"
3. Click "save and stay"

### Expected behavior

State of the string change to "Approved"

### Screenshots
1. Server error
![image](https://github.com/WeblateOrg/weblate/assets/92735527/0247960a-a8dc-4fb7-9c8d-7f005e199068)
2. Step to reproduce 
    2.1. Go to the component that needs to change the state
![image](https://github.com/WeblateOrg/weblate/assets/92735527/0b9fe861-a11c-488b-aaee-9181c64698a5)
   2.2. Change the review state to "Approved"
![image](https://github.com/WeblateOrg/weblate/assets/92735527/7cf2a044-99f0-43d7-93a9-1747acb00f41)

### Exception traceback

```pytb
Traceback (most recent call last):
gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
gunicorn stderr |     response = get_response(request)
gunicorn stderr |                ^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
gunicorn stderr |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
gunicorn stderr |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.12/contextlib.py", line 81, in inner
gunicorn stderr |     return func(*args, **kwds)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/trans/views/edit.py", line 641, in translate
gunicorn stderr |     response = handle_translate(request, unit, this_unit_url, next_unit_url)
gunicorn stderr |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/utils/ratelimit.py", line 132, in rate_wrap
gunicorn stderr |     return function(request, *args, **kwargs)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/trans/views/edit.py", line 421, in handle_translate
gunicorn stderr |     go_next = perform_translation(unit, form, request)
gunicorn stderr |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/trans/views/edit.py", line 335, in perform_translation
gunicorn stderr |     saved = unit.translate(
gunicorn stderr |             ^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.12/contextlib.py", line 81, in inner
gunicorn stderr |     return func(*args, **kwds)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/trans/models/unit.py", line 1476, in translate
gunicorn stderr |     saved = self.save_backend(
gunicorn stderr |             ^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/trans/models/unit.py", line 1065, in save_backend
gunicorn stderr |     self.commit_if_pending(author)
gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/trans/models/unit.py", line 1040, in commit_if_pending
gunicorn stderr |     self.translation.commit_pending("pending unit", None)
gunicorn stderr |   File "/usr/local/lib/python3.12/contextlib.py", line 81, in inner
gunicorn stderr |     return func(*args, **kwds)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/trans/models/translation.py", line 560, in commit_pending
gunicorn stderr |     return self.component.commit_pending(reason, user, skip_push=skip_push)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/trans/models/component.py", line 194, in on_link_wrapper
gunicorn stderr |     return getattr(linked, func.__name__)(*args, **kwargs)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/trans/models/component.py", line 195, in on_link_wrapper
gunicorn stderr |     return func(self, *args, **kwargs)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/trans/models/component.py", line 1957, in commit_pending
gunicorn stderr |     translation._commit_pending(reason, user)
gunicorn stderr |   File "/usr/local/lib/python3.12/contextlib.py", line 81, in inner
gunicorn stderr |     return func(*args, **kwds)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/trans/models/translation.py", line 611, in _commit_pending
gunicorn stderr |     self.update_units(units, store, author_name, author.id)
gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/trans/models/translation.py", line 807, in update_units
gunicorn stderr |     store.save()
gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/formats/ttkit.py", line 334, in save
gunicorn stderr |     self.save_atomic(self.storefile, self.save_content)
gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/formats/base.py", line 434, in save_atomic
gunicorn stderr |     callback(temp)
gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/formats/external.py", line 63, in save_content
gunicorn stderr |     ILLEGAL_CHARACTERS_RE.sub("", data[field]),
gunicorn stderr |                                   ~~~~^^^^^^^
gunicorn stderr | KeyError: ''
```

### How do you run Weblate?

Docker container

### Weblate versions

5.4.1

**Comment by nijel** [comment] 2024-04-17 16:18
Please upgrade, I think this has been already fixed

**Comment by nijel** [comment] 2024-04-17 18:06
Duplicate of #11231

**Closed by nijel** 2024-04-17 18:06 UTC
Labels: bug, duplicate
