### ISSUE TITLE
Improve difference in changes

### ISSUE THREAD

**Issue by jelv** [WeblateOrg/weblate#1902] opened 2018-03-13 11:39 UTC
Some suggestions to improve the differences recognition. 

**1. Full word changes**
Weblate recognizes small changes in words but goes to far when full words change with some of the same letters. 
Problem is that it no longer readable. 
Solutions would be strike the whole word that is changed instead of some letters.

_Examples were full word would be better_
![screenshot_1](https://user-images.githubusercontent.com/7106279/37338383-997d5e68-26b7-11e8-8677-b35ff79ec035.png)
Solution: gratis _red_ and vrije _green_

![screenshot_3](https://user-images.githubusercontent.com/7106279/37338381-993651d0-26b7-11e8-8391-d4b9f1dae708.png)
Solution: Betalingsdetails _red_ and Betalingsgegevens _green_ 

![screenshot_6](https://user-images.githubusercontent.com/7106279/37338777-c01ada72-26b8-11e8-863d-061b19050010.png)

![screenshot_7](https://user-images.githubusercontent.com/7106279/37338778-c03c7fec-26b8-11e8-9632-a96e64671e67.png)

**2. Sentences changes**
When whole sentences get changes it sometimes recognizes letters and makes a mess. 
Problem is the readability. 
Solutions would be strike the whole word that is changed instead of some letters.

![screenshot_5](https://user-images.githubusercontent.com/7106279/37338384-99964388-26b7-11e8-8df8-0ce664ceece6.png)
Show more details _red_ and Mostrar mais para todas as mensagens _green_ 

**The good in current difference**
It also has some good points. When only one small part of the word is changed it works out fine. Also two small letter changes look fine in mine eye. Also changes in the sentence, like the last example, are recognized fine so that should stay the same.

![screenshot_8](https://user-images.githubusercontent.com/7106279/37338779-c057662c-26b8-11e8-8302-252c02dc38b4.png)

![screenshot_4](https://user-images.githubusercontent.com/7106279/37338385-99b1b564-26b7-11e8-95be-ab6aa0e0b5b1.png)

![screenshot_2](https://user-images.githubusercontent.com/7106279/37338382-995be6f2-26b7-11e8-9b66-ceb7e08f16d3.png)

**Comment by nijel** [comment] 2018-03-13 16:52
The current diff is pretty simple suggestions how to improve the code are welcome:

https://github.com/WeblateOrg/weblate/blob/dccd0bc9d9b437687fb668b00b7e060e480ccd27/weblate/trans/simplediff.py#L22-L50

**Comment by nijel** [comment] 2018-03-13 16:53
The problem with word based diff is that it is less readable for fixing typos inside word.

**Comment by nijel** [comment] 2018-11-30 20:40
Duplicate of #1570

**Closed by nijel** 2018-11-30 20:40 UTC
Labels: enhancement
