### ISSUE TITLE
words_percent is not 100%

### ISSUE THREAD

**Issue by desmax** [WeblateOrg/weblate#1446] opened 2017-04-14 04:52 UTC
In project statistics I see such data. How come words_percent is 97.2? When I go to component list - everything is 100%

 ```{
        "total_words": 9414,
        "code": "en",
        "translated_words": 9151,
        "language": "English",
        "translated": 1147,
        "translated_percent": 100.0,
        "total": 1147,
        "words_percent": 97.2

**Comment by nijel** [comment] 2017-04-14 15:52
Looks like the word stats are not up to date. What version are you using?

**Comment by desmax** [comment] 2017-05-10 07:06
@nijel sorry, I missed your reply. I just updated to recent master and bad stats are still there

**Comment by nijel** [comment] 2017-05-10 14:50
So it's only project stats are wrong, at lower level it's correct?

**Comment by desmax** [comment] 2017-05-10 14:59
@nijel project language level is wrong(http://../projects/project-name/#languages), but components from that particular language is correct (this link http:/../languages/da/project-name/)

**Comment by nijel** [comment] 2017-05-10 15:01
PS: I see it's for English - what file format do you use? Does it happen for other languages as well?

**Comment by desmax** [comment] 2017-05-10 15:04
@nijel I see it for all languages which I have 100% percent translated(4 of them).
My format is XLIFF

**Comment by nijel** [comment] 2017-05-10 17:37
Can you try if editing some string does fix that? In that case it's probably fixed by latest update, but it just didn't propagate tot the database (where the counts are stored).

**Comment by desmax** [comment] 2017-05-11 00:39
@nijel did not help unfortunately (just pulled recent master)

**Comment by nijel** [comment] 2017-05-11 14:33
Apparently there is something fishy in the per project calculation as I've just found:

```json
  {
    "total_words": 7914, 
    "code": "en", 
    "translated_words": 7915, 
    "language": "English", 
    "translated": 2067, 
    "translated_percent": 100.0, 
    "total": 2067, 
    "words_percent": 99.9
  }
```

**Comment by nijel** [comment] 2017-05-11 14:34
Apparently the root cause is same as with #1413 - some of the translations have different source strings...

**Closed** 2017-05-11 14:33 UTC
Labels: bug

**Comment by nijel** [comment] 2017-05-11 14:49
However there still might be some inconsistency for monolingual strings which were edited before 4f72ce2630 or 067906d1fc77d2a1d5355f66ce1dd057896d64e9. But at least the total and translated numbers should match now...

**Comment by desmax** [comment] 2017-05-11 15:41
@nijel works indeed

**Comment by nijel** [comment] 2017-05-11 16:27
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
