### ISSUE TITLE
Glossary v4.5 - Source lang = DE => missing source in Glossary

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#5517] opened 2021-02-25 11:31 UTC
Since in cases where the source language of the project/component is != EN, the glossary feature does not create the correct source language in the glossary (see issue #5497), the component throws and issue of course:
![image](https://user-images.githubusercontent.com/26718215/109147242-143ee300-7765-11eb-9e2c-08000a2cea6f.png)

Setup of the glossary component generated by Weblate 4.5:
![image](https://user-images.githubusercontent.com/26718215/109147284-202aa500-7765-11eb-822b-cdd2cc15e38c.png)

But no de.tbx is generated, thus not present in the local git.
![image](https://user-images.githubusercontent.com/26718215/109147369-33d60b80-7765-11eb-8b8b-b6be51e546d0.png)

Will this also be fixed with #5497 or does this need extra work?
And how will this be fixed in existing, migrated projects?
I can not add the file myself, since I do not have write access with my username and API key to the local repo.
Maybe I am doing something wrong.

**Comment by nijel** [comment] 2021-02-25 11:34
Duplicate of #5492

**Closed by nijel** 2021-02-25 11:34 UTC
Labels: bug, duplicate

**Comment by nijel** [comment] 2021-02-26 19:19
Just to clarify - the source language file is expected not to be present, it's the alert which is wrong in this case.

**Comment by ilocit** [comment] 2021-02-26 19:49
Considering that TBX is Bilingual, that makes sense, yes. 

But where would you store the comments/explanations? 

Perhaps a DE/DE TBX file could help here? 

Anyhow, I leave that up to you guys. 
If the source != EN issue is fixed, most of this should work, I think.

**Comment by nijel** [comment] 2021-02-27 06:44
The additional metadata is currently stored in Weblate only.

**Comment by ilocit** [comment] 2021-02-27 07:21
OK. Can't it be stored in the TBX?
You can import this kind of content from the TBX, so it should 'stay there' so that you can export/import it. Same as with comments in Xlf and resx, properties.....

**Comment by nijel** [comment] 2021-03-02 08:38
Generally, Weblate doesn't store additional information in the files. It parses some of that from them when present, but the information entered in Weblate stays in the database. Most likely this would anyway use custom format because I don't see a format that would support storing all additional information Weblate collects - comments, suggestions, screenshots or flags.

**Comment by ilocit** [comment] 2021-03-02 08:41
No, of course it would not store it all, but the comments would work and could be a good way to let some, critical information travel through different systems in a consistent and preserving fashion.

**Comment by nijel** [comment] 2021-03-02 08:43
Anyway let's keep this in https://github.com/WeblateOrg/weblate/issues/5519
