### ISSUE TITLE
Add automated checks for Restructured Text/Sphinx syntax

### ISSUE THREAD

**Issue by freakboy3742** [WeblateOrg/weblate#10786] opened 2024-01-15 04:53 UTC
### Describe the problem

If Weblate is being used to translate content in RestructuredText / Sphinx format, there's no automated checks to ensure that:

1. The translated string is valid RestructuredText / Sphinx format
2. Any document references are consistent between the original and translated string
3. Markup such as the `::` at the end of a line used to indicate that the next line is a code sample is preserved in the translation.

### Describe the solution you would like

Automated checks, analogous to the `weblate.checks.markup.MarkdownSyntaxCheck`, `weblate.checks.markup.MarkdownRefLinkCheck` and `weblate.checks.markup.MarkdownLinkCheck`, but for RestructuredText/Sphinx syntax.

### Describe alternatives you have considered

There is basic support for Restructured Text using the `rst-text` translation flag. However, this doesn't appear to do much more than basic syntax highlighting in the editor.

### Additional context

RestructureText/Sphinx is the default format for docs in the Python ecosystem - Weblate's own documentation is written in RestructuredText. Having tools to ensure that translations are valid RestructureText avoids a common source of error.

Ideally, this would be combined with `.rst` being an identified content type, so that ReST checks don't need to be manually added.

**Comment by nijel** [comment] 2024-06-25 07:28
Duplicate of #8446

**Closed by nijel** 2024-06-25 07:28 UTC
Labels: enhancement, help wanted, duplicate, backlog
