### ISSUE TITLE
Language name for "nl_BE" "Flemish" is not the right name.

### ISSUE THREAD

**Issue by JosDeGraeve** [WeblateOrg/weblate#4379] opened 2020-08-25 10:07 UTC
**Describe the bug**

Weblate does not have the right name for the language "nl_BE"

**To Reproduce**

The language "nl_BE" in weblate has the name "Flemish" but that is not the right name.  

**Expected behavior**

I would like to suggest "Dutch (Belgium)" as a better name.

**Additional context**

I'm willing to create a PR with the proper name, do i only search in json and py files, and ignore po files ?

**Comment by nijel** [comment] 2020-08-25 18:10
Thanks, fixed by https://github.com/WeblateOrg/language-data/pull/27
  and 49338b647e70871d7ebdc1854f5df03c39ddc251

**Closed by nijel** 2020-08-25 18:10 UTC
Labels: bug

**Comment by KazamaSion** [comment] 2021-07-01 01:54
It seems like the issue is solved in 4.3, but the wrong name remains in 4.7.1.  
The wrong name can be found in the URL “/languages/”.  
  
![](https://vip2.loli.io/2021/07/01/sdb6cwRB13lVkyh.png)  
![](https://vip1.loli.io/2021/07/01/8V6Qojxyh2J7ver.png)  


I checked the languages.csv, but it is as supposed:
![](https://vip1.loli.io/2021/07/01/yW4KwNacugjYFVk.png)
