### ISSUE TITLE
Can Not Commit After 4.1 upgrade

### ISSUE THREAD

**Issue by buck-E** [WeblateOrg/weblate#4054] opened 2020-06-17 08:26 UTC
**Describe the bug**
After upgrading to 4.1, we can not commit to the repo.

**To Reproduce**
1. Notice that repo is not changed, even though there are weblate changes.
2. Go to project .#repository
3. See error

```
FATAL -- ACCESS DENIED
Repo            www                                                         
User            weblate                                                     
Stage           Before git was called                                       
Operation       Repo write                                                  

FATAL: W any www weblate DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
 (128)
```

**Expected behavior**
I expect to see a successful push.

**Server configuration and status**
On pip installed Weblate:

```
weblate list_versions

See: https://github.com/WeblateOrg/weblate/issues/4053


weblate check --deploy

(warnings/infos only - prefer not to share security info unless necessary)
```

**Additional context**

I wonder if the problem is reading the GPG key?  I verify it is in data/home/.gnupg and that settings.py has the correct `WEBLATE_GPG_IDENTITY =`

Because the about page is not visible (https://github.com/WeblateOrg/weblate/issues/4039), I can not verify if Weblate knows the GPG key at this time.

**Comment by nijel** [comment] 2020-06-17 08:39
This seems like error from pushing, are you sure it is from commit?

**Comment by nijel** [comment] 2020-06-17 08:40
PS: The keys are available on the /keys/ URL, that should not be affected by #4039.

**Comment by buck-E** [comment] 2020-06-17 08:47
> This seems like error from pushing, are you sure it is from commit?

It's push.  Thank you.

> PS: The keys are available on the /keys/ URL, that should not be affected by #4039.

Found.  I confirm the keys are visible.

**Comment by buck-E** [comment] 2020-06-17 08:48
Also a report that we can not read from the repo but I do not confirm yet.  If so it could be a repo set up problem.  I will look at it tomorrow.

**Comment by buck-E** [comment] 2020-06-18 02:09
The  #vcs page looks correct:

*Source code repository*

git+ssh://git@git.domain.com/project.git

*Repository branch*

master

*Repository push URL*

git+ssh://git@git.domain.com/project.git

Two things:

1 - I do not understand the `weblate://project/component` option.  What does that do, and how will the component know which Git location to use?

2 - I can not Pull using the Web UI.  When I do, I get a 502 nginx error, like with the About page (https://github.com/WeblateOrg/weblate/issues/4039).  Not sure if related?

So I can't really debug this until that is cleared up.

**Comment by nijel** [comment] 2020-06-18 06:44
1. See https://docs.weblate.org/en/latest/vcs.html#weblate-internal-urls
2. It's most likely a different error, can you double check that?

**Comment by buck-E** [comment] 2020-06-19 05:51
> See https://docs.weblate.org/en/latest/vcs.html#weblate-internal-urls

I've seen it.  It does not answer my questions but maybe it doesn't matter for this error.

> It's most likely a different error, can you double check that?

Definitely 502 nginx error.  Same with about/ page.

**Comment by buck-E** [comment] 2020-06-19 07:44
More clear:

```
To share one repository between different components you can use a special URL like weblate://project/component. This way, the component will share the VCS repository configuration with the referenced component, and the VCS repository will be stored just once on the disk.
```
Why would I want to share a repository between components?

If I do this, how does the component know what remote repository to use as the upstream?

> This way, the component will share the VCS repository configuration with the referenced component

Um, which component is "the component" and which is "the referenced component"?  What?

> the VCS repository will be stored just once on the disk

Okay, what?

**Comment by buck-E** [comment] 2020-06-19 08:08
When I try to change the URL (add or remove a trailing slash) I get this error:

Could not update repository: error: gpg failed to sign the data fatal: failed to write commit object (128)

I see my GPG key under `/keys` URL, and this started (I think) with 4.1 upgrade.

I will also verify with the repo that the key is available there ASAP but adding data as I get it.

**Comment by nijel** [comment] 2020-06-19 08:55
> Definitely 502 nginx error. Same with about/ page.

I've just seen it again. This error happens when showing the error page, so it contains additional error underneath, look for that one.

Maybe stupid question: Isn't your server running out of disk space?

**Comment by nijel** [comment] 2020-06-19 09:02
PS: I've clarified the internal URLs docs in 7c609e564c3c4297a04818292935d4fe70abd6f4, but I don't think it's related here...

**Comment by buck-E** [comment] 2020-06-20 00:10
> Maybe stupid question: Isn't your server running out of disk space?

No, not at all.

Upgraded to 4.1.1.  Now there is no nginx error.  Now the error is from Weblate.  It states:

```
Server Error
The server had serious problems serving your request. Trained monkeys are en-route fixing the issue.
```

**Comment by buck-E** [comment] 2020-06-20 00:13
https://docs.weblate.org/en/latest/vcs.html#weblate-internal-urls

```
To share one repository between different components you can use a special URL like weblate://project/component. This way, the component will share the VCS repository configuration with the referenced component (project/component in the example).
```

This makes no sense?  How can a repository share with itself?


```
Weblate automatically adjusts repository URL when creating component when it finds component with matching repository setup. You can override this in last step of component configuration.
```

Sorry but I have no idea what this means.

Actually I understand internal URLs worse than before.  And I still don't know when to use them, and when to use the normal URL (which I am using in this Issue) like `git+ssh://git.site.com/repository.git`

**Comment by buck-E** [comment] 2020-06-20 00:18
So we are still unable to use weblate, and I tried changing the *Source code repository* from `git+ssh://git.site.com/repository.git` to `weblate://project/component` (using the correct project and component names) and it won't allow it with this error:

```
Invalid link to a Weblate project, cannot link it to itself!
```

**Comment by buck-E** [comment] 2020-06-20 00:24
I feel like the problem could be with GPG commit signing since upgrading to 4.1?  Just a guess really.

**Comment by nijel** [comment] 2020-06-20 04:45
Until you show the actual error, I can't tell what could be the cause here

**Comment by buck-E** [comment] 2020-06-21 23:26
I've showed you every error we got so far.  

Again, I will say that the current error comes when I go to `#repository` and click on "Pull" button.  The error is:


```
Server Error
The server had serious problems serving your request. Trained monkeys are en-route fixing the issue.
```

What other info do you want?

**Comment by buck-E** [comment] 2020-06-21 23:35
I wrote a new Issue for the error that I think might be related.  This way we can focus on the actual error for this Issue (in my last comment).

**Comment by nijel** [comment] 2020-06-22 11:43
Okay, let's close this and followup in #4073

**Closed by nijel** 2020-06-22 11:43 UTC
Labels: question

**Comment by buck-E** [comment] 2020-06-22 23:02
> Okay, let's close this and followup in #4073

I don't think that's a great idea.  I opened the other Issue because it is different.

This issue is that the webUI shows me a `Server Error` when I try to commit.  Even if the underlying problem is https://github.com/WeblateOrg/weblate/issues/4073, this should not happen and it is a different issue.

**Comment by nijel** [comment] 2020-06-23 09:04
I thought that it's the gpg error what you get here. Check the logs what is actually cause of the error then. Or enable debug mode to show the error details in the browser.

**Comment by buck-E** [comment] 2020-06-24 00:01
Issue should not be considered resolved.  The GPG errors from https://github.com/WeblateOrg/weblate/issues/4073 do not have some reason to create UI errors, but they do.

**Comment by nijel** [comment] 2020-06-24 08:48
Okay, can you please include logs for the `Server Error` you get? Without that there is no way to diagnose this issue.

**Comment by buck-E** [comment] 2020-06-25 00:05
I did ask you to specify which logs you meant, and as I said "he UI is working now that the GPG error is different" so the `Server Error` is gone.  Why the error happened in the first place is not clear.

**Comment by nijel** [comment] 2020-06-25 05:40
Logs showing the actual exception. see https://docs.weblate.org/en/latest/contributing/debugging.html#weblate-logs.

**Comment by buck-E** [comment] 2020-06-25 05:54
Ah.  If you'd said "syslog" when you first wanted logs, I (maybe) could have provided them, although I don't have access to syslog - just the `weblate` user.  But since the error is gone, I can't provdide them anymore anyway.
