### ISSUE TITLE
Poor update performance after git repository update

### ISSUE THREAD

**Issue by SlavekB** [WeblateOrg/weblate#2670] opened 2019-04-01 17:55 UTC
**Describe the bug**
I have a repository that contains many linked components (563 files `pot`) and many translations (approximately 33700 files `po`). I use the `weblate.gettext.msgmerge` addin on all linked repositories.

Recently, I updated Weblate from 3.4 to 3.5.1 and then from Python 2.7.x to Python 3.5.x.

Prior to this update, after commit the updated `pot` files to that git repository, an update in Weblate followed. After 20 to 40 minutes, updated translations were pushed back into the git repository.

After update to Weblate 3.5.1 and Python 3.5, I pushed the updated `pot` files to git repository at 18:38 (UTC), and at 05:06 (UTC) updated translations were pushed back from Weblate to git repository. The same task took an incredible 10.5 hours!

**To Reproduce**
Have a large repository with many linked components and work with it…

**Expected behavior**
I wish it would work as it did with Weblate 3.4 and Python 2.7. The time of 20 to 40 minutes was very good compared to 10.5 hours.

**Server configuration and status**
```
 * Weblate 3.5.1
 * Python 3.5.3
 * Django 1.11.20
 * Celery 4.2.2
 * celery-batches 0.2
 * six 1.10.0
 * social-auth-core 3.1.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.1
 * translate-toolkit 2.3.1
 * translation-finder 1.1
 * Whoosh 2.7.0
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow 4.0.0
 * python-dateutil 2.5.3
 * lxml 4.2.5
 * django-crispy-forms 1.6.1
 * django_compressor 2.2
 * djangorestframework 3.9.2
 * user-agents 1.1.0
 * jellyfish 0.7.1
 * diff-match-patch 20121119
 * pytz 2016.7
 * pyuca 1.1.2
 * PyYAML 3.12
 * Database backends: django.db.backends.mysql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 3.16.6-042stab134.46 (x86_64)
```

```
System check identified some issues:

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.5.1/admin/install.html#collecting-errors

System check identified 1 issue (0 silenced).
```

**Additional context**
I don't know if the problem is caused by update Weblate 3.4 => Weblate 3.5.1 or by update Python 2.7.x => Python 3.5.x, because after updating to Weblate 3.5.1 with Python 2.7.x, I didn't commit to this repository.

For system status information before updating to Weblate 3.5.1 and Python 3.5.x – see #2543

**Comment by nijel** [comment] 2019-04-02 12:09
Can you please look into logs what actually took so long? Actually 3.5.1 is supposed to be a lot faster on big translations due to more aggressive caching and batching while performing updates.

**Comment by SlavekB** [comment] 2019-04-02 13:03
Example of the start of the log at the time commit was pushed and the update started with Weblate 3.4.0 + Python 2.7:
```
[2019-03-03 16:46:47,999: INFO/ForkPoolWorker-3] Lock 140086444616720 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-03 16:46:48,021: INFO/ForkPoolWorker-3] tde/tde-i18n: updating repository
[2019-03-03 16:46:48,022: INFO/ForkPoolWorker-3] Lock 140086444616720 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-03 16:46:53,499: INFO/ForkPoolWorker-3] tde/tde-i18n: update took 5.48 seconds
[2019-03-03 16:48:43,780: INFO/ForkPoolWorker-3] Lock 140086444616720 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-03 16:48:45,425: INFO/ForkPoolWorker-3] tde/tde-i18n: rebase remote into repo
[2019-03-03 16:48:49,689: INFO/ForkPoolWorker-3] Lock 140086444616720 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-03 16:48:49,690: INFO/ForkPoolWorker-3] Lock 140086444616720 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-03 16:48:53,085: INFO/ForkPoolWorker-3] Lock 140086444616720 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-03 16:48:53,086: INFO/ForkPoolWorker-3] Lock 140086444616720 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-03 16:48:55,382: INFO/ForkPoolWorker-3] Lock 140086444616720 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-03 16:48:55,383: INFO/ForkPoolWorker-3] Lock 140086444616720 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-03 16:48:59,407: INFO/ForkPoolWorker-3] Lock 140086444616720 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-03 16:48:59,408: INFO/ForkPoolWorker-3] Lock 140086444616720 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-03 16:49:02,434: INFO/ForkPoolWorker-3] Lock 140086444616720 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-03 16:49:02,435: INFO/ForkPoolWorker-3] Lock 140086444616720 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-03 16:49:06,625: INFO/ForkPoolWorker-3] Lock 140086444616720 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-03 16:49:06,626: INFO/ForkPoolWorker-3] Lock 140086444616720 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-03 16:49:09,490: INFO/ForkPoolWorker-3] Lock 140086444616720 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-03 16:49:09,491: INFO/ForkPoolWorker-3] Lock 140086444616720 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-03 16:49:11,985: INFO/ForkPoolWorker-3] Lock 140086444616720 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-03 16:49:11,985: INFO/ForkPoolWorker-3] Lock 140086444616720 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-03 16:49:14,618: INFO/ForkPoolWorker-3] Lock 140086444616720 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-03 16:49:14,619: INFO/ForkPoolWorker-3] Lock 140086444616720 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-03 16:49:16,701: INFO/ForkPoolWorker-3] Lock 140086444616720 acquired on /var/lib/webl
```

Example of the start of the log at the time commit was pushed and the update started with Weblate 3.5.1 + Python 3.5:
```
[2019-03-31 18:39:46,638: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:39:46,650: INFO/ForkPoolWorker-3] tde/tde-i18n: updating repository
[2019-03-31 18:39:46,650: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:39:53,580: INFO/ForkPoolWorker-3] tde/tde-i18n: update took 6.93 seconds
[2019-03-31 18:39:57,186: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:39:58,419: INFO/ForkPoolWorker-3] tde/tde-i18n: rebase remote into repo
[2019-03-31 18:40:49,601: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:40:50,326: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:40:50,327: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:40:50,506: INFO/ForkPoolWorker-3] tdelibs/katepart/sk: committing ['/var/lib/weblate/data/vcs/tde/tde-i18n/tde-i18n-sk/messages/tdelibs/katepart.po'] as Slávek Banko <slavek.banko@axis.cz>
[2019-03-31 18:40:57,429: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:40:57,503: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:40:57,504: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:40:57,589: INFO/ForkPoolWorker-3] tdelibs/tdetexteditor_isearch/sk: committing ['/var/lib/weblate/data/vcs/tde/tde-i18n/tde-i18n-sk/messages/tdelibs/tdetexteditor_isearch.po'] as Slávek Banko <slavek.banko@axis.cz>
[2019-03-31 18:41:23,977: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:41:23,978: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:42:27,698: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:42:27,699: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:43:23,628: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:43:23,629: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:44:32,763: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:44:32,771: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:45:36,805: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:45:36,805: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:46:37,504: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:46:37,504: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:47:37,146: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:47:37,147: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:48:37,614: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:48:37,615: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:49:37,001: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:49:37,002: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:50:46,366: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-03-31 18:50:46,367: INFO/ForkPoolWorker-3] Lock 140013780178928 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
```

You can see that in the case of Weblate 3.4.0 + Python 2.7, locking is done several times per second, while with Weblate 3.5.1 + Python 3.5 is locked once per minute. Throughout the time it has been seen that the celery process has consistently taken 30-60% load on one core.

**Comment by nijel** [comment] 2019-04-02 13:11
This can just mean that it needs to lock less often (what should be true since 82d44ec3a55db2f9629698d12d084bf480aaf01f). What would be more interesting to see is actual parsing of the files or checks execution to see the problematic parts.

What should give you some additional performance is 42b976bd8d848aad2986450674f92e85833be7f9, this is only regression in 3.5 I remember.

**Comment by SlavekB** [comment] 2019-04-02 14:39
Ok, I'll try backport 42b976bd8d to 3.5.1.

**Comment by nijel** [comment] 2019-04-03 07:36
I don't think this could make that big difference, can you still look into logs what takes so long. It might be one of introduced batching operations:

https://github.com/WeblateOrg/weblate/blob/ac88bc6cbcf727338a5c57f2e8091a91f0cee848/weblate/trans/models/component.py#L1103
https://github.com/WeblateOrg/weblate/blob/ac88bc6cbcf727338a5c57f2e8091a91f0cee848/weblate/trans/models/component.py#L1812
https://github.com/WeblateOrg/weblate/blob/ac88bc6cbcf727338a5c57f2e8091a91f0cee848/weblate/trans/models/component.py#L1826

**Comment by SlavekB** [comment] 2019-04-08 12:03
I have a commit 42b976b applied on my instance. During yesterday pushing the POT file update to the repository, the rebase of repository was correctly executed, but then nothing else followed. No task in the celery queue is waiting, no update has been done.

**Comment by nijel** [comment] 2019-04-08 12:04
Is Celery running? Maybe the task has crashed?

**Comment by SlavekB** [comment] 2019-04-08 12:09
Celery seems to be working without a problem – information about other regular tasks is properly written into the journal, there is nothing waiting in the queue. The only error message was due to memory overrun:

```
[2019-04-07 19:19:34,405: ERROR/ForkPoolWorker-94] child process exiting after exceeding memory limit (694500KiB / 200000KiB)
```

**Comment by nijel** [comment] 2019-04-08 14:31
Try restarting Celery, sometimes it stops executing jobs in case of memory limit (at least I've seen such reports before).

**Comment by SlavekB** [comment] 2019-04-08 14:37
Restarted. I suppose in such a case waiting tasks would be seen. However, in my instance:
```
-> memory@vps: OK
    - empty -
-> celery@vps: OK
    - empty -
-> search@vps: OK
    - empty -
```

**Comment by nijel** [comment] 2019-04-10 06:22
The issue with worker not starting up properly after reaching limit is described here (without resolution though): https://github.com/celery/celery/issues/4809

**Comment by SlavekB** [comment] 2019-04-14 17:58
I turned on the debug log level for Weblate to see what was happening. Something weird is happening there. You can see that there were two tasks. The first was processed by Worker-5 – it was a big repository update. The second was processed by Worker-6 – a small repository update. For update the small repository everything went well – the 'po' files were updated and pushed back into the git repository. Then Worker-6 was killed due to memory consumption. But Worker-5, as if it had ceased to exist, had stopped doing anything, the job had disappeared from the queue, updating large repository was not completed.

Subsequently, I tried to restart the celery demon, but that was useless again. Is there any way I can trigger the repository update? Previously it worked when I gave the rebase of git repository, but now it does nothing.

I'm not sure if this problem is related to celery/celery#4809 because celery jobs seem to be properly processed all the time.

[weblate-celery.log](https://github.com/WeblateOrg/weblate/files/3077666/weblate-celery.log)
[weblate-celery-1.log](https://github.com/WeblateOrg/weblate/files/3077667/weblate-celery-1.log)
[weblate-celery-2.log](https://github.com/WeblateOrg/weblate/files/3077668/weblate-celery-2.log)
[weblate-celery-3.log](https://github.com/WeblateOrg/weblate/files/3077669/weblate-celery-3.log)
[weblate-celery-4.log](https://github.com/WeblateOrg/weblate/files/3077670/weblate-celery-4.log)

**Comment by SlavekB** [comment] 2019-04-14 18:19
Forcing update I solved. I manually did `git reset HEAD~2` – it helped that Weblate considered it as a change and triggered a repository update.

During the update, I see strange behavior – between the `running post_update addon: weblate.gettext.msgmerge` message and the actual execution of msgmerge is a minute delay. What happens in that minute? One core of CPU is loaded by this celery task all the time.
```
[2019-04-14 18:10:23,024: INFO/ForkPoolWorker-4] Lock 139848938822232 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-04-14 18:10:23,024: INFO/ForkPoolWorker-4] Lock 139848938822232 acquired on /var/lib/weblate/data/vcs/tde/tde-i18n.lock
[2019-04-14 18:10:23,553: DEBUG/ForkPoolWorker-4] tdeaccessibility/kmouth: running post_update addon: weblate.gettext.msgmerge
[2019-04-14 18:11:32,972: DEBUG/ForkPoolWorker-4] tdeaccessibility/kmouth: weblate.gettext.msgmerge addon exec: ['msgmerge', '--backup=none', '--previous', '--update', '/var/lib/weblate/data/vcs/tde/tde-i18n/tde-i18n-ar/messages/tdeaccessibility/kmouth.po', '/var/lib/weblate/data/vcs/tde/tde-i18n/template/messages/tdeaccessibility/kmouth.pot']
[2019-04-14 18:11:33,018: DEBUG/ForkPoolWorker-4] tdeaccessibility/kmouth: exec result: b'............................ done.\n'
```

**Comment by nijel** [comment] 2019-04-14 19:17
Looking at the code, it most likely is looking for pending changes. It can certainly be done much faster...

**Comment by nijel** [comment] 2019-04-14 19:33
The possible improvement for this is in https://github.com/WeblateOrg/weblate/pull/2688, it needs some deeper testing though...

**Comment by SlavekB** [comment] 2019-04-14 22:56
Thank you. First, I have to wait until the current task is completed. Then I can make a backport to 3.5.1 and test it.

**Comment by nijel** [comment] 2019-04-19 17:15
Did you get to testing? I've just hit another possible bottleneck and addressed it in https://github.com/WeblateOrg/weblate/commit/778cd855dcaf194a5f91f08165f49c3e2cf1dfba.

If you didn't yet get to testing, you don't need to backport those as 3.6 containing both fixes will be out tomorrow.

**Comment by SlavekB** [comment] 2019-04-19 17:35
I made backport #2688 the day before yesterday. However, for the time being, a large repository has not been updated, so testing has not been done yet.

**Comment by SlavekB** [comment] 2019-04-21 19:04
Thank you – it seems good! Today I did upgrade to Weblate 3.6. After commit with update `POT` files into big repository, updated `PO` files were pushed back into git repository in about one hour.

**Comment by nijel** [comment] 2019-04-21 20:12
Thanks for testing. Closing this issue for now, but apparently there is still room for improvements.

**Closed by nijel** 2019-04-21 20:12 UTC
Labels: question
