### ISSUE TITLE
Handling OpenAI API Call Exceptions for Improved Batch Translation Efficiency

### ISSUE THREAD

**Issue by dxdx123** [WeblateOrg/weblate#12152] opened 2024-07-29 04:04 UTC
### Describe the issue

When I manually execute automatic translation for a large batch of translations, OpenAI Translate often terminates due to API call exceptions. I hope it can automatically skip the errors of the current batch and proceed with the translation of subsequent batches. This would improve the efficiency of the translation process.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

When I manually execute automatic translation for a large batch of translations.

Possible exceptions include:

Exceptions occurring while parsing the returned results.
The number of returned results may not match the number of original requests.
API call timeouts.

### How do you run Weblate?

Docker container

### Weblate versions

5.5.5

**Comment by nijel** [comment] 2024-07-29 11:11
As already mentioned in https://github.com/WeblateOrg/weblate/issues/11806#issuecomment-2255135938, this has been already fixed in https://github.com/WeblateOrg/weblate/commit/b4d31853d2748dcb58813037163fb56219a57e64.

PS: Posting the same question in two places is not really helpful.

**Comment by nijel** [comment] 2024-07-29 11:11
Duplicate of #11834

**Closed by nijel** 2024-07-29 11:11 UTC
Labels: bug, duplicate
