### ISSUE TITLE
ImportError: libtesseract.so.4

### ISSUE THREAD

**Issue by marco-doerig** [WeblateOrg/weblate#9860] opened 2023-09-04 22:39 UTC
### Describe the issue

I get the following error when trying to run Weblate 5 with Docker on an `aarch64` machine.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. git clone https://github.com/WeblateOrg/docker-compose.git weblate-docker
2. added minimal environment variables in `docker-compose.override.yml`

### Exception traceback

```pytb
weblate-weblate-1   | Starting...
weblate-weblate-1   | [2023-09-04 22:31:57,522: WARNING/10] Handled exception: ImportError: libtesseract.so.4: cannot open shared object file: No such file or directory
weblate-weblate-1   | Traceback (most recent call last):
weblate-weblate-1   |   File "/usr/local/bin/weblate", line 8, in <module>
weblate-weblate-1   |     sys.exit(main())
weblate-weblate-1   |              ^^^^^^
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/weblate/runner.py", line 19, in main
weblate-weblate-1   |     utility.execute()
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
weblate-weblate-1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
weblate-weblate-1   |     self.execute(*args, **cmd_options)
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
weblate-weblate-1   |     output = self.handle(*args, **options)
weblate-weblate-1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/check.py", line 76, in handle
weblate-weblate-1   |     self.check(
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 485, in check
weblate-weblate-1   |     all_issues = checks.run_checks(
weblate-weblate-1   |                  ^^^^^^^^^^^^^^^^^^
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
weblate-weblate-1   |     new_errors = check(app_configs=app_configs, databases=databases)
weblate-weblate-1   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/django/core/checks/urls.py", line 14, in check_url_config
weblate-weblate-1   |     return check_resolver(resolver)
weblate-weblate-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/django/core/checks/urls.py", line 24, in check_resolver
weblate-weblate-1   |     return check_method()
weblate-weblate-1   |            ^^^^^^^^^^^^^^
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/django/urls/resolvers.py", line 494, in check
weblate-weblate-1   |     for pattern in self.url_patterns:
weblate-weblate-1   |                    ^^^^^^^^^^^^^^^^^
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
weblate-weblate-1   |     res = instance.__dict__[self.name] = self.func(instance)
weblate-weblate-1   |                                          ^^^^^^^^^^^^^^^^^^^
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/django/urls/resolvers.py", line 715, in url_patterns
weblate-weblate-1   |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
weblate-weblate-1   |                        ^^^^^^^^^^^^^^^^^^^
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
weblate-weblate-1   |     res = instance.__dict__[self.name] = self.func(instance)
weblate-weblate-1   |                                          ^^^^^^^^^^^^^^^^^^^
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
weblate-weblate-1   |     return import_module(self.urlconf_name)
weblate-weblate-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate-weblate-1   |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
weblate-weblate-1   |     return _bootstrap._gcd_import(name[level:], package, level)
weblate-weblate-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate-weblate-1   |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
weblate-weblate-1   |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
weblate-weblate-1   |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
weblate-weblate-1   |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
weblate-weblate-1   |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
weblate-weblate-1   |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/weblate/urls.py", line 25, in <module>
weblate-weblate-1   |     import weblate.screenshots.views
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/weblate/screenshots/views.py", line 39, in <module>
weblate-weblate-1   |     from tesserocr import OEM, PSM, RIL, PyTessBaseAPI, iterate_level
weblate-weblate-1   | ImportError: libtesseract.so.4: cannot open shared object file: No such file or directory
weblate-weblate-1   | Failed to load configuration, please see errors above.
```

### How do you run Weblate?

Docker container

### Weblate versions

weblate/weblate:latest

**Comment by nijel** [comment] 2023-09-05 06:29
Duplicate of https://github.com/WeblateOrg/docker/issues/1944

**Closed by nijel** 2023-09-05 06:29 UTC
Labels: bug, duplicate
