### ISSUE TITLE
CSV load discards everything if some strings are missing

### ISSUE THREAD

**Issue by rthouvenin** [WeblateOrg/weblate#2805] opened 2019-06-07 16:59 UTC
**Describe the bug**
When a monolingual CSV file does not have all the strings that are declared in the source file, then no translation is imported at all. It is still possible to translate them.

**To Reproduce**

1. Create a monolingual CSV file with a few string ids and their translation
2. Create another file for another language, with translations for a subset of the source language
3. Define a component with monolingual CSV format
4. Check % of completion in second language: it is 0%, all strings are reported as missing. 

**Expected behavior**
I was expecting same behaviour as what I've seen for monolingual YAML files: available translations are imported and others are reported as missing, with possibility to translate them.

**Versions**
The `list_versions` fails with this error:

> File "/usr/local/lib/python3.7/dist-packages/weblate/settings.py", line 58, in <module>
    'PORT': os.environ['POSTGRES_PORT'],
  File "/usr/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'POSTGRES_PORT'

I am running Weblate in Docker (latest image) without docker-compose.

**Comment by nijel** [comment] 2019-06-09 17:30
How do you configure the translation component?

The `list_versions` error seems to be caused by passing it different environment than is used on application startup. I'm not really sure how to handle this properly with pure Docker withou compose.

**Comment by rthouvenin** [comment] 2019-06-13 07:50
I use the following configuration:

 - Version control: Git
 - File format: CSV File
 - Filemask: `/some/path/*.csv`
 - Language filter: `^[^.]+$`
 - Monolingual base file: `/some/path/en.csv`
 - Edit base file: Yes
 - New translation: no language additions

Let me know of there are other settings of interest.

**Comment by nijel** [comment] 2019-06-17 14:00
The configuration looks sane. How does the CSV file look like, can you share some example?

**Comment by rthouvenin** [comment] 2019-06-26 09:23
I think I didn't understand fully the conditions to reproduce, I am not able to reproduce the problem on a minimal example :( I will close this and re-open if I encounter the problem again. Thanks for your time.

**Comment by rthouvenin** [comment] 2019-06-26 13:43
Only 30min later I faced the problem again :/
I have now banged my head for 2h trying to understand the exact use case and get to a minimal example, without success. The problem appears somewhat randomly, but I *think* it could be related to parsing CSV files that contain escaped quotes. In some cases, I even saw failures to parse the file properly and the strings were cut "at random" in the file.
Contrarily to what I wrote earlier, it does not seem to be linked to missing strings.

Anyway, I am attaching the smallest example I could get to. There are 3 files: en.csv (base file), fr.csv which is correctly parsed, and ro.csv which shows with all strings as empty in Weblate: [test-csv.zip](https://github.com/WeblateOrg/weblate/files/3330282/test-csv.zip)

**Comment by nijel** [comment] 2019-06-27 09:20
The problem is caused by detection of actual CSV syntax in the translate-toolkit. I takes first 1024 bytes and tries to guess based on that. Depending on what is in those first 1024 bytes this results in different results. You can probably workaround this by using CSV style which can be determined from the first 1024 bytes.

**Comment by rthouvenin** [comment] 2019-06-27 10:21
Ah, now the randomness makes sense :)
It looks like that if I enforce putting quotes around all fields even when not needed, this should solve my problem.
Thanks! :bowing_man: 

Would it make sense to add a warning about this in the documentation? I don't see any reference to it neither in [Weblate doc](https://docs.weblate.org/en/latest/formats.html#csv) nor [translate toolkit](http://docs.translatehouse.org/projects/translate-toolkit/en/latest/formats/csv.html).

**Comment by nijel** [comment] 2019-06-27 11:06
I've added the warning in dc3398a807, but still this should be better addressed in long term.

**Comment by nijel** [comment] 2020-09-15 11:55
The translate-toolkit patch to allow setting of sample length by application: https://github.com/translate/translate/pull/4113

**Closed** 2020-09-21 12:39 UTC
Labels: bug, translate-toolkit
