### ISSUE TITLE
Git squash and linked repositories

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#4185] opened 2020-07-15 12:07 UTC
In this project: https://translate.fedoraproject.org/projects/languages-in-floss/
I have 9 components and two repositories:
* one for https://translate.fedoraproject.org/projects/languages-in-floss/about/
  with 7 linked components
* one for https://translate.fedoraproject.org/projects/languages-in-floss/website-theme/

I updated my pot files, and it refreshed this PR: https://github.com/languages-in-floss/site/pull/6
![image](https://user-images.githubusercontent.com/474883/87543010-38512680-c6a4-11ea-9f84-12e14f1d1051.png)

I would like to have one single commit for po updates per Weblate as it is the same repository.

Worse case scenario: as I activated git squash per author, it should aggregate this commits for the author Weblate.

Thanks for your help :)

**Comment by nijel** [comment] 2020-07-16 08:06
Duplicate of #3707

**Closed by nijel** 2020-07-16 08:06 UTC
Labels: bug
