### ISSUE TITLE
When using comment function user hits rate limit

### ISSUE THREAD

**Issue by rhofer** [WeblateOrg/weblate#3254] opened 2019-11-28 15:07 UTC
**To Reproduce**
1. Go to a Project > component > language'
2. Click on All Strings
3. Apply comments arbitrarely to strings within shortest time (about 10 times)
4. See error in picture:

![image](https://user-images.githubusercontent.com/8058166/69816247-4bd47d80-11f8-11ea-953b-b721a56eef06.png)

According https://docs.weblate.org/en/latest/admin/optionals.html#rate-limiting it is not obvious that rate limiting applies to commenting. It only says "translations".
I'd say if the limit for translations is 30 times within 60 sec, that this should also be sufficient for commenting ... but appealingly I'm kicked out a lot earlier.

Using weblate 3.9.1-2 from hub.docker.com

Remark: I quickly tested same for "Suggest" functionality. This seems ok.

**Comment by nijel** [comment] 2019-11-28 21:39
Duplicate of #3189

**Closed by nijel** 2019-11-28 21:39 UTC
Labels: bug

**Comment by rhofer** [comment] 2019-11-29 05:03
Ah, ok. Wasn't obvious from title in #3189
