### ISSUE TITLE
KeyError 'monthly_changes' on push translation via API

### ISSUE THREAD

**Issue by jorrit** [WeblateOrg/weblate#10460] opened 2023-11-22 10:42 UTC
### Describe the issue

Since 5.2 the following fails:

When POST-ing a partial PO file to `/api/translations/PROJECT/COMPONENT/LANGCODE/file/`, the response is HTTP 400 with content:

```
{
    "file": "'monthly_changes'"
}
```

Sentry contains:

KeyError 'monthly_changes'

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Push a translation to `/api/translations/PROJECT/COMPONENT/LANGCODE/file/`

### Expected behavior

The translation should be accepted and the HTTP response should be 200.

### Exception traceback

```pytb
KeyError: 'monthly_changes'
  File "weblate/api/views.py", line 1110, in file
    not_found, skipped, accepted, total = obj.handle_upload(
  File "contextlib.py", line 80, in inner
    with self._recreate_cm():
  File "django/db/transaction.py", line 307, in __exit__
    connection.set_autocommit(True)
  File "django/db/backends/base/base.py", line 501, in set_autocommit
    self.run_and_clear_commit_hooks()
  File "django/db/backends/base/base.py", line 779, in run_and_clear_commit_hooks
    func()
  File "weblate/trans/models/component.py", line 2528, in _invalidate_triger
    self.stats.update_language_stats()
  File "weblate/utils/stats.py", line 885, in update_language_stats
    self.update_parents(extras)
  File "weblate/utils/stats.py", line 286, in update_parents
    stat.update_stats()
  File "weblate/utils/stats.py", line 303, in update_stats
    self.calculate_basic()
  File "weblate/utils/stats.py", line 311, in calculate_basic
    self._calculate_basic()
  File "weblate/utils/stats.py", line 1197, in _calculate_basic
    super()._calculate_basic()
  File "weblate/utils/stats.py", line 805, in _calculate_basic
    stats[item] = sum(values)
  File "weblate/utils/stats.py", line 788, in <genexpr>
    values = (stats_obj.aggregate_get(item) for stats_obj in all_stats)
  File "weblate/utils/stats.py", line 211, in aggregate_get
    return self._data[name]
```

### How do you run Weblate?

weblate.org service

### Weblate versions

 * Weblate: 5.2
 * Django: 4.2.7
 * siphashc: 2.3
 * translate-toolkit: 3.11.1
 * lxml: 4.9.3
 * Pillow: 10.1.0
 * nh3: 0.2.14
 * python-dateutil: 2.8.2
 * social-auth-core: 4.5.0
 * social-auth-app-django: 5.4.0
 * django-crispy-forms: 2.1
 * oauthlib: 3.2.2
 * django-compressor: 4.4
 * djangorestframework: 3.14.0
 * django-filter: 23.3
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.13.1
 * rapidfuzz: 3.5.2
 * openpyxl: 3.1.2
 * celery: 5.3.5
 * django-celery-beat: 2.5.0
 * kombu: 5.3.4
 * translation-finder: 2.15
 * weblate-language-data: 2023.6
 * html2text: 2020.1.16
 * pycairo: 1.25.1
 * PyGObject: 3.46.0
 * diff-match-patch: 20230430
 * requests: 2.31.0
 * django-redis: 5.4.0
 * hiredis: 2.2.3
 * sentry-sdk: 1.35.0
 * Cython: 3.0.5
 * misaka: 2.1.1
 * GitPython: 3.1.40
 * borgbackup: 1.2.6
 * pyparsing: 3.1.1
 * ahocorasick_rs: 0.20.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.2
 * Python: 3.11.5
 * Git: 2.39.2
 * psycopg: 3.1.12
 * psycopg-binary: 3.1.12
 * phply: 1.2.6
 * ruamel.yaml: 0.18.5
 * tesserocr: 2.6.2
 * boto3: 1.29.2
 * zeep: 4.2.1
 * aeidon: 1.13
 * iniparse: 0.5
 * mysqlclient: 2.2.0
 * Mercurial: 6.5.3
 * git-svn: 2.39.2
 * git-review: 2.3.1
 * PostgreSQL server: 12.1
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.sendgrid.net
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://redis:6379/1, redis://redis:6379/1, regular
 * Platform: Linux 5.4.0-166-generic (x86_64)

### Weblate deploy checks

```shell
System check identified some issues:

INFOS:
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.2/admin/backup.html

System check identified 1 issue (1 silenced).
```

### Additional context

Seems related to #10439. Perhaps `monthly_changes` must be added to `LEGACY_KEYS` (872f989eeb1600af51b27ee28800105a22c5c01b).

**Comment by nijel** [comment] 2023-11-22 11:02
Duplicate of #10439

**Closed by nijel** 2023-11-22 11:02 UTC
Labels: bug, duplicate
