### ISSUE TITLE
New language creates empty components (libre plan)

### ISSUE THREAD

**Issue by kevinpapst** [WeblateOrg/weblate#12180] opened 2024-08-02 11:39 UTC
### Describe the issue

A user created a new language (Catalan):
https://hosted.weblate.org/projects/kimai/-/ca/

This created all components, but 50% of them are empty and contain no translation (something like that was [reported here](https://github.com/WeblateOrg/weblate/discussions/11516)).

This is the first time this issue happened, creating languages in the past never caused such an issue.

Even more strange is the PR: https://github.com/kimai/kimai/pull/5007/files
Some XLF files are entirely empty, but most contain the source keys without target (which seems wrong to me). 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

I tried to delete the component and re-create it, but it still is created with 0 translation keys.
I double checked settings and extension on all components and they match 100%.

### Expected behavior

New language: https://hosted.weblate.org/projects/kimai/messages/ca/ (0 keys)
should have the same amount of keys as base language: https://hosted.weblate.org/projects/kimai/messages/en/

### Screenshots

Component add-ons (same for all components, those with keys and those with missing keys):
<img width="559" alt="Bildschirmfoto 2024-08-02 um 13 37 28" src="https://github.com/user-attachments/assets/72a860de-ecbd-4ab1-8350-8b3d03a2699b">

Global add-ons:
<img width="757" alt="Bildschirmfoto 2024-08-02 um 13 37 43" src="https://github.com/user-attachments/assets/914cecf7-eea1-478e-92e2-ff08b64130d8">

Manage strings is disabled everywhere:
<img width="270" alt="Bildschirmfoto 2024-08-02 um 13 39 02" src="https://github.com/user-attachments/assets/006d1858-4ea0-4df6-901b-fbf7ccf3b806">

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment] 2024-08-02 18:29
Duplicate of #12106

**Closed by nijel** 2024-08-02 18:29 UTC
Labels: bug, duplicate
