### ISSUE TITLE
Zen mode Tab order reversed when descending

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#9015] opened 2023-03-30 07:29 UTC
### Describe the issue

I wanted to translate in Zen mode but sorted the string in descending order, now the tab moves the focus backwards.

Translated the first sentence and hit "Tab", now the focus switched to the Logo.
If I'm switching to the second string, translate it and hit Tab, now the focus is being switched to the first string.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to component translation.
2. Click 'Zen Mode'
4. Click on '![image](https://user-images.githubusercontent.com/406826/228759960-59405be3-0e1a-45e1-9868-1af7f55301f9.png)' so it becomes '![image](https://user-images.githubusercontent.com/406826/228760118-ce270059-1e96-42fb-8f74-eb6b1c4316b0.png)'
5. Translate one of the strings.
6. When done hit Tab.

### Expected behavior

It should probably scroll to the next string instead of the previous one.

### Screenshots

![image](https://user-images.githubusercontent.com/406826/228760702-100899e1-1c0f-4936-8039-4a1bbafafed7.png)
An example of OsmAnd in reversed Zen mode.

### How do you run Weblate?

weblate.org service

### Weblate versions

Tried with several instances and various versions, happened in all of them:
elementary OS, Fedora, LibreOffice, hosted.

**Comment by nijel** [comment] 2023-03-30 08:04
Duplicate of #6236

**Closed by nijel** 2023-03-30 08:04 UTC
Labels: bug, duplicate

**Comment by yarons** [comment] 2023-03-30 08:19
You're right, I'm not sure how I missed that, sorry.

**Comment by nijel** [comment] 2023-03-30 08:25
It had a confusing title, I've just renamed it.
