### ISSUE TITLE
Analysis issues do not link to content

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2106] opened 2018-06-27 14:00 UTC
This is the e-mail I got about QR Code Generator/Translations
"
'Expecting property name enclosed in double quotes: line 2 column 3 (char 4)'

Erroneous file

src/_locales/en/messages.json"

Would expect link to source and respective Weblate section here.

**Comment by nijel** [comment] 2018-06-27 19:56
In this case Weblate failed to parse the file, so the content is not in Weblate and it has to be fixed in the VCS directly. Suggestions to improve the mail are of course welcom.

**Comment by comradekingu** [comment] 2018-06-27 20:00
@nijel I was thinking the e-mail could link to the file in the VCS.

**Comment by nijel** [comment] 2018-06-27 20:17
Unfortunately there is no detailed information from the parser, so this is best error message we can provide.

Link to the VCS should be doable if project has set repository web browser, what is unfortunately not the case for most non Gettext projects...

**Comment by nijel** [comment] 2022-07-14 09:39
Link to the file should be easy to add since 4b2e079b80103364292464b585186943b7172890 does this in the UI.

**Comment by ParthS007** [comment] 2022-07-16 14:58
After going through the mentioned commit and the code, I found that, here => https://github.com/WeblateOrg/weblate/blob/main/weblate/templates/mail/parse_error.html, we parse the error and send it in the mail.

I made some changes in the template to test but I am not able to reproduce the issue. Can you please point me to the views code or where the mail is using this template? Thanks

**Comment by nijel** [comment] 2022-07-17 12:30
This is triggered in case the file in the repository cannot be parsed.

In the debug mode, you can also render individual change events directly without going through e-mail when browsing history by clicking on the bell icon.

**Closed** 2022-08-18 07:57 UTC
Labels: enhancement, good first issue
