### ISSUE TITLE
Feature: non-translatable strings

### ISSUE THREAD

**Issue by SirAnthony** [WeblateOrg/weblate#743] opened 2015-05-14 07:56 UTC
Hello,
Some of strings in several languages can have no translations (names, brands), or have same spelling as original translation (No -> No). Currently there is two ways: to ignore it and left blank, or copy translation and have failed check. It will be nice to have possibility to mark string as non-translatable, to keep it as-is and do not fail the check. 
##

**Comment by nijel** [comment] 2015-05-14 08:03
Why don't you just mark the string as non translatable in the project
itself? I don't think that non-translatable strings should appear in
files to translate. Indeed it can be handled in Weblate somehow, but
once somebody downloads the file, this information is gone...

-- 
	Michal Čihař | http://cihar.com | http://blog.cihar.com

**Comment by SirAnthony** [comment] 2015-05-14 10:02
Some non-transalatable strings can have translation in some languages (for example: arabic, japaneese, other with non-latin letters can have spelling for words in their language).
Current routine we use is to drop all strings which have matched key & value (as you suggested), before committing it to repository, but weblate still keep it (because english source have all strings) and convert to missing value. It confuses users and they keep translating non-translatable strings by inserting same value (then we commit it back to git, scripts remove same strings, and weblate creating blank fields again).

**Comment by emmapeel2** [comment] 2016-08-26 07:51
Our components are generated by a software that sometimes creates strings like 
`<div class="tip">`

It would be great to be able to hide them per-project, taking them out of the translation interface somehow, or translate them all at once.

**Comment by hram** [comment] 2018-02-07 09:10
Can I wote for this issue?
It would be great if I can mark string for specific language as "ignore-same"
For examle russian and ukrainian languages have more common strings
And this strings need to translate on other languages
I can not mark this strings as translatable="false"
But if strings the same I have warning https://docs.weblate.org/en/weblate-2.18/user/checks.html#check-same

**Comment by nijel** [comment] 2018-02-07 18:26
You can vote for this issue by money at https://www.bountysource.com/issues/14803450-feature-non-translatable-strings ;-)

**Comment by fennibay** [comment] 2019-01-15 12:50
Hi @nijel, since I'm also interested in this due to #2490, can you give a rough idea how much effort it would be to implement this?

**Comment by nijel** [comment] 2019-01-17 08:52
Doing that purely on content of the translation file (like you proposed in #2490) would be quite easy - it's just matter of implementing desired logic in `is_translatable` method on file format unit. The problem is that it would make it bound to single file format. Another issue might be that gettext tools do not like unknown flags (like you've introduced), so they won't work with typical xgettext/msgupdate workflow...

My original intention was to have this generic, but that brings other challenges in Weblate (how to store flags for units which should not be stored in Weblate).

**Comment by alesrosina** [comment] 2019-01-17 09:40
But you already have a custom flag, at least as far as I understood .po files - and that is `max-lenght:`, so adding this one would be same story ... or am I missing sth here?

**Comment by nijel** [comment] 2019-01-17 09:54
That flag is typically stored only in Weblate (technically you can also store it in the po file, but that was not the main intention). All flags can be parsed from the file (if the format supports it, so pretty much only gettext) or set in Weblate.

**Comment by alesrosina** [comment] 2019-01-17 09:59
Exactly, so this could be the same case for this flag - you can set it in weblate or it can be passed over in .po file - with this you ensure not to break any flows with gettext tools.

Maybe just a tag shoud be `#, allowed-langs:en|de|cz, max-length:100, fuzzy, c-format` so you would not break the thing. 

Again, just thinking out loud, maybe I am missing sth here :)

**Comment by nijel** [comment] 2019-01-17 10:22
The problem is that all native gettext tools just ignore this. So when you add these to pot file and run `msgmerge`, it becomes just `#, fuzzy, c-format` without any warning. But yes, Weblate would have no troubles in parsing those. Still this is solution just for single file format and I'd like to have something more generic.

**Comment by alesrosina** [comment] 2019-01-17 14:16
But for other file formats it could be enabled by hand, just like `max-length` is available only for .po files - but can be added later via UI.

**Comment by nijel** [comment] 2019-01-17 14:54
That's the problem I was mentioning few comments above - there is no way to specify flags in Weblate for strings which should not be present in Weblate. What we most likely need in the end is concept of non editable strings which would be properly loaded in Weblate, just marked as non editable and not shown to users when translating.

**Comment by nijel** [comment] 2019-02-28 11:54
Importing non translatable strings from the storage in some form would avoid confusion like in https://github.com/WeblateOrg/weblate/issues/2544.

**Comment by nijel** [comment] 2019-10-29 19:11
Thank you for your report, the issue you have reported has just been fixed by https://github.com/WeblateOrg/weblate/pull/3155.

* In case you see a problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Closed by nijel** 2019-10-29 19:11 UTC
Labels: enhancement
