### ISSUE TITLE
Support for xliff generic placeholder - <x />

### ISSUE THREAD

**Issue by ddukstas** [WeblateOrg/weblate#1535] opened 2017-06-29 07:59 UTC
Xliff entry with variables in it looks something like this:
```
<trans-unit id="6644865400824058724" datatype="html">
    <source>Shot by player <x id="PLAYER"/></source>
</trans-unit>
```
### Actual behaviour
Weblate UI does not seem to handle [\<x />](http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#x) tags - it just omits it from source field.
[example screenshot](https://ibb.co/crFgTQ)

### Expected behaviour
\<x /> placeholders should be displayed in translation source input field, so that translators would be aware of them. There should also be a way to enter these placeholders in translation target input field.

**Comment by PowerKiKi** [comment] 2018-10-24 22:40
@nijel, since this is a blocker for me, I'd be willing to submit a PR for it, but I have no experience in Weblate. Could you point me in the right direction, on how to contribute in general, and what should be done in what part of code for this specific feature ?

**Comment by nijel** [comment] 2018-10-26 12:56
Good point, it indeed is (though it doesn't specifically mention placeholders).

Duplicate of #490

**Closed by nijel** 2018-10-26 12:56 UTC
Labels: enhancement
