### ISSUE TITLE
Smart merge of po files

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#55] opened 2012-07-02 15:54 UTC
It should be possible to write smarter po file merger for git, actually using content of the files and pushing translations to new template. It might be indeed complex, but should by doable.
##

**Comment by quinox** [comment] 2015-10-27 19:53
I ran into a conflict today where the only difference was the po header timestamp.

I haven't tested it yet, but looking around I found [this gist](https://gist.github.com/mezis/1605647) which points to [git-whistles](https://github.com/mezis/git-whistles#merge-po). The heavy lifting by `git-whistles` is done by `msgmerge`/`msgcat`/`msguniq`, the driver itself doesn't do any `.po` parsing ([source code](https://github.com/mezis/git-whistles/blob/master/libexec/git-merge-po.sh) / [explanation](https://github.com/mezis/git-whistles/issues/42#issuecomment-94379526))

**Comment by nijel** [comment] 2015-10-29 13:11
There is already one po merge driver in Weblate sources: https://docs.weblate.org/en/latest/admin/continuous.html#updating-repositories

**Comment by nijel** [comment] 2017-05-19 12:50
Just to document current state:

* Weblate currently tries to use [git-merge-gettext-po](https://github.com/WeblateOrg/weblate/blob/master/examples/git-merge-gettext-po) as a merge driver
* However as that is shipped under examples, it doesn't find it on pip installed systems, this should be fixed
* Maybe it would be better to base the merge driver on something more clever, for example https://github.com/jan-hudec/podiffutils

**Comment by stanislav-brabec** [comment] 2017-05-19 14:03
Well, even msgcat alone (from gettext tools) is capable to perform the merge. But the merge itself is not sufficient. Most probably, the source of the conflict is pot file change and corresponding po file edit.
We want:
```shell
msgcat --use-first from_weblate.po from_upstream.po -o intermediate.po
msgmerge --previous --lang=my_language intermediate.po new_pot_file.pot -o merged.po
rm intermediate.po
```
Here is a problem: Weblate knows where the pot file is. Git does not. gettextize/autopoint knows it as well (because it creates the infrastructure). ⇒ It would be nice to integrate this feature to gettext tools, and additionally add to a tool generating a merge script (needs access to weblate component description).

Also note, that such a generic script requires pot file being merged before all po files.

Note that it would be better to replace --use-first by --use-latest (using PO-Revision-Date), but it is not implemented in gettext yet.

**Comment by jan-hudec** [comment] 2017-05-24 18:33
> Here is a problem: Weblate knows where the pot file is. Git does not.

And I believe it shouldn't be relevant. Merge is a merge and the best approach is to do a 3-way merge. I have prototyped 3-way merge for PO files in https://github.com/jan-hudec/podiffutils. I have used it on project for some time (before changing jobs last summer) and it worked. It would deserve integrating into translate-toolkit, but it would need to be polished a bit first.

> Also note, that such a generic script requires pot file being merged before all po files.

Not if you do a 3-way merge. Also, the only way to merge the pot is a 3-way merge and the algorithm is the same for pot and po, because pot is just a po with no translations filled.

**Comment by Jibec** [comment] 2019-05-14 14:02
hello, thanks to your documentation and my lack of patience, I wrote this script: https://pagure.io/fedora-docs/translations-scripts/blob/master/f/solve_weblate_merge_failures.sh

only the pot file path is specific to the way the localization are stored: https://pagure.io/fedora-docs/translations-scripts/blob/master/f/solve_weblate_merge_failures.sh#_43

If I understand correctly, weblate should be able to provide the upstream repository to this script (and the full path of the local git repo for the weblate's one, yes, you can git clone /any/local/path)

As we already have the "new_base", exposed by the component API, I assume this should be possible to automate it?

**Comment by eighthave** [comment] 2020-03-23 15:16
In my experience, one of the biggest ongoing source of git merge conflicts are the gettext fields `POT-Creation-Date:` and `PO-Revision-Date:`.  So I would not like to see those fields be required by Weblate, e.g. `--use-latest`.  IMHO, I think they should be stripped if possible.

**Comment by stanislav-brabec** [comment] 2020-03-23 22:43
> So I would not like to see those fields be required by Weblate, e.g. `--use-latest`. IMHO, I think they should be stripped if possible.

I disagree. These fields are mandatory for po file format. And they are one of most important fields for human review, e. g. check of maintenance status, check that po files are in sync with pot.

**Comment by eighthave** [comment] 2020-03-24 08:33
In the context of Weblate, the .po files will always be committed to
git.  That means there will always be a date of the git commit.  So for
.pot files, POT-Creation-Date could be derived from the last git commit
that contains a change to the .pot file.  For .po files,
PO-Revision-Date could be derived from the last git commit that changed
that .po file.  But that could be complicated sometimes.

I guess those dates are used in the merge/update processes?  Seems to me
that PO is the only format that has them.  In my experience, it would be
worth it to me to disable the features that require POT-Creation-Date
and PO-Revision-Date so that there will be fewer merge conflicts.

But maybe you have something else in mind to solve this?

**Comment by stanislav-brabec** [comment] 2020-03-24 12:24
> it would be worth it to me to disable the features that require POT-Creation-Date and PO-Revision-Date so that there will be fewer merge conflicts.

1. Again, these fields are mandatory parts of the file format definition (established 25 years ago). Third party tools can reject these po files, fail, or even applications and webs can fail (any runtime tool can check this header, and many really do it when they display translation credits). You would need to initiate file format definition change negotiation, and then request modification of all tools that depend on it, software and even webs. It would require ~10 years to complete.

2. It would make impossible fast translation status check. That it why the above will be rejected by GNU/FSF.
Example: `gettext libc '' | grep ^PO-Revision-Date:` allows to check glibc translation age in the _runtime_. There is no alternative for this feature.

3. Merge conflicts are caused by a diff/patch merge algorithm that is inferior for po files. This bug addresses it in the right way. Once we will provide the correct merge algorithm, rejects will rarely occur.

**Comment by eighthave** [comment] 2020-03-24 12:47
If there is a standard way to manage git merge algorithms for specific
file types, and this can be included in GNU/Linux and git distros, then
I think that sounds like a good solution.  Or maybe it would be enough
that the Weblate server is setup with this PO merge algorithm, but my
guess is no.

**Comment by stanislav-brabec** [comment] 2020-03-24 18:10
> If there is a standard way to manage git merge algorithms for specific file types

Git has support for custom merge strategies. https://git-scm.com/docs/git-merge#_merge_strategies

**Comment by eighthave** [comment] 2020-03-24 20:49
right, I mean that if it is something that can be included when someone
does `apt-get install weblate` or something like that.  I think it is
important that whatever the solution is, it is easy to deploy and
transparent to use.

**Comment by stanislav-brabec** [comment] 2020-03-25 01:51
> right, I mean that if it is something that can be included when someone does `apt-get install weblate` or something like that. I think it is important that whatever the solution is, it is easy to deploy and transparent to use.

It is not related with Weblate. But yes, ideally Weblate should install it automatically to hosted git repositories.

It is easy to do such three way merge manually:
```
msgcat --use-first local-old.po remote.po -o temporary.po # or new --use-newest feature
msgmerge --previous temporary.po local-new.pot -o local-new.po
rm temporary.po
```
Writing a generic three way merge command working with any translation layout is more complicated.

**Comment by cpa-level-it** [comment] 2020-04-09 09:40
> > it would be worth it to me to disable the features that require POT-Creation-Date and PO-Revision-Date so that there will be fewer merge conflicts.
> 
> 1. Again, these fields are mandatory parts of the file format definition (established 25 years ago). Third party tools can reject these po files, fail, or even applications and webs can fail (any runtime tool can check this header, and many really do it when they display translation credits). You would need to initiate file format definition change negotiation, and then request modification of all tools that depend on it, software and even webs. It would require ~10 years to complete.
> 2. It would make impossible fast translation status check. That it why the above will be rejected by GNU/FSF.
>    Example: `gettext libc '' | grep ^PO-Revision-Date:` allows to check glibc translation age in the _runtime_. There is no alternative for this feature.
> 3. Merge conflicts are caused by a diff/patch merge algorithm that is inferior for po files. This bug addresses it in the right way. Once we will provide the correct merge algorithm, rejects will rarely occur.

While I agree it's a standard I still think that 

- For most of the user using only weblate thoses fields are useless has the files are in git
- Most of the "newbie" users will encounter this merge problem and won't want to dig deeper into git to handle the merge

I say let the end-user make its own decisions and decide if he want it in the file or not.
If this doesn't break other functions inside Weblate of course.

**Comment by mikkorantalainen** [comment] 2021-08-16 12:19
Here's a more generic 3-way merge for .po files: https://stackoverflow.com/a/68799310/334451

**Closed** 2021-09-08 07:50 UTC
Labels: enhancement

**Comment by burner1024** [comment] 2023-05-26 06:14
@nijel so is this script used automatically by Weblate or needs additional configuration? I can't make it out from comments, and it's not mentioned in the documentation as far as I can see.
> Install with git config...
> Note that you also need file `.gitattributes` with following lines...
> This merge driver is now automatically installed for all Weblate internal...

**Comment by nijel** [comment] 2023-06-01 09:44
Please avoid posting the same question twice, https://github.com/WeblateOrg/weblate/issues/9328 already has the answer.

**Comment by burner1024** [comment] 2023-06-01 10:00
I asked here first. Since there was no response for a few days, I assumed you didn't see the notification.
Didn't mean to bother, sorry.
