### ISSUE TITLE
TTF_FONTS wrong?

### ISSUE THREAD

**Issue by Flohack74** [WeblateOrg/weblate#2173] opened 2018-08-12 06:16 UTC
Over night, I suddently got this amounts of errors sent by mail:

![grafik](https://user-images.githubusercontent.com/16186470/43999178-825cb89c-9e07-11e8-84cc-d77985f18ebe.png)

The error is:

```
Internal Server Error: /widgets/ubports-docs/zh_Hans/documentation-userguide/svg-badge.svg

ImproperlyConfigured at /widgets/ubports-docs/zh_Hans/documentation-userguide/svg-badge.svg
Failed to load truetype fonts, maybe your TTF_PATH is wrong?
```

Actually I checked the TTF_PATH variable, and its definitely pointing to the path with some TTF fonts. But I cant make up any idea what really is the problem here.

**Comment by nijel** [comment] 2018-08-12 06:41
It needs to be path to fonts shipped with Weblate - https://github.com/WeblateOrg/weblate/tree/master/weblate/ttf

**Comment by nijel** [comment] 2018-08-12 06:42
There should be system check for this so that the problem is visible before failing requests...

**Comment by Flohack74** [comment] 2018-08-12 07:36
Actually it is - the path is from default config and I did not change:
`TTF_PATH = u'/opt/weblate/local/lib/python2.7/site-packages/weblate/weblate/ttf'
`
Which is:
![grafik](https://user-images.githubusercontent.com/16186470/43999763-2f7ca7b6-9e13-11e8-829b-73ab61064ed9.png)

Sorry to not mention we are still on 2.20 - I will upgrade to latest during next 2 weeks or so.

**Comment by Flohack74** [comment] 2018-08-12 07:37
Uh no I  see directory replication TTF_PATH has 2 times weblate inside - how does this come?

**Comment by nijel** [comment] 2018-08-12 11:35
What is twice there? The files or setting?

**Comment by nijel** [comment] 2018-08-12 11:37
Thank you for your report, the issue you have reported has just been fixed by adding system check to complain about wrong setting earlier. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Closed** 2018-08-12 11:37 UTC
Labels: enhancement
