### ISSUE TITLE
Language section is not in the Django admin anymore

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#3706] opened 2020-04-09 14:47 UTC
**Describe the bug**
Contrary to what the documentation specify in https://docs.weblate.org/en/weblate-3.9.1/admin/languages.html and https://docs.weblate.org/en/weblate-3.9.1/admin/admin.html#admin-interface I don't have any "Weblate languages" section in Weblate 3.9.1.

**To Reproduce**
1. Go in Django administration
2. Look for language section

**Expected behavior**
The section was there in 3.8. 

**Screenshots**
![Capture d’écran_2020-04-09_16-43-08](https://user-images.githubusercontent.com/1478232/78907889-9bb63180-7a81-11ea-936d-e013355f5817.png)

**Comment by nijel** [comment] 2020-04-09 14:54
Duplicate of #3157

**Closed by nijel** 2020-04-09 14:54 UTC
Labels: bug

**Comment by surli** [comment] 2020-04-09 14:58
From what I see in #3157 the admin section is only available in Debug mode in 3.9.1 right? Is that true for newer versions? Shouldn't the documentation be updated?

**Comment by nijel** [comment] 2020-04-09 15:03
Yes that's true for 3.9, later this change was reverted, see https://github.com/WeblateOrg/weblate/commit/2b71589a0e5baa3224333691673ba8c764547209

**Comment by surli** [comment] 2020-04-09 15:08
Ok thanks for the confirmation.
