### ISSUE TITLE
Disabling fuzzy matches possible (gettext) ?

### ISSUE THREAD

**Issue by ReneBoehm** [WeblateOrg/weblate#2691] opened 2019-04-16 13:49 UTC
Is it possible to disable fuzzy matching when using gettext (with a gitlab hook) ? It's confusing our people ;) The reason is that they are focused on finding untranslated strings. But the fuzzy matches are creating very confusing and wrong translations.

**Comment by nijel** [comment] 2019-04-16 14:14
Duplicate of #2690

**Closed by nijel** 2019-04-16 14:14 UTC
