### ISSUE TITLE
Feature request: honor the work of people suggesting the same translation again

### ISSUE THREAD

**Issue by CodingSpiderFox** [WeblateOrg/weblate#8001] opened 2022-08-12 22:25 UTC
### Describe the problem

I went to this missing translation and tried to suggest a translation but it lead to an error because the same translation was already existing
![Screenshot from 2022-08-13 00 23 34](https://user-images.githubusercontent.com/25173078/184452228-ce569476-67d0-4ca6-9cf7-32c1a812ef92.png)

### Describe the solution you'd like

What I would like is that the suggestion is saved without error and just my avatar appear next to the already existing translation from before

**Comment by nijel** [comment] 2022-08-15 08:45
Duplicate of #7705

**Closed by nijel** 2022-08-15 08:45 UTC
Labels: duplicate
