### ISSUE TITLE
Showing non printable characters

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#3453] opened 2020-02-07 14:24 UTC
**Is your feature request related to a problem? Please describe.**
Someone added some RLM and LRM characters in a very uncoditional way in the LibreOffice translation and now we need to go over it and remove these characters where unnecessary.

**Describe the solution you'd like**
In Pootle there was a button to show the raw string I'm working on (like switching modes) and everytime something was suspicious I would switch to that mode and remove the exces characters.

**Describe alternatives you've considered**
It can be turned on all the time if the unprintable charactes will have colors or something so we'll know it's not part of the text and the user won't see it, but I don't think everybody will like it that way.

**Additional context**
Weblate already has a support for typing this kind of characters but not displaying them or searching for them, it might become an obstable in the future when we'll continue working on LibreOffice on their new Weblate system.

**Comment by nijel** [comment] 2020-02-08 07:29
Duplicate of #1930

**Closed by nijel** 2020-02-08 07:29 UTC
Labels: enhancement, duplicate
