### ISSUE TITLE
UTF-8 for XLIFF-files 

### ISSUE THREAD

**Issue by eschumacher-99** [WeblateOrg/weblate#5151] opened 2021-01-06 10:10 UTC
Hello, 
I've noticed that HTML entities used in XLIFF files arn't converted to UTF-8 on Weblate.
This is something that would make working with Weblate almost impossible for our translators. 
I did notice that this enhancement was already added to the todo list, but I would like to ask when to expect the solution?

Also, are there any other file formats that cause less problems concerning the encoding and the state of translation?
As far as I've seen, GNU Gettext format would be best practise, is that correct?

![image](https://user-images.githubusercontent.com/77051325/103756258-668a4000-500f-11eb-9a9f-b2cd9a91b0e9.png)
This is one of the HTML entities I'm talking about, which should be shown as "Hello, world! <" 

![image](https://user-images.githubusercontent.com/77051325/103756423-9e918300-500f-11eb-8874-eac2dc0bce96.png)
This is the xliff file taken from an example for xliff files.

**Comment by nijel** [comment] 2021-01-06 13:05
Duplicate of #3081

**Closed by nijel** 2021-01-06 13:05 UTC
Labels: enhancement, duplicate

**Comment by eschumacher-99** [comment] 2021-01-06 14:22
I did notice that this enhancement was already added to the todo list, but I would like to ask when to expect the solution?

Also, are there any other file formats that cause less problems concerning the encoding and the state of translation?
As far as I've seen, GNU Gettext format would be best practise, is that correct?

**Comment by nijel** [comment] 2021-01-06 14:29
There is no schedule on that, but in case you want to discuss that, please followup in the original issue.

The XML formats with possibly nested tags are problematic in this. Once the nested XML tags are allowed, the XML entities encoding must follow that behaviour. If you don't need the inner XML markup, anything besides XLIFF and Android resource strings will probably do a better job in this regard.
