### ISSUE TITLE
How to completely turn off email notifications

### ISSUE THREAD

**Issue by jzahradn** [WeblateOrg/weblate#3697] opened 2020-04-08 14:09 UTC
Hi,
I am creating bulk components via requests.post in Python.
After the post command when component is created our partners who also use Weblate are notified about event 'Created component'.
They are asking us what is happening so I would like to completely turn off notifications somewhere in the settings. Is it possible to do it easily in gui or in settings.py? I have tried to find it in the documentation but not successful with it.

Thank you
Regards
Jan

**Comment by nijel** [comment] 2020-04-08 14:16
Duplicate of #3511

**Closed by nijel** 2020-04-08 14:16 UTC
Labels: documentation, duplicate

**Comment by jzahradn** [comment] 2020-04-09 10:36
I have followed the instruction from: https://github.com/WeblateOrg/weblate/issues/3511 and added to settings.py this line: EMAIL_BACKEND = 'django.core.mail.backends.dummy.EmailBackend'

This is part of my settings.py now:

# Reverse proxy settings
IP_PROXY_HEADER = "HTTP_X_FORWARDED_FOR"
IP_BEHIND_REVERSE_PROXY = False
IP_PROXY_OFFSET = 0

# disable sending emails
EMAIL_BACKEND = 'django.core.mail.backends.dummy.EmailBackend'

# Sending HTML in mails
EMAIL_SEND_HTML = True

# Subject of emails includes site title
EMAIL_SUBJECT_PREFIX = "[{0}] ".format(SITE_TITLE)


However, users are still notified about creating components. This email was generated after settings.py was changed:

From: Jan Zahradnik <translate@XY.com> 
Sent: Thursday, April 9, 2020 11:45 AM
To: 
Subject: [Weblate] New translation component XY/Web server - Framework - UI_MS7.2

 Created component 
 zahradnik: Weblate / XY / Web server - Framework - UI_MS7.2 
Component Information 
Languages	1
All strings	0
Translated strings	0	100%
Not translated strings	0	0%
Strings needing action	0	0%
Strings marked for edit	0	0%

**Comment by nijel** [comment] 2020-04-09 19:18
Did you restart both wsgi and celery processes?

**Comment by jzahradn** [comment] 2020-04-15 10:28
I have solved it by creating new project with no subscription, then I created components in this project
