### ISSUE TITLE
How disable contact form?

### ISSUE THREAD

**Issue by perrfect** [WeblateOrg/weblate#9479] opened 2023-06-29 10:46 UTC
### Describe the issue

I'm using Weblate in docker-compose.
How can disable contact form to restrict access via the Internet?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

I tried to use `WEBLATE_CONTACT_FORM=0`, but the form is still working.

### How do you run Weblate?

Docker container

**Comment by nijel** [comment] 2023-06-30 12:27
Duplicate of #9353

**Closed by nijel** 2023-06-30 12:27 UTC
Labels: question
