### ISSUE TITLE
Eliminar registro

### ISSUE THREAD

**Issue by GustavoGirardelli** [WeblateOrg/weblate#8220] opened 2022-10-15 17:10 UTC
borrar cuenta de  Weblate

delete weblate account

Delete weblate record

Eliminar registro Weblate

**Comment by GustavoGirardelli** [comment] 2022-10-15 17:12
Ooooooooo......

**Comment by GustavoGirardelli** [comment] 2022-10-15 17:15
Oooo...


*      Lic. Gustavo A. Girardelli    .*

*.*

**Comment by nijel** [comment] 2022-10-17 09:25
Duplicate of #8219

**Closed by nijel** 2022-10-17 09:25 UTC
Labels: question, wontfix
