### ISSUE TITLE
Language-wide search and UI

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3701] opened 2020-04-09 11:03 UTC
It is possible to search project-wide https://hosted.weblate.org/#search

Curiously that view has two buttons that are duplicated in the top menu.
>Tools > 
All languages
All projects

In [project](https://hosted.weblate.org/languages/nb_NO/remmina/) and [component](https://hosted.weblate.org/projects/remmina/remmina/nb_NO/) view "Search" has a tab of its own

In any [language overview](https://hosted.weblate.org/languages/nb_NO/) there is no search, neither by tab or by menu. I prefer the tab.

**Comment by nijel** [comment] 2020-04-09 11:21
The duplicated items are there for historical reasons, but with 4.0 release it's probably good time to remove them, but please let's keep one topic per issue, thanks :-).

**Comment by nijel** [comment] 2020-04-09 11:22
As a workaround you can already do this on site-wide search by incliding `language:nb_NO` in the search query.

**Comment by Ricky-Tigg** [comment] 2021-03-26 13:29
What a pity; Sending a duplicate of the present. So `language:nb_NO` was presented here as a workaround; let's see is that so.

Option invariably available is that default: 
_Translated strings in a certain language_ | `is:translated AND language:cs` | <kbd>Add</kbd>

- To be coherent the default **language code** is expected to refer to _English_. Here though it is `cs`; indeed invoking a search query with default, covers a language referred there as _Czech_.
- Invoking a search query that suits a legitimate need would require to modify by hand the original filter string in order to become `language:fi`. Such dependency on users to get right things done does not look like any more what a well developed translation platform is aimed to be. A bit annoying isn't it that Fedora organisation decided to chose it.

**Comment by nijel** [comment] 2021-03-26 15:36
Thanks for providing useful feedback. Did you notice that that section is labelled "Query examples"?

**Comment by Ricky-Tigg** [comment] 2021-03-26 16:19
Thank you; that is the _action-reaction_ model applied. _Query examples_ | That's precisely where my above mentioned expression '_Translated strings in a certain language_ | `is:translated AND language:cs` | <kbd>Add</kbd>' came from. The section illustrates a knowledge that developers have, not common mortals.

**Comment by nijel** [comment] 2021-03-26 17:21
It has been described as a workaround not as a final solution. Somebody just needs to implement the search UI properly.

**Closed** 2021-04-16 12:02 UTC
Labels: enhancement, good first issue, hacktoberfest, help wanted
