### ISSUE TITLE
How to add new translation key using weblate?

### ISSUE THREAD

**Issue by desmax** [WeblateOrg/weblate#1145] opened 2016-06-07 04:21 UTC

**Comment by nijel** [comment] 2016-06-08 09:01
You need to add it to the translation files in git. This is usually managed by developers, not by translators. See also https://docs.weblate.org/en/latest/faq.html#does-weblate-update-translation-files-besides-translations

**Comment by desmax** [comment] 2016-06-08 09:26
Ok, then I have a feature request. Its not handy to add it manually to translation files(at least I have to check for duplicates)

**Comment by nijel** [comment] 2016-06-21 11:48
So far this have been considered out of scope for Weblate, but it seems that it makes some sense for monolingual translations...

**Comment by Enalmada** [comment] 2016-09-13 04:33
As a prospective user looking at the online demo, I became quite frustrated trying to figure out how to add new key.  I am new to translation tools so I could be missing something but Weblate seems so close to letting developers transcend having to maintain each individual language file repetitively.  Given enough time, manual updates cause message files get out of order, developer forgets to add/rename/remove a key from one language.   Any reason not to have an "add key" button that adds a specified key to all languages and defaults value to machine translation unverified?

**Comment by nijel** [comment] 2016-09-27 16:04
The translation keys are usually managed by tools which keep them in sync with the code (eg. xgettext/msgmerge), so there is no need to do that manually.

**Comment by lawmaestro** [comment] 2017-08-22 08:06
So the approach we've taken unfortunately means the likes of xgettext/msgmerge aren't really an option for us.

From our .po files we generate a static struct of translation keys. This means, when performing string lookups in code no only do we get autocomplete on key names but if someone removes a key (which is being used still) then the project will fail on compile. Other benefits include guarding against typos and warnings over unused strings in the project. For these reasons I really like the approach we've taken.

The problem is that we're generating our struct of keys from the .po files, instead of going the other way and generating keys from code (with a tool such as xgettext). Whilst there's benefits of both ways I can see far more with the approach we've taken. It does mean however that the process of adding new keys has to be done at the .po level and then Weblate updated through a git pull. It would be far better if we could add new keys through the Weblate interface as this would mean the process of adding new source strings could be shared, instead of it being just a dev task.

**Comment by nijel** [comment] 2017-09-06 09:33
It probably makes sense to implement this for monolingual formats, but it IMHO doesn't make sense for bilingual formats where the source strings are usually extracted from the source code, thus something clearly out of Weblate control.

**Comment by lawmaestro** [comment] 2017-09-06 12:15
Agreed. I think it would be a great Weblate addition for setups using monolingual formats.

**Comment by sebastienvermeille** [comment] 2017-09-12 11:57
+1 we defnitly need it. It's not because we are developer that we don't like to have a GUI if it bring something.

In this case I see clearly a good advantage of the GUI: the developer can add the key without get worried if it is already exists because weblate could check for this.

Would a pull request get refused if it add this feature ?

**Closed** 2017-12-06 15:15 UTC
Labels: enhancement, hosted

**Comment by lsimone** [comment] 2019-02-25 14:17
hello @nijel , I didn't find any reference on weblate decoumentation about how to add new units in a xliff project.
Could you help me?

**Comment by nijel** [comment] 2019-02-25 16:35
It's in *Tools* menu for source language:

![screenshot_2019-02-25 getback gps strings - english](https://user-images.githubusercontent.com/212189/53352749-aa946000-3923-11e9-8f7a-bf10676a260d.png)

**Comment by lsimone** [comment] 2019-02-25 16:38
@nijel thanks but it seems I don't have that option. 
Obviously I am administrator, with all the permission set.
Any idea?

![image](https://user-images.githubusercontent.com/3266650/53352916-ffd07180-3923-11e9-87ee-cdd996209eab.png)

![image](https://user-images.githubusercontent.com/3266650/53352995-242c4e00-3924-11e9-98f7-39a750b47cda.png)

**Comment by nijel** [comment] 2019-02-28 13:56
As written above you can do it on source language only and it works only on monolingual translations.

**Comment by lsimone** [comment] 2019-02-28 17:16
@nijel actually even with the source language (it should be [english by default](https://github.com/WeblateOrg/weblate/issues/876)), I cannot add units from the tools menu.
Do you think I am missing something?

![image](https://user-images.githubusercontent.com/3266650/53584811-c2b6ea00-3b84-11e9-833a-2ff5bf64e9c4.png)

**Comment by nijel** [comment] 2019-02-28 21:05
It really depends on your monolingual setup. I'm not sure when it was changed, but for quite some time the source language is highlighted on both [listing](https://hosted.weblate.org/projects/getback_gps/strings/) and [detail](https://hosted.weblate.org/projects/getback_gps/strings/en/).

**Comment by sebastienvermeille** [comment] 2019-08-28 13:29
Worked like a charms with your explainations @nijel thank you very much! a small more information for new users: you can't reach this from the project it self. You have first to click on a component of the project.

**Comment by jornvl90** [comment] 2019-11-18 14:12
@nijel will there be an API endpoint created for this?

**Comment by jornvl90** [comment] 2019-11-18 14:31
@nijel Will this also be available as an API call?

**Comment by nijel** [comment] 2019-12-02 08:52
@jornvl90 I've created https://github.com/WeblateOrg/weblate/issues/3261 to track this.

**Comment by grebulon** [comment] 2020-05-13 13:36
@nijel We also need this. In out project we can't connect our git to the weblate platform, and must use the API.

**Comment by nijel** [comment] 2020-05-13 15:28
Please discuss this at https://github.com/WeblateOrg/weblate/issues/3261 and not here on a closed issue, thanks.
