### ISSUE TITLE
how to locate/check/confirm which strings got skipped when using upload

### ISSUE THREAD

**Issue by shinji-ikari** [WeblateOrg/weblate#6059] opened 2021-05-21 21:02 UTC
**Is your feature request related to a problem? If so, please describe.**

sorry to bother here, but i really need some help.
if the question already existed and solved, please give a link to it and i'm sorry for my poor searching skill didn't find it.

here is the thing. i'm a translator, i translate by download the file, and when it done, i use upload  file to 
`add  as translation, Imported as translated, √ overwrite existing translations.`
why download and upload....because sometimes the weblate keep showing ISE ISE ISE....

but rencently, the weblate 4.0 version of the project owner used,  really trouble me with one thing.

`Processed 18 strings from the uploaded files (skipped: 8, not found: 0, updated: 10)`

it's lucky this file only 18 strings so i could check it easily to sure what been skipped.
the skipped one is like
>msgctxt "MasterDesc-JBSK0124" 
msgid "\_"
msgstr "\_"
>
↑in server, ↓what i uploaded.

>msgctxt "MasterDesc-JBSK0124"
msgid "せいどうきし"
msgstr "聖堂騎士"
>
so i know it's because msgid couldn't match....(shouldn't it be in `not found`?)

but the next one 
`Processed 342 strings from the uploaded files (skipped: 10, not found: 0, updated: 332)`
this could drive me crazy.....except the msgid couldn't match, the msgstr exactly the same. is there anyother situation could make it skipped? and how to check what had been skipped?

it's not the first time, it already happened several times, and when it happens, it takes me a lot of time to check.....

**Describe the solution you'd like**

when `Processed 18 strings from the uploaded files (skipped: 8, not found: 0, updated: 10)` is showed, click on it to export the log or open a log to check what skipped/not found.

or anyway could check what skipped/not found.

**and , thanks u guys.

**Comment by nijel** [comment] 2021-05-24 03:37
Duplicate of #1558

Generally skipped is a string which was found, but was not applied - for example when it is already translated, and you've chosen not to overwrite, or when the string is marked as read only.

**Closed by nijel** 2021-05-24 03:37 UTC
Labels: enhancement, duplicate
