### ISSUE TITLE
Can't type inverted exclamation sign in translation field

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#1574] opened 2017-07-21 11:42 UTC
### Steps to reproduce
1. Open translation window
2. Try to type **¡** (Option + 1 on Mac OS)

### Actual behaviour
Nothing happens. Can't type it (but can copy/paste).
Somewhere else in Weblate, say, component configuration, I can type it just fine with the same browser. Tested with Firefox and Vivaldi.

### Expected behaviour
**¡** appears in translation field

### Server configuration
```
 * Weblate weblate-2.15
 * Python 2.7.5
 * Django 1.10.3
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.13.2
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.6.4
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.3
 * pytz 2016.7
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 4.0
 * Database backends: django.db.backends.mysql
```

**Comment by nijel** [comment] 2017-07-21 13:08
Probably conflicts with keyboard shortcut for placeables, see https://docs.weblate.org/en/latest/user/translating.html#keyboard-shortcuts.

**Comment by burner1024** [comment] 2017-07-21 14:13
Option is Alt, so yes, it probably does. One possibility would be to add it to the mini-buttons next to copy button.
But if there's a simple hack that can be applied locally to disable this specific shortcut, that'd be good enough in my case (I have no placeables, but ¡ is used very often).

**Comment by nijel** [comment] 2017-07-21 14:49
Following should do that (it removes just fallback handlers, so the shortcuts will still work if placeable is found):

```patch
diff --git a/weblate/static/loader-bootstrap.js b/weblate/static/loader-bootstrap.js
index 7f3ed328f..5c986e616 100644
--- a/weblate/static/loader-bootstrap.js
+++ b/weblate/static/loader-bootstrap.js
@@ -842,14 +842,6 @@ $(function () {
         e.preventDefault();
     });
     /* and shortcuts */
-    for (var i = 1; i < 10; i++) {
-        Mousetrap.bindGlobal(
-            'alt+' + i,
-            function(e) {
-                return false;
-            }
-        );
-    }
     if ($('.hlcheck').length>0) {
         $('.hlcheck').each(function(idx){
             var $this = $(this);
```

**Comment by burner1024** [comment] 2017-07-22 00:50
Thank you for a swift reply. But it doesn't seem to work for me. I restarted uwsgi, flushed redis cache and browser cache, still no go.

**Comment by nijel** [comment] 2017-07-23 06:59
You need to run collectstatic after patching the file, sorry for not
mentioning it before...

**Comment by nijel** [comment] 2017-11-20 08:24
Duplicate of #1291

**Closed by nijel** 2017-11-20 08:24 UTC
Labels: bug
