### ISSUE TITLE
Celery issue

### ISSUE THREAD

**Issue by Viish** [WeblateOrg/weblate#4577] opened 2020-09-23 13:56 UTC
**Describe the bug**

Celery attemps to connect to amqp instead of redis:
```
[2020-09-23 15:47:23,300: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2020-09-23 15:47:23,301: DEBUG/MainProcess] | Worker: Building graph...
[2020-09-23 15:47:23,301: DEBUG/MainProcess] | Worker: New boot order: {Timer, Hub, Pool, Autoscaler, StateDB, Beat, Consumer}
[2020-09-23 15:47:23,307: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2020-09-23 15:47:23,307: DEBUG/MainProcess] | Consumer: Building graph...
[2020-09-23 15:47:23,337: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Agent, Events, Heart, Mingle, Tasks, Control, Gossip, event loop}
[2020-09-23 15:47:23,371: DEBUG/MainProcess] | Worker: Starting Hub
[2020-09-23 15:47:23,371: DEBUG/MainProcess] ^-- substep ok
[2020-09-23 15:47:23,371: DEBUG/MainProcess] | Worker: Starting Pool
[2020-09-23 15:47:23,463: DEBUG/MainProcess] ^-- substep ok
[2020-09-23 15:47:23,463: DEBUG/MainProcess] | Worker: Starting Beat
[2020-09-23 15:47:23,464: DEBUG/MainProcess] ^-- substep ok
[2020-09-23 15:47:23,464: DEBUG/MainProcess] | Worker: Starting Consumer
[2020-09-23 15:47:23,464: DEBUG/MainProcess] | Consumer: Starting Connection
[2020-09-23 15:47:23,476: INFO/Beat] beat: Starting...
[2020-09-23 15:47:23,483: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2020-09-23 15:47:23,576: DEBUG/Beat] Current schedule:
<ScheduleEntry: celery.backend_cleanup celery.backend_cleanup() <crontab: 0 4 * * * (m/h/d/dM/MY)>
[2020-09-23 15:47:23,576: DEBUG/Beat] beat: Ticking with max interval->5.00 minutes
[2020-09-23 15:47:23,577: DEBUG/Beat] beat: Waking up in 5.00 minutes.
[2020-09-23 15:47:25,489: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)
```

**To Reproduce**

Start celery:
`~/weblate-env/lib/python3.6/site-packages/weblate/examples/celery start`

Check the logs:
`cat weblate-celery.log`

**Expected behavior**

Celery trying to connect to redis

**Server configuration and status**

```
(weblate-env) [weblate@linphone ~]$ weblate list_versions
 * Weblate: 4.2.2
 * Django: 3.1.1
 * siphashc: 2.1
 * Whoosh: 2.7.4
 * translate-toolkit: 3.1.1
 * lxml: 4.5.2
 * Pillow: 7.2.0
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.1
 * django-filter: 2.3.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 50.3.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.5
 * celery: 4.4.7
 * kombu: 4.6.11
 * translation-finder: 2.1
 * html2text: 2020.1.16
 * pycairo: 1.19.1
 * pygobject: 3.38.0
 * diff-match-patch: 20200713
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.16.5
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.8
 * borgbackup: 1.1.13
 * pyparsing: 2.4.7
 * Python: 3.6.8
 * Git: 2.18.4
 * psycopg2-binary: 2.8.6
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.12
 * Redis server: 3.2.12
 * PostgreSQL server: 12.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 3.10.0-957.1.3.el7.x86_64 (x86_64)
```

**Weblate deploy checks**

```
(weblate-env) [weblate@linphone ~]$ weblate check --deploy
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E019) The Celery does not process tasks, or is too slow in processing them.
	HINT: https://docs.weblate.org/en/weblate-4.2.2/admin/install.html#celery

WARNINGS:
?: (weblate.W025.ass) Failure in loading handler for ass file format: aeidon or gaupol package required for Subtitle support
	HINT: https://docs.weblate.org/en/weblate-4.2.2/admin/install.html#optional-deps
?: (weblate.W025.ini) Failure in loading handler for ini file format: Missing iniparse library.
	HINT: https://docs.weblate.org/en/weblate-4.2.2/admin/install.html#optional-deps
?: (weblate.W025.islu) Failure in loading handler for islu file format: Missing iniparse library.
	HINT: https://docs.weblate.org/en/weblate-4.2.2/admin/install.html#optional-deps
?: (weblate.W025.laravel) Failure in loading handler for laravel file format: No module named 'phply'
	HINT: https://docs.weblate.org/en/weblate-4.2.2/admin/install.html#optional-deps
?: (weblate.W025.php) Failure in loading handler for php file format: No module named 'phply'
	HINT: https://docs.weblate.org/en/weblate-4.2.2/admin/install.html#optional-deps
?: (weblate.W025.srt) Failure in loading handler for srt file format: aeidon or gaupol package required for Subtitle support
	HINT: https://docs.weblate.org/en/weblate-4.2.2/admin/install.html#optional-deps
?: (weblate.W025.ssa) Failure in loading handler for ssa file format: aeidon or gaupol package required for Subtitle support
	HINT: https://docs.weblate.org/en/weblate-4.2.2/admin/install.html#optional-deps
?: (weblate.W025.sub) Failure in loading handler for sub file format: aeidon or gaupol package required for Subtitle support
	HINT: https://docs.weblate.org/en/weblate-4.2.2/admin/install.html#optional-deps
?: (weblate.W033.Gerrit) Failure in loading VCS module for Gerrit: git: 'review' is not a git command. See 'git --help'.
 (1)
	HINT: https://docs.weblate.org/en/weblate-4.2.2/vcs.html
?: (weblate.W033.GitHub) Failure in loading VCS module for GitHub: [Errno 2] No such file or directory: 'hub': 'hub'
	HINT: https://docs.weblate.org/en/weblate-4.2.2/vcs.html
?: (weblate.W033.GitLab) Failure in loading VCS module for GitLab: [Errno 2] No such file or directory: 'lab': 'lab'
	HINT: https://docs.weblate.org/en/weblate-4.2.2/vcs.html
?: (weblate.W033.Mercurial) Failure in loading VCS module for Mercurial: [Errno 2] No such file or directory: 'hg': 'hg'
	HINT: https://docs.weblate.org/en/weblate-4.2.2/vcs.html
?: (weblate.W033.Subversion) Failure in loading VCS module for Subversion: git: 'svn' is not a git command. See 'git --help'.

The most similar command is
	serve
 (1)
	HINT: https://docs.weblate.org/en/weblate-4.2.2/vcs.html

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.2.2/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.2.2/admin/backup.html

System check identified 16 issues (1 silenced).
```

**Additional context**

Installing weblate on centos7 server under weblate user/group with rh-git218, rh-postgresql12 and rh-httpd24 + python3.6 mod_wsgi.

**Comment by nijel** [comment] 2020-09-23 14:18
Duplicate of #4445

**Closed by nijel** 2020-09-23 14:18 UTC
Labels: bug, duplicate

**Comment by Viish** [comment] 2020-09-23 14:38
Thanks, downgrading to 4.4.6 did the trick, however there is now an error:
`The Celery process is outdated or misconfigured. Following items differ: encoding`

**Comment by nijel** [comment] 2020-09-23 14:46
See https://docs.weblate.org/en/latest/admin/install.html#system-locales-and-encoding
