### ISSUE TITLE
Glossary styling is off in Firefox

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#2185] opened 2018-08-17 16:42 UTC
### Steps to reproduce
1. Visit https://hosted.weblate.org/translate/weblate/master/es/?type=fuzzy in Firefox Quantum 61.0.1

### Actual behaviour
See screenshot
![captura de pantalla de 2018-08-17 23-39-12](https://user-images.githubusercontent.com/1279852/44278064-1318cb00-a277-11e8-8a7a-cc74108ac8a6.png)

### Expected behaviour
Proper styling.

### Server configuration and status
Hosted Weblate.

**Comment by nijel** [comment] 2018-08-19 19:56
Duplicate of #2041

**Closed by nijel** 2018-08-19 19:56 UTC
