### ISSUE TITLE
[4.10.1] Not valid response after creating translation unit

### ISSUE THREAD

**Issue by infureal** [WeblateOrg/weblate#9068] opened 2023-04-10 05:39 UTC
### Describe the issue

Hello. My bug is when I send request to `POST <host>/api/translations/catalog/dev/ru/units/` response is seems to be invalid.

<details>
<summary>Response</summary>

```json
{
    "language": {
        "code": "ru",
        "name": "Russian",
        "plural": {
            "id": 467,
            "source": 0,
            "number": 3,
            "formula": "n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2",
            "type": 2
        },
        "aliases": [
            "ru_r",
            "ru_rr",
            "rus"
        ],
        "direction": "ltr",
        "web_url": "<host>/languages/ru/",
        "url": "<host>/api/languages/ru/",
        "statistics_url": "<host>/api/languages/ru/statistics/"
    },
    "component": {
        "name": "Development",
        "slug": "dev",
        "id": 33,
        "source_language": {
            "code": "ru",
            "name": "Russian",
            "plural": {
                "id": 467,
                "source": 0,
                "number": 3,
                "formula": "n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2",
                "type": 2
            },
            "aliases": [
                "ru_r",
                "ru_rr",
                "rus"
            ],
            "direction": "ltr",
            "web_url": "<host>/languages/ru/",
            "url": "<host>/api/languages/ru/",
            "statistics_url": "<host>/api/languages/ru/statistics/"
        },
        "project": {
            "name": "Каталог товаров",
            "slug": "catalog",
            "id": 13,
            "web": "https://catalog.oma.kz",
            "web_url": "<host>/projects/catalog/",
            "url": "<host>/api/projects/catalog/",
            "components_list_url": "<host>/api/projects/catalog/components/",
            "repository_url": "<host>/api/projects/catalog/repository/",
            "statistics_url": "<host>/api/projects/catalog/statistics/",
            "changes_list_url": "<host>/api/projects/catalog/changes/",
            "languages_url": "<host>/api/projects/catalog/languages/",
            "translation_review": false,
            "source_review": false,
            "set_language_team": true,
            "instructions": "https://catalog.oma.kz",
            "enable_hooks": true,
            "language_aliases": ""
        },
        "vcs": "gitlab",
        "repo": "git@gitlab.itex.kz:weblateLang/catalog-dev.git",
        "git_export": "<host>/git/catalog/dev/",
        "branch": "main",
        "push_branch": "",
        "filemask": "*.po",
        "template": "ru.po",
        "edit_template": true,
        "intermediate": "",
        "new_base": "",
        "file_format": "po-mono",
        "license": "",
        "license_url": null,
        "agreement": "",
        "web_url": "<host>/projects/catalog/dev/",
        "url": "<host>/api/components/catalog/dev/",
        "repository_url": "<host>/api/components/catalog/dev/repository/",
        "translations_url": "<host>/api/components/catalog/dev/translations/",
        "statistics_url": "<host>/api/components/catalog/dev/statistics/",
        "lock_url": "<host>/api/components/catalog/dev/lock/",
        "links_url": "<host>/api/components/catalog/dev/links/",
        "changes_list_url": "<host>/api/components/catalog/dev/changes/",
        "task_url": null,
        "new_lang": "add",
        "language_code_style": "",
        "push": "",
        "check_flags": "",
        "priority": 100,
        "enforced_checks": [],
        "restricted": false,
        "repoweb": "",
        "report_source_bugs": "",
        "merge_style": "rebase",
        "commit_message": "Translated using Weblate ({{ language_name }})\n\nCurrently translated at {{ stats.translated_percent }}% ({{ stats.translated }} of {{ stats.all }} strings)\n\nTranslation: {{ project_name }}/{{ component_name }}\nTranslate-URL: {{ url }}",
        "add_message": "Added translation using Weblate ({{ language_name }})\n\n",
        "delete_message": "Deleted translation using Weblate ({{ language_name }})\n\n",
        "merge_message": "Merge branch '{{ component_remote_branch }}' into Weblate.\n\n",
        "addon_message": "Update translation files\n\nUpdated by \"{{ addon_name }}\" hook in Weblate.\n\nTranslation: {{ project_name }}/{{ component_name }}\nTranslate-URL: {{ url }}",
        "allow_translation_propagation": true,
        "manage_units": true,
        "enable_suggestions": true,
        "suggestion_voting": false,
        "suggestion_autoaccept": 0,
        "push_on_commit": true,
        "commit_pending_age": 24,
        "auto_lock_error": true,
        "language_regex": "^[^.]+$",
        "variant_regex": "",
        "addons": [],
        "is_glossary": false,
        "glossary_color": "silver"
    },
    "language_code": "ru",
    "id": 52,
    "filename": "ru.po",
    "revision": "c118058c9e6f7fd17ea5aa9713228f3d178eec90,c118058c9e6f7fd17ea5aa9713228f3d178eec90",
    "web_url": "<host>/projects/catalog/dev/ru/",
    "share_url": "<host>/engage/catalog/ru/",
    "translate_url": "<host>/translate/catalog/dev/ru/",
    "url": "<host>/api/translations/catalog/dev/ru/",
    "is_template": true,
    "is_source": true,
    "total": 10,
    "total_words": 47,
    "translated": 10,
    "translated_words": 47,
    "translated_percent": 100.0,
    "fuzzy": 0,
    "fuzzy_words": 0,
    "fuzzy_percent": 0.0,
    "failing_checks": 0,
    "failing_checks_words": 0,
    "failing_checks_percent": 0.0,
    "have_suggestion": 0,
    "have_comment": 0,
    "last_change": null,
    "last_author": null,
    "repository_url": "<host>/api/translations/catalog/dev/ru/repository/",
    "file_url": "<host>/api/translations/catalog/dev/ru/file/",
    "statistics_url": "<host>/api/translations/catalog/dev/ru/statistics/",
    "changes_list_url": "<host>/api/translations/catalog/dev/ru/changes/",
    "units_list_url": "<host>/api/translations/catalog/dev/ru/units/"
}
```
</details>

As I see ID field is ID for component's language. Not new created unit.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Expected behavior

Expected to return valid json as described at https://docs.weblate.org/ru/weblate-4.10.1/api.html#post--api-translations-(string-project)-(string-component)-(string-language)-units-

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment] 2023-04-11 10:49
Duplicate of #7603

**Closed by nijel** 2023-04-11 10:49 UTC
Labels: enhancement, duplicate
