### ISSUE TITLE
Allow translation propagation among different projects

### ISSUE THREAD

**Issue by jzahradn** [WeblateOrg/weblate#3802] opened 2020-04-30 11:47 UTC
Hi,
is it possible to set up Weblate to propagate component's translation changes within another projects?
According to our testing it is working only within single project.
Regards
Jan

**Comment by jzahradn** [comment] 2020-04-30 11:50
We would like to do changes in the only one master project and let Weblate to propagate the changes to another components in another projects (these projects uses the same components with the same translation files and the same gitlab settings but different branches).

**Comment by nijel** [comment] 2020-04-30 14:19
Duplicate of #3166

**Closed by nijel** 2020-04-30 14:19 UTC
Labels: enhancement, duplicate
