### ISSUE TITLE
Allow addon installation via API

### ISSUE THREAD

**Issue by jojurajan** [WeblateOrg/weblate#3930] opened 2020-05-22 05:46 UTC
**Is your feature request related to a problem? Please describe.**
I would like to trigger auto translation for a language based on `Translation Memory`. Currently I add a new language for the component via API and then manually apply the auto translation for the language.

**Describe the solution you'd like**
I would like to have an API which could trigger auto translation for the strings listed under a language under a translation component. Maybe under the component APIs.

**Additional context**
The auto-translation parameters and action is available in the GUI at Project -> Component -> Language -> Tools -> Automatic Translation
<img width="1422" alt="Screenshot 2020-05-22 at 11 08 14 AM" src="https://user-images.githubusercontent.com/3179427/82634932-ad602c80-9c1c-11ea-858d-5f6455b588ab.png">

**Comment by jojurajan** [comment] 2020-05-22 12:16
@nijel I misunderstood the auto-translation page actions. I have updated the issue to expose an API to trigger the translations.

**Comment by nijel** [comment] 2020-05-23 04:24
There is also [Automatic translation addon](https://docs.weblate.org/en/latest/admin/addons.html#automatic-translation) to trigger regularly.

**Comment by jojurajan** [comment] 2020-05-26 06:24
> There is also [Automatic translation addon](https://docs.weblate.org/en/latest/admin/addons.html#automatic-translation) to trigger regularly.

The addon looks promising. I think this would still need manual intervention to enable the addon on each translation component. I am trying to reduce the manual process related to setting up of a translation component to none or minimum. 
Could we enable and configure this addon via APIs? That would help even more since we wouldn't have to trigger the auto-translation everytime a string is added.

**Comment by nijel** [comment] 2020-05-26 11:56
I've created separate issue for that: https://github.com/WeblateOrg/weblate/issues/3948

**Comment by kamilgrymuza** [comment] 2020-06-02 11:45
@nijel - Sure, we'd like to do it on a per-component basis so that we have more control over which components are auto-translated and which are not. I'm not sure how to best implement that, but essentially we need an API that would allow us to trigger the action the "Apply" button on the screenshot shared by @jojurajan triggers. 

Does that make sense?

**Comment by nijel** [comment] 2020-06-02 11:59
Both is per component, the only difference is the trigger.

* The auto translate action does it once, see https://docs.weblate.org/en/latest/user/translating.html#auto-translation
* The addon triggers continuously, see https://docs.weblate.org/en/latest/admin/addons.html#automatic-translation

**Comment by kamilgrymuza** [comment] 2020-06-02 12:05
Ok, thank you @nijel  - now it's clear - so we'd like to be able to trigger it once (the #1 option you shared).

**Comment by nijel** [comment] 2020-06-03 11:19
Okay, let's split this up - this issue will cover addons API, and https://github.com/WeblateOrg/weblate/issues/3983 will cover onetime trigger of automatic translation.

**Comment by kamilgrymuza** [comment] 2020-06-03 13:22
Sounds good - thanks @nijel 👍

**Comment by nijel** [comment] 2020-08-03 07:52
Duplicate of #3948

**Closed by nijel** 2020-08-03 07:52 UTC
Labels: enhancement, duplicate
