### ISSUE TITLE
Ignore front matter in Markdown

### ISSUE THREAD

**Issue by Cryolitia** [WeblateOrg/weblate#12786] opened 2024-10-15 15:55 UTC
### Describe the problem

Nowadays, many blog frame would use markdown with front matter, it's a small piece at the start of a markdown file, it looks like:

```markdown
---
date: 2024-02-02T04:14:54-08:00
draft: false
params:
  author: John Smith
title: Example
weight: 10
---
```

or in hugo may be

```markdown
+++
date = 2024-02-02T04:14:54-08:00
draft = false
title = 'Example'
weight = 10
[params]
  author = 'John Smith'
+++
```

Now, weblate will only parse this picec as plain text like `title: Base Pitch parent: Pitch Naturalisation nav_order: 2`

I would like to let translate parse or just ignore it.

### Describe the solution you would like

Just ignore the front matter, and copy it to translated files as is.

**Comment by nijel** [comment] 2024-10-16 08:46
Duplicate of https://github.com/translate/translate/issues/5399

**Closed by nijel** 2024-10-16 08:46 UTC
Labels: bug, translate-toolkit, duplicate
