### ISSUE TITLE
Search for strings with glossary terms

### ISSUE THREAD

**Issue by KadAnna** [WeblateOrg/weblate#4904] opened 2020-11-23 17:42 UTC
**Is your feature request related to a problem? If so, please describe.**
I need to check if translation is using the translation defined by glossary.

**Describe the solution you'd like**
1. ~~One of the weblate check is to control usage of terms in glossary - it comes as failing check.~~
2. filter on strings that have some hit in glossary

**Additional context**
* the question is the match set-up: we suggest to check a word from translated phrase vs. a full glossary entry. This way a term would a part of a sentence, and yet the check would provide feedback. 
* reported as string status "failing check" if error
* there would be a filter for on strings with "glossary inconsistency"

**Comment by nijel** [comment] 2020-11-25 08:14
Duplicate of #1297

**Comment by nijel** [comment] 2021-02-09 14:59
I just noticed that the search part is not covered by the other issue. That's why it's a good idea to keep it one topic per issue ;-).

**Closed** 2021-02-11 09:40 UTC
Labels: enhancement
