### ISSUE TITLE
Add support for OpenShift 3

### ISSUE THREAD

**Issue by maxruby** [WeblateOrg/weblate#1523] opened 2017-06-17 02:44 UTC
### Steps to reproduce
1. Set up new `python 2.7` project in OpenShift following docs
2. Allocate 1 GB in OpenShift
3. Build from source `https://github.com/WeblateOrg/weblate.git`

### Actual behaviour
Build  'lxml.etree' extension **failed**. See https://gist.github.com/maxruby/6ce93a1a1a4b94927102d9ecbc66a684

### Expected behaviour
Build should not fail.

### Server configuration
Please paste the output of command `./manage.py list_versions` over here

**Comment by maxruby** [comment] 2017-06-18 22:04
@nijel.  Thanks for the efforts towards fixing this. However, it still fails at the same place when using the latest commit.

Please see new [gist](a55260a24b68e0485ce3317363b7bf10) documenting the error.

Can you please leave this issue open until it is actually fixed?  Thanks again for the amazing work on this project.

**Comment by nijel** [comment] 2017-06-19 05:14
It seems that the installation instructions are not used, probably that needs somebody experienced with openshift to fix rather than me :-).

**Comment by maxruby** [comment] 2017-06-19 06:30
Thanks for the clarification. The trouble is I also tried the OpenSUSE appliance installation with VirtualBox with no success :(

Can you kindly point me to the most reliable way of getting weblate installed on Linux running on a VM? I would like to run it on my MacOSX with VirtualBox.

**Comment by maxruby** [comment] 2017-06-19 08:06
According to a couple posts in [_StackOverflow_](https://stackoverflow.com/questions/35529761/openshift-cant-install-lxml-for-python-app), a possible reason for the _lxml_ build failure might be that `OpenShift` does not support _lxml_ version > `v3.2.5`.

Currently, the `OpenShift` build log for _weblate_ shows the following:
```
Building lxml version 3.8.0. 
``` 

The post in StackOverflow say that:
```
Openshift is only able to compile/install 'lxml==3.2.5' the last time I checked.
Set your 'requires' in your setup.py to 'lxml==3.2.5'.
```

Can you please change this _lxml_ requirement so that `OpenShift` can successfully build _lxml_?

**Comment by nijel** [comment] 2017-06-19 08:13
If you want to avoid manual installation using pip, the best way for deployment is Docker as it's automatically tested for every release and updated frequently. Anything else is behind: I haven't found time to maintain the openSUSE appliance for some releases, the OpenShift was contributed some time ago and hasn't received any updates recently.

Yes, the problem with lxml is known and was already workarounded this way, but apparently it does not work. I assume you're using OpenShift 3, which has changed build scripts and our build scripts are no longer used. The build scripts will probably still work on OpenShift 2...

**Comment by Redarcher9** [comment] 2017-08-04 17:24
Hey,i am interested to try this out.Can i be assigned for this?

**Comment by nijel** [comment] 2017-08-05 10:37
Feel free to work on this, AFAIK nobody is looking at this...

**Comment by macrojames** [comment] 2017-09-04 13:46
replace the line with lxml in requirements.txt
by
`https://pypi.python.org/packages/1b/e8/ce25c547daf9b84cafea605eb8a5709524fb53e1b3bb5ef6884e561b9d34/lxml-3.8.0-cp27-cp27mu-manylinux1_x86_64.whl#md5=2ab7288c05fe8a4c224fa48d4456e8f5`

This will load the compiled wheel instead of compiling and not use all your RAM.
But: There is still a lot of problems I wasn't able to solve completely. Missing env-vars, missing username being only some of them.

We are forced to migrate because the old platform is EOL on Sept 30th:
[EOL Announcement](https://blog.openshift.com/migrate-to-v3-v2-eol/)

**Comment by nijel** [comment] 2017-09-04 14:01
Patches welcome, but something like you've mentioned is certainly is not good fit for generic requirements.txt. 

Maybe it would be better to have the integration in separate repo same as we do with Docker: https://github.com/WeblateOrg/docker

**Comment by GrahamDumpleton** [comment] 2017-09-11 06:46
Has anyone actually tried the suggestion of ensuring OpenShift is using the latest ``pip`` version. The older ``pip`` version it uses by default may not be able to use Python wheels. Need to set the build configuration environment variable:

```
UPGRADE_PIP_TO_LATEST=1
```

**Comment by GrahamDumpleton** [comment] 2017-09-11 06:46
BTW, the prior link about ``lxml version > v3.2.5`` is likely not relevant as that is for OpenShift 2, not 3.

**Comment by nijel** [comment] 2017-09-12 18:06
The difference is that for OpenShift 2 we have support by @dtschan which pulls in working version of lxml, for OpenShift 3 nobody did that.

**Comment by sedubois** [comment] 2017-09-30 09:41
I just discovered Weblate and tried to deploy an instance to OpenShift as per the instructions at the top of the quickstart documentation (i.e., the documentation that any newcomer is bound to first discover), but the doc refers to the `rhc` command line instead of the apparently new `oc` (I don't know anything about Openshift). I followed the default flow on openshift.com to create a new container, and it took me ages to figure out that `rhc` is incompatible with that.

I suggest to remove the Openshift doc if it can't be maintained and if another method should be used instead. Whatever the recommended method is, it would help to highlight it proeminently in the GitHub README. After a couple of hours work, I still haven't figured out how to deploy a new Weblate instance. Also see #1645.

Just my two cents and thank you for creating this project 🙂

**Comment by GrahamDumpleton** [comment] 2017-09-30 21:21
Don't go removing any docs, and definitely not any code, related to deploying to OpenShift just yet, and I will have a stab at providing you some patches to tweak it for OpenShift 3.

**Comment by GrahamDumpleton** [comment] 2017-09-30 22:30
Have an initial deployment working under OpenShift 3. Two immediate issues.

* The Django settings module is missing definition of ``WSGI_APPLICATION`` which would normally exist, which caused a problem due to using the ``mod_wsgi-express`` integration for Django to start up the application.
* Running ``create_ssh_wrapper()`` in ``weblate/__init__.py`` will fail in a containerised application, including possibly with a straight Docker deployment, if a tighter security regime is used where the application is run as an arbirary user ID and write access to the file system is depending on group write access only. The ``chmod`` done by this call will fail as a result. This file already existed from the build phase of the container image, so it possibly shouldn't bother doing anything if the file already existed that it is trying to create.

I will create separate issues for these as I clean up things and work out how to use the application so can verify things work okay.

Then need to create some templates to simplify deployment so can be done in one click. Overall, doesn't appear to be too difficult to get it running.

**Comment by GrahamDumpleton** [comment] 2017-10-01 03:33
A further issue is caused when using ``mod_wsgi-express`` Django integration, by ``weblate`` changing the prevailing convention of what ``BASE_DIR`` is set to in the Django settings file. In a normal Django settings module this is the directory parent to the Django project directory. So where a normally Django settings module would contain:

```
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
```

in ``weblate`` it uses:

```
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
```

This will upset external tools intended to work with Django which rely on the prevailing convention set by what ``django_admin.py`` sets up with a new project.

**Comment by GrahamDumpleton** [comment] 2017-10-03 09:35
If you want to test out running Weblate on OpenShift 3, run the following steps in a suitable OpenShift environment. You need to have access to one persistent volume. You can use OpenShift Online 3 Starter.

```
oc new-build python:2.7~https://github.com/GrahamDumpleton/weblate --name weblate
```

This will build an application image for Weblate, but will not deploy it. It is easier at this point while getting things working to have the build as a separate step.

For deployment, load template for deploying a test environment using SQLite.

```
oc create -f https://raw.githubusercontent.com/GrahamDumpleton/weblate/master/openshift3/testing-sqlite.json
```

This will create a template in the OpenShift project called ``weblate-testing-sqlite``.

You can now go to the web console in OpenShift and select 'Add to Project'. Then select 'Python' and 'Weblate (Testing / SQLite)'.

Fill out the mandatory details for admin username, password and email. Click on 'Create'.

The initial setup will take a little while because of database creation steps, but once site is accessible, login using the admin credentials you used.

Note that this can be streamlined further, with the template also setting up the image build, I have just done it separately for now.

At this point I need others to validate and test it. I am not a Weblate user and so don't really understand all the appropriate setup and configuration steps, and definitely not how to use Weblate. I believe I have captured key steps in order to at least get it running.

Further work on start up scripts, improving on templates and adding templates for using MySQL or PostgreSQL, plus adding docs and creating a PR will depend on getting some feedback.

FWIW, the only change to Weblate itself which was required was:

* https://github.com/GrahamDumpleton/weblate/commit/2c519ced1f1a153a9097c16b50423ca59352e1ab

Everything else was just new files for working with OpenShift 3.

**Comment by nijel** [comment] 2017-10-04 10:30
* The BASE_DIR value probably comes from history where Django used to set it this way. It's probably safe to adjust it (not sure where it is used besides configuration).
* The create_ssh_wrapper operates in data dir, which is supposed to be writable. If you will change random parts of it to non writable, random parts of Weblate will break. Why the ssh wrapper is created externally?

**Comment by GrahamDumpleton** [comment] 2017-10-04 10:36
The ``BASE_DIR`` didn't matter in the end. I used manually configured mod_wsgi-express instead of using Django integration, so didn't rely on it.

I am not making the data directory non writable. The problem is that in a secure containerised environment, the build of the container image is done as one user, but at execution time it can run as an arbitrary user ID. To deal with that, you rely on giving root group write access to all directories and files. The arbitrary user ID will be in group root and so can write everything. The problem is that the attempt to remove group write when setting permissions on ssh wrapper script will fail at runtime as arbitrary user ID isn't the owner of the file.

The thing is, the ssh wrapper script was already created as part of the build of the container image, so there wasn't really a need for it to recreate it yet again everytime the weblate module is imported at runtime.

**Comment by nijel** [comment] 2017-10-04 10:43
Probably other things will break over time if parts of data dir are not owned by user running Weblate. Better to chown that dir after build to correct user...

**Comment by GrahamDumpleton** [comment] 2017-10-04 10:50
You can't. The build doesn't occur as root. You are going to have this issue with any containerised (ie., Docker/OCI based) environment which has better security than the typical stuff people build with Docker.

**Comment by nijel** [comment] 2017-10-04 10:56
With the docker there is nothing writing to the datadir before container start, so this problem doesn't exist there.

**Comment by GrahamDumpleton** [comment] 2017-10-04 11:10
There is if you run ``manage.py collectstatic`` during the build of the image, which should technically be possible unless Weblate does something strange. Systems like Heroku and OpenShift where they supported Django have always done ``collectstatic`` during the build phase and not at deployment time.

Anyway, there is a way around the problem if are going to do ``collectstatic`` as part of the build. In fact this issue only comes up when not mounting a persistent volume over the data directory when run, and didn't think of that before as did all my testing with ephemeral container file system. The solution is to simply delete the data directory at the end of the build phase and recreate it as an empty directory. Then when even run as ephemeral instance, nothing will be there and will create with ownership/permissions okay for the arbitrary user ID it runs as.

**Comment by GrahamDumpleton** [comment] 2017-10-04 11:11
Also, right now I can't see any reason why ``compilemessages`` can't also be done during the build since I am assuming it works of the static code.

**Comment by nijel** [comment] 2017-10-04 12:17
We do `collectstatic` at startup time in Docker as the data dir is separate volume, which is not available at build time. It should be possible to place static files outside data dir and do that at build time though.

The `compilemessages` is only needed when you base on git, if you use released versions it's not needed (so it's not needed for Docker).

The current Weblate approach to check and write to datadir at every startup is certainly not optimal. I've changed the ssh wrapper creation in 3b38099618006c7e2c851e959541e334f72c782f.

**Comment by nijel** [comment] 2017-10-04 12:25
And the BASE_DIR should match Django default one as of 2a8e4df5d.

**Comment by GrahamDumpleton** [comment] 2017-10-09 03:07
Latest versions if anyone wants to try:

For PostgreSQL. Requires two volumes.

```
oc new-app https://raw.githubusercontent.com/GrahamDumpleton/weblate/master/openshift3/persistent-postgresql.json
```

For MySQL. Requires two volumes.

```
oc new-app https://raw.githubusercontent.com/GrahamDumpleton/weblate/master/openshift3/persistent-mysql.json
```

For SQLite. Requires single volume. Okay for OpenShift Online Starter.

```
oc new-app https://raw.githubusercontent.com/GrahamDumpleton/weblate/master/openshift3/persistent-sqlite.json
```

For SQLite. No volume, is ephemeral. Only suitable for testing.

```
oc new-app https://raw.githubusercontent.com/GrahamDumpleton/weblate/master/openshift3/ephemeral-sqlite.json
```

The admin user/password is generated and available in output from ``oc new-app`` command.

```
     Weblate (Persistent / PostgreSQL)
     ---------
     Creates a Weblate installation with separate PostgreSQL database instance. Requires that two persistent volumes be available. If a ReadWriteMany persistent volume type is available and used, Weblate can be scaled to multiple replicas and the deployment strategy switched to Rolling to permit rolling deployments on restarts.

     * With parameters:
        * APPLICATION_NAME=my-weblate-site
        * WEBLATE_REPOSITORY_URL=https://github.com/GrahamDumpleton/weblate
        * WEBLATE_VOLUME_SIZE=1Gi
        * WEBLATE_VOLUME_TYPE=ReadWriteOnce
        * WEBLATE_DEPLOYMENT_STRATEGY=Recreate
        * WEBLATE_MEMORY_LIMIT=256Mi
        * WEBLATE_ADMIN_USERNAME=admin53624 # generated
        * WEBLATE_ADMIN_PASSWORD=GWFsNFRbA3Bu # generated
        * WEBLATE_ADMIN_EMAIL=noreply@example.com
        * DATABASE_VOLUME_SIZE=1Gi
        * DATABASE_MEMORY_LIMIT=256Mi
        * DATABASE_USERNAME=user135338 # generated
        * DATABASE_PASSWORD=ga1mxOJ6TPU2 # generated
        * POSTGRESQL_VERSION=9.5
        * PYTHON_VERSION=3.5
```

You can override specific parameters of template when running with ``oc new-app`` using ``--param`` option.

**Comment by GrahamDumpleton** [comment] 2017-10-09 03:41
I am going to stop work on this now. I can't continue unless someone is going to actually want to use it and try it and provide feedback I need. I don't know anything about using Weblate so can't really test out whether the deployments are working okay with the setup created.

Outstanding work still to be done is documentation updates, and working out how to handle cron jobs. OpenShift 3 doesn't have cron job support built into container images themselves. One would need to look at use Kubernetes jobs, but they are still in alpha in latest OpenShift and only beta in latest Kubernetes. Will be a few more versions before they are GA.

**Comment by nijel** [comment] 2017-10-09 14:27
Thanks @GrahamDumpleton for your work! I will try to find some time for testing, but I on the other side have zero experience with OpenShift...

**Comment by wolpi** [comment] 2018-07-09 09:41
Hi,

I wanted to deploy weblate in openshift to translate my little android app. I started with templates of @GrahamDumpleton but they didn't work for me :cry: 

Those templates create a openshift `buildconfig` to build a custom docker image. That build kept failing. I coudn't figure out why.

Next I started to deploy prebuilt image from dockerhub. That one uses [start script](https://github.com/WeblateOrg/docker/blob/2.20-1/start) to do some setup tasks inside container. As openshift launches containers with random UID, which don't have an entry in `/etc/passwd` inside container, that script fails. Thus I did some of those setup tasks in openshift yaml and updated configs of nginx and superviserd.

You can find it [here](https://gist.github.com/wolpi/c8917d839ecaa8a0e1c3896b9c75233d)

As free openshift keeps loosing my postgres data I'm looking for some other hosting solution now. Just want to share my experience.

**Comment by GrahamDumpleton** [comment] 2018-07-09 10:17
@wolpi There is no reason why OpenShift would loose your PostgreSQL data, even on free starter tier, so your setup must be the issue. You should have let me know earlier that you were having issues with my version as I can update it to latest Weblate and make sure it works.

**Comment by wolpi** [comment] 2018-07-09 10:21
I had fun playing with it :smile:

**Comment by GrahamDumpleton** [comment] 2018-07-09 10:57
@wolpi Initial reason builds fail with my fork and templates is because original ``requirements.txt`` didn't pin packages with maximum versions. It therefore had ``Django>=1.10``, which means it grabs Django 2.X, which fails with the older Weblate code base.

Anyway, do let me know if you are interested in seeing updated version or not. If I don't hear anything I'll still put it on a long list of things I have to do, but don't promise anything. In other words, whether I work on it is really driven by interest in it, and up to now not seen any concrete interest from either developers or users of package, so hasn't been a priority.

**Comment by GrahamDumpleton** [comment] 2018-07-09 12:15
@wolpi FWIW, I looked at it very quickly, pulled in latest upstream and it builds and deploys fine for SQLite template at least, didn't try others.

The only thing that doesn't appear to work out of the box is the automatic addition of an initial super user.

```
-----> Creating predefined Django super user
--
  | ERROR Handled exception AttributeError: b"Manager isn't available; 'auth.User' has been swapped for 'weblate_auth.User'"
```

You would just have to ``oc rsh`` into the pod and run:

```
python manage.py createsuperuser
```

yourself to add one.

Fixing the addition of the super user automatically shouldn't be that hard.

**Comment by wolpi** [comment] 2018-07-09 12:29
@GrahamDumpleton, thanks for your help. But during my experiments openshift free felt slow and unrelibale (that might just be my personal impression). I don't intend to use it anymore.

**Comment by GrahamDumpleton** [comment] 2018-07-09 12:43
The OpenShift free tier is only intended for experimentation and testing. Part of the reason for it appearing slow with the templates I had though was that memory was only set at 256Mi. Reducing the memory, also reduces the CPU allocated in proportion. Set the memory at 512Mi and you would have had twice as much CPU allocation. Overall you only have 1Gi memory to play with though and if you also need to run PostgreSQL, you have to give it enough memory. So is a juggling act trying to divide up resources.

**Comment by wolpi** [comment] 2018-07-09 12:50
> So is a juggling act trying to divide up resources. 

Oh yes, I was juggling a lot :laughing:

**Comment by nijel** [comment] 2018-07-22 15:10
How about merging this back? It might not be perfect, but still better than nothing ;-).

**Comment by nosijf982** [comment] 2018-07-30 12:04
I follow the steps and gives this error @GrahamDumpleton 
`
[Mon Jul 30 11:58:52.399378 2018] [wsgi:error] [pid 335:tid 139813629839552] mod_wsgi (pid=335): Failed to exec Python script file '/tmp/mod_wsgi-localhost:8080:1038760000/handler.wsgi'.
--
  | [Mon Jul 30 11:58:52.399449 2018] [wsgi:error] [pid 335:tid 139813629839552] mod_wsgi (pid=335): Exception occurred processing WSGI script '/tmp/mod_wsgi-localhost:8080:1038760000/handler.wsgi'.
  | [Mon Jul 30 11:58:52.401630 2018] [wsgi:error] [pid 335:tid 139813629839552] Traceback (most recent call last):
  | [Mon Jul 30 11:58:52.401716 2018] [wsgi:error] [pid 335:tid 139813629839552]   File "/tmp/mod_wsgi-localhost:8080:1038760000/handler.wsgi", line 94, in <module>
  | [Mon Jul 30 11:58:52.401731 2018] [wsgi:error] [pid 335:tid 139813629839552]     recorder_directory=recorder_directory)
  | [Mon Jul 30 11:58:52.401744 2018] [wsgi:error] [pid 335:tid 139813629839552]   File "/opt/app-root/lib/python3.5/site-packages/mod_wsgi/server/__init__.py", line 1391, in __init__
  | [Mon Jul 30 11:58:52.401748 2018] [wsgi:error] [pid 335:tid 139813629839552]     __import__(entry_point)
  | [Mon Jul 30 11:58:52.401756 2018] [wsgi:error] [pid 335:tid 139813629839552]   File "/opt/app-root/src/weblate/wsgi.py", line 44, in <module>
  | [Mon Jul 30 11:58:52.401759 2018] [wsgi:error] [pid 335:tid 139813629839552]     application = get_wsgi_application()
  | [Mon Jul 30 11:58:52.401769 2018] [wsgi:error] [pid 335:tid 139813629839552]   File "/opt/app-root/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
  | [Mon Jul 30 11:58:52.401773 2018] [wsgi:error] [pid 335:tid 139813629839552]     django.setup(set_prefix=False)
  | [Mon Jul 30 11:58:52.401781 2018] [wsgi:error] [pid 335:tid 139813629839552]   File "/opt/app-root/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
  | [Mon Jul 30 11:58:52.401784 2018] [wsgi:error] [pid 335:tid 139813629839552]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  | [Mon Jul 30 11:58:52.401792 2018] [wsgi:error] [pid 335:tid 139813629839552]   File "/opt/app-root/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
  | [Mon Jul 30 11:58:52.401842 2018] [wsgi:error] [pid 335:tid 139813629839552]     self._setup(name)
  | [Mon Jul 30 11:58:52.401850 2018] [wsgi:error] [pid 335:tid 139813629839552]   File "/opt/app-root/lib/python3.5/site-packages/django/conf/__init__.py", line 43, in _setup
  | [Mon Jul 30 11:58:52.401853 2018] [wsgi:error] [pid 335:tid 139813629839552]     self._wrapped = Settings(settings_module)
  | [Mon Jul 30 11:58:52.401861 2018] [wsgi:error] [pid 335:tid 139813629839552]   File "/opt/app-root/lib/python3.5/site-packages/django/conf/__init__.py", line 106, in __init__
  | [Mon Jul 30 11:58:52.401864 2018] [wsgi:error] [pid 335:tid 139813629839552]     mod = importlib.import_module(self.SETTINGS_MODULE)
  | [Mon Jul 30 11:58:52.401872 2018] [wsgi:error] [pid 335:tid 139813629839552]   File "/opt/app-root/lib64/python3.5/importlib/__init__.py", line 126, in import_module
  | [Mon Jul 30 11:58:52.401875 2018] [wsgi:error] [pid 335:tid 139813629839552]     return _bootstrap._gcd_import(name[level:], package, level)
  | [Mon Jul 30 11:58:52.401883 2018] [wsgi:error] [pid 335:tid 139813629839552]   File "/opt/app-root/src/weblate/settings_openshift.py", line 120, in <module>
  | [Mon Jul 30 11:58:52.401886 2018] [wsgi:error] [pid 335:tid 139813629839552]     import_env_vars(os.environ, sys.modules[__name__])
  | [Mon Jul 30 11:58:52.401894 2018] [wsgi:error] [pid 335:tid 139813629839552]   File "/opt/app-root/src/weblate/openshiftlib.py", line 62, in import_env_vars
  | [Mon Jul 30 11:58:52.401897 2018] [wsgi:error] [pid 335:tid 139813629839552]     ast.literal_eval(Template(value).substitute(environ)))
  | [Mon Jul 30 11:58:52.401904 2018] [wsgi:error] [pid 335:tid 139813629839552]   File "/opt/rh/rh-python35/root/usr/lib64/python3.5/ast.py", line 46, in literal_eval
  | [Mon Jul 30 11:58:52.401907 2018] [wsgi:error] [pid 335:tid 139813629839552]     node_or_string = parse(node_or_string, mode='eval')
  | [Mon Jul 30 11:58:52.401914 2018] [wsgi:error] [pid 335:tid 139813629839552]   File "/opt/rh/rh-python35/root/usr/lib64/python3.5/ast.py", line 35, in parse
  | [Mon Jul 30 11:58:52.401917 2018] [wsgi:error] [pid 335:tid 139813629839552]     return compile(source, filename, mode, PyCF_ONLY_AST)
  | [Mon Jul 30 11:58:52.401946 2018] [wsgi:error] [pid 335:tid 139813629839552]   File "<unknown>", line 1
  | [Mon Jul 30 11:58:52.401969 2018] [wsgi:error] [pid 335:tid 139813629839552]     172.11.44.94
  | [Mon Jul 30 11:58:52.401998 2018] [wsgi:error] [pid 335:tid 139813629839552]             ^
  | [Mon Jul 30 11:58:52.402010 2018] [wsgi:error] [pid 335:tid 139813629839552] SyntaxError: invalid syntax
`

**Comment by GrahamDumpleton** [comment] 2018-07-31 12:09
Which steps? What were the commands you ran?

**Comment by nosijf982** [comment] 2018-07-31 13:26
Forget it. Sorry. I tried again and already works

**Comment by nijel** [comment] 2018-09-04 05:39
I've just merged changes done by @GrahamDumpleton, thanks for making them. There is always space for improvements, but it seems this works quite well. 

If somebody happens to have issues with this, please open separate issues to avoid extending this long discussion.

**Closed by nijel** 2018-09-04 05:39 UTC
Labels: enhancement, good first issue
