### ISSUE TITLE
Offer multiple translation

### ISSUE THREAD

**Issue by KadAnna** [WeblateOrg/weblate#8295] opened 2022-11-02 08:59 UTC
### Describe the problem

Project has multiple strings with the same text. I have to translate them one by one.

### Describe the solution you'd like

When translating a string, which is in fact multiple times in a project, I would like 
- Weblate showing me that this string is multiple times in the project and
- Weblate giving the chance to apply the translation to all the strings at once. 

Additionally, duplicates could be reflected in statistics, as it could lower the translation cost.

**Comment by Geeyun-JY3** [comment] 2022-11-03 04:04
Could you give an example of a project that has multiple strings with the same text where you have to translate them one by one?

**Comment by nijel** [comment] 2022-11-04 10:25
That's what "Other occurences" tab shows, see for example: https://hosted.weblate.org/translate/weblate/application/cs/?checksum=1302f55c88f998e2#others

**Comment by Geeyun-JY3** [comment] 2022-11-04 10:35
AFAIK, if multiple strings are totally the same (including other information such as context, key, and source string description), they are shown as one string in Weblate, while the locations of these strings are listed in the `String information` panel (**`Source string location`**).

Additionally, if the project has multiple strings with the same text but different in other information (Context, Key, Source string description), they would be listed under the `Other occurrences` tab in the full editor: https://docs.weblate.org/en/latest/user/translating.html#translation-context

**Comment by Geeyun-JY3** [comment] 2022-11-04 10:35
AFAIK, if multiple strings are totally the same (including other information such as context, key, and source string description), they are shown as one string in Weblate, while the locations of these strings are listed in the `String information` panel (**`Source string location`**).

Additionally, if the project has multiple strings with the same text but different in other information (Context, Key, Source string description), they would be listed under the `Other occurrences` tab in the full editor: https://docs.weblate.org/en/latest/user/translating.html#translation-context

**Comment by ilocit** [comment] 2022-11-10 12:26
@Geeyun-JY3 and @nijel you are right about your answers, but still, I understand and concur with what @KadAnna is saying.
An issue with Weblate is that if you have such strings with the same source text but different context, there is really no way to distribute those automatically while translating. Plus the statistics show them as different words which increases cost. Usually, in CAT tools, 100% matches are counted differently, and the cost is lower. 
I will think about how this could be implemented in Weblate.
The distribution (propagation) should be a big problem to implement. How to reflect this in the stats and word count is more challenging.

**Comment by comradekingu** [comment] 2022-11-10 14:40
@ilocit
Don't know how it is counted, but here are the options to automate translation:

(I'd really want a confidence level set that signifies auto-translation of any sort, but that is another matter.)

Automated propagation
https://docs.weblate.org/no/latest/admin/projects.html#component-allow-translation-propagation
https://hosted.weblate.org/settings/remmina/project/#translation

Sharing TM
https://hosted.weblate.org/settings/project/#workflow
Shared translation memory

Auto-translation for components
https://docs.weblate.org/no/latest/admin/addons.html#addon-weblate-autotranslate-autotranslate
https://hosted.weblate.org/addons/project/component/

Automated suggestions from the instance TM
https://docs.weblate.org/no/latest/admin/config.html#weblate-machinery
https://hosted.weblate.org/machinery/project/
Here you can turn on "Weblate translation memory" site-wide.

My main problem with your instance is not being let in to translate projects I use.

**Comment by ilocit** [comment] 2022-11-10 14:47
I know about those options, @comradekingu .
What do you mean by 

> My main problem with your instance is not being let in to translate projects I use

Do you want to have access to my Weblate instance? What for?

**Comment by nijel** [comment] 2022-11-21 13:00
> The distribution (propagation) should be a big problem to implement.

I guess there is “not” missing in the sentence. The problem is here to agree on the specification (see https://github.com/WeblateOrg/weblate/issues/3166), once we have that the implementation will most likely be not that hard.

> How to reflect this in the stats and word count is more challenging.

Accounting that in reports will not be that hard once the propagated/distributed changes will be marked as such in the history.

**Comment by ilocit** [comment] 2022-11-21 13:11
I added the **not** to the sentence. Of course it was missing ;-)
Thx, @nijel!

Regarding the "Accounting" it is a little more complex, since traditional CAT (Computer Assisted Translation) tools basically give you the option to calculate statistics and cost up-front.

Like this, for example:
![image](https://user-images.githubusercontent.com/26718215/203062938-1ed39db5-2058-4e90-b747-baa2e828dc11.png)

The translators are then paid different percentages of a full "per word rate" for each category. I don't think that we (you) need to build a similar analysis and reporting, but the 100% matches (Repetitions) should be handled in some sort. I will think about it and maybe also add suggestions to issue #3166

**Closed** 2022-12-07 02:04 UTC
Labels: wontfix

**Comment by nijel** [comment] 2022-12-07 08:54
@ilocit I think including something for cost estimation is a good fit for Weblate. There is https://github.com/WeblateOrg/weblate/issues/7389 for that, and I've posted your comment there.

As usual, we need good specification before implementing a new feature, and that applies to both https://github.com/WeblateOrg/weblate/issues/7389 and https://github.com/WeblateOrg/weblate/issues/3166

I believe the original issue by @KadAnna is addressed by *Other occurrences* tab, if you think it should be extended somehow, https://github.com/WeblateOrg/weblate/issues/8425 is the place to discuss that.
