### ISSUE TITLE
Adding new Component takes very long / causes gateway timeout

### ISSUE THREAD

**Issue by Flohack74** [WeblateOrg/weblate#1624] opened 2017-09-05 16:45 UTC
Hello,

while adding our projects for UBports to Weblate (self-hosted) we see the issue that the initial indexing takes very long. This is because we got a lot of languages and a lot of strings in each file.

Eventually after some minutes the server comes back with a gateway timeout but luckily the background process finishes its work and adds the component.

I still only know if it has been finished if I log in via ssh and check the load of the server. Sometimes it takes over 10 minutes until this import is finished.

I would be happy to have either kind of progress reporting, or a complete background processing for that. Because now its not easy to work with.

Thanks!

**Comment by nijel** [comment] 2017-09-07 14:00
There is some information on this in our documentation: https://docs.weblate.org/en/latest/admin/projects.html#importing-speed

The progress reporting is already there in our tracker.

Duplicate of #372

**Closed by nijel** 2017-09-07 14:00 UTC
