### ISSUE TITLE
Strings per page option additional to zen infinite loading

### ISSUE THREAD

**Issue by Aikatsui** [WeblateOrg/weblate#5535] opened 2021-02-27 21:39 UTC
**Is your feature request related to a problem? If so, please describe.**
Zen mode is perfect solution when someone need to view all strings according to order for find issues, mistakes or other editing tasks rather than view under nearby strings

**Describe the solution you'd like**
There's a big gap between strings when view under zen mode infinite loading then it's quite difficult to scroll or memorize about certain strings positions, move back to particular string etc.

I think that may suitable to common mode. It has 15 nearby strings by default then if has way to jump to next 15 nearby strings, it'll address this problem
```
|< < 1/500 > >| 
> - jump to next string
>| - jump to end (500)

|<< |< < 1/500 > >| >>|
> - jump to next string
>| - jump to next 15 strings (configured x nearby)
>>| - jump to end (500)
```
**Resources**

Crowdin editor

**Comment by nijel** [comment] 2021-02-28 07:18
To view strings, there is also browse mode (introduced in 4.5).

**Comment by Aikatsui** [comment] 2021-02-28 23:28
Does it already live on hosted weblate? can you specify more about it because i cannot recognize
I mean as below random sample, it show around 50 strings per page (amount configurable on weblate as nearby strings)

![ksnip-20210301-061759](https://user-images.githubusercontent.com/63988538/109437323-eb656900-7a56-11eb-830a-64a5b2474aeb.png)

**Comment by nijel** [comment] 2021-03-02 06:51
Yes, the browse is already there: https://hosted.weblate.org/browse/weblate/application/cs/

**Comment by Aikatsui** [comment] 2021-03-05 06:18
> Yes, the browse is already there: https://hosted.weblate.org/browse/weblate/application/cs/

Thank you. It seems suitable for maintainer or translator to see a quick overview but annoying with below use cases
as i said above i expect to have this in editor mode similar crowdin (looks like catch 2 birds using one stone) Currently browse mode only able to use for viewing purpose, i think it's rare need; most are re-check for find mistakes, translations quality, find or look back random words or sentences, copy certain string translation that unable to get using memory, missing or forgot contents, compare etc then it'll be better if possible to edit immediately without move between different pages or positions

Small enhancement to editor mode will help to address this issue.
![image](https://user-images.githubusercontent.com/63988538/110073065-60b39f80-7db1-11eb-9877-fc7f7f475248.png)

```
|<< |< < 1/500 > >| >>|
(available)  > - jump to next string
(proposed)   >| - jump to next 15 strings (configured x nearby)
(available)  >>| - jump to end (500)
```

**Comment by nijel** [comment] 2021-09-08 08:25
Duplicate of #6393

**Closed by nijel** 2021-09-08 08:25 UTC
Labels: enhancement, ux, duplicate, backlog

**Comment by Aikatsui** [comment] 2022-07-14 18:27
https://github.com/WeblateOrg/weblate/issues/7655
