### ISSUE TITLE
No notification when source strings are added or updated

### ISSUE THREAD

**Issue by laoneo** [WeblateOrg/weblate#10651] opened 2023-12-18 12:10 UTC
### Describe the issue

When a source strings get's updated or added in a component through a git commit in the en-GB "Monolingual base language file", then no notification mail goes out. In the notification settings I'v set "New string is available for translation" and "String was changed" to instant notification. Do I miss here something or is this a bug?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [x] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Choose a translated language in the user settings
2. Watch a project in the user settings
3. Set all notifications to Instant in the user settings
4. Commit a new string and an update string in a base monolingual file

### Expected behavior

A notification mail goes out to the user.

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/251072/39ffcda6-ba13-438b-8385-8460e5f5b66a)

### How do you run Weblate?

Docker container

### Weblate versions

5.3

**Comment by nijel** [comment] 2023-12-18 12:15
There is currently no notification for source string being changed. Closest to that is "Unfinished strings exist" as that will trigger when some string will need a translation.

**Comment by laoneo** [comment] 2023-12-18 12:18
Any plan to integrate this? Coming from Transifex this is one of the key features as rarely no translators are polling weblate for changes. It keeps them engaged.

**Comment by nijel** [comment] 2023-12-18 15:20
This seems like a duplicate of https://github.com/WeblateOrg/weblate/issues/5602. Can you please review that and close this if this is really the case?

**Comment by laoneo** [comment] 2023-12-19 07:16
Not really, mine is more about notifications and not about pending tasks.

**Comment by laoneo** [comment] 2023-12-19 07:17
Or is there another way a translator who watches a project gets a notification when a source string has change or is added?

**Comment by Aga-C** [comment] 2023-12-19 10:26
@nijel @laoneo I can confirm that it's a bug. I haven't changed anything in the settings, but some time ago, I stopped receiving any emails about new strings to translate or that someone translated something. I am only receiving notifications about new comments or new components.

**Comment by nijel** [comment] 2023-12-19 13:44
@laoneo The notification for new string is there (New string is available for translation), the notification when source string changes is not there.

@Aga-C Unfortunately, we're not talking about a bug here, but about a missing feature. If you see a bug, please open a separate issue for that and provide more information (especially what notifications you have configured).

**Comment by laoneo** [comment] 2023-12-19 13:47
Thanks @nijel , but I do not get a mail when a new string is added either after a git rebase from the github webhook.

**Comment by laoneo** [comment] 2023-12-19 17:27
@nijel how big is the chance that you will implement this feature request that when a source string is added/update that notification mails are going out? With this change you can catch up to the big providers like transifex or crowdin as this is an important feature to keep the translators engaged.

**Comment by nijel** [comment] 2023-12-19 19:19
You're right, the strings added in the repository do not trigger the notification, https://github.com/WeblateOrg/weblate/pull/10659 should address this.

**Comment by kvikshaug** [comment] 2024-01-31 16:22
@nijel is it possible the issue wasn't completely solved? I'm testing locally version `5.3.1+2024-01-31` (which includes #10659). Adding a new string to the repo still does not trigger the notification, even though the setting `New string is available for translation` is set to `Instant notification`. (I do get a `Repository operation` notification.)

Rolling back to version 4.18.2 works. That is, with the same app data folder and database, adding a new string to the repo successfully sends a `New string to translate` notification.

**Comment by nijel** [comment] 2024-01-31 18:38
The issue indeed isn't completely solved at it is still open.

Do you see "String added in the repository" event in the string history?

**Comment by kvikshaug** [comment] 2024-02-01 10:44
Ahh... I see. Yes indeed, the event is there:
![image](https://github.com/WeblateOrg/weblate/assets/64745/81609f4a-44f7-442e-9fed-f350e22aee5b)

**Comment by nijel** [comment] 2024-02-14 15:19
https://github.com/WeblateOrg/weblate/pull/11002 should fix the new string notification not being sent.

**Comment by laoneo** [comment] 2024-02-15 05:59
Thanks, so only update is missing and then can this issue being closed?

**Comment by nijel** [comment] 2024-02-15 07:16
Yes.

**Comment by laoneo** [comment] 2024-02-15 13:22
Ok, then I wait with closing this issue.

**Closed** 2024-05-15 13:04 UTC
Labels: enhancement
