### ISSUE TITLE
Make it possible to hide some keys

### ISSUE THREAD

**Issue by JiDW** [WeblateOrg/weblate#8084] opened 2022-09-06 13:39 UTC
### Describe the problem

Hello,

We have to translate a nested JSON file format that can contain an unknown number of meta keys that should not be translated.

Ex:

```json
{
	"label": "Pré-tirés",
	"mapping": {
		"keywords": "system.keywords",
		"profile":  "system.info.profile",
		"profdef": "system.info.profdef"
	},
	"entries": {
		"Archie “Bulldog” Grimm": {
			"name": "Archie “Bulldog” Grimm",
			"keywords": "53 ans. Caucasien. Taille moyenne.\nCheveux blancs. Costume noir.\nPardessus beige. Mine renfrognée.",
			"profile": "Ancien policier",
			"profdef": "Psychologue : en utilisant 1 point de Ressource, Archie peut savoir si on lui ment ou omet sciemment des informations."
		},
		"Damien Barnes": {
			"name": "Damien Barnes",
			"keywords": "33 ans. Noir. Taille moyenne.\nCheveux courts bruns. Bouc. Cernés.\nSoutane. Chapelet en main.",
			"profile": "Exorciste",
			"profdef":  "Imposition des mains : en utilisant 1 point de Ressource et en touchant un tiers, Damien peut savoir si la personne est possédée ou étroitement liée à un démon."
		}
	}
}
```

In this example, we would like to hide every keys in the "mapping" level.

### Describe the solution you'd like

It could be an addon or component setting to have a "Hide keys mask" feature.

Ex: 

![image](https://user-images.githubusercontent.com/581736/188649419-b8cf2644-81e5-4c0c-8745-75effef5d28d.png)

### Describe alternatives you've considered

I may be able to create my own addon, I already created one for a very specific need, but I have no idea how to interact with key visibility as I could not find another addon interacting with this part of the code.

**Comment by nijel** [comment] 2022-09-07 06:00
It might be possible to implement as an add-on based on `StoreBaseAddon` and monkey-patching the store. On the other side, I'm not convinced whether it's a good approach to such filtering.

What you can do right now is using bulk edit add-on to mark such strings read-only, see https://docs.weblate.org/en/latest/admin/addons.html#bulk-edit

**Comment by JiDW** [comment] 2022-09-08 12:53
I'll try to understand how the StoreBaseAddon works, thanks! If you have any other pointers to help me understand how it works, and what event I could listen to monkey-patch the store, that would be very welcome. If not, I'll manage.

I can't use bulk-edit for this because we'll have hundreds of different components that can change their meta at any time from more than 50 different developers and teams.
That's why I need something to actively filter these keys.

We're hosting a Weblate for a decently large community of open-source developers creating free addons for a role-playing game software (called Foundry VTT), so I need to find a hands-free solution.

**Comment by nijel** [comment] 2022-09-12 08:25
The `store_post_load` of the add-on is called whenever file is parsed. You can then monkey-patch `all_store_units` property of the store to do filtering you want.

**Comment by JiDW** [comment] 2022-09-12 08:30
Thank you!

**Comment by bebroll** [comment] 2022-11-13 20:27
I would like to chime in on this topic because it also applies to our use case:

In one project where I've tried to make use of Weblate, some textual contents that are supposed to be localized are stored in project-specific JSON files. In our case, the entries in the example posted by @JiDW would contain an ID, for example, or some parameters that configure the appearance of the entry. Since neither the ID nor the parameters should be changed, having them show up in Weblate is not ideal.

While we can manually set them to "readonly", I don't see a way how you'd be able to use the bulk edit feature to add the "readonly" flag to all of them at once. As far as I understand, there is no "add flag to all strings where the key matches a JSON key path" option, right?

Ideally, there would be a translation component-specific add-on that can be enabled where you can specify a list of JSON key paths (as @JiDW had suggested in the screenshot) and which will cause the matching entries of the JSON file to be hidden in the UI.

**Comment by nijel** [comment] 2022-11-14 12:58
> While we can manually set them to "readonly", I don't see a way how you'd be able to use the bulk edit feature to add the "readonly" flag to all of them at once. As far as I understand, there is no "add flag to all strings where the key matches a JSON key path" option, right?

That's exactly what the [bulk edit add-on])(https://docs.weblate.org/en/latest/admin/addons.html#bulk-edit) can do. You can use any search query there. Still, I consider this more like a workaround than a final solution.

**Comment by bebroll** [comment] 2022-11-15 22:08
I missed that you can use a regex as the query with the bulk-edit add-on. When using a regex, you can, indeed, query the JSON keys with wildcards and mark them "read-only" with little effort. That is very helpful, indeed, thanks!

The drawback of the workaround is that any change to the underlying files which adds new entries will require another bulk-edit run to mark the new keys as read-only. That's where a solution for excluding certain JSON key paths via an add-on would work better.

**Comment by nijel** [comment] 2022-11-21 10:15
The bulk-edit add-on is run on every update of the file...

**Comment by nijel** [comment] 2024-05-06 06:53
Duplicate of #11562

**Closed by nijel** 2024-05-06 06:53 UTC
Labels: enhancement, undecided, duplicate
