### ISSUE TITLE
OpenAI addon does not work with large glossaries

### ISSUE THREAD

**Issue by gzor** [WeblateOrg/weblate#10836] opened 2024-01-22 14:12 UTC
### Describe the issue

Instead of getting suggestings from openai, i only get an error 400 with a reference a too big context.
```
gunicorn stderr | [2024-01-22 13:48:49,406: WARNING/448] Machinery error: BadRequestError: Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens. However, your messages resulted in 9223 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}
```
Since i already imported a big file, and marked it as glossary, i guess that the glossary is just appended to the message, and the message gets to big after adding this.

BTW: The error display is solved nicely.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

- Import a lage file (which is largely translated), and mark it as glossary. (My file has roughly 4k words, and is 94% translated)
- Enable OpenAI Addon
- Try to get a translation suggestion by navigating to an untranslated string and klick on automatic suggestion on the bottom half.

### Expected behavior

I would expect to see a translation suggestion.

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 5.3.1
 * Django: 4.2.8
 * siphashc: 2.3
 * translate-toolkit: 3.11.1
 * lxml: 4.9.3
 * Pillow: 10.1.0
 * nh3: 0.2.15
 * python-dateutil: 2.8.2
 * social-auth-core: 4.5.1
 * social-auth-app-django: 5.4.0
 * django-crispy-forms: 2.1
 * oauthlib: 3.2.2
 * django-compressor: 4.4
 * djangorestframework: 3.14.0
 * django-filter: 23.5
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.13.1
 * rapidfuzz: 3.5.2
 * openpyxl: 3.1.2
 * celery: 5.3.6
 * django-celery-beat: 2.5.0
 * kombu: 5.3.4
 * translation-finder: 2.15
 * weblate-language-data: 2023.9
 * html2text: 2020.1.16
 * pycairo: 1.25.1
 * PyGObject: 3.46.0
 * diff-match-patch: 20230430
 * requests: 2.31.0
 * django-redis: 5.4.0
 * hiredis: 2.2.3
 * sentry-sdk: 1.39.1
 * Cython: 3.0.6
 * misaka: 2.1.1
 * GitPython: 3.1.40
 * borgbackup: 1.2.7
 * pyparsing: 3.1.1
 * ahocorasick_rs: 0.20.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.2
 * Python: 3.11.7
 * Git: 2.39.2
 * psycopg: 3.1.16
 * psycopg-binary: 3.1.16
 * phply: 1.2.6
 * ruamel.yaml: 0.18.5
 * tesserocr: 2.6.2
 * boto3: 1.34.3
 * zeep: 4.2.1
 * aeidon: 1.13
 * iniparse: 0.5
 * mysqlclient: 2.2.1
 * Mercurial: 6.6.1
 * git-svn: 2.39.2
 * git-review: 2.3.1
 * PostgreSQL server: 16.1
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mail.intern.inform-software.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.10.0-11-amd64 (x86_64)

### Weblate deploy checks

```shell
ARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/backup.html
```

**Comment by nijel** [comment] 2024-01-22 18:17
Duplicate of https://github.com/WeblateOrg/weblate/issues/10749

**Closed** 2024-01-22 18:17 UTC
Labels: enhancement, duplicate

**Comment by gzor** [comment] 2024-01-23 08:02
Ah, sorry i think i only searched for open issues.
