### ISSUE TITLE
AttributeError: 'tzlocal' object has no attribute '_hasdst'

### ISSUE THREAD

**Issue by paulpach** [WeblateOrg/weblate#2422] opened 2018-11-30 23:08 UTC
**Describe the bug**
getting exception when opening a component

**To Reproduce**
1. run docker version of weblate
2. login
3. navigate to a component (po )
4. observer error in the logs

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/weblate/trans/views/basic.py", line 286, in show_translation
    'exporters': list_exporters(),
  File "/usr/local/lib/python3.6/dist-packages/weblate/trans/util.py", line 236, in render
    return django_render(request, template, context, status=status)
  File "/usr/local/lib/python3.6/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.6/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.6/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/defaulttags.py", line 512, in render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/defaulttags.py", line 512, in render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/dist-packages/django/templatetags/i18n.py", line 132, in render
    tmp_context[var] = val.resolve(context)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 694, in resolve
    obj = template_localtime(obj, context.use_tz)
  File "/usr/local/lib/python3.6/dist-packages/django/utils/timezone.py", line 177, in template_localtime
    not is_naive(value) and
  File "/usr/local/lib/python3.6/dist-packages/django/utils/timezone.py", line 255, in is_naive
    return value.utcoffset() is None
  File "/usr/lib/python3/dist-packages/dateutil/tz/tz.py", line 178, in utcoffset
    if self._isdst(dt):
  File "/usr/lib/python3/dist-packages/dateutil/tz/tz.py", line 243, in _isdst
    if not self._hasdst:
AttributeError: 'tzlocal' object has no attribute '_hasdst'
```

**Expected behavior**
No error,  server responds normally

**Screenshots**

**Server configuration and status**

weblate list_versions

 * Weblate 3.3
 * Python 3.6.7
 * Django 2.1.3
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.11.0
 * social-auth-core 2.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.17.1
 * Pillow 5.1.0
 * python-dateutil 2.6.1
 * lxml 4.2.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.0
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.7
 * pyuca 1.2
 * PyYAML 3.12
 * tesserocr 2.3.1
 * Mercurial 4.5.3
 * git-svn 2.17.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.14.65+ (x86_64)

```
$ weblate check --deploy
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Can not send email ([Errno 101] Network is unreachable), please check EMAIL_* settings.
	HINT: https://docs.weblate.org/en/weblate-3.3/admin/install.html#out-mail
?: (weblate.E012) The server email has default value
	HINT: https://docs.weblate.org/en/weblate-3.3/admin/install.html#production-email
?: (weblate.E013) The default from email has default value
	HINT: https://docs.weblate.org/en/weblate-3.3/admin/install.html#production-email

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

System check identified 6 issues (0 silenced).
```

**Additional context**

Upgraded from previously working version

**Comment by nijel** [comment] 2018-12-01 07:00
Duplicate of #2421

**Closed by nijel** 2018-12-01 07:00 UTC
