### ISSUE TITLE
Some glossary terms are saved twice to TBX causing translations to disappear

### ISSUE THREAD

**Issue by yilmazdurmaz** [WeblateOrg/weblate#9701] opened 2023-08-08 11:12 UTC
### Describe the issue

There is no way to tell when this will happen. And I cannot trace who or what changes these. But happens in many languages at different times.

my translation is deleted today:
https://hosted.weblate.org/translate/godot-engine/glossary/tr/?checksum=ed18aa2599356aed&q=+changed%3A%3E%3D2023-07-08&sort_by=source

a chinese one deleted3 days ago:
https://hosted.weblate.org/translate/godot-engine/glossary/zh_Hans/?checksum=ed18aa2599356aed&q=+changed%3A%3E%3D2023-07-08&sort_by=source

As per a previous statement, I thought it could be a new addition to the English source, but there does not seem anything new there. besides, that should possibly be added as a duplicate.

I could only trace so far. I would say it might be related how translations propagates from components, but that does not tell anything about "deleting"

Please check the system and fix whatever causes the issue.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Seeming randomly happening. Only clue for me is the "None" username

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment] 2023-08-08 12:55
The problem seems caused by duplicate entries in the TBX file:

```xml
            <termEntry>
                <langSet xml:lang="en"><tig><term>Signals</term></tig></langSet>
                <langSet xml:lang="tr"><tig><term/></tig></langSet>
            </termEntry>
...
            <termEntry>
                <langSet xml:lang="en"><tig><term>Signals</term></tig></langSet>
                <langSet xml:lang="tr"><tig><term>Sinyaller, İşaretler</term></tig></langSet>
            </termEntry>
```

The question is how they appeared there.

**Comment by yilmazdurmaz** [comment] 2023-08-08 13:03
> The problem seems caused by duplicate entries in the TBX file:

That is also interesting because if I search for that word, I get only 1 result: https://hosted.weblate.org/browse/godot-engine/glossary/tr/?q=Signals&sort_by=-priority%2Cposition&checksum=

**Comment by nijel** [comment] 2023-08-09 12:08
That's expected, but it should trigger the duplicate string alert instead. Seems like there is some bug in processing TBX files.

**Comment by timothyqiu** [comment] 2023-08-14 09:59
I have the exact opposite problem. Whenever I delete one of these three glossaries, the "None" user recovers it immediately :rofl: 

* https://hosted.weblate.org/translate/godot-engine/glossary/zh_Hans/?checksum=74d5f3866906da0b
* https://hosted.weblate.org/translate/godot-engine/glossary/zh_Hans/?checksum=7d337a13ea32f347
* https://hosted.weblate.org/translate/godot-engine/glossary/zh_Hans/?checksum=320d0f7752d3f8b6

**Comment by ngocanhtve** [comment] 2023-10-29 13:19
I've also had a few deleted/edited by this "None" user.

**Comment by Cerno-b** [comment] 2023-11-02 06:07
I can confirm that this is still a problem and not only occurs for adding or deleting a text, but also for editing. Is there any possible workaround until this is fixed?

**Comment by nijel** [comment] 2023-12-21 10:36
Workaround is to fix the TBX files manually to remove duplicate entries.

**Comment by nijel** [comment] 2024-06-17 12:28
Has anybody seen this issue recently? I still fail to reproduce it and in case we don't see it on recent releases, it might have been fixed by some other fix (like https://github.com/WeblateOrg/weblate/issues/10581).

**Closed** 2024-06-26 12:22 UTC
Labels: bug

**Comment by yilmazdurmaz** [comment] 2024-06-26 13:53
Thanks, and sorry for not responding previously.

I am not able to test this fix for a few more weeks. Let's hope it is alright.

I marked the issue to test later, and will ask to reopen the issue if what I was experiencing is around.

**Comment by nijel** [comment] 2024-06-26 14:05
I was able to reproduce the issue after deleting a glossary term in all languages (what deleted it from the database and not from the file, see https://github.com/WeblateOrg/weblate/issues/10403) and adding it again. There might have been other way to trigger this, so in case you can reproduce this, it would be great to know how.
