### ISSUE TITLE
Impossible to delete a key from the web interface

### ISSUE THREAD

**Issue by ad-boschung** [WeblateOrg/weblate#2599] opened 2019-03-04 12:45 UTC
**Is your feature request related to a problem? Please describe.**
I can't delete a translation in the web interface. I don't understand why this feature is not implemented when it is possible to add a new key from the web interface.
 

**Describe the solution you'd like**
It will be great to have a "Delete" button next to the "Save" button (editing mode).  Of course this should be only available for the project/component administrators.

**Comment by nijel** [comment] 2019-03-04 12:46
Duplicate of #1974

**Closed by nijel** 2019-03-04 12:46 UTC
