### ISSUE TITLE
Unable to resolve "Other translation" check

### ISSUE THREAD

**Issue by maldn** [WeblateOrg/weblate#2563] opened 2019-02-19 18:00 UTC
I have a translation where the source string is also present in another component of the same project.
(One component translates the server-side strings, the other translates the JS/client-side strings.)

For one language (de) where the translation is different from the source, after clicking "Use this translation" the failed check goes away.
For another language (nl) where the source and translation are the exact same string, i cannot get the check "other translation" to disappear, resulting in a non-100% translation despite the correct translations.

am i missing something, or is this a bug?

weblate version: 3.4
i also tried with a fresh project including those 2 components with those 2 languages; same thing

maybe related to https://github.com/WeblateOrg/weblate/issues/2085

**Comment by nijel** [comment] 2019-02-20 11:56
Duplicate of #1694

**Closed by nijel** 2019-02-20 11:56 UTC
Labels: bug

**Comment by maldn** [comment] 2019-02-20 13:38
the issue in #1694 was that the string was not translated in the other component.
in my case it is, and no combination of "Use this translation" in either component will make the "failed" check dissapear.
![image](https://user-images.githubusercontent.com/354077/53095430-22761b00-351d-11e9-9172-fc5c0e6bf113.png)

**Comment by nijel** [comment] 2019-02-20 13:39
The fix for #1694 was to remove the problematic check here, see https://github.com/WeblateOrg/weblate/commit/3e4e09e49a5379f73dc598f64a3c62f2e558a038
