### ISSUE TITLE
How to avoid adding language again after pull?

### ISSUE THREAD

**Issue by wastee** [WeblateOrg/weblate#1916] opened 2018-03-21 08:49 UTC
### Steps to reproduce
1. Add a project, add a component. Push to Github
2. Change po file in github which i push by weblate
3. Then weblate auto pull these changed.
4. Re-add language to see tranlations.

### Actual behaviour
Before i change po file in github and pull to weblate, component shows language and detiles.
After change po and pull to weblate, i have to readd language to see translations.

### Expected behaviour
Pull the changed po file to weblate, and see changed translate in weblate. No need to readd language.

### Server configuration
 * Weblate 2.19.1
 * Python 2.7.13
 * Django 1.11.11
 * six 1.10.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.7.2
 * compressor 2.2
 * djangorestframework 3.7.7
 * user-agents 1.1.0
 * pytz 2018.3
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.2.2
 * Mercurial 4.0
 * git-svn 2.11.0
 * hub 2.2.9
 * Database backends: django.db.backends.postgresql_psycopg2

------------------------------
Thanks for you time!

**Comment by nijel** [comment] 2018-03-21 08:55
Are you sure Weblate does pull the changes? What does happen when you manually hit Pull in the repository maintenance?

**Comment by wastee** [comment] 2018-03-21 09:20
Wow. Your reply so fast.

## What i did
I am not familiar with git. This is what i do use web ui.
1. change file from github
![change po](https://user-images.githubusercontent.com/22229962/37701733-115f14ac-2d2b-11e8-977e-f758d6909192.png)
2. Click Pull button from  "projects/<project_name>/#repository" -> "Repository tools"
3. Check the component, and miss the language 
![miss language](https://user-images.githubusercontent.com/22229962/37701815-6844af3e-2d2b-11e8-996e-843cbd731cda.png)
4. Readd language
![readd language](https://user-images.githubusercontent.com/22229962/37701833-79df87a0-2d2b-11e8-9df4-a158475a1c12.png)
5. see the change
![see the change](https://user-images.githubusercontent.com/22229962/37701851-8906d6f2-2d2b-11e8-9a8d-d685a157b12f.png)

## How i build project and components

I use weblate with docker. Docker image is the offical weblate image.
I import 618 components in single project use import_json.
One component use git repo. The other 617 components use weblate://project/component as repo link.

-----------------------------------------
I can't really find what I missed

**Comment by nijel** [comment] 2018-03-21 09:30
That sounds correct. What is filemask configured on the component and filename of the translation? Do you have set language_regex for the component (check that in the admin interface)?

I'm suspecting that the last question is the problem - maybe this field is not properly set when using import_json.

**Comment by wastee** [comment] 2018-03-21 09:55
In my project, [about] is the one component use git repo.
Use [aaccess] component as an example. It use weblate://project/about as repo.
Language filter is default, because i don't really know what it means.
------------------------------------------------------------------------------------------
## Json format
I generate json file use this format:
`
            "name": [aaccess],
            "slug": aaccess,
            "repo": "weblate://reaper/about",
            "push": "git@github.com:wastee/REAPER_zh-hans.git", # <<After your reminder i know this value is wrong and i remove it from admin page.>>
            "branch": "master",
            "filemask": "po/[aaccess]-*.po",
            "new_base": "pot/[aaccess].pot",
            "committer_name": "REAPER Weblate",
            "committer_email": "i@lado.me"
`
## Field value in admin page
- Source code repository: weblate://reaper/about
- File mask: po/[aaccess]-*.po
- po file in github path: po/[aaccess]-zh_Hans.po
- Language filter: ^[^.]+$  # DEFAULT

After your reminder, i delete the push link. And i try again, but the component language missed again.

**Comment by nijel** [comment] 2018-03-21 10:54
Okay, the problem is in using `[]` chars in the filename - these are interpreted by [filename matching](https://docs.python.org/2/library/fnmatch.html) as well, so that's why the languages disappear. The language adding just replaces `*` in the filename, that's why it works in this case.

**Comment by wastee** [comment] 2018-03-21 13:23
Fix.You help me a lot. Thank you.

**Comment by nijel** [comment] 2018-03-21 14:36
Reopening, as this really should be fixed in Weblate. 

BTW: Have you changed the names or escaped the `[]` chars?

**Comment by wastee** [comment] 2018-03-21 14:39
I think it is not a bug. It should be a rule. This rule can add in document.

**Comment by nijel** [comment] 2018-03-21 15:07
I've added it to the documentation.

Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Closed** 2018-03-21 15:06 UTC
Labels: bug
