### ISSUE TITLE
Limit languages per string

### ISSUE THREAD

**Issue by fennibay** [WeblateOrg/weblate#2490] opened 2019-01-14 16:06 UTC
**Is your feature request related to a problem? Please describe.**
We have some texts in our setup that need to be English-only for referencing purposes. For example, when talking about the related artifacts we want everybody to use the English term for clarity.

**Describe the solution you'd like**
Weblate can already limit languages per component and per user. Could we also have it per string?

In the po file this could be represented with a custom flag such as:

`#, english-only`

or in a more generic way:

`#, allowed-langs:en,de`

**Describe alternatives you've considered**

I considered grouping such strings in a component, but:
1. from domain POV they belong together with other strings (longer and translatable)
1. from source code POV I'd then need to separate such strings into different folders etc.
1. I'd need to maintain this component manually, as new strings are added

**Comment by nijel** [comment] 2019-01-15 12:09
Probably duplicate of https://github.com/WeblateOrg/weblate/issues/743

**Comment by fennibay** [comment] 2019-01-15 12:48
Yes, looks like a duplicate. #743 comes from a different need, but ends up as a similar feature request.

Sorry I missed that. We can close this one, continue with the old one.

Duplicate of #743

**Closed** 2019-01-17 08:45 UTC
