### ISSUE TITLE
Adding Azure Login afterwards

### ISSUE THREAD

**Issue by reloxx13** [WeblateOrg/weblate#8052] opened 2022-08-24 07:02 UTC
### Describe the issue

Heya,

i have a weblate instance running with only email login.   
Now i want to add Azure. The users are not linkted to Azure now.    

If they login with azure now, it says "email already in use". I would expect that the azure login would match and use the existing user instead of creating a new user.

Is the default auth pipeline wrong? as it has "associate_user" and "associate_by_email". The pipeline task for duplicate check should only be triggered when creating a new user, it seems to run too early in the pipeline. but i dont know which one is the duplicate check. 

PS: i know the users should link their accounts manual now in their profile settings, but you know... :D 

```
# Social auth settings
SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.auth_allowed",
    "social_core.pipeline.social_auth.social_user",
    "weblate.accounts.pipeline.store_params",
    "weblate.accounts.pipeline.verify_open",
    "social_core.pipeline.user.get_username",
    "weblate.accounts.pipeline.require_email",
    "social_core.pipeline.mail.mail_validation",
    "weblate.accounts.pipeline.revoke_mail_code",
    "weblate.accounts.pipeline.ensure_valid",
    "weblate.accounts.pipeline.remove_account",
    "social_core.pipeline.social_auth.associate_by_email",
    "weblate.accounts.pipeline.reauthenticate",
    "weblate.accounts.pipeline.verify_username",
    "social_core.pipeline.user.create_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    "weblate.accounts.pipeline.cleanup_next",
    "weblate.accounts.pipeline.user_full_name",
    "weblate.accounts.pipeline.store_email",
    "weblate.accounts.pipeline.notify_connect",
    "weblate.accounts.pipeline.password_reset",
)
```

Another problem is, that the saved user id is not the user id azure shows, so i cannot even create those links manual.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Create a user with email    
logout     
login with azure now with same email  

### How do you run Weblate?

Git checkout

### Weblate versions

4.13

**Comment by nijel** [comment] 2022-08-24 07:08
Duplicate of #7666

**Closed by nijel** 2022-08-24 07:08 UTC
Labels: question, duplicate

**Comment by reloxx13** [comment] 2022-08-24 07:10
> Duplicate of #7666

yeah i just found it now
