### ISSUE TITLE
XLIFF exported files source tag doesn't contain the source HTML tags

### ISSUE THREAD

**Issue by lacroixdavid1** [WeblateOrg/weblate#5818] opened 2021-04-09 15:05 UTC
**Describe the issue**

When exporting in XLIFF, the source HTML tags are stripped out. This causes issues when exporting to an XLIFF file and then reimporting into Weblate. Weblate will skip because the source doesn't match.

**To Reproduce the issue**

Steps to reproduce the behaviour:

1. Create a translated key and add HTML in the content
2. Export it to XLIFF
3. The source content doesn't have HTML tags.
4. Change the target tag content 
5. Reimport the file
6. Weblate will say it didn't find the string.

```
Processed 1 string from the uploaded files (skipped: 0, not found: 1, updated: 0).
```

**Expected behaviour**

The exported source tag should contain the original HTML so it can be imported again or there should be an option to rely only on the translation ID for comparison when importing.

**Screenshots**

Exported language. See the translated tag has the HTML tags but the source does not.
```
<trans-unit xml:space="preserve" approved="yes" id="a_new_version_is_available_message" weblate-flags="angularjs-format, safe-html, strict-same">
   <source>A new version of our application was just released. Your browser will automatically refresh {{appWillReloadAtTime}} or click here to refresh now.</source>
   <target state="translated">A new version of our application was just released. Your browser will automatically refresh {{appWillReloadAtTime}} or <a ef-i18n-click="reloadApplication">click here to refresh now</a>.</target>
   <note from="developer">NetworkUI / AffiliateUI / AdvertiserUI</note>
</trans-unit>
```

**Comment by nijel** [comment] 2021-04-10 06:20
What Weblate version do you use? It might be a duplicate of #3762.

**Comment by lacroixdavid1** [comment] 2021-04-10 20:07
We're running Weblate 4.5.1. Thanks for your quick reply.

**Comment by lacroixdavid1** [comment] 2021-04-12 18:15
Any ideas?

**Closed** 2021-04-13 11:17 UTC
Labels: bug

**Comment by lacroixdavid1** [comment] 2021-04-13 12:29
Thank you @nijel.
