### ISSUE TITLE
Ignore empty source strings

### ISSUE THREAD

**Issue by fdosanjuan** [WeblateOrg/weblate#3163] opened 2019-10-31 16:36 UTC
**Is your feature request related to a problem? Please describe.**

If a component has some empty source strings (e.g., a line in a Java Properties file with only key and not value), they are displayed in Weblate as "not translated strings". The problem is that they will never be translated and remain forever as "not translated".

**Describe the solution you'd like**

I think it would be nice if those strings were not shown at all.

What do you think?

**Comment by nijel** [comment] 2019-10-31 18:31
Duplicate of #1920

**Closed by nijel** 2019-10-31 18:31 UTC
