### ISSUE TITLE
How to use HTML tags with XLIFF?

### ISSUE THREAD

**Issue by RafaelKr** [WeblateOrg/weblate#7224] opened 2022-02-08 15:51 UTC
### Describe the issue

I'm trying to use Weblate with XLIFF files for translation.
My translations include HTML, that's why source and target are wrapped in `CDATA`. Since some hours I try to get it working that the HTML tags are displayed as HTML tags and not escaped with their entities.

Example:
```xml
<source><![CDATA[<div><h1>Section 1</h1></div><div>Slot 1</div>]]></source>
```
is displayed as
```html
&lt;div&gt;&lt;h1&gt;Section 1&lt;/h1&gt;&lt;/div&gt;&lt;div&gt;Slot 1&lt;/div&gt;
```
instead I would like it to be displayed as
```html
<div><h1>Section 1</h1></div><div>Slot 1</div>
```

I tried many combinations of the `datatype` attributes on the `file` and `trans-unit` elements. I also set `weblate-flags="safe-html"` and `weblate-flags="ignore-safe-html"` on `trans-unit`.
I didn't find any combination which was working for me.

Here's the current version of my file:
```xliff
<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
  <file datatype="plaintext" original="en-GB.xlf" source-language="en-GB" target-language="de-DE">
    <body>
      <trans-unit id="90801210034e42a29adfcf506ae60ab4" resname="Test - Section 0 - Block 0" approved="yes" restype="string" datatype="html" weblate-flags="safe-html">
        <source><![CDATA[<div><h1>Section 1</h1></div><div>Slot 1</div>]]></source>
        <target><![CDATA[<div><h1>Sektion 1</h1></div><div>Slot 1</div>]]></target>
      </trans-unit>
    </body>
  </file>
</xliff>
```

I also read/searched a lot in the docs which didn't help me. Maybe it's just a little adjustment?

Would be very helpful for a quick tip if it's even possible. Maybe this even is a bug?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Expected behavior

```xml
<source><![CDATA[<div><h1>Section 1</h1></div><div>Slot 1</div>]]></source>
```
should be displayed as
```html
<div><h1>Section 1</h1></div><div>Slot 1</div>
```

### Screenshots

![image](https://user-images.githubusercontent.com/14234815/153023084-c2f5b109-0822-4728-a976-0f99283a4f8d.png)

with this file it was displayed a little bit better, but still with entities
```xliff
<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
  <file original="en-GB.xlf" source-language="en-GB" target-language="de-DE">
    <body>
      <trans-unit id="90801210034e42a29adfcf506ae60ab4" resname="Test - Section 0 - Block 0" approved="yes" datatype="html" weblate-flags="ignore-safe-html">
        <source><![CDATA[<div><h1>Section 1</h1></div><div>Slot 1</div>]]></source>
        <target><![CDATA[<div><h1>Sektion 1</h1></div><div>Slot 1</div>]]></target>
      </trans-unit>
    </body>
  </file>
</xliff>
```

![image](https://user-images.githubusercontent.com/14234815/153023467-b52dede5-cb93-463b-9c80-fa9012670228.png)

### How do you run Weblate?

Docker container

### Weblate versions

```
 * Weblate: 4.10.1
 * Django: 4.0
 * siphashc: 2.1
 * translate-toolkit: 3.5.1
 * lxml: 4.7.1
 * Pillow: 8.4.0
 * bleach: 4.1.0
 * python-dateutil: 2.8.2
 * social-auth-core: 4.1.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.13.0
 * oauthlib: 3.1.1
 * django-compressor: 3.1
 * djangorestframework: 3.13.1
 * django-filter: 21.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.4.0
 * setuptools: 60.0.4
 * jellyfish: 0.8.9
 * openpyxl: 3.0.9
 * celery: 5.2.1
 * kombu: 5.2.2
 * translation-finder: 2.10
 * weblate-language-data: 2021.7
 * html2text: 2020.1.16
 * pycairo: 1.20.1
 * pygobject: 3.42.0
 * diff-match-patch: 20200713
 * requests: 2.26.0
 * django-redis: 5.2.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.5.1
 * Cython: 0.29.26
 * misaka: 2.1.1
 * GitPython: 3.1.24
 * borgbackup: 1.1.17
 * pyparsing: 3.0.6
 * pyahocorasick: 1.4.2
 * python-redis-lock: 3.7.0
 * Python: 3.10.1
 * Git: 2.30.2
 * psycopg2: 2.9.2
 * psycopg2-binary: 2.9.2
 * phply: 1.2.5
 * chardet: 4.0.0
 * ruamel.yaml: 0.17.17
 * tesserocr: 2.5.2
 * akismet: 1.1
 * boto3: 1.20.26
 * zeep: 4.1.0
 * aeidon: 1.10.1
 * iniparse: 0.5
 * mysqlclient: 2.1.0
 * Mercurial: 6.0
 * git-svn: 2.30.2
 * git-review: 2.2.0
 * Redis server: 6.2.6
 * PostgreSQL server: 13.5
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mail1.vi-ops.net
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.13.0-28-generic (x86_64)
```

### Weblate deploy checks

```shell
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Cannot send e-mail (SMTP AUTH extension not supported by server.), please check EMAIL_* settings.
	HINT: https://docs.weblate.org/en/weblate-4.10.1/admin/install.html#out-mail

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.10.1/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.10.1/admin/backup.html

System check identified 7 issues (1 silenced).
```

**Comment by RafaelKr** [comment] 2022-02-19 09:46
unstale

**Comment by nijel** [comment] 2022-02-22 07:16
This works as intended, see also https://github.com/WeblateOrg/weblate/issues/3081

**Comment by RafaelKr** [comment] 2022-02-22 08:42
Thanks for your feedback. I'm interested why it's handled differently for XML files? When using PO files the HTML tags are shown correctly.

**Comment by nijel** [comment] 2022-03-02 10:31
The problem is that XLIFF can contain XML tags which should be shown to the translators. That's why it behaves this way. Maybe we could have another XLIFF format that would not expose raw XML.

Duplicate of #3081

**Closed by nijel** 2022-03-02 10:31 UTC
Labels: enhancement, duplicate

**Comment by RafaelKr** [comment] 2022-03-02 10:38
Thanks for clarifying. We found another tool for now.  
Unfortunately, because Weblate looks very promising!

**Comment by nijel** [comment] 2022-03-02 14:11
I'd still like to hear your input on https://github.com/WeblateOrg/weblate/issues/3081#issuecomment-1056972411. One of the solutions might be easy to implement...
