### ISSUE TITLE
TimeoutTooLarge

### ISSUE THREAD

**Issue by Badiboy** [WeblateOrg/weblate#5934] opened 2021-04-27 21:53 UTC
It seems that my carma is bad. No one update completes successfully... :(

After upgrading from 4.5.3 to 4.6 I got the error when I press "Save" button after edit translation text. The same when edit translation in Zen. (Other functions seems ok, including Suggestion acception).

Debug mode returned this:

**Timeout (120) cannot be greater than expire (5)**

> Request Method: POST
> -- | --
> https://address/translate/buttons/de/?q=state%3A%3E%3Dtranslated&offset=18
> 3.1.4
> TimeoutTooLarge
> Timeout (120) cannot be greater than expire (5)
> /drive/weblate-env/lib/python3.8/site-packages/redis_lock/__init__.py, line 233, in acquire
> /usr/bin/uwsgi-core
> 3.8.5
> ['/drive/weblate-env/lib/python3.8/site-packages/git/ext/gitdb',  '/drive',  '.',  '',  '/usr/lib/python38.zip',  '/usr/lib/python3.8',  '/usr/lib/python3.8/lib-dynload',  '/drive/weblate-env/lib/python3.8/site-packages',  '/drive/weblate-env/lib/python3.8/site-packages/gitdb/ext/smmap']
> Wed, 28 Apr 2021 00:20:07 +0300
> 

> Traceback Switch to copy-and-paste view
> /drive/weblate-env/lib/python3.8/site-packages/django/core/handlers/exception.py, line 47, in inner
>                 response = get_response(request) …
> ▶ Local vars
> /drive/weblate-env/lib/python3.8/site-packages/django/core/handlers/base.py, line 179, in _get_response
>                 response = wrapped_callback(request, *callback_args, **callback_kwargs) …
> ▶ Local vars
> /drive/weblate-env/lib/python3.8/site-packages/weblate/trans/views/edit.py, line 568, in translate
>             response = handle_translate(request, unit, this_unit_url, next_unit_url) …
> ▶ Local vars
> /drive/weblate-env/lib/python3.8/site-packages/weblate/utils/ratelimit.py, line 116, in rate_wrap
>             return function(request, *args, **kwargs) …
> ▶ Local vars
> /drive/weblate-env/lib/python3.8/site-packages/weblate/trans/views/edit.py, line 382, in handle_translate
>         go_next = perform_translation(unit, form, request) …
> ▶ Local vars
> /drive/weblate-env/lib/python3.8/site-packages/weblate/trans/views/edit.py, line 304, in perform_translation
>     saved = unit.translate( …
> ▶ Local vars
> /usr/lib/python3.8/contextlib.py, line 75, in inner
>                 return func(*args, **kwds) …
> ▶ Local vars
> /drive/weblate-env/lib/python3.8/site-packages/weblate/trans/models/unit.py, line 1212, in translate
>         saved = self.save_backend( …
> ▶ Local vars
> /drive/weblate-env/lib/python3.8/site-packages/weblate/trans/models/unit.py, line 854, in save_backend
>                 self.translation.commit_pending("pending unit", user, force=True) …
> ▶ Local vars
> /usr/lib/python3.8/contextlib.py, line 75, in inner
>                 return func(*args, **kwds) …
> ▶ Local vars
> /drive/weblate-env/lib/python3.8/site-packages/weblate/trans/models/translation.py, line 522, in commit_pending
>         with self.component.repository.lock: …
> ▶ Local vars
> /drive/weblate-env/lib/python3.8/site-packages/weblate/utils/lock.py, line 81, in __enter__
>                 if not self._lock.acquire(timeout=self._timeout): …
> ▶ Local vars
> /drive/weblate-env/lib/python3.8/site-packages/redis_lock/__init__.py, line 233, in acquire
>             raise TimeoutTooLarge("Timeout (%d) cannot be greater than expire (%d)" % (timeout, self._expire)) …
> ▶ Local vars
> Variable Value
> -- | --
> blocking | True
> self | <redis_lock.Lock object at 0x7f05873577f0>
> timeout | 120

PS: Ubuntu 20, python 3.8.

**Comment by nijel** [comment] 2021-04-28 04:09
Duplicate of #5918

**Closed** 2021-04-28 04:10 UTC
Labels: bug, duplicate
