### ISSUE TITLE
(Exact) string search don't find existing string

### ISSUE THREAD

**Issue by buhtz** [WeblateOrg/weblate#10793] opened 2024-01-16 08:36 UTC
### Describe the issue

Searching strings does not behave as expected. The string `Remote path exists but is not a directory.` exists as a source string. But using exact the same string (copy & paste) does not give a result.
Using just some parts of the search strings comes to a result.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Open https://translate.codeberg.org/projects/backintime/common/da/#search
2. Search for `Remote path exists but is not a directory.`
3. Result: "No strings found!"
4. Try it again and search for `Remote path exists but is not`.
5. Result: String found.

### Expected behavior

Find the strings I am looking for.

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/11861496/8dca5afb-96a3-4376-b7e8-e2be443b74b2)

![image](https://github.com/WeblateOrg/weblate/assets/11861496/47fc4574-ff85-4c44-8afe-a4e9d0ac7143)

### How do you run Weblate?

Other

### Weblate versions

It is Weblate 5.3.1 running at translate.codeberg.org

**Comment by nijel** [comment] 2024-01-16 08:41
Search supports boolean expressions, so if you are searching for a string, it is always better to quote it, see https://docs.weblate.org/en/latest/user/search.html.

Your search is looking for all strings containing `Remote` `path` `exists` `but` `is` `directory.` and not containing `a`.

**Comment by nijel** [comment] 2024-01-16 09:40
Duplicate of #9728

**Closed by nijel** 2024-01-16 09:40 UTC
Labels: duplicate
