### ISSUE TITLE
using weblate to translate .MD files

### ISSUE THREAD

**Issue by Svetlana-T** [WeblateOrg/weblate#6096] opened 2021-05-27 07:56 UTC
**Describe the issue** I have .MD (markdown) files that need translation. This is not clear to me how to deploy weblate for this and in what format it will output translations. I tried searching the official documentation without success.

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [ ] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

2. Scroll down to '...'
3. Click on '...'

**Expected behavior**

**Screenshots**

**Exception traceback**

**Server configuration and status**

Weblate installation: weblate.org service / Docker / PyPI / other

**Weblate deploy checks**

**Additional context**

**Comment by Svetlana-T** [comment] 2021-05-27 08:05
yes, bot, i know, thanks

**Comment by nijel** [comment] 2021-05-28 04:37
Duplicate of #3106

**Closed by nijel** 2021-05-28 04:37 UTC
Labels: question, duplicate
