### ISSUE TITLE
How to Obtain Translation Credits from API

### ISSUE THREAD

**Issue by PeterNjeim** [WeblateOrg/weblate#8140] opened 2022-09-21 17:34 UTC
Can't find any way to obtain the translation credits from the REST API documentation. Workaround is to use a curl request with a sessionid cookie. I don't know if that id lasts forever so I'd rather have an API option instead.

Weblate version: `4.14.1` `Docker container`

**Comment by nijel** [comment] 2022-09-22 08:10
Duplicate of #5459

**Closed by nijel** 2022-09-22 08:10 UTC
Labels: question, duplicate
