### ISSUE TITLE
Weblate and `lupdate` disagree about Turkish plurals

### ISSUE THREAD

**Issue by rubdos** [WeblateOrg/weblate#7427] opened 2022-03-26 18:51 UTC
### Describe the issue

Weblate seems to have a singular and plural form for `%n`-style translations, while `lupdate` wants to remove these:

```
$ lupdate qml/ -noobsolete -ts translations/*.ts
Removed plural forms as the target language has less forms.
If this sounds wrong, possibly the target language is not set or recognized.
```

Example on Weblate:

https://hosted.weblate.org/translate/whisperfish/whisperfish-application/tr/?offset=1&q=whisperfish-message-action-resend&sort_by=-priority%2Cposition&checksum=

I don't know Turkish, so I am definitely not qualified to decide on this. Since I regularly run `lupdate` on the translations to update the line numbers and context, and insert new trId's (in fact, I run it in CI), it would be great if Weblate and lupdate agreed on this.

Finally, I would like to note that all plural forms that I got from my Turkish translator were the same as the singular, except for one:

<details>
<summary>Plural translations deleted by `lupdate` that have the same text as their singulars</summary>
```diff
diff --git a/translations/harbour-whisperfish-tr.ts b/translations/harbour-whisperfish-tr.ts
index 95763d9..5ae2998 100644
--- a/translations/harbour-whisperfish-tr.ts
+++ b/translations/harbour-whisperfish-tr.ts
@@ -286,7 +286,6 @@
         <extracomment>Remorse: *locally* deleted one or multiple message (past tense)</extracomment>
         <translation>
             <numerusform>Yerel olarak silinen %n mesaj</numerusform>
-            <numerusform>Yerel olarak silinen %n mesaj</numerusform>
         </translation>
     </message>
     <message id="whisperfish-react-message-menu">
@@ -1121,7 +1120,6 @@ Settings page share contacts</extracomment>
         <extracomment>Number of attachments currently selected for sending</extracomment>
         <translation>
             <numerusform>%n ek</numerusform>
-            <numerusform>%n ek</numerusform>
         </translation>
     </message>
     <message id="whisperfish-chat-input-placeholder-personal">
@@ -1148,7 +1146,6 @@ Settings page share contacts</extracomment>
         <extracomment>Label hinting at more attachments than are currently shown. Read as &quot;and %n more&quot;.</extracomment>
         <translation>
             <numerusform>+%n</numerusform>
-            <numerusform>+%n</numerusform>
         </translation>
     </message>
     <message id="whisperfish-attachments-loader-show-more" numerus="yes">
@@ -1158,7 +1155,6 @@ Settings page share contacts</extracomment>
         <extracomment>Note if some message attachments are hidden instead of being shown inline</extracomment>
         <translation>
             <numerusform>ve %n tane daha</numerusform>
-            <numerusform>ve %n tane daha</numerusform>
         </translation>
     </message>
     <message id="whisperfish-message-no-timestamp">
@@ -1342,7 +1338,6 @@ Settings page share contacts</extracomment>
         <extracomment>Info label shown while selecting messages</extracomment>
         <translation>
             <numerusform>%n mesaj seçildi</numerusform>
-            <numerusform>%n mesaj seçildi</numerusform>
         </translation>
     </message>
     <message id="whisperfish-message-action-clear-selection" numerus="yes">
@@ -1351,7 +1346,6 @@ Settings page share contacts</extracomment>
         <extracomment>Message action description, shown if one or more messages are selected</extracomment>
         <translation>
             <numerusform>Seçimi temizle</numerusform>
-            <numerusform>Seçimi temizle</numerusform>
         </translation>
     </message>
     <message id="whisperfish-message-action-copy" numerus="yes">
@@ -1361,7 +1355,6 @@ Settings page share contacts</extracomment>
         <extracomment>Message action description</extracomment>
         <translation>
             <numerusform>%n mesajı kopyala</numerusform>
-            <numerusform>%n mesajı kopyala</numerusform>
         </translation>
     </message>
     <message id="whisperfish-message-action-info">
@@ -1377,7 +1370,6 @@ Settings page share contacts</extracomment>
         <extracomment>Message action description</extracomment>
         <translation>
             <numerusform>Yerel olarak %n mesajı sil</numerusform>
-            <numerusform>Yerel olarak %n mesajı sil</numerusform>
         </translation>
     </message>
     <message id="whisperfish-message-action-delete-for-all" numerus="yes">
@@ -1387,7 +1379,6 @@ Settings page share contacts</extracomment>
         <extracomment>Message action description</extracomment>
         <translation>
             <numerusform>Tümü için %n mesajı sil</numerusform>
-            <numerusform>Tümü için %n mesajı sil</numerusform>
         </translation>
     </message>
     <message id="whisperfish-message-action-resend" numerus="yes">
@@ -1396,7 +1387,6 @@ Settings page share contacts</extracomment>
         <extracomment>Message action description</extracomment>
         <translation>
             <numerusform>Başarısız mesajı yeniden göndermeyi dene</numerusform>
-            <numerusform>Başarısız mesajları yeniden göndermeyi dene</numerusform>
         </translation>
     </message>
     <message id="whisperfish-share-page-title">
```
</details>

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Have a project with a `%n`-style numerusform.
2. Translate the plural form in Weblate Turkish
3. Sync with git
4. Run `lupdate`, e.g. `lupdate qml/ -noobsolete -ts translations/*.ts` and see the diff

### Expected behavior

Either Weblate should not provide a plural, or this is a `lupdate` bug and `lupdate` should not delete the plural form.

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment] 2022-03-28 07:36
Duplicate of https://github.com/translate/translate/issues/786

**Closed by nijel** 2022-03-28 07:36 UTC
Labels: bug, translate-toolkit, duplicate
