### ISSUE TITLE
Support for Angular i18n inline elements for interpolation ?

### ISSUE THREAD

**Issue by PowerKiKi** [WeblateOrg/weblate#2346] opened 2018-10-24 05:38 UTC
**Describe the bug**

On an Angular project, the [official i18n tooling](https://angular.io/guide/i18n) would extract strings containing interpolation as inline elements in XLIFF 1.2. It seems that those inline elements are lost in Weblate.

I am unsure if this is a bug, a missing feature or a lack of knowledge on my side, but this does not match my expectation. And I would need advice on what to do ?

**To Reproduce**

My XLIFF 1.2 translation looks like the following, note the `<x>` element used for interpolation by Angular:

```xml
<trans-unit id="a164c79524f91b49f25e64696e2388c674958237">
  <source xml:space="preserve">Upload de <x id="INTERPOLATION" equiv-text="{{ data.files.length }}"/> fichiers</source>
  <target xml:space="preserve">Upload de <x id="INTERPOLATION" equiv-text="{{ data.files.length }}"/> fichiers</target>
  <context-group purpose="location">
    <context context-type="sourcefile">../app/admin/group-documents/upload/upload-group-documents.component.ts</context>
    <context context-type="linenumber">1</context>
  </context-group>
</trans-unit>
```

But when viewed in Weblate, the interpolation is not really visible, instead there is what seems to be a scpecial display for whitespace:

![image](https://user-images.githubusercontent.com/72603/47408085-9b50aa80-d7a9-11e8-8dc4-81b8a5b31abd.png)

**Expected behavior**

I would expect a similar behavior as seen in PHP string formatting, where a "special block" is clearly visible in the source and easily insertable in the translation. Something like that:

![image](https://user-images.githubusercontent.com/72603/47408328-a2c48380-d7aa-11e8-9c3e-c6bce046ba6d.png)

**Server configuration and status**

```sh
# ./manage.py list_versions
 * Weblate weblate-3.1.1
 * Python 2.7.15rc1
 * Django 1.11.16
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.17.1
 * Pillow 5.1.0
 * python-dateutil 2.7.3
 * lxml 4.2.5
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.5
 * pyuca 1.2
 * Database backends: django.db.backends.mysql
 * Cache backends: default:FileBasedCache, avatar:FileBasedCache
 * Platform: Linux 4.15.0-36-generic (x86_64)
```
 
 
```sh
# ./manage.py check --deploy
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.

System check identified 1 issue (0 silenced).
```

**Comment by nijel** [comment] 2018-10-24 14:33
Duplicate of #1535 

Indeed the xliff placeholders are currently not supported.

**Closed by nijel** 2018-10-24 14:33 UTC
