### ISSUE TITLE
Weblate not outputing Android <plurals> fields properly, causing app crashes 

### ISSUE THREAD

**Issue by eighthave** [WeblateOrg/weblate#1550] opened 2017-07-07 19:39 UTC
With Hebrew, the user interface shows One and Other as the options:
* https://hosted.weblate.org/translate/f-droid/f-droid/he/?checksum=&offset=0&q=details_last_update_weeks&search=substring&context=on&type=all&ignored=

But the _strings.xml_ then has One and Two filled out, then Many and Other blank:
```xml
<plurals name="details_last_update_weeks">
	<item quantity="one">עודכן לפני שבוע</item>
	<item quantity="two">עודכן לפני %1$d שבועות</item>
	<item quantity="many"></item>
	<item quantity="other"></item>
</plurals>
```

An empty Other string can cause crashes.  Especially because we remove blank strings, since they cause other problems.  Weblate should ensure that if any item of `<plurals>` has been translated, then `<item quantity="other">` must be translated.  Here's the Android source reference on the requirement for other:
https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/content/res/ResourcesImpl.java#268

### Server configuration

https://hosted.weblate.org/translate/f-droid/f-droid

**Comment by eighthave** [comment] 2017-07-07 19:52
<div class="issue">
<div class="id"><a href="#" title="Return to top">MissingQuantity: Missing quantity translation</a><div class="issueSeparator"></div>
</div>
<div class="warningslist">
<span class="location"><a href="../../src/main/res/values-he/strings.xml">../../src/main/res/values-he/strings.xml</a>:355</span>: <span class="message">For locale "he" (Hebrew) the following quantities should also be defined: <code>many</code>, <code>two</code></span><br /><pre class="errorlines">
<span class="lineno"> 352</span>     &lt;string name="updates__hide_updateable_apps">&#1492;&#1505;&#1514;&#1512;&#1514; &#1497;&#1497;&#1513;&#1493;&#1502;&#1493;&#1504;&#1497;&#1501;&lt;/string>
<span class="lineno"> 353</span>     &lt;string name="updates__show_updateable_apps">&#1492;&#1510;&#1490;&#1514; &#1497;&#1497;&#1513;&#1493;&#1502;&#1493;&#1504;&#1497;&#1501;&lt;/string>
<span class="lineno"> 354</span> 
<span class="lineno"> 355</span>     <span class="errorspan">&lt;plurals name="updates__download_updates_for_apps"></span>
<span class="lineno"> 356</span> 	&lt;item quantity="one">&#1492;&#1493;&#1512;&#1491;&#1514; &#1506;&#1491;&#1499;&#1493;&#1503; &#1500;&#1497;&#1497;&#1513;&#1493;&#1502;&#1493;&#1503; &#1488;&#1495;&#1491;.&lt;/item>
<span class="lineno"> 357</span> 	&lt;item quantity="other">&#1492;&#1493;&#1512;&#1491;&#1514; &#1506;&#1491;&#1499;&#1493;&#1503; &#1500;&#1470;%1$d &#1497;&#1497;&#1513;&#1493;&#1502;&#1493;&#1504;&#1497;&#1501;.&lt;/item>
</pre>
<span class="location"><a href="../../src/main/res/values-iw/strings.xml">../../src/main/res/values-iw/strings.xml</a>:355</span>: <span class="message">For locale "iw" (Hebrew) the following quantities should also be defined: <code>many</code>, <code>two</code></span><br /><pre class="errorlines">
<span class="lineno"> 352</span>     &lt;string name="updates__hide_updateable_apps">&#1492;&#1505;&#1514;&#1512;&#1514; &#1497;&#1497;&#1513;&#1493;&#1502;&#1493;&#1504;&#1497;&#1501;&lt;/string>
<span class="lineno"> 353</span>     &lt;string name="updates__show_updateable_apps">&#1492;&#1510;&#1490;&#1514; &#1497;&#1497;&#1513;&#1493;&#1502;&#1493;&#1504;&#1497;&#1501;&lt;/string>
<span class="lineno"> 354</span> 
<span class="lineno"> 355</span>     <span class="errorspan">&lt;plurals name="updates__download_updates_for_apps"></span>
<span class="lineno"> 356</span> 	&lt;item quantity="one">&#1492;&#1493;&#1512;&#1491;&#1514; &#1506;&#1491;&#1499;&#1493;&#1503; &#1500;&#1497;&#1497;&#1513;&#1493;&#1502;&#1493;&#1503; &#1488;&#1495;&#1491;.&lt;/item>
<span class="lineno"> 357</span> 	&lt;item quantity="other">&#1492;&#1493;&#1512;&#1491;&#1514; &#1506;&#1491;&#1499;&#1493;&#1503; &#1500;&#1470;%1$d &#1497;&#1497;&#1513;&#1493;&#1502;&#1493;&#1504;&#1497;&#1501;.&lt;/item>
</pre>
<span class="location"><a href="../../src/main/res/values-he/strings.xml">../../src/main/res/values-he/strings.xml</a>:437</span>: <span class="message">For locale "he" (Hebrew) the following quantities should also be defined: <code>many</code>, <code>two</code></span><br /><pre class="errorlines">
<span class="lineno"> 434</span>     &lt;string name="notification_content_single_downloading_update">&#1502;&#1514;&#1489;&#1510;&#1506;&#1514; &#1492;&#1493;&#1512;&#1491;&#1514; &#1506;&#1491;&#1499;&#1493;&#1503; &#1506;&#1489;&#1493;&#1512; &#8222;%1$s&#8220;&#8230;&lt;/string>
<span class="lineno"> 435</span>     &lt;string name="notification_content_single_installing">&#1492;&#1492;&#1514;&#1511;&#1504;&#1492; &#1513;&#1500; &#8222;%1$s&#8220; &#1502;&#1514;&#1489;&#1510;&#1506;&#1514; &#1499;&#1506;&#1514;&#8230;&lt;/string>
<span class="lineno"> 436</span>     &lt;string name="notification_content_single_installed">&#1492;&#1492;&#1514;&#1511;&#1504;&#1492; &#1492;&#1510;&#1500;&#1497;&#1495;&#1492;&lt;/string>
<span class="lineno"> 437</span>     <span class="errorspan">&lt;plurals name="notification_summary_updates"></span>
<span class="lineno"> 438</span> 	&lt;item quantity="one">&#1506;&#1491;&#1499;&#1493;&#1503; &#1488;&#1495;&#1491;&lt;/item>
<span class="lineno"> 439</span> 	&lt;item quantity="other">%1$d &#1506;&#1491;&#1499;&#1493;&#1504;&#1497;&#1501;&lt;/item>
</pre>
<span class="location"><a href="../../src/main/res/values-iw/strings.xml">../../src/main/res/values-iw/strings.xml</a>:437</span>: <span class="message">For locale "iw" (Hebrew) the following quantities should also be defined: <code>many</code>, <code>two</code></span><br /><pre class="errorlines">
<span class="lineno"> 434</span>     &lt;string name="notification_content_single_downloading_update">&#1502;&#1514;&#1489;&#1510;&#1506;&#1514; &#1492;&#1493;&#1512;&#1491;&#1514; &#1506;&#1491;&#1499;&#1493;&#1503; &#1506;&#1489;&#1493;&#1512; &#8222;%1$s&#8220;&#8230;&lt;/string>
<span class="lineno"> 435</span>     &lt;string name="notification_content_single_installing">&#1492;&#1492;&#1514;&#1511;&#1504;&#1492; &#1513;&#1500; &#8222;%1$s&#8220; &#1502;&#1514;&#1489;&#1510;&#1506;&#1514; &#1499;&#1506;&#1514;&#8230;&lt;/string>
<span class="lineno"> 436</span>     &lt;string name="notification_content_single_installed">&#1492;&#1492;&#1514;&#1511;&#1504;&#1492; &#1492;&#1510;&#1500;&#1497;&#1495;&#1492;&lt;/string>
<span class="lineno"> 437</span>     <span class="errorspan">&lt;plurals name="notification_summary_updates"></span>
<span class="lineno"> 438</span> 	&lt;item quantity="one">&#1506;&#1491;&#1499;&#1493;&#1503; &#1488;&#1495;&#1491;&lt;/item>
<span class="lineno"> 439</span> 	&lt;item quantity="other">%1$d &#1506;&#1491;&#1499;&#1493;&#1504;&#1497;&#1501;&lt;/item>
</pre>
<span class="location"><a href="../../src/main/res/values-he/strings.xml">../../src/main/res/values-he/strings.xml</a>:441</span>: <span class="message">For locale "he" (Hebrew) the following quantities should also be defined: <code>many</code>, <code>two</code></span><br /><pre class="errorlines">
<span class="lineno"> 438</span> 	&lt;item quantity="one">&#1506;&#1491;&#1499;&#1493;&#1503; &#1488;&#1495;&#1491;&lt;/item>
<span class="lineno"> 439</span> 	&lt;item quantity="other">%1$d &#1506;&#1491;&#1499;&#1493;&#1504;&#1497;&#1501;&lt;/item>
<span class="lineno"> 440</span> &lt;/plurals>
<span class="lineno"> 441</span>     <span class="errorspan">&lt;plurals name="notification_summary_installed"></span>
<span class="lineno"> 442</span> 	&lt;item quantity="one">&#1497;&#1497;&#1513;&#1493;&#1502;&#1493;&#1503; &#1492;&#1493;&#1514;&#1511;&#1503;&lt;/item>
<span class="lineno"> 443</span> 	&lt;item quantity="other">%1$d &#1497;&#1497;&#1513;&#1493;&#1502;&#1493;&#1504;&#1497;&#1501; &#1492;&#1493;&#1514;&#1511;&#1504;&#1493;&lt;/item>
</pre>
<button id="MissingQuantityDivLink" onclick="reveal('MissingQuantityDiv');" />+ 11 More Occurrences...</button>
<div id="MissingQuantityDiv" style="display: none">
<span class="location"><a href="../../src/main/res/values-iw/strings.xml">../../src/main/res/values-iw/strings.xml</a>:441</span>: <span class="message">For locale "iw" (Hebrew) the following quantities should also be defined: <code>many</code>, <code>two</code></span><br /><pre class="errorlines">
<span class="lineno"> 438</span> 	&lt;item quantity="one">&#1506;&#1491;&#1499;&#1493;&#1503; &#1488;&#1495;&#1491;&lt;/item>
<span class="lineno"> 439</span> 	&lt;item quantity="other">%1$d &#1506;&#1491;&#1499;&#1493;&#1504;&#1497;&#1501;&lt;/item>
<span class="lineno"> 440</span> &lt;/plurals>
<span class="lineno"> 441</span>     <span class="errorspan">&lt;plurals name="notification_summary_installed"></span>
<span class="lineno"> 442</span> 	&lt;item quantity="one">&#1497;&#1497;&#1513;&#1493;&#1502;&#1493;&#1503; &#1492;&#1493;&#1514;&#1511;&#1503;&lt;/item>
<span class="lineno"> 443</span> 	&lt;item quantity="other">%1$d &#1497;&#1497;&#1513;&#1493;&#1502;&#1493;&#1504;&#1497;&#1501; &#1492;&#1493;&#1514;&#1511;&#1504;&#1493;&lt;/item>
</pre>
<span class="location"><a href="../../src/main/res/values-he/strings.xml">../../src/main/res/values-he/strings.xml</a>:454</span>: <span class="message">For locale "he" (Hebrew) the following quantities should also be defined: <code>many</code>, <code>two</code></span><br /><pre class="errorlines">
<span class="lineno"> 451</span>     &lt;string name="notification_title_summary_installed">&#1492;&#1493;&#1514;&#1511;&#1503; &#1489;&#1492;&#1510;&#1500;&#1495;&#1492;&lt;/string>
<span class="lineno"> 452</span>     &lt;string name="tts_category_name">&#1511;&#1496;&#1490;&#1493;&#1512;&#1497;&#1492; %1$s&lt;/string>
<span class="lineno"> 453</span> 
<span class="lineno"> 454</span>     <span class="errorspan">&lt;plurals name="tts_view_all_in_category"></span>
<span class="lineno"> 455</span> 	&lt;item quantity="one">&#1492;&#1510;&#1490;&#1514; &#1497;&#1497;&#1513;&#1493;&#1502;&#1493;&#1503; %1$d &#1489;&#1511;&#1496;&#1490;&#1493;&#1512;&#1497;&#1492; %2$s&lt;/item>
<span class="lineno"> 456</span> 	&lt;item quantity="other">&#1492;&#1510;&#1490;&#1514; &#1499;&#1500; %1$d &#1492;&#1497;&#1497;&#1513;&#1493;&#1502;&#1493;&#1504;&#1497;&#1501; &#1489;&#1511;&#1496;&#1490;&#1493;&#1512;&#1497;&#1492; %2$s&lt;/item>
</pre>
<span class="location"><a href="../../src/main/res/values-iw/strings.xml">../../src/main/res/values-iw/strings.xml</a>:454</span>: <span class="message">For locale "iw" (Hebrew) the following quantities should also be defined: <code>many</code>, <code>two</code></span><br /><pre class="errorlines">
<span class="lineno"> 451</span>     &lt;string name="notification_title_summary_installed">&#1492;&#1493;&#1514;&#1511;&#1503; &#1489;&#1492;&#1510;&#1500;&#1495;&#1492;&lt;/string>
<span class="lineno"> 452</span>     &lt;string name="tts_category_name">&#1511;&#1496;&#1490;&#1493;&#1512;&#1497;&#1492; %1$s&lt;/string>
<span class="lineno"> 453</span> 
<span class="lineno"> 454</span>     <span class="errorspan">&lt;plurals name="tts_view_all_in_category"></span>
<span class="lineno"> 455</span> 	&lt;item quantity="one">&#1492;&#1510;&#1490;&#1514; &#1497;&#1497;&#1513;&#1493;&#1502;&#1493;&#1503; %1$d &#1489;&#1511;&#1496;&#1490;&#1493;&#1512;&#1497;&#1492; %2$s&lt;/item>
<span class="lineno"> 456</span> 	&lt;item quantity="other">&#1492;&#1510;&#1490;&#1514; &#1499;&#1500; %1$d &#1492;&#1497;&#1497;&#1513;&#1493;&#1502;&#1493;&#1504;&#1497;&#1501; &#1489;&#1511;&#1496;&#1490;&#1493;&#1512;&#1497;&#1492; %2$s&lt;/item>
</pre>
<span class="location"><a href="../../src/main/res/values-he/strings.xml">../../src/main/res/values-he/strings.xml</a>:460</span>: <span class="message">For locale "he" (Hebrew) the following quantities should also be defined: <code>many</code>, <code>two</code></span><br /><pre class="errorlines">
<span class="lineno"> 457</span> &lt;/plurals>
<span class="lineno"> 458</span> 
<span class="lineno"> 459</span>     &lt;string name="details_last_updated_today">&#1506;&#1493;&#1491;&#1499;&#1503; &#1492;&#1497;&#1493;&#1501;&lt;/string>
<span class="lineno"> 460</span>     <span class="errorspan">&lt;plurals name="details_last_update_days"></span>
<span class="lineno"> 461</span> 	&lt;item quantity="one">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; &#1497;&#1493;&#1501;&lt;/item>
<span class="lineno"> 462</span> 	&lt;item quantity="other">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; %1$d &#1497;&#1502;&#1497;&#1501;&lt;/item>
</pre>
<span class="location"><a href="../../src/main/res/values-iw/strings.xml">../../src/main/res/values-iw/strings.xml</a>:460</span>: <span class="message">For locale "iw" (Hebrew) the following quantities should also be defined: <code>many</code>, <code>two</code></span><br /><pre class="errorlines">
<span class="lineno"> 457</span> &lt;/plurals>
<span class="lineno"> 458</span> 
<span class="lineno"> 459</span>     &lt;string name="details_last_updated_today">&#1506;&#1493;&#1491;&#1499;&#1503; &#1492;&#1497;&#1493;&#1501;&lt;/string>
<span class="lineno"> 460</span>     <span class="errorspan">&lt;plurals name="details_last_update_days"></span>
<span class="lineno"> 461</span> 	&lt;item quantity="one">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; &#1497;&#1493;&#1501;&lt;/item>
<span class="lineno"> 462</span> 	&lt;item quantity="other">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; %1$d &#1497;&#1502;&#1497;&#1501;&lt;/item>
</pre>
<span class="location"><a href="../../src/main/res/values-he/strings.xml">../../src/main/res/values-he/strings.xml</a>:464</span>: <span class="message">For locale "he" (Hebrew) the following quantities should also be defined: <code>many</code>, <code>two</code></span><br /><pre class="errorlines">
<span class="lineno"> 461</span> 	&lt;item quantity="one">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; &#1497;&#1493;&#1501;&lt;/item>
<span class="lineno"> 462</span> 	&lt;item quantity="other">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; %1$d &#1497;&#1502;&#1497;&#1501;&lt;/item>
<span class="lineno"> 463</span> &lt;/plurals>
<span class="lineno"> 464</span>     <span class="errorspan">&lt;plurals name="details_last_update_weeks"></span>
<span class="lineno"> 465</span> 	&lt;item quantity="one">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; &#1513;&#1489;&#1493;&#1506;&lt;/item>
<span class="lineno"> 466</span> 	&lt;item quantity="other">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; %1$d &#1513;&#1489;&#1493;&#1506;&#1493;&#1514;&lt;/item>
</pre>
<span class="location"><a href="../../src/main/res/values-iw/strings.xml">../../src/main/res/values-iw/strings.xml</a>:464</span>: <span class="message">For locale "iw" (Hebrew) the following quantities should also be defined: <code>many</code>, <code>two</code></span><br /><pre class="errorlines">
<span class="lineno"> 461</span> 	&lt;item quantity="one">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; &#1497;&#1493;&#1501;&lt;/item>
<span class="lineno"> 462</span> 	&lt;item quantity="other">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; %1$d &#1497;&#1502;&#1497;&#1501;&lt;/item>
<span class="lineno"> 463</span> &lt;/plurals>
<span class="lineno"> 464</span>     <span class="errorspan">&lt;plurals name="details_last_update_weeks"></span>
<span class="lineno"> 465</span> 	&lt;item quantity="one">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; &#1513;&#1489;&#1493;&#1506;&lt;/item>
<span class="lineno"> 466</span> 	&lt;item quantity="other">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; %1$d &#1513;&#1489;&#1493;&#1506;&#1493;&#1514;&lt;/item>
</pre>
<span class="location"><a href="../../src/main/res/values-he/strings.xml">../../src/main/res/values-he/strings.xml</a>:468</span>: <span class="message">For locale "he" (Hebrew) the following quantities should also be defined: <code>many</code>, <code>two</code></span><br /><pre class="errorlines">
<span class="lineno"> 465</span> 	&lt;item quantity="one">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; &#1513;&#1489;&#1493;&#1506;&lt;/item>
<span class="lineno"> 466</span> 	&lt;item quantity="other">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; %1$d &#1513;&#1489;&#1493;&#1506;&#1493;&#1514;&lt;/item>
<span class="lineno"> 467</span> &lt;/plurals>
<span class="lineno"> 468</span>     <span class="errorspan">&lt;plurals name="details_last_update_months"></span>
<span class="lineno"> 469</span> 	&lt;item quantity="one">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; &#1495;&#1493;&#1491;&#1513;&lt;/item>
<span class="lineno"> 470</span> 	&lt;item quantity="other">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; %1$d &#1495;&#1493;&#1491;&#1513;&#1497;&#1501;&lt;/item>
</pre>
<span class="location"><a href="../../src/main/res/values-iw/strings.xml">../../src/main/res/values-iw/strings.xml</a>:468</span>: <span class="message">For locale "iw" (Hebrew) the following quantities should also be defined: <code>many</code>, <code>two</code></span><br /><pre class="errorlines">
<span class="lineno"> 465</span> 	&lt;item quantity="one">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; &#1513;&#1489;&#1493;&#1506;&lt;/item>
<span class="lineno"> 466</span> 	&lt;item quantity="other">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; %1$d &#1513;&#1489;&#1493;&#1506;&#1493;&#1514;&lt;/item>
<span class="lineno"> 467</span> &lt;/plurals>
<span class="lineno"> 468</span>     <span class="errorspan">&lt;plurals name="details_last_update_months"></span>
<span class="lineno"> 469</span> 	&lt;item quantity="one">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; &#1495;&#1493;&#1491;&#1513;&lt;/item>
<span class="lineno"> 470</span> 	&lt;item quantity="other">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; %1$d &#1495;&#1493;&#1491;&#1513;&#1497;&#1501;&lt;/item>
</pre>
<span class="location"><a href="../../src/main/res/values-he/strings.xml">../../src/main/res/values-he/strings.xml</a>:472</span>: <span class="message">For locale "he" (Hebrew) the following quantities should also be defined: <code>many</code>, <code>two</code></span><br /><pre class="errorlines">
<span class="lineno"> 469</span> 	&lt;item quantity="one">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; &#1495;&#1493;&#1491;&#1513;&lt;/item>
<span class="lineno"> 470</span> 	&lt;item quantity="other">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; %1$d &#1495;&#1493;&#1491;&#1513;&#1497;&#1501;&lt;/item>
<span class="lineno"> 471</span> &lt;/plurals>
<span class="lineno"> 472</span>     <span class="errorspan">&lt;plurals name="details_last_update_years"></span>
<span class="lineno"> 473</span> 	&lt;item quantity="one">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; &#1513;&#1504;&#1492;&lt;/item>
<span class="lineno"> 474</span> 	&lt;item quantity="other">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; %1$d &#1513;&#1504;&#1497;&#1501;&lt;/item>
</pre>
<span class="location"><a href="../../src/main/res/values-iw/strings.xml">../../src/main/res/values-iw/strings.xml</a>:472</span>: <span class="message">For locale "iw" (Hebrew) the following quantities should also be defined: <code>many</code>, <code>two</code></span><br /><pre class="errorlines">
<span class="lineno"> 469</span> 	&lt;item quantity="one">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; &#1495;&#1493;&#1491;&#1513;&lt;/item>
<span class="lineno"> 470</span> 	&lt;item quantity="other">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; %1$d &#1495;&#1493;&#1491;&#1513;&#1497;&#1501;&lt;/item>
<span class="lineno"> 471</span> &lt;/plurals>
<span class="lineno"> 472</span>     <span class="errorspan">&lt;plurals name="details_last_update_years"></span>
<span class="lineno"> 473</span> 	&lt;item quantity="one">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; &#1513;&#1504;&#1492;&lt;/item>
<span class="lineno"> 474</span> 	&lt;item quantity="other">&#1506;&#1493;&#1491;&#1499;&#1503; &#1500;&#1508;&#1504;&#1497; %1$d &#1513;&#1504;&#1497;&#1501;&lt;/item>
</pre>
</div>
</div>
<div class="metadata">Priority: 8 / 10<br/>
Category: Correctness:Messages</div>
Severity: <span class="error">Error</span><div class="summary">
Explanation: Missing quantity translation.</div>
<div class="explanation">
Different languages have different rules for grammatical agreement with quantity. In English, for example, the quantity 1 is a special case. We write "1 book", but for any other quantity we'd write "n books". This distinction between singular and plural is very common, but other languages make finer distinctions.<br/>
<br/>
This lint check looks at each translation of a <code>&lt;plural></code> and makes sure that all the quantity strings considered by the given language are provided by this translation.<br/>
<br/>
For example, an English translation must provide a string for <code>quantity="one"</code>. Similarly, a Czech translation must provide a string for <code>quantity="few"</code>.
</div>
<br/><div class="moreinfo">More info: <a href="http://developer.android.com/guide/topics/resources/string-resource.html#Plurals">http://developer.android.com/guide/topics/resources/string-resource.html#Plurals</a>
</div><br/>To suppress this error, use the issue id "MissingQuantity" as explained in the <a href="#SuppressInfo">Suppressing Warnings and Errors</a> section.<br/>
</div>

**Comment by nijel** [comment] 2017-07-09 17:42
Apparently Gettext is not following CLDR plurals here and it causes problems in this case. Weblate is based on Gettext ones, where there are just two plural forms (`n != 1`), while CLDR (and Android) [use four](http://www.unicode.org/cldr/charts/29/supplemental/language_plural_rules.html#he) (one, two, many, other). This will be tricky to address...

**Comment by eighthave** [comment] 2017-07-09 19:58
As a temporary workaround, maybe you could just stick the Other value into Two and Many?

**Comment by eighthave** [comment] 2017-07-09 20:10
It seems that some languages are including more than One/Other.  For example, Russian has One, Few, and Many, but is missing Other:
```xml
     <plurals name="details_last_update_days">
	<item quantity="one">Обновлено %1$d день назад</item>
	<item quantity="few">Обновлено %1$d дня назад</item>
	<item quantity="many">Обновлено %1$d дней назад</item>
</plurals>
```

And Slovak includes One, Few, Many, and Other, but Many is apparently not supposed to be there:
```xml
<plurals name="updates__download_updates_for_apps">
	<item quantity="one">Stiahnuť aktualizáciu pre %1$d aplikáciu.</item>
	<item quantity="few">Stiahnuť aktualizácie pre %1$d aplikácie.</item>
	<item quantity="many">Stiahnuť aktualizácie pre %1$d aplikácií.</item>
	<item quantity="other">Stiahnuť aktualizácie pre %1$d aplikácií.</item>
</plurals>
```

**Comment by eighthave** [comment] 2017-07-09 20:12
Serbian seems to correctly have One, Few, and Other:
```xml
<plurals name="details_last_update_days">
	<item quantity="one">Ажурирана пре %1$s дана</item>
	<item quantity="few">Ажурирана пре %1$s дана</item>
	<item quantity="other">Ажурирана пре %1$s дана</item>
</plurals>
```

**Comment by eighthave** [comment] 2017-07-09 20:13
Serbian seems to have the correct plurals (One, Few, Other):
```xml
<plurals name="tts_view_all_in_category">
	<item quantity="one">Прикажи %1$d апликацију у категорији %2$s</item>
	<item quantity="few">Прикажи све %1$d апликације у категорији %2$s</item>
	<item quantity="other">Прикажи свих %1$d апликација у категорији %2$s</item>
</plurals>
```

**Comment by nijel** [comment] 2017-07-13 11:27
This is problem only for languages where CLDR plurals do not match the ones commonly used by Gettext. I guess there won't be much of such languages...

**Comment by nijel** [comment] 2017-07-14 18:06
Thinking more about this we really have to add plural definitions per translation, which would be based on file format and fallback to language definition if nothing is defined for file format or within the file. This way we could also address different plural forms being used for one language (such as https://github.com/WeblateOrg/weblate/issues/901).

**Comment by nijel** [comment] 2017-07-14 18:28
Some formats will be easy to support properly:

* Use CLDR rules for Android (they can be probably extracted from Babel)
* Use ``Plural-Forms`` header for Gettext PO

Others might be a bit tricky and we will probably stick to current language defaults:

* XLIFF plurals are usually based on Gettext ones without mentioning the file format
* Qt TS [rules themselves are not documented](http://doc.qt.io/qt-5/i18n-plural-rules.html)

Note: The Babel rules are not same as Gettext ones we're currently using, so it might need some more tweaks:

```
>>> import babel
>>> l = babel.Locale('cs')
>>> l.plural_form.tags
frozenset(['few', 'one', 'many'])
>>> l.plural_form.rules
{'few': 'i in 2..4 and v in 0', 'one': 'i in 1 and v in 0', 'many': 'v not in 0'}
>>> l.plural_form.abstract
[('few', ('and', (('relation', ('in', (u'i', ()), ('range_list', [(('value', (2,)), ('value', (4,)))]))), ('relation', ('in', (u'v', ()), ('range_list', [(('value', (0,)), ('value', (0,)))])))))), ('many', ('not', (('relation', ('in', (u'v', ()), ('range_list', [(('value', (0,)), ('value', (0,)))]))),))), ('one', ('and', (('relation', ('in', (u'i', ()), ('range_list', [(('value', (1,)), ('value', (1,)))]))), ('relation', ('in', (u'v', ()), ('range_list', [(('value', (0,)), ('value', (0,)))]))))))]
```

The variables are defined in [the specification](http://unicode.org/reports/tr35/tr35-numbers.html#Plural_Operand_Meanings), there is also tool to convert them (written in PHP): https://github.com/mlocati/cldr-to-gettext-plural-rules

**Comment by nijel** [comment] 2018-01-09 15:29
After digging into this for few hours (trying to add CLDR plurals to Weblate), now I finally understand where the problem is - it's not that the CLDR plural rules would be that different (the differences are there, but they are limited to few languages).

The problem lies a bit deeper:

Translate-toolkit *always* adds `other` to the plurals:

https://github.com/translate/translate/blob/441fcd1e40e2902e6d88616e8fd4f5dd0103bf44/translate/storage/aresource.py#L309-L310

It might sound weird, but apparently the root cause is in Babel not returning `other` for most of the languages it should. There is even bug reported for similar thing since April 21, see https://github.com/python-babel/babel/issues/495

**Comment by nijel** [comment] 2018-01-09 16:39
This should be fixed by following PR which replaces Babel usage in translate-toolkit by own plurals data: https://github.com/translate/translate/pull/3762

It would be really great if somebody with Android knowledge (eg. @eighthave , @TobiGr, @theScrabi    ) could check if the tags are correct there - I was not able to find some official docs for Android covering this and the CLDR is still a bit magic for me as a result I'm not sure if the table I've generated correct (I've checked few languages which I know were problematic and they look correct).

**Comment by eighthave** [comment] 2018-01-17 11:39
I don't quite understand what I should check.  I looked at this diff of 5d853aa and I have no idea what that data is.  I looked at https://github.com/translate/translate/pull/3762/commits/65b4000b01acc428289f09e8b5fc8f78877e5dd6, and I could see that some of the languages are missing "other".  __All__ languages must have at least "other", that is a hard requirement.  If a language has only one plurals form, it should be "other".  I would include a CI test case that checks that all languages have "other" in them.  I can see that _be_, _pl_, and _uk_ are missing "other".

**Comment by nijel** [comment] 2018-01-19 09:29
No, not all languages use other for integers (that's what android cares for plurals), see for example [Belarusian](http://www.unicode.org/cldr/charts/32/supplemental/language_plural_rules.html#be), [Polish](http://www.unicode.org/cldr/charts/32/supplemental/language_plural_rules.html#pl) or [Russian](http://www.unicode.org/cldr/charts/32/supplemental/language_plural_rules.html#ru).

And yes https://github.com/translate/translate/commit/65b4000b01acc428289f09e8b5fc8f78877e5dd6 is think I'd like to get reviewed (or more precisly https://github.com/translate/translate/pull/3762/files).

**Comment by TobiGr** [comment] 2018-01-20 12:36
I agree with @eighthave. Android requires "other" and if it does not exist this can cause a crash.

**Comment by nijel** [comment] 2018-01-22 15:54
So far I thought that Android is simply following CLDR, but that doesn't seem to be the case, so this has to be implemented somewhere (apparently documentation doesn't seem to exist).

To me it really looks weird that it would require the "other" even for languages where it won't be used - the [getQuantityString](https://developer.android.com/reference/android/content/res/Resources.html#getQuantityString(int,%20int)) used to evaluate this accepts only integers...

Looking at the [code](http://grepcode.com/file/repo1.maven.org/maven2/org.robolectric/android-all/4.4_r1-robolectric-0/android/content/res/Resources.java#Resources.getQuantityText%28int%2Cint%29) I still think that "other" is not needed as long as all valid choices are there.

So can somebody actually test that other is really needed in *all* cases? Testing simple string with one of above mentioned languages (eg. Polish) should do that.

**Comment by mauriciocolli** [comment] 2018-01-24 20:42
I've test it and can confirm, some languages don't require the _other_ field, here's some tests that I did:

##### The test consists on loop through 0 to 220 and check if the the `getQuantityString` returns the language code or throws an error (using `"language_code" + %1$d`in the strings).


|          API          |           25          | 23 | 19 | 16 |
|:---------------------:|:---------------------:|:--:|:--:|:--:|
| Without field "other" 						 | only <br>`be, pl, ru, uk` |  	same as 25		  |  same as 25, but some fallback  | same as 19 |
| Without field "other"<br>(plural deleted if empty)<br>| same as above, <br>some fallback | same as 25 |  same as 25  | same as 25|
|   Following PR rules strictly 				 | ✓ |         ✓                         |  ✓, except `bem, bez` | same as 19|

* Exception when fail: `Resources$NotFoundException: Plural resource ID #id quantity=x item=other`
* You **cannot** have an empty plurals tag
* Deleted plurals just fallback to default

---

You can find the generator (to generate the strings.xml file and their contents) that follows the rules of `PLURAL_TAGS` that it's in your pull request (translate/translate#3762) and the app source code here:
https://github.com/mauriciocolli/LanguageTest

There's some already compiled apks if you want to test in your device.

**Comment by nijel** [comment] 2018-01-25 08:56
@mauriciocolli Thanks for verifying this! I've just deployed this change to Hosted Weblate, so that will give these changes some more real life testing.

There are still few languages whose plural rules in CLDR differ to what is usually used in Gettext, so these will need additional fixes on the Weblate side:

* Lithuanian (see also https://github.com/WeblateOrg/weblate/issues/901)
* Cornish
* Upper Sorbian
* Hebrew (see https://github.com/WeblateOrg/weblate/issues/1781#issuecomment-356652692)
* Lower Sorbian

**Comment by nijel** [comment] 2018-01-30 10:25
Thank you for your report, the issue you have reported has just been fixed in Weblate. The complete fix depends on https://github.com/translate/translate/pull/3762 (which is already deployed in Hosted Weblate).

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Closed** 2018-01-31 16:13 UTC
Labels: bug, translate-toolkit
