### ISSUE TITLE
Glossary not working well

### ISSUE THREAD

**Issue by LongHyukLee** [WeblateOrg/weblate#2735] opened 2019-05-11 13:08 UTC
**Is your feature request related to a problem? Please describe.**
Some projects I'm working on now, isn't showing every of word in source what I saved in glossary.

**Describe the solution you'd like**
![KakaoTalk_20190511_221020326](https://user-images.githubusercontent.com/35549913/57570143-d1016c00-7439-11e9-985f-bb63905334e9.png)

I know that I could see everything that I saved if I click that "pen on paper icon", but it's inconvenient to open new Chrome.
I thought it showed every word that matches in source and glossary.

**Describe alternatives you've considered**
Showing every word from glossary which matches in source.
(I thought it worked, but isn't working nowadays)

**Additional context**
-

**Comment by nijel** [comment] 2019-05-11 15:34
Maybe duplicate of https://github.com/WeblateOrg/weblate/issues/2183? What is actually the source string for the glossary on a screenshot?

**Comment by ccppoo** [comment] 2019-05-12 14:23
@nijel 
![image](https://user-images.githubusercontent.com/46418312/57583511-efd03300-750b-11e9-8203-4629ece0f6ef.png)

This would tell what's wrong.
That "BACK TO BASICS" keep on showing on every source. 
I saw #2183 but it looks like a different case because, in this case it only shows some of it and "BACK TO BASICS" is shown every page.

It's the third one ↓
![image](https://user-images.githubusercontent.com/46418312/57583560-7edd4b00-750c-11e9-8ef7-e4045756fbe9.png)

Link : https://hosted.weblate.org/translate/debian-handbook/01_the-debian-project/ko/?type=todo

**Comment by nijel** [comment] 2019-05-12 17:35
The problem is in the lookup used - it looks for all words, so the "to" word is probably present in lot of strings (see https://github.com/WeblateOrg/weblate/issues/2183#issuecomment-414152088).

**Comment by ccppoo** [comment] 2019-05-13 04:34
I should have looked more into it, thanks!

**Comment by nijel** [comment] 2019-05-13 05:06
Duplicate of #2183

**Closed by nijel** 2019-05-13 05:06 UTC
Labels: question
