### ISSUE TITLE
Make a hint about "Source change" in Zen mode

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#1234] opened 2016-09-16 12:27 UTC
If the translator uses the Zen mode, there is no hint that "Source change" (red/green info) is available for particular string.
### Steps to reproduce
1. Make a string translated.
2. Make string change. Update pot and po files using --previous feature.
3. Go to the Zen mode editor.
### Actual behaviour

Standard editor shows nice red/green "Source change". Zen mode does not show it, and it even does not show any information that the source change is available. Only if you click to Edit, you can see that the Source change is available.
### Expected behaviour

Either embed Source change directly to the Zen mode window, or at least make a hint that the source change is available (e. g. click to show, and continue to show while editing the translation)
Tell us what should happen
### Server configuration
- Weblate 2.6
- Python 2.7.9
- Django 1.8.4
- six 1.9.0
- python-social-auth 0.2.7
- Translate Toolkit 1.14.0-rc1
- Whoosh 2.7.0
- Git 1.8.5.6
- Pillow (PIL) 1.1.7
- dateutil 2.4.2
- lxml 3.2.3
- django-crispy-forms 1.5.2
- compressor 1.5
- djangorestframework 3.3.3
- pytz 2013.9
- pyuca N/A
- Database backends: django.db.backends.mysql

Temporary example URL:
Here you can see Source change hint:
https://l10n.opensuse.org/translate/skelcd-opensuse/master/ar/?type=fuzzy
Here you cannot see Source change hint:
https://l10n.opensuse.org/zen/skelcd-opensuse/master/ar/?sid=c689b998-7c08-11e6-aa17-525400a48651
##

**Comment by nijel** [comment] 2019-12-16 12:55
Duplicate of #2665

**Closed by nijel** 2019-12-16 12:55 UTC
Labels: enhancement, duplicate
