### ISSUE TITLE
unable to modify subscriptions after loging in via github third party auth

### ISSUE THREAD

**Issue by ghost** [WeblateOrg/weblate#1891] opened 2018-03-08 15:03 UTC
### Steps to reproduce
1. login via github into a new account
2. got to /accounts/profile/#subscriptions
3. chose a project
4. click save

### Actual behaviour
Nothing happens

### Expected behaviour
The subscription is saved

### Workaround

Set the password for the user.

### Server configuration

<pre>
$ sudo docker-compose run --rm weblate list_versions
WARNING: Found orphan containers (weblate_https-portal_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Starting weblate_cache_1 ... 
Starting weblate_database_1 ... done
Postgres is up
</pre>

 * Weblate 2.17.1
 * Python 2.7.13
 * Django 1.11.6
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.6.1
 * compressor 2.2
 * djangorestframework 3.7.0
 * pytz 2017.2
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.2.2
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment] 2018-03-08 15:25
Do you get some error?

**Comment by nijel** [comment] 2018-03-08 15:27
I've just noticed that you're on older version, so it might be fixed by e75798da7b2bd312a8c67a378dc4e2aeb0582ae3, though it's just my guess.

**Comment by dachary** [comment] 2018-03-08 15:32
> Do you get some error?

There was no error. The workaround we found was a wild guess, because a yellow box asked that the password is set. And I figured it was maybe something that blocked the validation of the subscription.

**Comment by nijel** [comment] 2018-03-08 15:43
That certainly should not block the saving, but I can't reproduce this on current version anyway, so it really might be the commit I've posted before...

**Comment by dachary** [comment] 2018-03-08 15:52
Ok, thanks for the quick feedback. I will upgrade and add to this ticket with progress. :+1:

**Closed** 2018-04-15 09:32 UTC
Labels: question, wontfix
