### ISSUE TITLE
Spammer management

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#3548] opened 2020-03-02 14:14 UTC
**Is your feature request related to a problem? Please describe.**
Our weblate instance is open to any contributor, which means that we have from time to time users trying to spam us by injecting wrong translations. I'm not talking about automatic spam here, more about users having fun in putting manually wrong translations.

**Describe the solution you'd like**
Would be nice to have an admin option allowing at the same time to block an user for further logging (without deleting him) and revert all his translations at once.
Note that in my recent case, the user actually created a new language so I wasn't able to use the "revert" option from UI for his translation: I had to manually save an empty translation.

**Describe alternatives you've considered**
Right now I performed the following:
 - opened the user profile to see all his changes
 - revert manually all the translations (by removing the translation, saving and dismissing the check)
 - go in Django admin to mark the user as not active. 

**Additional context**
We are still using Weblate 3.9.1, I did not checked properly so maybe there's already some options for it now.

**Comment by nijel** [comment] 2020-03-02 14:31
Reverting the changes in Git might be easier and less error prone. But you will still run into troubles if somebody has changed the strings meanwhile. That's also reason why one click of reverting all changes won't be that easy.

Setting the user as not active should do the right thing in this case, though it won't prevent malicious user to register with another email.

**Comment by surli** [comment] 2020-03-02 15:21
> Reverting the changes in Git might be easier and less error prone.

Actually we are working with pull requests: so what happens is that we closed the PR, but it kept being opened back by Weblate until I decided to rollback the change in Weblate. Which makes sense IMO: for me the process should be:
  - a user perform a translation
  - we review the change in PR
  - if it happens it's a spam, we close the PR and ban the user from Weblate

We especially don't want to accept the PR and revert it after because:
  1. it will remains in Weblate memory which is not good
  2. the spammer will appear in our authors, and we don't really want that :)

**Comment by nijel** [comment] 2020-03-02 15:31
If you generate list of authors on Weblate, even reverted edits count for that. Similarly, with translation memory - reverting the change doesn't make the translation memory make go away.

Right now the easiest approach to deal with this is on git level. Either revert the commit ot rewrite history to skip it.

Having something in Weblate might be useful, but doing this properly is not that easy.

**Comment by nijel** [comment] 2020-03-04 14:29
Duplicate of #3040

**Comment by nijel** [comment] 2020-03-04 14:30
Turns out this has been already reported...

**Closed by nijel** 2020-03-04 14:29 UTC
Labels: enhancement, duplicate, backlog

**Comment by surli** [comment] 2020-03-04 14:33
Indeed :)
