### ISSUE TITLE
Too many matches in the glossary

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#5393] opened 2021-02-10 08:08 UTC
**Describe the issue**

On the source text side, everything is fine now. There are too many results on the glossaries side.
![image](https://user-images.githubusercontent.com/39633242/107482121-8ddcab80-6b7f-11eb-9c8a-0ab0b79ba71e.png)

bleeding-2021-02-10-3df84888adb796e5f02bb125a5cd24cf8a93bdbd

**Comment by nijel** [comment] 2021-02-10 08:30
I think this is a duplicate of #5387, are you sure you are running the mentioned image? It should already contain fix for that, and I can't reproduce this behavior on 3df84888adb796e5f02bb125a5cd24cf8a93bdbd.

**Comment by tomkolp** [comment] 2021-02-10 08:52
Yes, the docker image is up to date. Fix partially works because text highlighting works fine.

**Comment by nijel** [comment] 2021-02-10 09:55
I've added tests to cover this in d1cece9d29d58bce11f29e51543c86043bb35bec, but it works as expected. Are you using PostgreSQL or MySQL?

**Comment by tomkolp** [comment] 2021-02-10 10:29
> I've added tests to cover this in [d1cece9](https://github.com/WeblateOrg/weblate/commit/d1cece9d29d58bce11f29e51543c86043bb35bec), but it works as expected. Are you using PostgreSQL or MySQL?

PostgreSQL
[https://weblate.eso-spolszczenie.eu/translate/eso-spolszczenie/21337012/pl/?checksum=371ec15ee8c15cd0&q=21337012-0-1913&sort_by=-priority%2Cposition](https://weblate.eso-spolszczenie.eu/translate/eso-spolszczenie/21337012/pl/?checksum=371ec15ee8c15cd0&q=21337012-0-1913&sort_by=-priority%2Cposition)
Maybe wait for the next docker image bleeding. Then it will be sure that the image is correct.

**Closed** 2021-02-10 13:19 UTC
Labels: bug

**Comment by nijel** [comment] 2021-02-10 14:09
Thanks for sharing the link, I've imported the glossary to my staging environment and could reproduce the issue.
