### ISSUE TITLE
Please reopen #2668

### ISSUE THREAD

**Issue by UncleSamSwiss** [WeblateOrg/weblate#2720] opened 2019-05-01 11:29 UTC
Sorry to write a separate report for this, but could you please reopen #2668 as it seems not to be working correctly for at least three people in the thread.

**Comment by nijel** [comment] 2019-05-01 12:40
Duplicate of #2668

**Closed by nijel** 2019-05-01 12:40 UTC

**Comment by UncleSamSwiss** [comment] 2019-05-01 13:02
I'm sorry, I didn't mean to urge you in any way. The work you're doing is amazing and I'm always surprised how fast you answer to issues. As an open source developer with little time on the side, I know how difficult it is to satisfy all requests. The only reason I opened this ticket is because I know from my own experience that I tend to forget about closed issues and the comments that are coming after closing it.
