### ISSUE TITLE
API: add an endpoint to get the list of contributors of a project or a component

### ISSUE THREAD

**Issue by Deuchnord** [WeblateOrg/weblate#6315] opened 2021-07-20 15:28 UTC
**Is your feature request related to a problem? If so, please describe.**

As the maintainer of a project, I would like to be able to generate a page that lists the contributors of my project/component based on the data provided by Weblate.

**Describe the solution you'd like**

Providing an endpoint to the REST API that returns a list of all the contributors would help a lot.

**Describe alternatives you've considered**

The solution that I have found is to create a JSON report manually from the `/projects/{slug}/#reports` page, but this means that I need to manually regenerate this report regularly, which is not really ideal for big projects with a lot of activity.
Plus, the reports only return the list of contributors on a given period, but I would prefer listing _all_ the contributors (even those who haven't been active since a lot of time)

**Comment by nijel** [comment] 2021-12-22 12:07
Duplicate of #5459

**Closed by nijel** 2021-12-22 12:07 UTC
Labels: enhancement, duplicate
