### ISSUE TITLE
Shared translation memory settings don't work correctly

### ISSUE THREAD

**Issue by tariver** [WeblateOrg/weblate#3205] opened 2019-11-14 10:08 UTC
**Describe the bug**
I have a Weblate installation with several projects.
One is the main project, where I put files of those components that are ready for localization, it's a production project so to speak. It's access level is "Protected".
There are also several other projects which contain files for those applications that are not yet ready for integration with Weblate, some projects are for testing purposes etc. All of these are private projects.
What I wanted to do:
Make the main project contribute to shared translation memory but not to use it, so I put the "Use shared translation memory" check off and "Contribute to shared translation memory" on.
All other projects should not contribute to the shared memory but should be able to use main project's memory i.e. the shared translation memory. So I put the "Use shared translation memory" check on and "Contribute to shared translation memory" off.
For some reason the main project doesn't contribute to the shared memory, but other projects do.

**To Reproduce**
1. Have several projects with translation memory settings as described above
2. Wipe out all translation memory using `weblate delete_memory --all` management command
3. Go to main project's > Manage > Translation memory and press the "Import" button. Wait for the translation memory to be populated
4. Go to one of the other (second) project's Manage > Translation memory menu and press the "Import" button. Wait for the translation memory to be populated
5. Now go to the another non-main (third) project, start translating and switch to "Translation memory" tab.
6. You'll see that suggestions from translation memory will have "Shared: second-project/component" as their origin.

**Expected behavior**
Translation memory in the third project should have "Shared:main-project/component" as it's origin.

**Server configuration and status**
```
 * Weblate 3.9-dev
 * Python 3.5.3
 * Django 2.2.5
 * Celery 4.3.0
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.2.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.4.0
 * translation-finder 1.6
 * Whoosh 2.7.4
 * defusedxml 0.6.0
 * Git 2.11.0
 * Pillow 6.1.0
 * python-dateutil 2.8.0
 * lxml 4.4.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.3
 * djangorestframework 3.10.3
 * user-agents 2.0
 * jellyfish 0.7.2
 * diff-match-patch 20181111
 * ruamel.yaml 0.16.5
 * Mercurial 4.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.9.0-3-amd64 (x86_64)
```

**Comment by nijel** [comment] 2019-11-14 10:18
Already fixed by f2c228c, duplicate of #2983

**Closed by nijel** 2019-11-14 10:18 UTC
