### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by subins2000** [WeblateOrg/weblate#3320] opened 2019-12-18 18:52 UTC
**Is your feature request related to a problem? Please describe.**
It's hard to know who contributed the most

**Describe the solution you'd like**
A leaderboard that has points (like stackoverflow reputation) depending on project and as a whole. Pootle had this feature. It helped drive contributions.

**Describe alternatives you've considered**
Manually download report and calculate a point ?
or use stats API to generate a leaderboard.

**Additional context**

**Comment by nijel** [comment] 2019-12-18 18:53
It's already there for whole instance - https://hosted.weblate.org/stats/

**Comment by subins2000** [comment] 2019-12-18 18:58
Oh great ! I couldn't notice it thought in the UI. Where was the button located ? Is it in project pages too ?

**Comment by nijel** [comment] 2019-12-18 19:01
You can get there from the about page, I don't think there is direct link somewhere.

**Comment by comradekingu** [comment] 2019-12-19 07:05
I think stats can be utilized more to learn something about different aspects of contributions.
The problem is stats are not on every page, stops after a few positions, and are not linked to actual lists. It also includes uploads. I accidentally uploaded 1500 strings that were the same as my target once.

**Comment by subins2000** [comment] 2019-12-23 15:52
@comradekingu Yes it should. In case of weblate instances with `Peer review` or `Dedicated reviewers`, the leaderboard should be focused on suggestions.

Also, isn't stats site-wide ? Or can we get stats/leaderboard per project ? That would be a good feature.

**Comment by comradekingu** [comment] 2019-12-24 07:12
@subins2000 Or actual reviews made. Is someone a pure reviewer, or not?
The latter would be the last part of #2752

**Comment by nijel** [comment] 2020-01-06 15:45
Stats are currently site-wide, we currently do not track per project ones.

**Comment by comradekingu** [comment] 2020-01-06 16:07
I will read through the terms and conditions to see how it is worded.

**Comment by nijel** [comment] 2020-01-16 19:40
Having some kind of more detailed stats is something what we might consider in future.

**Comment by nijel** [comment] 2020-03-18 09:44
Duplicate of #2752

**Closed by nijel** 2020-03-18 09:44 UTC
Labels: duplicate, enhancement
