### ISSUE TITLE
Compare auto suggestion with source

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#7925] opened 2022-07-25 19:38 UTC
### Describe the problem

Automatic suggestions below 100% should indicate differences between the source.  Differences are hard to find now.

### Describe the solution you'd like

The difference is highlighted in the automatic suggestion or in the segment source.

### Screenshots

![Przechwytywanie](https://user-images.githubusercontent.com/39633242/180860475-5e0360e8-3c5b-47b8-a71c-0044d404760d.PNG)

**Comment by Geeyun-JY3** [comment] 2022-07-26 00:50
Duplicate of #4368

**Closed** 2022-07-27 09:52 UTC
Labels: duplicate
