### ISSUE TITLE
cannot add go-i18n JSON project:  Could not parse translation base file: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by eighthave** [WeblateOrg/weblate#4844] opened 2020-11-09 15:39 UTC
**Describe the bug**

When adding a new go-i18n component, the  "Monolingual base language file"  says "Could not parse translation base file: 'str' object has no attribute 'get'"

**To Reproduce the bug**

1. add new component
2. https://github.com/fsfe/reuse-website
3. Version control system: GitHub
4. File format: go-i18n JSON file
5. Filemask: `site/i18n/*.json`
6. Monolingual base language file: `site/i18n/en.json`
7. Click "Save".

**Expected behavior**

There should be no error.

**Screenshots**

![Screenshot from 2020-11-09 16-37-01](https://user-images.githubusercontent.com/143465/98562003-70a6f100-22a1-11eb-8ded-57f2593d30e5.png)

**Comment by nijel** [comment] 2020-11-09 15:46
Duplicate of #4323

**Closed by nijel** 2020-11-09 15:46 UTC
Labels: enhancement, duplicate
