### ISSUE TITLE
Search fails with hotkey symbols

### ISSUE THREAD

**Issue by yarons** [WeblateOrg/weblate#4152] opened 2020-07-09 18:23 UTC
**Describe the bug**

Searching for "Preview" doesn't return terms such as "Pre_view" and "P~review".
I'm not sure if it's a bug or a feature request but I'll leave it here.

**To Reproduce**

1. Look for a term with a hotkey symbol (such as _ or & or ~).
2. Search for the text but without the symbol (Pr_eview -> Preview)
3. Take a look at the results

**Expected behavior**

The search should find it regardless of the hotkey symbol.

**Server configuration and status**

LibreOffice instance (4.1.1)

**Comment by nijel** [comment] 2020-07-10 05:39
Duplicate of #1861

**Closed by nijel** 2020-07-10 05:39 UTC
Labels: duplicate
