### ISSUE TITLE
Add labels to Github Pull Requests

### ISSUE THREAD

**Issue by Adammatthiesen** [WeblateOrg/weblate#13030] opened 2024-11-14 21:14 UTC
### Describe the problem

Currently i have to setup a custom GitHub Action to monitor whether the PR meets the filters for a pull request from weblate and then apply the label, it would be nice to have this built in

### Describe the solution you would like

It would be a great feature if we could have the VCS when configured to open Pull requests to GitHub to also be able to apply labels to the pull requests as well! instead of having to build 

### Describe alternatives you have considered

creating a custom GitHub action that looks for specific criteria and then applies labels such as `translation`

**Comment by nijel** [comment] 2024-11-15 07:47
Duplicate of #8494

**Closed by nijel** 2024-11-15 07:47 UTC
Labels: enhancement, duplicate
