### ISSUE TITLE
Cannot translate string: "Source in review" #4083 (Unresolved prior bug)

### ISSUE THREAD

**Issue by HubertusVIE** [WeblateOrg/weblate#4227] opened 2020-07-27 10:26 UTC
This same issue has been reported before as  #4083 but remained unresolved and was closed as "stale". 

I can translate some strings in my project, but (at least) one is marked as "Source in review" besides the header "Translation". Problem: The edit field for language "English" below is greyed out for this string and the old translation cannot be changed. Like the prior user, the arcane error message: "Error in parameter review: Select a valid choice. 100 is not one of the available choices." appears on top but refers to nothing I did. (I never selected a parameter, not do I know what the "100" choice refers to.)

How do I resolve this problem so I can edit the English key? 

<img width="1060" alt="Screenshot 2020-07-27 at 12 12 21" src="https://user-images.githubusercontent.com/13375538/88531982-0cb73000-d004-11ea-9be0-75489cfcda51.png">

**Comment by nijel** [comment] 2020-07-27 13:20
The root cause is that source string is in review, please edit it and adjust it's state, you will be then allowed to edit the translation.

The error message is confusing because you should not have permissions to edit the string at all, it has been fixed by e336d27f48b1bd2560008390299c88e375fb55ad.

**Comment by codebykenny** [comment] 2020-08-13 19:25
I am experience this problem as well after Updating Weblate from 3.x to 4.x.

Many many strings have this "Source in Review" label and we cannot translate the strings.

I also can't find a place to see all the "Sources in Review"

Why is this happening? Whats the easiest way to get this resolved?

**Comment by nijel** [comment] 2020-08-17 09:13
Seems like the state of the source string is wrongly calculated in your case. What Weblate version do you use?

**Closed** 2020-09-02 10:21 UTC
Labels: question, wontfix
