### ISSUE TITLE
Git integration for making use of suggestions

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#12452] opened 2024-09-09 11:05 UTC
### Describe the issue

Every so often I think about making this issue, and here it is.
The process of making stringbase edits really doesn't lend itself to textfiles or the web UI of popular Git platforms.

Right now there is no Weblate-only way to make changes to source strings,
unless editing source strings is allowed.
Between not allowing any edits and full access, MRs and PRs could be made from suggestions.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Find an error
2. Be on the go with the laptop that doesn't have the keys and setup
3. Fix the error
4. Notice more errors
5. Try to consistently change those across many different files using searches in Weblate as a guide.
6. MR/PR is too big, or errors didn't all perfectly align into separate entities.

### Expected behavior

Would like to make suggestions for everything and then look at that in Matrix mode to
get a grasp of what I think I am doing when keeping track of a lot of strings mentally.

### How do you run Weblate?

weblate.org service

### Additional context

Suggestions could go somewhere.
Evidence of things fixed in a downstream language only could stop.
Shouldn't have to cruise through translations of all translated languages looking for what should be easier to fix upstream.

I think one MR/PR per component is all it needs.
The case could be made for extra Weblate UI to divide available suggestions into different batches,
but it can be added on later, there are ways around it, and nobody has requested it yet.

The maintainer looks at all suggestions before stringfreeze.
Drops the bad ones, or changes them to be better.
APIs and/or clicks buttons and creates something that can be implemented.

Edit: Integration obviously also saves on having to do something about each suggestion after they are otherwise implemented.

**Comment by nijel** [comment] 2024-09-10 10:57
This is about source string or translation suggestions? Maybe a duplicate of https://github.com/WeblateOrg/weblate/issues/10163?

**Closed** 2024-09-23 10:31 UTC
Labels: enhancement, duplicate
