### ISSUE TITLE
translate will escape backslash , like '\n' will be 'n' in the translation result.

### ISSUE THREAD

**Issue by berubou** [WeblateOrg/weblate#2347] opened 2018-10-24 07:27 UTC
**Describe the bug**
translate will escape backslash , like '\n' will be 'n' in the translation result.

**To Reproduce**
1. upload a txt file in csv format. 
  ![image](https://user-images.githubusercontent.com/14237234/47413405-c682cc00-d7a0-11e8-8714-09a1e93b18cb.png)

2. the file content are as follows
    ![image](https://user-images.githubusercontent.com/14237234/47413465-eb773f00-d7a0-11e8-95b8-015e58cbe0c0.png)

3. the translation result will replace '\n' to 'n'
  ![image](https://user-images.githubusercontent.com/14237234/47413534-1a8db080-d7a1-11e8-98dd-2915b3ce8eba.png)

**Expected behavior**
retain backslash 

**Server configuration and status**
- list_versions
``` 
* Weblate 3.2.2
 * Python 3.5.3
 * Django 2.1.2
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.10.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow 4.0.0
 * python-dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.0
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.5
 * pyuca 1.2
 * PyYAML 3.12
 * tesserocr 2.3.1
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Platform: Linux 4.4.0-132-generic (x86_64) 
```
- check --deploy
```
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

System check identified 3 issues (0 silenced).
```

**Additional context**
was working on version 3.1.1, running in the docker. it happens
and after upgrade to version 3.2.2. it still happens.

**Comment by berubou** [comment] 2018-10-25 12:41
besides, i also found that '0' (zero) will be replaced to 'False'

**Comment by nijel** [comment] 2019-01-28 06:36
Duplicate of #987

**Closed as completed by nijel** 2019-01-28 06:36 UTC
Labels: bug, Blocked by upstream
