### ISSUE TITLE
gettext addon is not wrapping lines

### ISSUE THREAD

**Issue by strk** [WeblateOrg/weblate#7122] opened 2022-01-18 23:25 UTC
### Describe the issue

We have the `gettext` addon installed and configured with  `Long lines wrapping Wrap lines at 77 characters and at newlines 
Approval of a translated string resulted in this commit being pushed to our repository: https://gitlab.com/postgis/postgis/-/commit/8bb507f8f9084095728dc4062cdcb9431b76e7d4

You can see the commit created by weblate actually _removed_ the existing long-lines wrapping.
[this](https://gitlab.com/postgis/postgis/-/commit/8bb507f8f9084095728dc4062cdcb9431b76e7d4#c9dc3612394b6996cc0eed7e941fe9ce5a40bbcd_49_43) line is 204 characters long !

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 4.10.1
 * Django: 4.0.1
 * siphashc: 2.1
 * translate-toolkit: 3.5.2
 * lxml: 4.7.1
 * Pillow: 8.4.0
 * bleach: 4.1.0
 * python-dateutil: 2.8.2
 * social-auth-core: 4.1.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.13.0
 * oauthlib: 3.1.1
 * django-compressor: 3.1
 * djangorestframework: 3.13.1
 * django-filter: 21.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.4.2
 * setuptools: 60.3.1
 * jellyfish: 0.8.9
 * openpyxl: 3.0.9
 * celery: 5.2.2
 * kombu: 5.2.3
 * translation-finder: 2.10
 * weblate-language-data: 2022.1
 * html2text: 2020.1.16
 * pycairo: 1.20.1
 * pygobject: 3.42.0
 * diff-match-patch: 20200713
 * requests: 2.26.0
 * django-redis: 5.2.0
 * hiredis: 2.0.0
 * sentry_sdk: 1.5.1
 * Cython: 0.29.26
 * misaka: 2.1.1
 * GitPython: 3.1.25
 * borgbackup: 1.1.17
 * pyparsing: 3.0.6
 * pyahocorasick: 1.4.2
 * python-redis-lock: 3.7.0
 * Python: 3.10.1
 * Git: 2.30.2
 * psycopg2: 2.9.3
 * psycopg2-binary: 2.9.3
 * phply: 1.2.5
 * chardet: 4.0.0
 * ruamel.yaml: 0.17.20
 * tesserocr: 2.5.2
 * akismet: 1.1
 * boto3: 1.20.30
 * zeep: 4.1.0
 * aeidon: 1.10.1
 * iniparse: 0.5
 * mysqlclient: 2.1.0
 * Mercurial: 6.0.1
 * git-svn: 2.30.2
 * git-review: 2.2.0
 * Redis server: 6.2.6
 * PostgreSQL server: 13.5
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mail.osgeo.org
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.4.0-81-generic (x86_64)

**Comment by strk** [comment] 2022-01-19 07:25
Uhm. Indeed counting with my eyes reveal that line I referenced is actually 79 glyphs, which is what I would expect

**Comment by strk** [comment] 2022-01-19 07:27
For the record, here's the downstream ticket: https://trac.osgeo.org/postgis/ticket/5057

**Comment by nijel** [comment] 2022-01-19 09:07
Duplicate of https://github.com/translate/translate/issues/4452

**Closed by nijel** 2022-01-19 09:07 UTC
Labels: bug, duplicate
