### ISSUE TITLE
adding the function of correspondence with the user on the user's page and adding the user to the group

### ISSUE THREAD

**Issue by gfghjjk** [WeblateOrg/weblate#10012] opened 2023-09-22 06:49 UTC
### Describe the problem

add the ability to correspond with translators on the translator page and add a translator to the group

### Describe the solution you'd like

I suggest adding the ability to write directly to translators on the translator's page and suggest adding a translator to a group for joint translation on a selected project

**Comment by nijel** [comment] 2023-09-22 06:58
Duplicate of #5533

**Closed by nijel** 2023-09-22 06:58 UTC
Labels: duplicate
