### ISSUE TITLE
When adding components, can add a feature to custom delimiter?

### ISSUE THREAD

**Issue by Pinkuburu** [WeblateOrg/weblate#4821] opened 2020-11-05 09:18 UTC
**Is your feature request related to a problem? If so, please describe.**
Sometimes I get files that don't conform to CSV format.
But they are also key-value pair content.
such as：
![image](https://user-images.githubusercontent.com/4962790/98220639-8bb7ef00-1f89-11eb-8547-22df5c3ce42c.png)
they split by"|"
I want to add a feature when I setting new component, I can  define a delimiter to import files correctly

**Describe the solution you'd like**
The idea for this came from Excel in Office
In Excel, you can customize the import of any format of text into Excel,You just need to define a delimiter when you import.
As shown in picture：
![image](https://user-images.githubusercontent.com/4962790/98220919-f5d09400-1f89-11eb-9ed6-efa0da6e248f.png)
how to use:
![image](https://user-images.githubusercontent.com/4962790/98221256-61b2fc80-1f8a-11eb-853c-f1de421e4624.png)

**Comment by nijel** [comment] 2020-11-05 09:29
Right now it's not possible to add parameters to file formats, the only way around is to implement own format with adjusted parameters.

Duplicate of #1897

**Closed by nijel** 2020-11-05 09:29 UTC
Labels: duplicate, enhancement
