### ISSUE TITLE
Some languages don't have all strings available for translation

### ISSUE THREAD

**Issue by spacecowboy** [WeblateOrg/weblate#10595] opened 2023-12-12 10:37 UTC
### Describe the issue

My project is here: https://hosted.weblate.org/projects/feeder/android-strings

A few languages Polish, French and Chinese (Simplified), are missing a dozen strings.

One example is the string `other_minutes` which is not available for translation in these languages.

I have tried re-scanning strings and similar with no change.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Not sure how to reproduce it but it is happening here :https://hosted.weblate.org/projects/feeder/android-strings

look at string `other_minutes`, it is missing from Polish, French, and Chinese (Simplified)

### Expected behavior

All strings should be available for translation in all languages.

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment] 2023-12-13 08:32
I've forced rescan of these files and the strings are now there. The root cause should be addressed by https://github.com/WeblateOrg/weblate/pull/10604.

PS: Why not using plurals as supported in Android instead of doing that manually?

**Closed** 2023-12-13 11:27 UTC
Labels: bug

**Comment by spacecowboy** [comment] 2023-12-13 13:44
> I've forced rescan of these files and the strings are now there. The root cause should be addressed by #10604.
> 
> PS: Why not using plurals as supported in Android instead of doing that manually?

The strings ARE used in plurals. But each string is individually referenced because not all translation tools support parsing plurals. No idea if weblate supports them, but tools I've used in the past have not.

**Comment by nijel** [comment] 2023-12-13 13:50
Yes, Weblate supports plurals and shows only forms which are used for the given language.
