### ISSUE TITLE
Translatable blogposts

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#5744] opened 2021-03-25 14:11 UTC
The good news is Nijel's English improved since 2012.
The bad news is that celebrating it takes the form of making everyone aware at the top of https://weblate.org/nb/news/archive/looking-pootle-alternative/

Blogposts are still a bit so-so, which leads me to think the solution would be to have it all be translatable and editable. Directly even.
If merging changes automatically takes 12 hours, I don't think anything malicious would get through.
Even blogposts made by others would be possible.

**Comment by nijel** [comment] 2021-03-25 14:23
Duplicate of https://github.com/WeblateOrg/website/issues/84

**Closed by nijel** 2021-03-25 14:23 UTC
Labels: duplicate
