### ISSUE TITLE
Backslash are not exported correctly for .strings files

### ISSUE THREAD

**Issue by nathanfallet** [WeblateOrg/weblate#7562] opened 2022-04-29 08:59 UTC
### Describe the issue

I have some strings in which I'm using LaTeX, so I have `\`. In `Localizable.strings` files, they need to be escaped as `\\` (else they are treated as control chars).

My source strings is declared this way:
```
"example_card_1_content" = "The set of natural numbers is denoted as $\\mathbb{N}$:\n$$\\mathbb{N} = \\{0, 1, 2, 3, \\dots\\}$$";
```

After translations on weblate, it was exported like this:
```
"example_card_1_content" = "El conjunto de los números naturales se denota como $\mathbb{N}$:\n$$\mathbb{N} = \{0, 1, 2, 3, \dots\}$$";
```
So backslash are not escaped correctly!

Note that the same string is present in `strings.xml` files for Android, and it is exported correctly:
```xml
    <string name="example_card_1_content">El conjunto de los números naturales se denota como $\\mathbb{N}$:
 \n$$\\mathbb{N} = \\{0, 1, 2, 3, \\dots\\}$$</string>
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Import any `Localizable.strings` file with a string containing `\\`, translate to another language using weblate, and see the exported string with only `\` instead of `\\`.

### Expected behavior

I expected the exported string to contain `\\`, like in the source string, and also like the android xml generated file.

### Additional context

After inspection, https://github.com/translate/translate/pull/4618 should fix the problem.

**Comment by nijel** [comment] 2022-04-29 10:54
Duplicate of https://github.com/translate/translate/issues/4617

**Closed by nijel** 2022-04-29 10:54 UTC
Labels: bug, translate-toolkit, duplicate
