### ISSUE TITLE
HTML entities shown in user view

### ISSUE THREAD

**Issue by williamdes** [WeblateOrg/weblate#10139] opened 2023-10-10 16:19 UTC
### Describe the issue

HTML escaped

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

https://hosted.weblate.org/projects/tb-android/

![Screenshot_2023-10-10-18-17-34-245_org mozilla fenix](https://github.com/WeblateOrg/weblate/assets/7784660/897d645b-a3c7-40ec-b66e-dbb750d795c6)

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment] 2023-10-11 07:30
Duplicate of #10102

**Closed by nijel** 2023-10-11 07:30 UTC
Labels: bug, duplicate
