### ISSUE TITLE
Glossary terms should only appear when the whole term is detected into string

### ISSUE THREAD

**Issue by Porrumentzio** [WeblateOrg/weblate#5810] opened 2021-04-07 07:55 UTC
**Describe the issue**
Sometimes glossary terms appear even when the whole term is not into the string.

**To Reproduce the issue**

1. Add the term "check box" to the glossary
2. Go to a string containing, for example, the word "check"
3. The term "check box" will be suggested, even if that term is not on the original string

**Expected behavior**
Terms should only be displayed only when the whole term is detecting into the string.

**Screenshots**

![irudia](https://user-images.githubusercontent.com/61913683/113830573-0aa69300-9787-11eb-8d02-2964e53b0025.png)

**Additional context**

Instance: https://i18n.e.foundation/
Weblate v.: `3.11.3`

**Comment by nijel** [comment] 2021-04-08 05:28
Duplicate of #2183

**Closed by nijel** 2021-04-08 05:28 UTC
Labels: bug, duplicate
