### ISSUE TITLE
The "Remove blank strings" addon removes all strings from a newly created translation and leaves an empty file

### ISSUE THREAD

**Issue by dleidert** [WeblateOrg/weblate#12106] opened 2024-07-22 09:11 UTC
### Describe the issue

I have an Android project which uses Android String Resources. I've created a new translation project with a translation component. The "Remove blank strings" addon is enabled by default. According to my preferences, Weblate suggests creating a new German translation for it and shows the correct number of strings and words. But when I create it, the resulting file is empty. It only contains the opening and closing <resources> tags, but none of the actual string resources. The reason is that first, the new language file is [created](https://github.com/dleidert/weblate.bug-android-strings/commit/05ce22fdaddff1a7ab49921c6bc1e3368ed55bf1). And then the plugin [removes all empty strings](https://github.com/dleidert/weblate.bug-android-strings/commit/bc80519ff1d03442ad615a0e38a56babbeda5c78), which are all strings. I have created a test repository to demonstrate it at <https://github.com/dleidert/weblate.bug-android-strings>. If I disable the plugin, everything works fine.

Unfortunately, just disabling the addon does not bring back the missing keys. I had to remove and re-create the language.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Create a test project e.g. with an Android Strings resource file
2. Create a translation project in weblate
3. Create a translation component for this project (the "Remove empty strings" addon is enabled by default)
4. Create a new translation in any language for the component
5. The created resource file does not contain any translatable strings

### Expected behavior

The "Remove empty strings" addon should not be enabled by default. In any new translation, the strings will be empty. I actually have trouble seeing the benefit of this plugin, to be honest.

### Screenshots

Repository at <https://github.com/dleidert/weblate.bug-android-strings>

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 5.6.2
 * Django: 5.0.6
 * siphashc: 2.4.1
 * translate-toolkit: 3.13.1
 * lxml: 5.2.2
 * pillow: 10.3.0
 * nh3: 0.2.17
 * python-dateutil: 2.9.0.post0
 * social-auth-core: 4.5.4
 * social-auth-app-django: 5.4.1
 * django-crispy-forms: 2.2
 * oauthlib: 3.2.2
 * django_compressor: 4.5
 * djangorestframework: 3.15.2
 * django-filter: 24.2
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.15.4
 * rapidfuzz: 3.9.3
 * openpyxl: 3.1.5
 * celery: 5.4.0
 * django-celery-beat: 2.6.0
 * kombu: 5.3.7
 * translation-finder: 2.16
 * weblate-language-data: 2024.5
 * html2text: 2024.2.26
 * pycairo: 1.26.1
 * PyGObject: 3.48.2
 * diff-match-patch: 20230430
 * requests: 2.32.3
 * django-redis: 5.4.0
 * hiredis: 2.3.2
 * sentry-sdk: 2.7.1
 * Cython: 3.0.10
 * misaka: 2.1.1
 * GitPython: 3.1.43
 * borgbackup: 1.2.8
 * pyparsing: 3.1.2
 * ahocorasick_rs: 0.22.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.2
 * Python: 3.12.4
 * Git: 2.39.2
 * psycopg: 3.2.1
 * psycopg-binary: 3.2.1
 * phply: 1.2.6
 * ruamel.yaml: 0.18.6
 * tesserocr: 2.7.0
 * boto3: 1.34.136
 * zeep: 4.2.1
 * aeidon: 1.15
 * iniparse: 0.5
 * mysqlclient: 2.2.4
 * Mercurial: 6.7.4
 * git-svn: 2.39.2
 * git-review: 2.4.0
 * PostgreSQL server: 16.3
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.office365.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 6.1.0-18-amd64 (x86_64)

### Weblate deploy checks

```shell
System check identified no issues (1 silenced).
```

**Comment by nijel** [comment] 2024-07-22 11:17
The add-on behaves as intended, it removes blank strings. If you don't want this behavior, don't install it.

There should be no issue with having a blank strings file on Android.

> The "Remove empty strings" addon should not be enabled by default.

It is not enabled by default, there is no add-on enabled in the default configuration.

**Comment by dleidert** [comment] 2024-07-22 11:53
@nijel I'm not arguing that the add-on works as intended. However, this plugin has neither been enabled site-wide nor for the project nor via compose file. However, when I create a new component, it is active. I have this behavior on two different instances. So it is enabled by default, I just don't know by what. Please check this yourself. I can also provide you with access to an instance.

IMHO, it also doesn't make sense to act on new translations because they will always only contain empty strings, thus leading to an empty file. Of course, that is just my opinion.

**Comment by nijel** [comment] 2024-07-24 08:49
Sorry for missing that, indeed the add-on is automatically turned on for Android because the blank strings have undesired effects in Android, see #7248. Does it behave differently for you?

**Comment by dleidert** [comment] 2024-07-24 12:40
Hm, no, I have not yet observed that behavior, but this is also the first Android project on that instance. So, there isn't much experience I can rely on.

For me, the main issue is, that when I add a new language, weblate creates a copy of the main file which includes all keys, but the translations are of course empty (but not as in #7248; instead like this `<string name="key"></string>`). This can be seen [here](https://github.com/dleidert/weblate.bug-android-strings/commit/05ce22fdaddff1a7ab49921c6bc1e3368ed55bf1). And then the plugin swoops in immediately and removes all empty translation, thus removing all keys, leaving just a completely empty file, seen [here](https://github.com/dleidert/weblate.bug-android-strings/commit/bc80519ff1d03442ad615a0e38a56babbeda5c78). So the plugin also acts on every new language file created, removing all keys from that file. That cannot be the desired effect.

**Comment by dleidert** [comment] 2024-07-24 12:42
Would it make sense if the plugin only acted on empty elements like that: `<string name="key"/>`, instead of `<string name="key"></string>` as well?

**Comment by nijel** [comment] 2024-08-01 10:27
`<string name="key"/>` and `<string name="key"></string>` are equal from XML view, I doubt Android treats them differently.

The desired effect is not to have empty strings in Android because these are invalid (at least that was described in https://github.com/WeblateOrg/weblate/issues/7248). If this is no longer true (or was never true), the add-on can be removed from the file format. But still, the add-on itself behaves as expected.

Furthermore, you don't actually need a template file for new translations in Android, Weblate will start with a blank file if it is not specified.

**Comment by dleidert** [comment] 2024-08-01 11:44
Hi. It appears that there might be some kind of misunderstanding going on. When I created the project and component, the created `values-de/strings.xml` file was emptied and the translation status was shown as 100% translated without anything to translate. I wasn't presented any keys to translate. Thus, I had an empty file with nothing to translate. And that didn't make any sense. But, your last sentence sounds like that Weblate should have presented the keys to translate from the base file, even if they are not in the translated strings.xml file or even if that translated strings.xml file is empty, thus adding only the translated keys to the translated strings.xml file. Is that what you are saying? I'll happily check again, then. That workflow would work, but that wasn't what I observed.

**Comment by kevinpapst** [comment] 2024-08-02 12:50
I created a bug a bit earlier with likely the same finding: https://github.com/WeblateOrg/weblate/issues/12180

This behavior is definitely new and broken, because the [newly created component](https://hosted.weblate.org/projects/kimai/messages/ca/) has no translation keys and therefor can't be translated.

**Comment by nijel** [comment] 2024-08-02 18:32
Ah, I thought that the issue was *blank file* and I didn't notice that there are no strings to translate in Weblate as well.

Does forcing reload in repository management resolve the issue for you?

**Comment by nijel** [comment] 2024-08-02 19:08
https://github.com/WeblateOrg/weblate/pull/12186 should fix this (in case forced rescan works for you as workaround).

**Comment by kevinpapst** [comment] 2024-08-02 19:18
> Ah, I thought that the issue was blank file and I didn't notice that there are no strings to translate in Weblate as well.

I'd say there are two issues: 
- no translations in Weblate (you already tackled that)
- the [pushed files](https://github.com/kimai/kimai/pull/5007/files) (in my case XLIFF) did not look like that for new languages in the past. In my opinion the keys should either be skipped or the default translation should be added, but this (missing `<target>`) leads to errors:
```
 <trans-unit id="QCf1FUG" resname="reload">
        <source>reload</source>
      </trans-unit>
```

> Does forcing rescan in repository management resolve the issue for you?

What does that mean? If you mean forced reload, I can't currently merge for testing, because tests are broken due to the current contents of the XLIFF files.

I am very certain that this behavior is new. Is there a configuration setting or a plugin to prevent XLIFF files like that?

**Comment by nijel** [comment] 2024-08-02 19:46
I'm not really aware of any recent changes that could cause this. 

The blank translations in Weblate is a race-condition, so it's merely luck whether you hit that or not (and you have to use add-ons to actually hit it).

I don't recall any related change in XLIFF handling recently. The empty target tags are removed since 42d052c14c7 which is three years old.

**Comment by kevinpapst** [comment] 2024-08-02 19:52
I just merged and this PR was pushed: 
https://github.com/kimai/kimai/pull/5010/files 
All new files are now empty `Updated by "Remove blank strings" hook in Weblate.` - that is the file layout I expected initially.

After merging this one, still no translations in weblate.

Then I clicked "Rescan" and translations are now visible:
https://hosted.weblate.org/projects/kimai/messages/ca/

Hooray 🎉

**Closed** 2024-08-02 21:45 UTC
Labels: bug

**Comment by dleidert** [comment] 2024-08-06 09:48
@nijel Thanks!
