### ISSUE TITLE
string edit logged but not persisted

### ISSUE THREAD

**Issue by ce-4** [WeblateOrg/weblate#3717] opened 2020-04-11 11:10 UTC
Hi Michal,

We had an issue where the entry "Ghost bike" needed two edit/saves to persist, history shows that two recent and identical edits were made to change the german translation from "Geisterfahrrad" to "Ghost bike". The earlier edit from two days ago is logged but didnt get persisted and was again edited to fix it today (which worked).

Not sure how to reproduce this but I'm filing this anyway because @critdroid recalled that it happened to him with other strings as well recently.

https://hosted.weblate.org/translate/osmand/phrases/de/?checksum=c1c44d3d2e8b6bf4#history

Thank you!

Cheers,
Chris

**Comment by nijel** [comment] 2020-04-11 11:37
That looks like https://github.com/translate/translate/pull/3951, https://github.com/WeblateOrg/weblate/issues/3699 ... the fix was deployed to Hosted Weblate two days ago.

**Comment by nijel** [comment] 2020-04-11 11:38
Duplicate of #3699

**Closed by nijel** 2020-04-11 11:38 UTC
Labels: duplicate

**Comment by ce-4** [comment] 2020-04-11 11:48
Ok thanks, wasnt aware that it was the same underlying issue!

**Comment by nijel** [comment] 2020-04-11 11:55
I think it is, but I might be wrong as well.
