### ISSUE TITLE
Component discovery has stopped discovering components

### ISSUE THREAD

**Issue by nikclayton** [WeblateOrg/weblate#11946] opened 2024-06-26 14:05 UTC
### Describe the issue

I have component discovery configured (https://hosted.weblate.org/addons/pachli/fastlane-metadata/) and until recently it would correctly discover new components.

For example, after submitting https://github.com/pachli/pachli-android/commit/e4a065ca9fa3c6fdc05160090050f0d25de3b3c8, which adds a new file `core/data/src/main/res/values/strings.xml`, the addon picked that up, and created a new component called "Core/Data : Main" (https://hosted.weblate.org/projects/pachli/coredata-main/).

The addon then created this PR -- https://github.com/pachli/pachli-android/pull/737/files -- to populate the `values-*` directories with empty resource files.

So this worked up to at least June 13.

On June 17 I merged https://github.com/pachli/pachli-android/pull/734 which created `feature/suggestions/src/main/res/values/strings.xml`.

The addon should have noticed this, and created a component "Feature/Suggestions : Main", and then sent a PR to populate the `value-*` directories (the addon has created "Feature/..." components before, see https://hosted.weblate.org/projects/pachli/ for examples.

It hasn't -- the component "Feature/Suggestions : Main" has not been created, and a PR to populate the `value-*` directories has not been created.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

N/A -- it's not an intermittent reproducible issue, it's the state of the project now.

### How do you run Weblate?

weblate.org service

### Additional context

Viewing the addon logs (https://hosted.weblate.org/addon/14753/logs/) didn't show any problems.

I tried reconfiguring the addon to see if that would prompt it to recheck.

Opening https://hosted.weblate.org/addons/pachli/fastlane-metadata/, then clicking "Configure" for the addon opens https://hosted.weblate.org/addon/14753/ showing the addon configuration.

If I make no changes and click "Save" I am prompted to "Please review and confirm the matched components." where it shows the  components it's already created.  Ticking "I confirm the above matches look correct" and clicking "Save" again succeeds, but does not change the state -- the "Features/Suggestions : Main" component is not created.

https://hosted.weblate.org/projects/pachli/#repository shows that Weblate has an up to date copy of the repository (last commit 18 hours ago). I tried resetting the repository through https://hosted.weblate.org/projects/pachli/#repository but that didn't appear to have an effect.

**Comment by nijel** [comment] 2024-06-26 14:14
The discovery is based on the translation files and there are none. If you would create for example `feature/suggestions/src/main/res/values-cs/strings.xml`, the discovery would work.

This is almost what is described in https://github.com/WeblateOrg/weblate/issues/2084.

The problem here is that there is no pattern to look for the monolingual base - its name is currently built from the translation name.

Duplicate of #2084

**Closed by nijel** 2024-06-26 14:14 UTC
Labels: duplicate
