### ISSUE TITLE
Reveal hidden characters

### ISSUE THREAD

**Issue by iriman** [WeblateOrg/weblate#3417] opened 2020-01-23 17:59 UTC
**Is your feature request related to a problem? Please describe.**
Some characters are invisible and could have unwanted effects on the final translation. like directional characters such as LRE, RLE, etc.

**Describe the solution you'd like**
Making them visible, e.g. by name: `<LRE>`, `<RLE>`, etc.

**Additional context**
I'm specially speacking about these highlighted characters that sometimes need to be inserted in translations:
![image](https://user-images.githubusercontent.com/8467903/73009428-d1099680-3e25-11ea-973e-e067dd63c09e.png)

**Comment by nijel** [comment] 2020-01-28 13:54
Duplicate of #1930

**Closed by nijel** 2020-01-28 13:54 UTC
Labels: enhancement, duplicate
