### ISSUE TITLE
(bug) Using an automatic suggestion adds a "blank" text

### ISSUE THREAD

**Issue by ldmpub** [WeblateOrg/weblate#8110] opened 2022-09-13 06:32 UTC
### Describe the issue

**When a string has to be translated and I use an "automatic suggestion" it adds a blank text.**

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

See video attached: 
- Go to an empty translation
- Choose one "automatic suggestion"
- **Behavior: it looks like no text is added to the translation area** ; in fact the text is added but with white font on white background 😮
=> Selecting the "invisible text" or removing a character makes the text appear ...

https://user-images.githubusercontent.com/1452146/189826072-0454b311-b960-443a-9bfc-6adfec9cd6ae.mp4

### Expected behavior

**Expected behavior: add and display the added suggestion in black font ...**

### Screenshots

see video above.

### How do you run Weblate?

weblate.org service

### Weblate versions

Seen on Weblate 4.14.1-dev

### Additional context

Fails on several browsers (Firefox, Chrome) and devices (PC running Windows, tablet and smartphone running Android).

**Comment by nijel** [comment] 2022-09-14 06:59
Duplicate of #8100

**Closed by nijel** 2022-09-14 06:59 UTC
Labels: bug, duplicate

**Comment by ldmpub** [comment] 2022-09-14 08:26
Thanks 👍.

Yes, it's a duplicate (I think I have not searched issues containing the word "white" 🙃).
