### ISSUE TITLE
Improve docu about "Fetching updated translations from Weblate"

### ISSUE THREAD

**Issue by buhtz** [WeblateOrg/weblate#9189] opened 2023-05-01 14:28 UTC
### Describe the issue

This is about

https://docs.weblate.org/en/latest/devel/integration.html#fetching-updated-translations-from-weblate

The text doesn't help.

 - Explain the term "underlying Git repository" and give the correct URL for it.
 - Remove the misleading paragraph beginning with "This can be automated..." because the whole section is about "manual fetching" and not about "automation".

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

see above

### How do you run Weblate?

Other

**Comment by buhtz** [comment] 2023-05-02 10:07
I beg for the possibility to block that damn @github-actions fake user.

**Comment by comradekingu** [comment] 2023-05-13 09:44
"Underlying …" could link to https://docs.weblate.org/en/latest/admin/continuous.html ?
Where does the confusion about automation arise?
It tries to help by stating it can be automated, but isn't clear that the steps are otherwise manual?

"VCS" should also be a link.
It is possible to help fix issues by submitting a PR :)

**Comment by buhtz** [comment] 2023-05-13 10:32
> "Underlying …" could link to https://docs.weblate.org/en/latest/admin/continuous.html ?

That link is interesting. Point 2 the most. How can I automate point 2? Can I somehow with weblate?
Following the [link](https://docs.weblate.org/en/latest/faq.html#translations-update) in point 2 just brings to to an explanation that I have to do this manually.

What I'm talking about is calls to `xgettext` ans `msgmerge` and things like that. Can Weblate do this for me?

**Comment by nijel** [comment] 2023-05-15 08:23
The problem is that you typically do not just run `xgettext` and `msgmerge`, but it's wrapped by some other tooling ([intltool](https://freedesktop.org/wiki/Software/intltool/), [Django's `makemessages`](https://docs.djangoproject.com/en/4.2/ref/django-admin/#django-admin-makemessages), or completely [custom solutions](https://github.com/LibreTranslate/LibreTranslate/blob/main/scripts/update_locales.py)). So, this ends up being a generic service for executing untrusted code. There are a bunch of existing CI services available, which have already developed a way of doing that securely. Presently, this is out of scope for Weblate.

PS: There is [msgmerge](https://docs.weblate.org/en/latest/admin/addons.html#update-po-files-to-match-pot-msgmerge) add-on in Weblate.

**Comment by buhtz** [comment] 2023-05-15 10:19
I think we still talk around each other. 😄 But this issue isn't about if and how to automate that step.
It is about being clear about it in the docu.

The docu tells me it is automatable.
But behind the link there is no docu about automation but about manual steps.
The docu is full of misleading informations about that topic.

And I don't see a difference between calling xgettext/msgmerg or any other tool.

**Closed** 2023-05-19 08:18 UTC
Labels: documentation, hacktoberfest, help wanted, good first issue
