### ISSUE TITLE
Alt key does not work on login screen in Mac OSX

### ISSUE THREAD

**Issue by Yopli2k** [WeblateOrg/weblate#1691] opened 2017-11-20 07:57 UTC
### Steps to reproduce
1. go to weblate.artextrading.com
2. go to login page (in corner top-right)
3. try to insert @ into user name

### Actual behaviour
When entering the email address, you can not enter the @ character. It seems that the Alt key does not work. Tested with Chrome and Safari on Mac OSX with error. Tested with Chrome and IE in Windows7 and works correctly.

### Server configuration
 * Weblate weblate-2.17-227-g5f6793f
 * Python 2.7.12
 * Django 1.11.7
 * six 1.11.0
 * social-auth-core 1.5.0
 * social-auth-app-django 2.0.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.1
 * lxml 4.1.1
 * django-crispy-forms 1.7.0
 * compressor 2.2
 * djangorestframework 3.7.3
 * pytz 2017.3
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.2.2
 * Mercurial 4.4.1
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment] 2017-11-20 08:04
Duplicate of #1291

**Closed by nijel** 2017-11-20 08:04 UTC

**Comment by nijel** [comment] 2017-11-20 08:05
This has been already reported, unfortunately it's nearly impossible for me to debug without OSX as I even can't reproduce this on remotely accessible hardware...
