### ISSUE TITLE
Search for a string in 'flags'

### ISSUE THREAD

**Issue by BernhardBaeumle** [WeblateOrg/weblate#10310] opened 2023-10-31 09:19 UTC
### Describe the problem

I set some flags to check if the text fits the text box:
So I do a 'Bulk edit' with "note:Button" in the search field and I fill 'Translation flags to add' with "max-size:110:2,font-family:NotoSans,font-size:22".
That's really great! Now I can search for "check:max-size" and I see all the texts that need to be shortened :-)
So far this works fine!

**Now, to clean older "max-size" settings I would like to search for flags with "max-size" or even search for flags with "font-family" not equals to "NotoSans".

I expected the search string "flags:searchstring" to do what I want but it results in "Invalid search query!" (Error in parameter q: Could not parse query string: Unsupported field: flags)**

### Describe the solution you'd like

Using the search string "flags:searchstring" should result in all strings that have "searchstring" in the "Flags" field!

### Describe alternatives you've considered

So far, to make sure my flags-settings are all correct (no old ones) I search for "has:flags", remember a few flags I see, then I do a 'Bulk edit' with "has:flags" and 'Translation flags to remove' with some of the flags I have seen.
I repeat until "has:flags" returns no strings anymore. Now that all flags are cleared, I have to add the flags that I want with a series of Bulk edits.
This is my work-around how to get rid of old flags :-(

### Additional context

Note that "flags:searchstring" would close the gap and be consistent with the other queries:

What I want >> What I enter
Find strings with Suggestions >> has:suggestion
Find strings with Comments >> has:comment
Find strings with Explanations >> has:explanation
Find strings with Flags >> has:flags - This works fine!
Search for a string in Suggestions >> suggestion:"a string"
Search for a string in Comments >> comment:"a string"
Search for a string in Explanation >> explanation:"a string"
Search for a string in Flags >> flags:"a string" - This does not work!

**Comment by nijel** [comment] 2023-11-02 19:10
Duplicate of #10204

**Closed by nijel** 2023-11-02 19:10 UTC
Labels: enhancement, duplicate
