### ISSUE TITLE
Adding new translation string fails silently

### ISSUE THREAD

**Issue by nebulade** [WeblateOrg/weblate#5160] opened 2021-01-08 09:06 UTC
**Describe the issue**

At some point after adding over 1000 translation strings to our project, eventually we were not able to add new ones. From the webui side, I can add new strings and submit that form, however after the UI shows success, the key was actually not created and also I can see it in the local git repo that the key is not in the translation file.

We use json format and translating existing strings in other languages still works as expected.

Unfortunately there are no errors shown, not even when loglevel is set to DEBUG and debug set to True:

```
10:00:07 - [2021-01-08 09:00:07,733: INFO/255] cloudron/dashboard: skipped push: upstream not configured
10:00:11 - [2021-01-08 09:00:11,117: DEBUG/255] cloudron/dashboard/en: running pre_commit addon: weblate.cleanup.generic
10:00:11 - [2021-01-08 09:00:11,118: INFO/MainProcess] Received task: weblate.accounts.tasks.notify_change[8bc95c3b-aab7-49a8-ad0b-267d6fa17946]  
10:00:11 - [2021-01-08 09:00:11,183: INFO/255] cloudron/dashboard/en: committed ['/app/data/weblate/data/vcs/cloudron/dashboard/en.json'] as Johannes Zellner <johannes@cloudron.io>
10:00:11 - [2021-01-08 09:00:11,195: INFO/MainProcess] Received task: weblate.accounts.tasks.notify_change[ac2a58fe-bc08-4952-b7b2-dc0b6b72673e]  
10:00:12 - [2021-01-08 09:00:12,779: INFO/255] cloudron/dashboard: checking en.json (en) [1/9]
10:00:13 - [2021-01-08 09:00:13,011: INFO/255] cloudron/dashboard: checking de.json (de) [2/9]
10:00:13 - [2021-01-08 09:00:13,021: INFO/255] cloudron/dashboard: checking fr.json (fr) [3/9]
10:00:13 - [2021-01-08 09:00:13,032: INFO/255] cloudron/dashboard: checking it.json (it) [4/9]
10:00:13 - [2021-01-08 09:00:13,044: INFO/255] cloudron/dashboard: checking ja.json (ja) [5/9]
10:00:13 - [2021-01-08 09:00:13,052: INFO/255] cloudron/dashboard: checking nl.json (nl) [6/9]
10:00:13 - [2021-01-08 09:00:13,061: INFO/255] cloudron/dashboard: checking pl.json (pl) [7/9]
10:00:13 - [2021-01-08 09:00:13,071: INFO/255] cloudron/dashboard: checking vi.json (vi) [8/9]
10:00:13 - [2021-01-08 09:00:13,080: INFO/255] cloudron/dashboard: checking zh_Hans.json (zh_Hans) [9/9]
10:00:13 - [2021-01-08 09:00:13,090: INFO/255] cloudron/dashboard: checking triggered alerts
10:00:13 - [2021-01-08 09:00:13,099: INFO/255] cloudron/dashboard: updating completed
10:00:13 - [pid: 255|app: 0|req: 8/32] 172.18.0.1 () {62 vars in 1370 bytes} [Fri Jan  8 09:00:07 2021] POST /new-unit/cloudron/dashboard/en/ => generated 0 bytes in 5543 msecs (HTTP/1.1 302) 9 headers in 461 bytes (1 switches on core 0)
10:00:13 - 172.18.0.1 - - [08/Jan/2021:09:00:13 +0000] "POST /new-unit/cloudron/dashboard/en/ HTTP/1.1" 302 5 "https://translate.cloudron.io/" "Mozilla/5.0 (X11; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0"
```

I am a bit of ideas now how to debug this further. Also since I am no django expert. Any help would be much appreciated.

**Server configuration and status**

This is running Weblate 4.4 on Cloudron.

**Comment by nijel** [comment] 2021-01-08 12:44
The English file was committed in the above log, it doesn't contain the new string? What is your component configuration?

**Comment by nebulade** [comment] 2021-01-08 16:59
Correct it is not actually committed to the git repo nor added to the `en.json` We can however see commits to other languages just fine. Maybe if you can point me to the parts in the code, I can see if adding some more debug messages reveals something?

**Comment by nebulade** [comment] 2021-01-08 17:11
I may have found some other clue. I updated some strings for english and in weblate itself they do show as updated, however they are also not commited to the repo nor put into the `en.json`. Not sure if this only happens in some async task which may take some time, but for other languages I can see that essentially immediately.

**Comment by nijel** [comment] 2021-01-08 19:08
What is your component configuration? (Especially filenames, masks and formats)

**Comment by nebulade** [comment] 2021-01-10 09:25
Hi, is the information in the following screenshot helping?

![image](https://user-images.githubusercontent.com/646768/104119185-1d4b3080-532e-11eb-8722-fa92a555428f.png)

Also please note that we have not set any VCS remote repository, so the skipped git push is probably to be expected.

**Comment by nijel** [comment] 2021-01-10 11:04
I don't see any issue with that. Are you using some structure inside of the JSON files? What does typical key look like? I recall there were some related fixes in the translate-toolkit library.

**Comment by nebulade** [comment] 2021-01-10 12:50
The original translation file for english is public, so https://translate.cloudron.io/download/cloudron/dashboard/en/ 

But I think that gave a good clue, since there appears to be some key issue at least once. There are those two toplevel properties, which appear wrong (they should have been merged I think):
```
"lang.ja": "Japanese",
"lang": {
        "en": "English",
        "de": "German",
        "fr": "French",
        "it": "Italian",
        "nl": "Dutch"
}
```

Could this be causing the problem?

**Comment by nijel** [comment] 2021-01-10 18:11
Yes, that can be the issue. You might want to switch to "JSON nested structure file", see https://docs.weblate.org/en/latest/formats.html#json-files

**Comment by nebulade** [comment] 2021-01-10 19:50
Changing the file type didn't fix the issue. But in fact I do wonder why the exported json files always looked like what the nested one should look like. Either way now that I have read a bit more of the code, I think that exported json file into that local git repo may not be the root cause. Since those are generated fine for other files and, please correct me if wrong, those are just the outputted files, while the actual translation key is in fact not put into the dataset at all in the first place.

**Comment by nijel** [comment] 2021-01-10 20:43
I don't know your workflow, so it's hard to guess. How do you add strings? In Weblate or uploading new file? But the mixed keys (nested/non nested) might be related issue...

**Comment by nebulade** [comment] 2021-01-10 20:47
We use the weblate UI for adding new translation strings, I wasn't even aware of some other way.

**Comment by nijel** [comment] 2021-01-11 17:18
Yes, there are - https://docs.weblate.org/en/latest/devel/integration.html#adding-new-strings

But that's not a main topic here. One of the issues is nested/non nested JSON. In current Weblate versions both preserve existing structure, but the major difference is how they handle adding new strings - nested one tries to reconstruct nesting from the key name, while plain JSON uses the key as is without any changes. This is something what has been changed recently (before the existing format was not preserved in some cases), so it might be the cause for different behavior over time - if you upgraded meanwhile.

Anyway if the adding new string fails, there should be at least log entry indicating the error, but that doesn't seem to be the case here.

Let's try to figure out what is broken:

- Will changed strings show up in the file? (You might have to force the commit because it doesn't happen immediatelly, see https://docs.weblate.org/en/latest/admin/continuous.html#lazy-commits)
- Does adding simple key which is not currently present work?

**Comment by nebulade** [comment] 2021-01-12 10:11
So the changes for new keys never show up in the file in the vcs folder/git repo. Also adding simple keys, in this case I tried some without a dot for structure, does not work.

I have cloned the app for further debugging and testing into a test Cloudron. Let me know if you want direct access to the instance, if that avoids much back and forth here.

**Comment by nijel** [comment] 2021-01-12 14:18
I've identified the issue - there is caching issue when cleanup addon is installed and it removes the newly added string. Working on a fix.

**Closed** 2021-01-12 14:23 UTC
Labels: bug

**Comment by nebulade** [comment] 2021-01-12 14:49
Great news. Thanks a lot for fixing this. We will verify the fix on our production instance then, when a new release is out.

**Comment by nebulade** [comment] 2021-01-13 09:52
Works great after update :+1:

**Comment by reloxx13** [comment] 2021-01-13 15:18
Heya,
i got the same issue, new keys dont get added.
now i updated to 4.4.1 (was on 4.4) but the new string still did get not in weblate.

its a pot and po file, updated by git. the pot file in data/vcs is getting updated and has the new stirng.
the po file does not have it. the addon for msgmerge is installed but seems to not work.
@nijel could this also relate to this caching issue?

ADDON:
Update PO files to match POT (msgmerge) 

Configure addon
OFF Keep previous msgids of translated strings
OFF Remove locations of translated strings
OFF Use fuzzy matching

**Comment by nijel** [comment] 2021-01-13 15:24
@reloxx13 that's completely different topic and is covered by FAQ: https://docs.weblate.org/en/latest/faq.html#does-weblate-update-translation-files-besides-translations

**Comment by reloxx13** [comment] 2021-01-13 15:27
Its not about the missing strings in the po file, the new strings from teh POT file ae NOT showing up in weblate as new strings.
