### ISSUE TITLE
regression: cannot save changes in team admin

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#8793] opened 2023-02-13 10:09 UTC
### Describe the issue

The "Save" button in Admin > Team page is broken so it's not possible anymore to save any change related to a team of users. 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to the Administration, click on "Team" tab and on the pencil link of a team to edit it (e.g. "Users" team)
2. Make a change (e.g. add a role)
3. Click on "Save"
4. Wait: you'll see that nothing happens

### Expected behavior

The changes are properly saved.

### How do you run Weblate?

PyPI module

### Weblate versions

 * Weblate: 4.15.1
 * Django: 3.2.4
 * siphashc: 1.3
 * translate-toolkit: 3.8.3
 * lxml: 4.9.2
 * Pillow: 9.1.0
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 4.3.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.1
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.9.0
 * rapidfuzz: 2.13.7
 * openpyxl: 3.0.5
 * celery: 5.1.0
 * kombu: 5.1.0
 * translation-finder: 2.15
 * weblate-language-data: 2023.1
 * html2text: 2020.1.16
 * pycairo: 1.19.1
 * pygobject: 3.38.0
 * diff-match-patch: 20200713
 * requests: 2.27.1
 * django-redis: 4.12.1
 * hiredis: 1.0.1
 * sentry_sdk: 1.14.0
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.8
 * borgbackup: 1.1.13
 * pyparsing: 3.0.8
 * pyahocorasick: 1.4.2
 * python-redis-lock: 4.0.0
 * charset-normalizer: 2.0.12
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2-binary: 2.8.6
 * phply: 1.2.6
 * ruamel.yaml: 0.16.12
 * tesserocr: 2.5.2
 * boto3: 1.22.10
 * zeep: 4.1.0
 * aeidon: 1.11
 * iniparse: 0.5
 * Mercurial: 6.1.2
 * git-review: 2.3.1
 * Redis server: 5.0.14
 * PostgreSQL server: 11.18
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.19.0-20-amd64 (x86_64)

### Additional context

There's no error in the JS console and I can see in the network console that no request is sent when clicking on "Save". 
A brief look on the html shows that apparently the "Save" button is a submit button, but it's outside the form so it's probably the issue here: 
![image](https://user-images.githubusercontent.com/1478232/218429591-e3f02f1a-0a83-4fc0-9b44-c0e9b0948793.png)

[Edit: I moved the button in the form from the html inspector and I confirm it's working properly then, so it's a good workaround for now]

**Comment by nijel** [comment] 2023-02-15 14:54
Duplicate of #8605

**Closed by nijel** 2023-02-15 14:54 UTC
Labels: bug

**Comment by surli** [comment] 2023-02-15 15:00
Hmmm are you sure it's a duplicate of #8605 AFAICS this one was fixed in 4.15.1 and I actually have this bug in Weblate 4.15.1.

**Comment by nijel** [comment] 2023-02-15 15:05
Good point, I thought it was fixed later (and didn't look at the milestone). Anyway, the editing works for me in 4.16-dev. Can you please check where the form is wrongly closed?

**Comment by surli** [comment] 2023-02-15 15:13
> Can you please check where the form is wrongly closed?

I have this html:
![image](https://user-images.githubusercontent.com/1478232/219067933-9cb4e058-94cd-4c2d-9401-f5840b69a536.png)

**Comment by nijel** [comment] 2023-02-16 10:56
The code has it the other way:

https://github.com/WeblateOrg/weblate/blob/20a5696c39bcdaa692e099bc93ad84af9a66e6d5/weblate/templates/auth/team.html#L139-L142
