### ISSUE TITLE
Missing "Add Languages" option

### ISSUE THREAD

**Issue by arbaes** [WeblateOrg/weblate#12856] opened 2024-10-24 09:02 UTC
### Describe the issue

It seems I can no longer add new languages to an existing project, the "+" button is missing in the language tab and I can't figure out why. I stumbled upon #1722 but it seems pretty outdated

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Go to a Project > Language Tab
2. Add language option is missing

### Expected behavior

I should be able to add a new language

### Screenshots

![image](https://github.com/user-attachments/assets/695ba49f-613b-4be4-966f-6f798aa57319)

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 5.8.1
 * Django: 5.1.2
 * siphashc: 2.5
 * translate-toolkit: 3.14.1
 * lxml: 5.3.0
 * pillow: 10.4.0
 * nh3: 0.2.18
 * python-dateutil: 2.9.0.post0
 * social-auth-core: 4.5.4
 * social-auth-app-django: 5.4.2
 * django-crispy-forms: 2.3
 * oauthlib: 3.2.2
 * django-compressor: 4.5.1
 * djangorestframework: 3.15.2
 * django-filter: 24.3
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.16.1
 * RapidFuzz: 3.10.0
 * openpyxl: 3.1.5
 * celery: 5.4.0
 * django-celery-beat: 2.7.0
 * kombu: 5.4.2
 * translation-finder: 2.16
 * weblate-language-data: 2024.9
 * html2text: 2024.2.26
 * pycairo: 1.27.0
 * PyGObject: 3.50.0
 * diff-match-patch: 20230430
 * requests: 2.32.3
 * django-redis: 5.4.0
 * hiredis: 3.0.0
 * sentry-sdk: 2.17.0
 * Cython: 3.0.11
 * mistletoe: 1.4.0
 * GitPython: 3.1.43
 * borgbackup: 1.4.0
 * pyparsing: 3.2.0
 * ahocorasick_rs: 0.22.1
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.4.0
 * cyrtranslit: 1.1.1
 * drf-spectacular: 0.27.2
 * Python: 3.12.7
 * Git: 2.39.5
 * psycopg: 3.2.3
 * psycopg-binary: 3.2.3
 * phply: 1.2.6
 * ruamel.yaml: 0.18.6
 * tesserocr: 2.7.1
 * boto3: 1.35.45
 * aeidon: 1.15
 * iniparse: 0.5
 * mysqlclient: 2.2.5
 * google-cloud-translate: 3.16.0
 * openai: 1.52.0
 * Mercurial: 6.8.1
 * git-svn: 2.39.5
 * git-review: 2.4.0
 * PostgreSQL server: 16.4
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp-relay.sendinblue.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.4.0-1113-kvm (x86_64)

### Weblate deploy checks

```shell
System check identified some issues:

INFOS:
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-5.8.1/admin/backup.html

System check identified 1 issue (11 silenced).
```

### Additional context

For some reasons, it's actually possible to add new languages to the glossary

**Comment by arbaes** [comment] 2024-10-24 10:14
Quick Update, I noticed it's actually possible only on components, is there no way to add it for the whole project anymore ?

**Comment by nijel** [comment] 2024-10-24 10:56
Duplicate of #6094

**Comment by nijel** [comment] 2024-10-24 10:57
It was actually never implemented.

**Closed by nijel** 2024-10-24 10:56 UTC
Labels: enhancement, duplicate

**Comment by arbaes** [comment] 2024-10-24 12:46
My memory playing tricks on me again, thanks for the answer
