### ISSUE TITLE
Default A-Z sort for component list

### ISSUE THREAD

**Issue by endervad** [WeblateOrg/weblate#7755] opened 2022-06-08 14:17 UTC
### Describe the problem

Currently if you go into any component list, it will be sorted seemingly randomly. Usually though you'd probably want it to be sorted alphabetically.

### Describe the solution you'd like

Component list should be sorted by component name by default.

### Describe alternatives you've considered

Theoretically this could also be a separate setting in `/accounts/profile/#preferences`, something like:
Component list - Default sorting order: (Component Name, Translated, Untranslated, Suggestions, etc.)

**Comment by nijel** [comment] 2022-06-09 08:20
It should be a sortable list, same as listing projects or components.

**Comment by pranathi000** [comment] 2022-06-13 13:07
I request you to assign this issue to me. 
As a beginner i will definately work on it to produce a worthful outcome.
eager to work !

**Comment by nijel** [comment] 2022-06-13 14:20
Thanks, don't hesitate to ask if anything is unclear. All of the logic (listing, sorting) is already present, it just needs to be applied on this view.

**Comment by pranathi000** [comment] 2022-06-15 12:55
Thankyou for doing this great help sir. I am actually pursuing (my higher
schooling*) in an integrated University. This is the first step I am taking
in contributing open source.

In the case I have any doubts or queries regarding this issue, I request
you to help me so that I can contribute much in developing weblate org.

I will try my best to clear it soon.
Thanking you !

**Comment by pranathi000** [comment] 2022-06-19 09:56
Hey Nijel, I was wondering if you could give me a lil clarification. So, based on my understanding, the rows listed in the components tab in [this](https://hosted.weblate.org/projects/3dslicertestversioncontrol/#components) website must be sorted alphabetically as opposed to the random sort that in place now. Am I right?

**Comment by nijel** [comment] 2022-06-20 08:09
Component lists are not used on Hosted Weblate. You can see it in action here: https://translate.fedoraproject.org/component-list/fedora-34-release/

Related code is here:

https://github.com/WeblateOrg/weblate/blob/12b1090216018c4c0fdf13ec29d47ea21ce62f33/weblate/trans/views/basic.py#L464-L480

**Comment by mohammedpithapur** [comment] 2022-08-10 03:05
Hii where can I see this components part on your website I can't find it.
sorry I am new to open source contribution

**Comment by mohammedpithapur** [comment] 2022-08-10 03:08
ok found it

**Comment by mohammedpithapur** [comment] 2022-08-10 03:23
ok so I am a little lost here I have never done this can someone help me

**Comment by nijel** [comment] 2022-08-10 13:30
This feature is not used much, see for example the Fedora site link I've posted in https://github.com/WeblateOrg/weblate/issues/7755#issuecomment-1160114460

**Comment by John-Poulos** [comment] 2022-09-04 01:14
@nijel Is this worth contributing too if it is not an issue on hosted Weblate? Should this be closed?

**Comment by Akshat-321** [comment] 2022-09-07 19:29
please assign it to me

**Comment by nijel** [comment] 2022-10-25 11:56
@John-Poulos Other installations are using this feature, so it's definitely worth implementing.

@AkshatGoel-321 Thanks for your interesting, the issue is now assigned to you.

**Closed** 2024-07-24 07:06 UTC
Labels: enhancement, hacktoberfest, help wanted, good first issue, ux
