### ISSUE TITLE
Glossary of entries with two words and more.

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#5067] opened 2020-12-18 18:34 UTC
**Describe the bug**

The glossary does not correctly find entries that contain two words. Instead of looking for the entire string, it looks for each word separately.

**Screenshots**

![image](https://user-images.githubusercontent.com/39633242/102647961-f488ae80-4166-11eb-8557-cb0e8684a670.png)
![image](https://user-images.githubusercontent.com/39633242/102648002-04a08e00-4167-11eb-945f-f44927f9d67c.png)

**Comment by nijel** [comment] 2020-12-18 19:15
Duplicate of #2183

**Closed by nijel** 2020-12-18 19:15 UTC
Labels: enhancement, duplicate
