### ISSUE TITLE
Implement spellchecking all translations in a particular language

### ISSUE THREAD

**Issue by Changaco** [WeblateOrg/weblate#977] opened 2016-01-24 10:01 UTC
I don't see a way to do that in the UI, and the only issue I could find that mentions "spell" is #443, but it's about a particular tool that does more than a simple spellcheck.
##

**Comment by Changaco** [comment] 2016-01-24 10:06
To illustrate, what I'm looking for is the Weblate equivalent of `aspell -l $lang -x check "$file"`.

**Comment by Changaco** [comment] 2016-01-24 15:36
Temporary workaround: [an `aspell` wrapper script](https://github.com/Changaco/misc-scripts/#spellcheck) written in python which supports basic spellchecking of `.po` files (requires [Babel](https://pypi.python.org/pypi/Babel)).

**Comment by nijel** [comment] 2016-01-25 15:10
Indeed spell checking is currently not there. I was hoping to have it with #443, but I'd still not sure about pulling Java into the chain just for this...

**Comment by Changaco** [comment] 2016-01-25 15:19
Why pull anything in? Just use whatever is installed on the server: LanguageTool, aspell, or other; and warn the server admin if there isn't any of that, and also if the spellchecker only has a few language packs installed.

**Comment by nijel** [comment] 2016-01-25 15:20
Yes that would be perfect, it just needs to be implemented ;-).

**Comment by Changaco** [comment] 2016-01-25 15:26
I'm afraid I currently don't have the time to implement it myself.

**Comment by nijel** [comment] 2016-01-31 14:24
Probably easiest approach would be to use pyenchant and it's SpellChecker. It has simpl API and uses whatever backend is available on a system.

**Comment by Changaco** [comment] 2019-10-26 09:48
I don't recommend using pyenchant since it adds a dependency to the enchant C library, which is nothing more than a thin wrapper around various spellcheckers. That abstraction layer would be easier to maintain and distribute if written in pure Python.

In another project I ended up using https://pypi.org/project/hunspell/ instead of pyenchant, but Weblate needs a library that provides tokenizers (functions that split a text into words), whereas this hunspell module only provides functions that analyze a single word. pyenchant only includes an English tokenizer.

**Comment by Bachstelze** [comment] 2019-10-26 15:23
We could use [polyglot](https://github.com/aboSamoor/polyglot) that provides tokenization for 165 languages. Hunspell looks great, but I don't know which languages and dictionaries are maintained.

**Comment by nijel** [comment] 2024-07-01 12:15
Duplicate of #443

**Closed by nijel** 2024-07-01 12:15 UTC
Labels: enhancement, undecided, duplicate
