### ISSUE TITLE
Provide a short cut to "TO-DO"

### ISSUE THREAD

**Issue by rhofer** [WeblateOrg/weblate#7232] opened 2022-02-10 09:23 UTC
### Describe the problem

As follow-up to #7227 

The new search flag is great, allowing to look for unresolved comments with explicit mentioning of `@user`.
- Query: `comment:@Username`

Would there be a way to provide this to the current user as a shortcut so that he doesn't need to navigate to Search then manually entering the query?

### Describe the solution you'd like

Examples:

Gitlab provides a short cut to a "ToDo - list" on the top right just aside the user's avatar:

![image](https://user-images.githubusercontent.com/8058166/153375947-6c344333-7f47-454d-a3ad-e557b5809814.png)

Github provides a short cut to a "Notification Center" on the top right just aside the user's avatar:

![image](https://user-images.githubusercontent.com/8058166/153376317-381b4cc5-4243-42db-a9f1-287c794dda62.png)

Would it be possible to introduce in Weblate such a shortcut (by icon) which may provokes the serach page with pre-executed query `comment:@Username`?
- first step: just show Search page with results, as it is today
- next steps: this could be evolved to a notification center later on (if required) also comprising transactional messages ... or whatever Weblate users desire to see there.

**Comment by Geeyun-JY3** [comment] 2022-02-10 10:48
#6569?

**Comment by rhofer** [comment] 2022-02-10 10:53
@Geeyun-JY3 yep is basically the same as #6569. But instead of definen a full notification hub from beginning on, this could be a small first and easily achievable step into the direction of #6569

**Comment by rhofer** [comment] 2022-02-21 05:58
@nijel can we actively decide on this issue and not just letting the stale bot closing it? To me, it is not urgent but just a small step towards #6569 . I'd like to leave it to you to decide whether to go a small step or to close this issue in favor of #6569.

**Comment by nijel** [comment] 2022-02-21 15:16
I don't think it makes sense for any intermediate steps. Having notifications in the UI is the way to go.

Duplicate of #6569

**Closed by nijel** 2022-02-21 15:16 UTC
Labels: enhancement, wontfix, duplicate
