### ISSUE TITLE
Error pulling weblate docker (no matching manifest)

### ISSUE THREAD

**Issue by keunes** [WeblateOrg/weblate#6364] opened 2021-08-02 08:01 UTC
**Describe the issue**

I'm trying to install Weblate via Docker on my Raspberry Pi 4 (with Raspberry Pi OS 10, 23 bit). I've followed the [Docker installation docs](https://docs.weblate.org/en/latest/admin/install/docker.html#).

When trying to start the container with `docker-compose up` I get the following error (after a whole bunch of success messages):
```
latest: Pulling from weblate/weblate
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries
```

Is it supposed to be possible to run Weblate on RPi OS? Might I be doing something wrong? Any pointers are welcome :)

**Comment by nijel** [comment] 2021-08-02 13:10
Duplicate of https://github.com/WeblateOrg/docker/issues/968

**Closed by nijel** 2021-08-02 13:10 UTC
Labels: enhancement, duplicate
