### ISSUE TITLE
Pip can't install weblate 2.17.1 with python 2

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#1759] opened 2017-12-18 07:18 UTC
### Steps to reproduce
1. `virtualenv-2 hop`
2. `source hop/bin/activate`
3. `pip install weblate==2.17.1`

### Actual behaviour
It crashes

### Expected behaviour
It would install without issue

### Server configuration
Please paste the output of command `./manage.py list_versions` over here
Non relevant.

This issue is in "Collecting Django>=1.10 (from weblate==2.17.1)".
What's the impact?

1. Current YunoHost installation is broken: https://github.com/YunoHost-Apps/weblate_ynh/tree/58c98267fa4c3ea5c1ff8fd4c63655a3230a2134
2. I can't run installation tests from previous version (2.17.1) to current version (2.18) to finish the migration script: https://github.com/YunoHost-Apps/weblate_ynh

**Comment by nijel** [comment] 2017-12-18 09:40
The problem is probably that Django 2.0 is out which no longer supports Python 2. The problem is that pip still tries to install that and it crashes. So if you're on Python 2, you need `Django<2.0`.

**Comment by nijel** [comment] 2018-01-12 08:49
Apparently the root cause is that [Django 2.0](https://pypi.python.org/pypi/Django/2.0) did not specify Python 3 requirement (this was fixed in [Django 2.0.1](https://pypi.python.org/pypi/Django/2.0.1)). However still when you do `pip install Django` on Python 2, you will get Django 2.0 which fails with above message...

**Comment by nijel** [comment] 2018-01-12 08:49
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Closed** 2018-01-12 08:49 UTC
Labels: bug

**Comment by Jibec** [comment] 2018-01-17 20:54
Thanks, I used this workaround: https://github.com/YunoHost-Apps/weblate_ynh/blob/master/scripts/install#L203
