### ISSUE TITLE
API: delete user's groups

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#7610] opened 2022-05-07 12:42 UTC
### Describe the problem

Right now API only allows to add groups to user, not remove them.

### Describe the solution you'd like

Either a separate endpoint to delete groups, or extend current implementation to allow to add/set/delete group assosiation.

(Edit: actually, some UI for mass membership change would be nice too)

**Comment by nijel** [comment] 2022-05-10 07:51
Duplicate of #4353

**Closed by nijel** 2022-05-10 07:51 UTC
Labels: enhancement, duplicate
