### ISSUE TITLE
Automatic translations from non-source (non-English) languages

### ISSUE THREAD

**Issue by WofWca** [WeblateOrg/weblate#7712] opened 2022-05-29 09:12 UTC
### Describe the problem

Some languages are more similar to each other than to English (e.g. Slavic languages), and machine translations between them usually produce better results than from English

### Describe the solution you'd like

Add a way to (also) get automatic translations from other, non-source languages.
It could be per-profile, per-language, per-project, per-Weblate instance. Maybe like a graph of similarities - which language is similar to which.
Also if the string has not been translated to any of the similar languages, translating it from some other non-source ones could also be useful. It provides alternative wording to consider. Getting stuck in a local maximum sucks.

### Screenshots

![image](https://user-images.githubusercontent.com/39462442/170860599-a0e85224-fc86-4f16-a11c-38978c91b2df.png)

**Comment by nijel** [comment] 2022-05-30 06:03
Duplicate of #2136

**Closed by nijel** 2022-05-30 06:03 UTC
Labels: enhancement, duplicate
