### ISSUE TITLE
Support previous-untranslated-string in gettext files

### ISSUE THREAD

**Issue by jorrit** [WeblateOrg/weblate#9766] opened 2023-08-17 13:53 UTC
### Describe the problem

I would like to inform translators of the previous version of the source string whenever a unit is marked fuzzy because of a source string change.

Gettext files support this using the `#| ` syntax, as described in https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html.

### Describe the solution you'd like

I would like to suggest a new tab on the translation page named 'Previous source'. It shows the difference between the previous and current source text using the 'diff' viewer that is already used for showing the difference between translations.

In addition, Weblate could use this information to link old and new units between pot file changes:
Right now, when I change the source text of an entry in the pot file and the po files, the history of this new unit does not show the translations of the previous source version.

Weblate could use the `previous-untranslated-string` in the pot file to link the old unit and the new unit so the history remains intact.

### Describe alternatives you've considered

I could add the previous versions to a comment in the pot file, but this wouldn't give the diff view that translators need to see what changed in the source text.

**Comment by nijel** [comment] 2023-08-18 04:44
It is supported and should be shown as Previous source together with a diff.

**Comment by jorrit** [comment] 2023-08-18 07:08
@nijel My apologies ... you're right, thanks a lot for already supporting it!

**Comment by nijel** [comment] 2023-08-18 07:15
Duplicate of #74

**Closed by nijel** 2023-08-18 07:15 UTC
Labels: enhancement, duplicate
