### ISSUE TITLE
Wrong date / time on hosted.weblate.com?

### ISSUE THREAD

**Issue by phw** [WeblateOrg/weblate#1809] opened 2018-01-24 07:43 UTC
I have noticed hosted.weblate.org doing commits dated Nov 2017, e.g. https://github.com/phw/peek/commit/0a710ed0359d9d30010500ec2994771700ac1577

This is definitely no old translation getting merged late, it is a brand new translation (I added the string in question just yesterday to the code).

**Comment by nijel** [comment] 2018-01-24 08:12
This happens only when you complete the translation and you have translated only single string - the problem is that current changes are not yet committed to the database when generating the commit, so it does not see the last change.

Responsible code:

https://github.com/WeblateOrg/weblate/blob/9a6af9a61b401957e38d85311bae886f646227c8/weblate/trans/models/unit.py#L715-L724

**Comment by nijel** [comment] 2018-01-24 08:36
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Closed** 2018-01-24 08:36 UTC
Labels: bug
