### ISSUE TITLE
Mark down input translation issue - Guidance text inside code/code blocks is not translated

### ISSUE THREAD

**Issue by Kavithay123** [WeblateOrg/weblate#10132] opened 2023-10-10 05:41 UTC
### Describe the issue

Guidance text inside the code block content is not translated. Please find below source content and translated content.

Source Content:
```
**Network configuration**

All machines in our scenario are configured to use DNS and all of them have internet access. The initial entry point is nginx.example.com, which in our case can be reached from the internet. Your NGINX might reside behind a load balancer instead. To let the machines interoperate properly, consider the following inbound ports to be opened on your firewall:
    
    -   connections.internal.example.com:
        -   443 from nginx.example.com
        -   443 from cpmaster.internal.example.com
    -   cpmaster.internal.example.com:
        -   30301 from connections.internal.example.com \(Customizer\)
        -   30301 from nginx.example.com \(Customizer\)
        -   30098 from connections.internal.example.com \(Elasticsearch 7 – Connections 7 only\)
        -   30099 from connections.internal.example.com \(OpenSearch – Connections 7 or 8, Elasticsearch 5 – Connections 6.5 only\)
        -   32080 from connections.internal.example.com \(Ingress Controller\)
        -   31810 from connections.internal.example.com \(Microsoft Outlook add-in – Connections 7 only\)
    -   nginx.example.com:
        -   443 from everywhere
        -   80 from everywhere \(in case you plan to redirect to 443 and no load balancer does this job\)
```

Translated content screenshot:
![image](https://github.com/WeblateOrg/weblate/assets/99732456/a8049f81-f6ce-4e85-86de-9c100024ba4c)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to Weblate site, create new project and component
2. Upload the markdown input file (source content is provided in the Issue Description)
3. Translate the input file
4. Notice the guidance text from code block is not translated (provided the screenshot in the Issue Description)

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment] 2023-10-10 11:23
Duplicate of https://github.com/translate/translate/issues/5048

**Closed by nijel** 2023-10-10 11:23 UTC
Labels: enhancement, wontfix, translate-toolkit

**Comment by Kavithay123** [comment] 2023-10-10 11:36
Thanks Michal for your quick response.
