### ISSUE TITLE
automatic fixup for French language breaks asciidoctor xref

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#10833] opened 2024-01-22 08:43 UTC
### Describe the issue

on Fedora Weblate, https://translate.fedoraproject.org/translate/fedora-docs-l10n-fedora-silverblue/nav/fr/?checksum=ea8793ceeb4d44c8 
we have  xref:tips-and-tricks.adoc[Tips and Tricks] to translate

weblate forces a non breaking space before the semicolumn
this might be the same issue as https://github.com/WeblateOrg/weblate/issues/10779

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

translate the string with "xref :tips-and-tricks.adoc[Trucs et astuces]", a non breaking space will be added

### How do you run Weblate?

Other

**Comment by nijel** [comment] 2024-01-22 09:52
Duplicate of #10779

**Closed by nijel** 2024-01-22 09:52 UTC
Labels: bug, duplicate
