### ISSUE TITLE
Layout/navigation for large projects - confusing and overwhelming

### ISSUE THREAD

**Issue by eyalroz** [WeblateOrg/weblate#7356] opened 2022-03-05 20:38 UTC
### Describe the issue

I'm not a direct Weblate user; I occasionally help with translating some strings into Hebrew for LibreOffice, which uses Weblate. So, it's possible what I'm describing is partially that project's fault rather than Weblate. Also, this issue may need to be split into several issues, and I would appreciate your input about that.

Anyway, when I visit this page:

https://translations.documentfoundation.org/languages/he/libo_ui-master/

Issues:

1. I am kind of overwhelmed by the layout. The window is too fully-loaded; and the bars across it are somewhat disorienting. I wonder why they can't be in a column. If I try to change the text size, this doesn't help.
2. I'm shown a huge number of "components", most of which are apparently paths . So, why can't components be hierarchical?
3. I see multiple repeated entries (e.g. "Glossary [LibreOffice UI - master](https://translations.documentfoundation.org/projects/libo_ui-master/glossary/he/) MPL-2.0")
4.  It seems like some of the components for Hebrew actually involve languages other than Hebrew. Again, not sure whether Weblate is to blame or the project.
6. When I hover over a component's name, I don't get a description of what that component means in the project I'm trying to help translate.
7. When I hover over a link icon near a component name, I get that component is linked to _another_ component, which really doesn't look like it should be part of the project. There's no explanation of what being "linked" means or why the two are linked.

### I already tried

- I've _not_ read [the documentation](https://docs.weblate.org/), because I should not need to, to be met with an intelligible UI.
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Just visit https://translations.documentfoundation.org/languages/he/libo_ui-master/

### Expected behavior

N/A

### How do you run Weblate?

Other

### Weblate versions

4.8.1

**Comment by nijel** [comment] 2022-03-06 09:55
Duplicate of #263

**Closed by nijel** 2022-03-06 09:55 UTC
Labels: enhancement, duplicate

**Comment by eyalroz** [comment] 2022-03-06 10:08
@nijel : Do you believe #263 covers all of the issues I've mentioned?

**Comment by nijel** [comment] 2022-03-06 16:03
I think it covers the part Weblate can improve - i introduce way to better structure the projects. Current fixed layout works well for small projects, but does not really scale for LibreOffice or Fedora documentation.
