### ISSUE TITLE
Subscription form broken

### ISSUE THREAD

**Issue by nescim** [WeblateOrg/weblate#1416] opened 2017-03-20 09:56 UTC
### Steps to reproduce
1. navigate to /accounts/profile/#subscriptions (tested on latest Chrome and Firefox browsers on Mac OS X)
2. check any of the checkboxes in the Subscription Settings panel
3. click the save button

### Actual behaviour
The main settings form is submitted as a POST request, omitting all the checkboxes contained in the Subscription Settings panel.

### Expected behaviour
The form should be submitted with all fields included

### Workaround
The bug is caused by the fact that those checkboxes are inside a nested `<form>` element that lays inside the main settings `<form>` element (nested forms are not allowed in HTML).

 * open the browser's inspector.
 * change the inner `<form>`tag containing the checkboxes to a `< div>` tag.
 * submit the form normally.

### Server configuration
 * Weblate 2.11
 * Python 2.7.9
 * Django 1.10.5
 * six 1.10.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * Translate Toolkit 2.0.0
 * Whoosh 2.5.7
 * defusedxml 0.4.1
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.2
 * lxml 3.4.0
 * django-crispy-forms 1.6.1
 * compressor 1.6
 * djangorestframework 3.5.4
 * pytz 2012c
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.11
 * Database backends: django.db.backends.mysql

**Comment by nijel** [comment] 2017-03-20 13:30
Seems to be duplicate of https://github.com/WeblateOrg/weblate/issues/1355 and should be fixed in 2.12.

**Closed by nijel** 2017-03-20 13:30 UTC
