### ISSUE TITLE
Drop-down menu to add new flags to a string is gone in new design

### ISSUE THREAD

**Issue by tariver** [WeblateOrg/weblate#3327] opened 2019-12-20 08:33 UTC
**Is your feature request related to a problem? Please describe.**
Before the redesign there was a very convenient drop-down menu to add flags to a string. It saved both typing and remembering flags / looking them up in documentation.
With the redesign this drop-down menu is gone.

**Describe the solution you'd like**
It would be nice if this drop-down menu was brought back to the screen where you add flags to a string.

**Comment by nijel** [comment] 2019-12-20 09:12
Yes, it's temporarily gone until we have better solution.

Duplicate of #1567

**Closed by nijel** 2019-12-20 09:12 UTC
Labels: bug, duplicate
