### ISSUE TITLE
Add an option to look up terminology by whole phrase and not single words

### ISSUE THREAD

**Issue by Artuvazro** [WeblateOrg/weblate#2828] opened 2019-06-22 10:56 UTC
Terminology search should have an option to look up only whole phrases and not single words. For example, currently, if I have a term that is written like this: "gate of hell", weblate suggests me that term in a sentence like this: "Come to think of it..." Just because there is an "of" in the sentence and that "of" is also present in the term. This floods the terminology window with a lot of terms that are far from being usable in the segment.

Also, terminology could be highlighted in the source segment.

**Comment by nijel** [comment] 2019-06-22 11:31
Duplicate of #2183

**Closed by nijel** 2019-06-22 11:31 UTC
