### ISSUE TITLE
Committed strings missing, had to "Rescan"

### ISSUE THREAD

**Issue by nikclayton** [WeblateOrg/weblate#12201] opened 2024-08-05 20:36 UTC
### Describe the issue

Similar to https://github.com/WeblateOrg/weblate/issues/12112.

- https://github.com/pachli/pachli-android/pull/867 added new strings
- I received reports from translators that the new strings weren't present in Weblate (e.g., https://mastodonsweden.se/@kallekn/112911161961890439)
- I checked https://hosted.weblate.org/projects/pachli/app-main/#repository and verified the "Last remote commit" showed a commit *after* the one that added the new strings
- I opened https://hosted.weblate.org/projects/pachli/app-main/fi/ and verified it showed the Finnish translation as being 100% complete. It's not complete, because the new strings are missing. The page listed 711 strings total, 711 strings translated.
- I clicked "Rescan" on https://hosted.weblate.org/projects/pachli/app-main/#repository and waited for that to complete
- I reloaded the Finnish translation page (https://hosted.weblate.org/projects/pachli/app-main/fi/) and now it's showing 716 strings in total, 711 strings translated. 716 - 711 == 5, which is the 5 new strings that were added in https://github.com/pachli/pachli-android/pull/867

Just like https://github.com/WeblateOrg/weblate/issues/12112 there was no indication I could see in the UI that a rescan was necessary.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

N/A

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment] 2024-08-05 20:58
Any add-ons installed? It might be fixed by https://github.com/WeblateOrg/weblate/pull/12186

**Comment by nijel** [comment] 2024-08-06 05:51
Duplicate of #12106

**Closed by nijel** 2024-08-06 05:51 UTC
Labels: bug, duplicate
