### ISSUE TITLE
Ignore a keyboard acceleration mark('_', '~') for search

### ISSUE THREAD

**Issue by baffclan** [WeblateOrg/weblate#7035] opened 2022-01-02 08:15 UTC
### Describe the problem

If there is a shortcut key in a word, you cannot search for that word.
Ignore a keyboard acceleration mark('_', '~') for search

STR:
1. https://hosted.weblate.org/languages/en/gtkhash/
2. Search "source:hash"

3. "Ha_sh" does not appear in the search results.
https://hosted.weblate.org/translate/gtkhash/translations/en/?checksum=fda0cab97a49ffd3

### Describe the solution you'd like

Search for "source:hash" so that words with acceleration keys such as "Ha_sh" are also included in the search results.

**Comment by nijel** [comment] 2022-01-03 12:23
Duplicate of #1861

**Closed by nijel** 2022-01-03 12:23 UTC
Labels: enhancement, duplicate
