### ISSUE TITLE
inconsistencies between store units with java properties and comments

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#3322] opened 2019-12-19 09:41 UTC
**Describe the bug**
When translating a java properties containing headers, the internal units are inconsistent: the unit for the headers actually contains the data of the second unit. 
This has been reproduced on both Weblate 3.9.1 and current master.

**To Reproduce**
1. Import the [xwiki-commons-job.zip](https://github.com/WeblateOrg/weblate/files/3982785/xwiki-commons-job.zip) as a new component with default proposed configuration
2. Put a breakpoint on https://github.com/WeblateOrg/weblate/blob/master/weblate/trans/models/translation.py#L614
3. Make a new translation and commit it
4. On the breakpoint, check `self.store.all_units[0].unit` and `self.store.all_units[1].unit`: they shouldn't be the same, but they are.

![Capture d’écran_2019-12-19_10-38-06](https://user-images.githubusercontent.com/1478232/71162755-0bdb4600-224c-11ea-9029-414c86c6e04a.png)

I tried to created a dedicated unit test for it, but AFAICS I don't perform the right actions: see https://github.com/surli/weblate/commit/9ac1a452222889cab672c9427e01f9f54bdda985 (the data file is added on the same branch)

**Comment by surli** [comment] 2019-12-19 09:48
I have not been able to properly locate where the bug is: the problem is accessing the `all_units` property in the debugger trigger the code to gather the units and the breakpoints called from internal methods of the debugger are skipped by default. I'll continue to investigate on it.

**Comment by nijel** [comment] 2019-12-19 10:09
Maybe it's related to monolingual units? Try adding the same file as template in https://github.com/surli/weblate/commit/9ac1a452222889cab672c9427e01f9f54bdda985#diff-7528f5a66693be334235bd63f6b6519dR382

**Comment by surli** [comment] 2019-12-19 10:16
You mean to call `storage = self.FORMAT(self.FILE, is_template=True)`?

**Comment by surli** [comment] 2019-12-19 10:18
I still don't reproduce with that, but note that my test already fail on https://github.com/surli/weblate/commit/9ac1a452222889cab672c9427e01f9f54bdda985#diff-7528f5a66693be334235bd63f6b6519dR390 Looks like the comments are not taken into account for unit equality which might be part of the issue I guess.

**Comment by nijel** [comment] 2019-12-19 10:23
Sorry for not being clear: `storage = self.FORMAT(self.FILE, template=self.FORMAT(self.FILE), is_template=True)` (the is_template flag is not really needed for this, but just to be consistent)

**Comment by surli** [comment] 2019-12-19 10:25
Ok so I definitely reproduce with it, committing my change and trying to debug.

**Comment by surli** [comment] 2019-12-19 10:34
So the issue is indeed in all_units: the context of both my comments is `''`, so when calling `self.find_unit_mono(unit.context)`, it returns the second unit, I guess because the index is ordered and `####.` is before `# ---`.

**Comment by surli** [comment] 2019-12-19 10:36
> I guess because the index is ordered and ####. is before # ---.

no actually it's because the index is a dictionary and the first entry for `''` is overridden.

**Comment by nijel** [comment] 2019-12-20 11:02
I think the root cause is that translate-toolkit parses two empty units. I'm not sure what is the best approach here as comments behavior is not really well-defined (see https://github.com/translate/translate/issues/3928).

But what we probably should do in Weblate is to ignore strings with empty ID rather than doing some magic with that. These are not really translatable units anyway.

**Comment by nijel** [comment] 2019-12-20 11:03
PS: https://github.com/nijel/translate/commit/08642ccf7c281b6bac8d16a63ebc44ec450fb38c shows how the comments currently behave in the translate-toolkit. Is this really expected to get three units in this case?

**Comment by surli** [comment] 2019-12-20 11:21
> But what we probably should do in Weblate is to ignore strings with empty ID rather than doing some magic with that. These are not really translatable units anyway.

Actually I found this issue while working on a Weblate extension to support XWiki Formats, and I currently need those units to create the new translations files: I want to have all comments of the original source files. And I don't want to use the template approach described in #3296 because I need to know what units have been translated and what units have not: we comment out the missing translation in our output translations files (see for example: https://github.com/xwiki/xwiki-commons/blob/master/xwiki-commons-core/xwiki-commons-job/src/main/resources/ApplicationResources_ug.properties#L51)

So I guess completely ignoring those strings would make my work more difficult here. 

> PS: nijel/translate@08642cc shows how the comments currently behave in the translate-toolkit. Is this really expected to get three units in this case?

It's questionable to have two separate units for the comments separated by a blank line, but I'm personally fine with it.

**Comment by nijel** [comment] 2019-12-20 12:43
But these are not a translatable units - I see no point in showing them in Weblate.

**Comment by surli** [comment] 2019-12-20 14:00
Just to clarify I'm not talking about showing those units in Weblate UI, just talking about allowing to manipulate them in the storage API.

**Comment by nijel** [comment] 2019-12-21 06:54
They should be IMHO ignored in the Weblate API, they have no use there.

**Comment by nijel** [comment] 2019-12-22 05:25
Maybe you want to use translate-toolkit directly then? What are you actually trying to achieve.

**Comment by surli** [comment] 2019-12-22 11:58
You can check what I did there: https://github.com/surli/weblate/blob/support-xwiki-formats/weblate/formats/xwiki.py#L71-L89
The idea is to get exactly the same comments as in the original source.

**Comment by nijel** [comment] 2020-01-09 12:20
Proposed fix is here https://github.com/translate/translate/pull/3931

**Comment by nijel** [comment] 2020-01-09 12:23
Hit wrong button, this one should be closed in favor of https://github.com/translate/translate/issues/3928

**Closed by nijel** 2020-01-09 12:23 UTC
Labels: bug, translate-toolkit
