### ISSUE TITLE
Allow non-VCS components 

### ISSUE THREAD

**Issue by dragosv** [WeblateOrg/weblate#2340] opened 2018-10-22 21:28 UTC
**Is your feature request related to a problem? Please describe.**
Weblate is dependent on VCS integration. However, the workflow when using something like https://serge.io/ (https://github.com/evernote/serge) is to have Serge communicate with the VCS, extract the strings, push the sources and translations to the Translation Service (Weblate in our scenario), then bring them back and push them into 

**Describe the solution you'd like**
Add None to the VCS list.

**Describe alternatives you've considered**
None

**Additional context**
Serge is capable of a lot of functionality that Weblate does not provide
- A lot more formats supported
- Ability to filter and transform the strings (Ex: only consider for translation some strings)
- Integration with several other Translation services, making migration less of a concern between providers (See  https://github.com/dragosv/serge-plugins)

**Comment by nijel** [comment] 2018-10-23 05:10
Duplicate of #2210

**Closed by nijel** 2018-10-23 05:10 UTC
