### ISSUE TITLE
browse projects: add short descriptions and icons for projects

### ISSUE THREAD

**Issue by WofWca** [WeblateOrg/weblate#8388] opened 2022-11-27 19:53 UTC
### Describe the problem

* [ ] When searching for a new project to translate some people might try using "Browse all projects" `/projects/`, but currently you can only see project names there, which is usually not enough to understand what the project is about.
* [ ] Maybe also add a way to list projects from self-hosted Weblate instances.

Maybe could also pull this info from the project's repos.

### Describe the solution you'd like

Make it possible for project admins to add a short description of their project(s), and maybe add an icon.

### Describe alternatives you've considered

Create a separate website for searching what to translate.

### Screenshots

![image](https://user-images.githubusercontent.com/39462442/204156660-8f2f5b46-e5f4-41a8-8bc4-485a1741ebc8.png)
![image](https://user-images.githubusercontent.com/39462442/204156685-c7d23e20-464c-430c-8d01-49ef23b4f412.png)

### Additional context

Maybe check out GitHub's ["Explore"](https://github.com/explore) and [search](https://github.com/search?q=i18n&type=repositories) pages for inspiration.

**Comment by Geeyun-JY3** [comment] 2022-11-29 05:59
For reference:

- Crowdin allows adding descriptions and images for projects. But the explore page would only show the image.
![image](https://user-images.githubusercontent.com/49396421/204449213-14a57398-31a3-46ae-b754-d57eb7d57f99.png)
- Transifex allows adding icons for projects and the explore page would show the icon.
![image](https://user-images.githubusercontent.com/49396421/204448710-419c2327-ceef-4455-910c-17ccc9d5e2b9.png)

**Comment by nijel** [comment] 2022-11-29 18:55
Duplicate of #3724

**Closed** 2022-11-29 18:56 UTC
Labels: duplicate
