### ISSUE TITLE
Always show string search

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#3742] opened 2020-04-16 16:35 UTC
It should be possible to always show the search, so that it can be readily used.
Regular editor
![bilde](https://user-images.githubusercontent.com/13802408/79481477-155c9b00-7fff-11ea-9de3-c95706445d9a.png)
vs
![bilde](https://user-images.githubusercontent.com/13802408/79481493-1b527c00-7fff-11ea-8e20-f3671dbdfb5b.png)
in Zen
![bilde](https://user-images.githubusercontent.com/13802408/79481511-21e0f380-7fff-11ea-8fb4-3ea93fc8ce46.png)
vs
![bilde](https://user-images.githubusercontent.com/13802408/79481524-25747a80-7fff-11ea-9496-8b9ecb49a247.png)

If not side-by side, then that gray line up top could make way for what is a usable feature.
![bilde](https://user-images.githubusercontent.com/13802408/79482131-e3980400-7fff-11ea-97c1-ae20b01f8836.png)
Maybe it could be the same as the search in other places #2327?

**Comment by nijel** [comment] 2020-04-16 17:42
Duplicate of #3308

**Closed by nijel** 2020-04-16 17:42 UTC
