### ISSUE TITLE
How to safely delete component in an addon script.

### ISSUE THREAD

**Issue by exzhawk** [WeblateOrg/weblate#4398] opened 2020-08-28 15:00 UTC
**Describe the issue**

I'm writing an addon to automatic add/remove components per file changes in git repo. Actually it's a more customized builtin 'Component discovery' addon. When it comes to removing component, it failed and produced logs below.

**To Reproduce**
To remove a components. I'm using 
```python
    def post_update(self, main_component: Component, previous_head):
        for component in main_component.linked_childs:
            if file_not_exists_anymore(component):
                component.delete()
```
, a simplified version of https://github.com/WeblateOrg/weblate/blob/weblate-4.2.1/weblate/trans/discovery.py#L270 

**Expected behavior**
Remove component successfully.

**Screenshots**

**Server configuration and status**

**Weblate deploy checks**

**Exception traceback**

When it runs, log says
```
weblate_1   | celery-main stderr | DEBUG project_id/base_component_id: running post_update addon: MyAddonName
weblate_1   | celery-main stderr | [2020-08-28 19:44:42,276: DEBUG/ForkPoolWorker-1031] project_id/base_component_id: running post_update addon: MyAddonName
weblate_1   | celery-main stderr | WARNING addon error: IntegrityError: update or delete on table "trans_component" violates foreign key constraint "trans_alert_component_id_e9bdfacb_fk_trans_component_id" on table "trans_alert"
weblate_1   | celery-main stderr | DETAIL:  Key (id)=(3093) is still referenced from table "trans_alert".
weblate_1   | celery-main stderr | 
weblate_1   | celery-main stderr | [2020-08-28 19:45:01,081: WARNING/ForkPoolWorker-1031] addon error: IntegrityError: update or delete on table "trans_component" violates foreign key constraint "trans_alert_component_id_e9bdfacb_fk_trans_component_id" on table "trans_alert"
weblate_1   | celery-main stderr | DETAIL:  Key (id)=(3093) is still referenced from table "trans_alert".
weblate_1   | celery-main stderr | 
```
**Additional context**

I then tried to remove those components on web interface and succeeded.

I wonder if there is a way to remove a component safely in an addon script, just like the web interface. Or am I using a wrong deleting method?

Thank you!

**Comment by nijel** [comment] 2020-08-31 08:59
The problem is probably caused by something in the transaction triggering an alert (most likely alert that the translation can not be parsed because of missing file). It's not yet committed to the database, so the delete method doesn't discover it, but the INSERT query is still pending in the current database transaction.

**Closed** 2020-09-20 03:42 UTC
Labels: question, wontfix
