### ISSUE TITLE
Highlighting difference between source and source of proposals in "Machinery" (Translation / Automatic Suggestions)

### ISSUE THREAD

**Issue by ilocit** [WeblateOrg/weblate#4513] opened 2020-09-14 08:55 UTC
Currently the tab "Machinery" (in the future perhaps Automatic Suggestions) lists all fuzzy matches one by one with an indication of % match quality.

It would be super helpful during translation if the difference in source between the source string which is currently being translated and the source string for which a match is proposed were highlighted in some form.

Here is how Pontoon does it:
![image](https://user-images.githubusercontent.com/26718215/93067389-72767e80-f67b-11ea-94a3-95aa97116548.png)

Thanks for considering this.

**Comment by nijel** [comment] 2020-11-16 12:30
Duplicate of #4368

**Closed by nijel** 2020-11-16 12:30 UTC
Labels: enhancement, hacktoberfest, help wanted, good first issue, Area: UX, duplicate
