### ISSUE TITLE
Line spacing in different views is different

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/weblate#2799] opened 2019-06-06 12:29 UTC
- [ ] **Spacing**
In the middle, the line spacing is actually different

![bilde](https://user-images.githubusercontent.com/13802408/59002572-2d766200-8813-11e9-8132-8472541b7a15.png)
[Bigger](https://hosted.weblate.org/languages/nb_NO/guardianproject/#overview)
vs
[smaller](https://hosted.weblate.org/projects/guardianproject/)

**Comment by nijel** [comment] 2019-06-06 14:07
This is caused by buttons in one of the views, in the end related to https://github.com/WeblateOrg/weblate/issues/2802.

**Comment by nijel** [comment] 2019-11-18 13:53
Thank you for your report, the issue you have reported has just been fixed by b24e3d830ecc6756a8659b2c15231a9dfcc7ee4a. 

* In case you see a problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Closed by nijel** 2019-11-18 13:53 UTC
Labels: enhancement, ux
