### ISSUE TITLE
DeepL don't translate Python brace format

### ISSUE THREAD

**Issue by jelv** [WeblateOrg/weblate#2374] opened 2018-11-07 10:28 UTC
**Describe the bug**
DeepL translates the Python brace format text when it can. When you copy DeepL you have to change those words back.  Copy & save is not possible to use even if DeepL gives the best suggestion.

**To Reproduce**
1. Open line with a brace with translatable words like https://hosted.weblate.org/translate/liberapay/core/nl/?checksum=e2b793c5bd36e786 
2. Then look at the DeepL suggestion and see the translated braced words.

**Expected behavior**
Don't translate the braced words.

**Screenshots**
![Hosted Weblate screenshot of Liberapay project line with DeepL suggestion to translate braced words](https://user-images.githubusercontent.com/7106279/48125881-0c02c700-e280-11e8-8279-6b145dcc79ef.png)

**Server configuration and status**
Hosted Weblate.

**Comment by nijel** [comment] 2018-11-07 10:52
The same is true for all machine translation services, they have no knowledge of the markup.

For DeepL, the only supported markup is xml (see https://www.deepl.com/api.html), so there is possibility of converting the text to xml with xml placeholders and converting it back after translation. Maybe similar approach would work for other services as well.

**Comment by nijel** [comment] 2018-11-30 20:36
Duplicate of #1980

**Closed by nijel** 2018-11-30 20:36 UTC
Labels: enhancement, undecided
