### ISSUE TITLE
Multiple Github servers with docker

### ISSUE THREAD

**Issue by tsoslow** [WeblateOrg/weblate#8312] opened 2022-11-05 16:14 UTC
### Describe the problem

Docker allows you to set GITHUB_CREDENTIALS for a a single server by setting WEBLATE_GITHUB_USERNAME, WEBLATE_GITHUB_TOKEN, and WEBLATE_GITHUB_HOST environment variables. But there doesn't seem to be a way to enter a second server.

### Describe the solution you'd like

Allow me to enter a full json text as WEBLATE_GITHUB_CREDENTIALS or provide a way to enter multiple servers WEBLATE_GITHUB_USERNAME_2? Neither approach is particularly pretty, but we need to figure out some way to create Pull Requests on two different GitHub servers.

### Describe alternatives you've considered

I've tried setting WEBLATE_GITHUB_CREDENTIALS and it doesn't appear to do anything.

**Comment by nijel** [comment] 2022-11-05 16:20
Duplicate of #8132

**Closed by nijel** 2022-11-05 16:20 UTC
Labels: enhancement, duplicate
