### ISSUE TITLE
Glossary term Highlighting mangles case of the characters

### ISSUE THREAD

**Issue by Fat-Zer** [WeblateOrg/weblate#5419] opened 2021-02-13 11:11 UTC
**Describe the issue**

If a word is highlighted as a glossary term weblate displays it in the case from the glossary (at least if terms it the glossary are lower-cased)

**To Reproduce the issue**

1. Go to https://hosted.weblate.org/translate/weblate/application/ru/?checksum=d10c4f6a47ff5aba&sort_by=-priority,position
2. Scroll down to 'Source string'
3. See that it displays as `string prefix`, when it should be `String prefix`

**Expected behavior**

The case should be kept as-is

**Screenshots**

![scr28](https://user-images.githubusercontent.com/1060057/107841197-e0a9a380-6dc9-11eb-99b2-2f29dd9035ca.png)
![scr30](https://user-images.githubusercontent.com/1060057/107848569-7878b300-6e05-11eb-83a7-aca724e39d1f.png)

**Server configuration and status**

Weblate installation: weblate.org service

**Comment by nijel** [comment] 2021-02-13 11:55
Duplicate of #5408

**Comment by nijel** [comment] 2021-02-13 11:56
It's already fixed for some time, did you load the page earlier than opening this issue? Anyway it now looks correct.

**Closed by nijel** 2021-02-13 11:55 UTC
Labels: bug, duplicate

**Comment by Fat-Zer** [comment] 2021-02-13 19:13
yep, sorry.... I've felled in the bug 12 hours earlier but forgot to press "send"...
