### ISSUE TITLE
add labels as a further **Search filter** for automatic translations

### ISSUE THREAD

**Issue by JohnRDOrazio** [WeblateOrg/weblate#12027] opened 2024-07-07 22:53 UTC
### Describe the problem

In one of my projects, I have labeled translation strings such that some (UI strings, error message strings) can be machine translated, whereas others must be translated by a human based on given existing resources. However, the current UI for the automatic translation feature only allows to filter by a few options

### Describe the solution you would like

It would be nice to have a second `label` filter, allowing to restrict which of the resulting strings from the previous filter should be machine translated. For example: **Search filter: Untranslated strings || Label filter: machine translatable**.

This would have to be a second filter, not mutually exclusive with the first (i.e. they shouldn't be in the same dropdown, you shouldn't have to choose between **Untranslated strings** and **Label: machine translatable**).

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/231298/afdb911f-8c75-4b7b-86bb-0ada68e95070)

**Comment by nijel** [comment] 2024-07-08 06:16
Duplicate of #4107

**Closed by nijel** 2024-07-08 06:16 UTC
Labels: enhancement, duplicate
