### ISSUE TITLE
Add an REST API endpoint that removes a monolingual unit

### ISSUE THREAD

**Issue by superDross** [WeblateOrg/weblate#4376] opened 2020-08-24 15:50 UTC
**Is your feature request related to a problem? Please describe.**
I would like to be able to remove a monolingual unit from a monolingual base file.

**Describe the solution you'd like**
DELETE request available at `/api/units/(int: id)/`

**Comment by nijel** [comment] 2020-08-24 18:17
Duplicate of #1974

**Closed by nijel** 2020-08-24 18:17 UTC
Labels: duplicate
