### ISSUE TITLE
Suggest to use accurate date / time stamp for history entry

### ISSUE THREAD

**Issue by mksie** [WeblateOrg/weblate#7240] opened 2022-02-11 14:49 UTC
### Describe the issue

Suggest to use accurate time stamp for history entry.
[Weblate 4.10.1]

Situation: Translation takes place as an iterative process, often leading to several changes within an hour, a day, or several days.

Issue: The used pattern for the history log is not useful if several changes happen in short time. Exact time stamp info only available with a 'mouse over'.
Example:
![image](https://user-images.githubusercontent.com/49721307/153610305-fd94b7bd-9c83-4212-afaf-45d86cb3c911.png)

Suggestion:
Display a proper date / time format for example as used as mouse over information already.
An accurate date/time stamp would allow easier and faster identification of changes and improvements done, not only for several changes in short time, but also in longer period (e.g. '2021-05-xx' has much better usability than '9 months ago', due to better matching with project timelines or whatever. Projects and business is mainly fixed date oriented).

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Expected behavior

Display a proper date / time format not only as 'mouse over' information but also in the static history entry list.

![image](https://user-images.githubusercontent.com/49721307/153612358-4bf51ed4-1cc9-47ec-9174-482132222ec0.png)

### How do you run Weblate?

Docker container

### Weblate versions

[Weblate 4.10.1]

**Comment by nijel** [comment] 2022-02-22 07:09
Duplicate of #2639

**Closed** 2022-02-22 07:10 UTC
Labels: enhancement, duplicate
