### ISSUE TITLE
msgmerge addon not triggered

### ISSUE THREAD

**Issue by ReneBoehm** [WeblateOrg/weblate#2561] opened 2019-02-18 14:00 UTC
**Describe the bug**
Maybe this is related to #2522 but even after patching api.py to work for our scenario (see #2560) the msgmerge addon gets not triggered.

**To Reproduce**
0. Run Weblate wih DEBUG mode
1. Configure a project + component and activate msgmerge addon
2. Configure a push webhook in gitlab
3. Trigger the push by changing the POT source file in git.
4. See Weblate log
5. You don't see anything related to the "upcoming" change and the msgmerge addon

**Expected behavior**
The msgmerge addon gets triggered and merges the new strings.

**Screenshots**
If needed

**Server configuration and status**
I'm using the current docker image.
```
 * Weblate 3.4
 * Python 3.6.7
 * Django 2.1.7
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * translation-finder 1.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.17.1
 * Pillow 5.1.0
 * python-dateutil 2.8.0
 * lxml 4.2.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.1
 * user-agents 1.1.0
 * jellyfish 0.7.1
 * diff-match-patch 20121119
 * pytz 2018.9
 * pyuca 1.2
 * PyYAML 3.12
 * tesserocr 2.4.0
 * Mercurial 4.5.3
 * git-svn 2.17.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 3.16.0-4-amd64 (x86_64)
```

**Additional context**
Here is the relevant log output:
```
INFO received GitLab notification on repository http://.../test/backend/app, branch initial-locale, 1 matching components, 1 to process
INFO GitLab notification will update test/Backend App
[2019-02-18 13:36:23,784: INFO/MainProcess] Received task: weblate.trans.tasks.perform_update[7af834a1-94f6-4658-969e-1bbcd4479934]  
172.30.0.1 - - [18/Feb/2019:13:36:23 +0000] "POST /hooks/gitlab/ HTTP/1.1" 200 71 "-" "-"
[pid: 188|app: 0|req: 2/18] 172.30.0.1 () {42 vars in 683 bytes} [Mon Feb 18 13:36:23 2019] POST /hooks/gitlab/ => generated 71 bytes in 115 msecs (HTTP/1.1 200) 8 headers in 355 bytes (1 switches on core 0)
[2019-02-18 13:36:23,802: INFO/ForkPoolWorker-2] Lock 139634425583712 acquired on /app/data/vcs/test/backend-app.lock
INFO test/backend-app: updating repository
[2019-02-18 13:36:23,802: INFO/ForkPoolWorker-2] test/backend-app: updating repository
[2019-02-18 13:36:23,802: INFO/ForkPoolWorker-2] Lock 139634425583712 acquired on /app/data/vcs/test/backend-app.lock
INFO test/backend-app: update took 0.60 seconds
[2019-02-18 13:36:24,410: INFO/ForkPoolWorker-2] test/backend-app: update took 0.60 seconds
[2019-02-18 13:36:24,518: INFO/ForkPoolWorker-2] Lock 139634425583712 acquired on /app/data/vcs/test/backend-app.lock
INFO test/backend-app: rebase remote into repo
[2019-02-18 13:36:24,731: INFO/ForkPoolWorker-2] test/backend-app: rebase remote into repo
[2019-02-18 13:36:24,986: INFO/ForkPoolWorker-2] Lock 139634425583712 acquired on /app/data/vcs/test/backend-app.lock
[2019-02-18 13:36:24,986: INFO/ForkPoolWorker-2] Lock 139634425583712 acquired on /app/data/vcs/test/backend-app.lock
[2019-02-18 13:36:25,025: INFO/ForkPoolWorker-2] Lock 139634425583712 released on /app/data/vcs/test/backend-app.lock
INFO test/backend-app: checking locale/de.po (de) [1/2]
[2019-02-18 13:36:25,026: INFO/ForkPoolWorker-2] test/backend-app: checking locale/de.po (de) [1/2]
INFO test/backend-app: checking locale/en.po (en) [2/2]
[2019-02-18 13:36:25,038: INFO/ForkPoolWorker-2] test/backend-app: checking locale/en.po (en) [2/2]
INFO test/backend-app: running batch check: inconsistent
[2019-02-18 13:36:25,054: INFO/ForkPoolWorker-2] test/backend-app: running batch check: inconsistent
INFO test/backend-app: updating completed
[2019-02-18 13:36:25,152: INFO/ForkPoolWorker-2] test/backend-app: updating completed
```

**Comment by nijel** [comment] 2019-02-18 14:46
Most likely this is same issue as https://github.com/WeblateOrg/weblate/issues/2522. The root cause is that we were mistakenly not looking at process exit codes, so failing msgmerge went not noticed. This was addressed in several commits linked from that issue.

**Comment by ReneBoehm** [comment] 2019-02-18 14:53
That sound's great. Do you have any code snippets to patch a docker image ? ;)

**Comment by nijel** [comment] 2019-02-19 11:29
You can try applying patches referenced there, though I'm not sure it will work without problems, there were probably other changes in the codebase as well. Anyway I'm not going to put effort into that as  [next release](https://github.com/WeblateOrg/weblate/milestone/38) should happen next week.

**Comment by ReneBoehm** [comment] 2019-02-19 12:16
That's fine. I also don't want to make the system unstable, even it's a test installation right now. I'll wait for the release. :+1:

**Closed** 2019-04-11 14:44 UTC
Labels: question, wontfix
