### ISSUE TITLE
suggestions not seen in zen mode

### ISSUE THREAD

**Issue by mfrasca** [WeblateOrg/weblate#849] opened 2015-09-13 12:36 UTC
it would be nice to be able to accept (and edit) a suggestion when in zen mode.
in particular useful when reviewing whole bulks of suggestions.

a compact, zen-friendly, possibility?
you could have a `pop suggestion` button, with as tooltip the suggestion itself.
so you can review the suggestion in the tooltip.
activating the button would destroy the suggestion and put it into the current edit field.
ctrl-click could just destroy the suggestion without putting it in the edit field.
##

**Comment by nijel** [comment] 2019-12-16 12:34
Duplicate of #671

**Closed by nijel** 2019-12-16 12:34 UTC
Labels: enhancement, duplicate
