### ISSUE TITLE
Desinstalar

### ISSUE THREAD

**Issue by GustavoGirardelli** [WeblateOrg/weblate#8218] opened 2022-10-15 16:46 UTC
### Describe the issue

Hola:
Como desinstalo todo lo que instalé desde [aquí](https://docs.weblate.org/es/latest/admin/install/venv-debian.html) ya que nada funciona ni sé como debería funcionar.

Muchas gracias

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### Expected behavior

Que me indicaran como desinstalar lo ya instalado.

### Screenshots

.

### Exception traceback

```pytb
.
```

### How do you run Weblate?

Other

### Weblate versions

`?@?:~$ list_versions 

list_versions: orden no encontrada

?@?:~$ weblate list_versions

weblate: orden no encontrada

?@?:~$ ./manage.py list_versions

bash: ./manage.py: No existe el archivo o el directorio`

### Weblate deploy checks

```shell
~$ weblate check --deploy
weblate: orden no encontrada
```

### Additional context

.

**Comment by GustavoGirardelli** [comment] 2022-10-15 16:56
They still don't help me
Aún no me ayudan

I sent it to support
Yo lo mandé a soporte

**Comment by comradekingu** [comment] 2022-10-15 20:57
@GustavoGirardelli This isn't a support forum.
https://weblate.org/support/

**Comment by nijel** [comment] 2022-10-17 09:25
Duplicate of #8219

**Closed by nijel** 2022-10-17 09:25 UTC
Labels: question, wontfix
