### ISSUE TITLE
OpenShift image build should not be adding database details to image.

### ISSUE THREAD

**Issue by GrahamDumpleton** [WeblateOrg/weblate#2875] opened 2019-07-11 00:49 UTC
Seems to have been added by @alesrosina and don't know reason why, but database credentials shouldn't be added to the container image built by the ``BuildConfig`` in OpenShift. Eg.

https://github.com/WeblateOrg/weblate/blob/master/openshift3/persistent-postgresql.json#L173

They should only be set in the ``DeploymentConfig``.

The problem with having added them in the build is that they are persistent in the image. If for some reason the image were pulled down and redistributed, the credentials, including password, would go with it and so you could share it with someone you shouldn't.

If there is some build step which is somehow dependent on the database being available, then that is wrong and needs to change in some way. You don't want a build step trying to talk to your database.

**Comment by alesrosina** [comment] 2019-07-11 08:35
@GrahamDumpleton the problem is, that inside build script, there is a line:

```sh
python manage.py collectstatic --noinput
``` 
And this line somehow require database connection. Without those it triggeres:

```
ERROR Handled exception: ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.7.17).
```

I agree, this is not a nice solution, so we should solve the underlying problem.


@nijel is there any way of disabling requirement for database when running this command? Even sql lite should not be required, since (as far as I understand) this command is not doing anything with databse. Or even better - is this command even required for Weblate to work?

**Comment by nijel** [comment] 2019-07-11 11:37
This is probably caused by Django checks, not sure how to disable them on invocation.

**Comment by nijel** [comment] 2019-07-11 11:50
Maybe better approach is to have configuration not using sqlite at that point.

**Comment by GrahamDumpleton** [comment] 2019-07-11 11:53
For SQLite issue, suggest setting default for `PYTHON_VERSION` to be 3.6. It is possibly the older Python 3.5 which is the issue.

**Comment by alesrosina** [comment] 2019-07-11 11:57
I've tested this on python 3.6 also, same error occurs.

**Comment by nijel** [comment] 2019-07-11 12:08
I don't think it's anyhow useful to provide sqlite based setup, so how about changing the default config this way:

```patch
--- a/weblate/settings_openshift.py
+++ b/weblate/settings_openshift.py
@@ -29,8 +29,8 @@ DEBUG = False
 DATABASES = {
     'default': {
-        'ENGINE': 'django.db.backends.sqlite3',
-        'NAME': os.path.join(os.environ['OPENSHIFT_DATA_DIR'], 'weblate.db'),
+        'ENGINE': 'django.db.backends.postgresql',
+        'NAME': os.environ['OPENSHIFT_APP_NAME'],
         'ATOMIC_REQUESTS': True,
     }
 }
```

**Comment by GrahamDumpleton** [comment] 2019-07-11 12:09
So the issue is likely that Python versions supplied in Software Collections Library (SCL) are just too old to use with latest Django if it thinks SQLite is being used. As per suggestion that just came in while writing this, somehow have the database section of config, or at least the SQLite fallback, disabled when running `collectstatic`.

**Comment by nijel** [comment] 2019-07-11 12:36
As for database selection, it's likely that Weblate will support only PostgreSQL in future (see https://github.com/WeblateOrg/weblate/issues/2825), so if that can make some things easier, just ditch this and support PostgreSQL only (similarly like we do in the Docker container).

**Comment by alesrosina** [comment] 2019-07-11 12:40
If that is a plan, I would ditch mysql & sqllite implementation.

I could also test out your suggestion (today I'm busy with some other things, so I'll try it out tomorrow) for default DB. It sounds like it could work.

**Comment by nijel** [comment] 2019-07-11 12:45
It's not yet decided, but it's likely. The current external fulltext engine has several problems and replacing it by the one built in PostgreSQL seems like a good idea. It would definitely make lot of things easier to rely only on the database here.

**Comment by alesrosina** [comment] 2019-11-04 17:18
@nijel I think this issue could be closed, since we removed this and is now using docker image on openshift.

**Comment by nijel** [comment] 2019-11-04 18:38
Okay, closing.

**Closed by nijel** 2019-11-04 18:38 UTC
Labels: bug, help wanted
