### ISSUE TITLE
Bitbucket webhooks not working

### ISSUE THREAD

**Issue by nechudav** [WeblateOrg/weblate#2029] opened 2018-05-22 07:52 UTC
I have weblate hosted on my own server and I tried to synchronize weblate with bitbucket using hooks, but when I try to connect with bitbucket I get an error.

### Steps to reproduce
1. Put url of my weblate hosting server to Bitbucket (with /hooks/bitbucket/ behind url)
2. Press Test Connection
3. Bitbucket gets an error "Could not parse JSON payload"

### Expected behaviour
Establish a successful connection between bitbucket and weblate

**Comment by nijel** [comment] 2018-05-22 08:19
Probably the test payload doesn't include all information which is present in the real payload. Can you try if the actual hooks work? 

Anyway having the test payload would help to diagnose this issue...

**Comment by nijel** [comment] 2018-05-31 09:22
I've just tested this and it works fine for both Mercurial and Git repos, so more information how to trigger this is certainly needed. Please visit the Webhooks settings in Bitbucket, click on Weblate hook, View requests and then post here body for the failed request.

**Comment by dsnoeck** [comment] 2018-06-20 07:11
Same as #1958

**Comment by nijel** [comment] 2018-08-26 08:54
Duplicate of #1958

**Closed by nijel** 2018-08-26 08:54 UTC
Labels: bug
