### ISSUE TITLE
Status widgets for components

### ISSUE THREAD

**Issue by sikmir** [WeblateOrg/weblate#1541] opened 2017-07-04 09:56 UTC
For now status widgets are available only for whole project. But if more than one component in the project, it's getting a bit inconvenient. So it would be great to have separate widgets for components within project.

**Comment by nijel** [comment] 2017-07-19 12:44
Duplicate of #558

**Closed by nijel** 2017-07-19 12:44 UTC
Labels: enhancement

**Comment by nijel** [comment] 2017-08-15 11:14
Thank you for your report, the issue you have reported has just been fixed (see #558). 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
