### ISSUE TITLE
Please add `lacks the keyboard accelerator mark '_'` option in `Strings status` to find `fatal errors`

### ISSUE THREAD

**Issue by ovari** [WeblateOrg/weblate#8174] opened 2022-10-01 04:27 UTC
### Describe the problem

Please add `lacks the keyboard accelerator mark '_'` option in Weblate `Strings status`
* https://github.com/Gnucash/gnucash/pull/1440#issuecomment-1263843243
* https://github.com/Gnucash/gnucash/pull/1441#issuecomment-1263843485

### Describe the solution you'd like

Please add `lacks the keyboard accelerator mark '_'` option in Weblate `Strings status`

### Describe alternatives you've considered

> Weblate is still missing this test. Perhaps easiest is to compare them in
https://hosted.weblate.org/browse/gnucash/gnucash/hu/?offset=1&q=_&sort_by=source&checksum=
If the right side is missing `_`, fix it.

https://github.com/Gnucash/gnucash/pull/1440#issuecomment-1263843243

### Additional context

What do you think?

Thank you

**Comment by Geeyun-JY3** [comment] 2022-10-01 05:26
Duplicate of #5962

**Closed** 2022-10-05 12:22 UTC
Labels: duplicate
