### ISSUE TITLE
Project/Component creation via REST API now shows an Error message in the web interface

### ISSUE THREAD

**Issue by luebbe** [WeblateOrg/weblate#12600] opened 2024-09-26 08:57 UTC
### Describe the issue

We are using a command line application to create/update/delete weblate projects and components via the rest api. The client uploads a zip file and sets the file masks for po/pot files. 
This combination has been working flawlessly for several years up to and including Weblate 5.6.2. 

Since we upgraded Weblate to 5.7.2 (directly from 5.6.2), the project/component creation via the rest api still works. Weblate returns a "201 - created" and the project with its components and all languages shows up in the web ui. Nothing seems to be missing.
But the web UI shows a red warning icon for each component and inside the component for each language which leads to the following message:

### Project view 
![grafik](https://github.com/user-attachments/assets/4840f736-f8c9-4888-bf22-27a09888c60e)
### Component view
![grafik](https://github.com/user-attachments/assets/67826477-977a-4a5b-9bdb-e7ed00a40657)
### Warning for the component "User Interface"
![grafik](https://github.com/user-attachments/assets/19eee5a5-26af-44cc-a262-ec9c7bd9063a)

It says "no matching file mask", but this file mask was correct for the past years. Weblate has also obviously found all languages inside the .zip file. Otherwise the overview of the "User Interface" component wouldn't show any languages or their translation status.

I have searched the issues mentioned in the 5.7.* changelogs for "component", "path" and "mask" and found nothing that hinted at changes in this area.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Create a project with its components from a .zip file using the rest api

### Expected behavior

Project component creation without the "no matching file mask" error.

### How do you run Weblate?

Docker container

### Weblate versions

I have no access to the docker installation, but we upgraded from 5.6.2 to 5.7.2 about two weeks ago. If needed, I can ask for the information and append it here.

**Comment by nijel** [comment] 2024-09-26 09:13
In case the alert disappears on its own, this is already fixed by 3b91257282b5c1560795dd8d7baf056a217b8e74.

There might also be an issue with using backslash `\` instead of forward slash `/` in the mask (I'm surprised that it works at all).

**Comment by luebbe** [comment] 2024-09-26 11:54
Thanks for your reply. The backslash has always worked for us. I thought that maybe there were now stricter checks on using backslash instead of forward slash and was about to test it with forward slashes instead.

**Comment by nijel** [comment] 2024-09-26 11:59
As far as I know, there is no change in that. But such thing can change unintentionally, as this is not something we would be testing or claiming to work.

**Comment by luebbe** [comment] 2024-09-27 07:18
As you have predicted, the warning has disappeared over night. So we just wait until the next relase which will make the warning disappear quicker. Thank you.

**Comment by nijel** [comment] 2024-09-27 11:37
It will make it disappear directly upon parsing translations. The issue is that the component is initially created blank, what triggers the alert until the translations are parsed.

**Closed by nijel** 2024-09-27 11:37 UTC
Labels: bug
