### ISSUE TITLE
PostgreSQL hangs when creating a translation for a new language

### ISSUE THREAD

**Issue by SlavekB** [WeblateOrg/weblate#3664] opened 2020-04-03 11:10 UTC
**Describe the bug**
Every time a translation for a new language is created by Weblate UI, a PO file for new language is loaded or a new translation component is added, PostgreSQL reports a constrains duplicity error and hangs a process that consumes 100% of one CPU core. Such stuck processes remain active and consuming CPUs until they are manually killed.

**To Reproduce**
Steps to reproduce – variant A:
1. Go to the component for which you want to add a new language.
2. Click on Start new translation
3. Select the language and click Start new translation
4. You'll see it gets stuck because it's waiting for the stuck SQL query to complete

Note: A new translation is created, committed and pushed to the GIT server. The stuck occurs as a result of loading a new PO file into Weblate.

Steps to reproduce – variant B:
1. From CLI enter a management command `loadpo` for the component that has just added a new translation that has not been loaded into Weblate.
2. The command ends properly, however the celery job ends stuck waiting for the stuck SQL query to complete.

Note: The new translation is loaded into Weblate and users can start working on it.

Steps to reproduce – variant C:
1. From CLI enter a management command `import_json` to create a new component.
2. The command ends properly, however the celery job ends stuck waiting for the stuck SQL query to complete.

Note: The new component is created, new translations are loaded into Weblate and users can start working on it.

**Expected behavior**
The expected behavior is that everything will work properly and there will be no need for constant monitoring of PostgreSQL server status and manual execution of commands to load new translations created by users in the UI.

**Server configuration and status**
```
 * Weblate: 3.11.3
 * Django: 2.2.9
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.4.0
 * lxml: 4.4.2
 * Pillow: 6.2.1
 * bleach: 3.1.1
 * six: 1.13.0
 * python-dateutil: 2.8.1
 * social-auth-core: 3.2.0
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.8.1
 * oauthlib: 3.1.0
 * django-compressor: 2.3
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.3
 * user-agents: 2.0
 * filelock: 3.0.12
 * setuptools: 42.0.2
 * jellyfish: 0.7.2
 * openpyxl: 2.6.4
 * celery: 4.3.0
 * kombu: 4.6.7
 * celery-batches: 0.2
 * translation-finder: 1.8
 * html2text: 2019.9.26
 * pycairo: 1.18.2
 * pygobject: 3.34.0
 * diff-match-patch: 20181111
 * requests: 2.22.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.13.5
 * Cython: 0.29.14
 * misaka: 2.1.1
 * GitPython: 3.0.5
 * borgbackup: 1.1.10
 * Python: 3.5.3
 * Git: 2.11.0
 * psycopg2: 2.8.4
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.5
 * aeidon: 1.6.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django_sendmail_backend.backends.EmailBackend: localhost
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 3.16.6-042stab141.42 (x86_64)
```
```
System check identified no issues (3 silenced).
```

**Comment by nijel** [comment] 2020-04-03 11:37
Looking at the logs you've sent me privately, it seems that there are a lot of failing checks triggered on the addition. I've recently fixed some issues in related code (bdd28140de20fa9ece6ef5bcc3121f89bae1bfb0, 587df4ab534fe79407a3f16ff55beddaa9065ae5), but I'm not sure they will address it for you.

How big is the project where you are adding this translation? Do you use linked components a lot?

**Comment by SlavekB** [comment] 2020-04-03 12:53
There is also a problem when adding a translation to a component that is the only one without the linked ones.

In any case, yes, linked components are used to a high degree. A huge number of linked components are created for one tde-i18n main git repository. For smaller applications, there is usually one catalog for messages, so one component. However, we are now adding translations also for desktop style files, so virtually every small application will have at least one linked component.

I'll try to backport the patches you mentioned. Let's see if the situation changes.

**Comment by nijel** [comment] 2020-04-03 12:59
Just to clarify, is this about https://mirror.git.trinitydesktop.org/weblate/projects/applications/?

I think it has something to do with amount of components in the project...

**Comment by SlavekB** [comment] 2020-04-03 13:13
Yes, hovewer, it's not just about applications, but about all other projects.

In `applications`, individual components are mostly like single git repository == without linked components. However, you can see, for example, dolphin, which already has two linked components for desktop style files in the same git repository.

Other projects like `tdelibs`, `tdebase`, `tde...` are exclusively linked components. Here is a huge number of linked components over one git repository.

**Comment by SlavekB** [comment] 2020-04-03 13:18
Regarding the number of components – it should be noted that previously there was no problem. I'm not sure if problems with adding new translations have started to show up with 3.11.x. When it was above MySQL, it caused a python crash and sending crash reports. When it is above PostgreSQL, it causes database hangs and requires manual killing.

With MySQL I initially did not know if it was any random problem. However, after migration to PostgreSQL, it escalated because it obviously hangs in 100% of cases and requires manual intervention.

**Comment by nijel** [comment] 2020-04-03 14:05
I think the problem is in batch checks run and flags updates. Some of them are done project-wide leading to massive selects and possibly updates, which is quite likely to cause some locking issues. Ironically most of these are no longer useful, but the code is still there and needs to be revisited and cleaned up.

**Comment by SlavekB** [comment] 2020-04-04 17:46
FYI, I have now backported only bdd2814 because 587df4a expects `unitdata.py` which is not present in 3.11.3.

**Comment by SlavekB** [comment] 2020-04-04 23:39
Note: There was no visible change with commit bdd2814.

**Comment by nijel** [comment] 2020-04-08 12:09
This should be addressed by https://github.com/WeblateOrg/weblate/pull/3695. I don't think it's reasonable to attempt to backport these changes.

**Closed** 2020-04-09 07:50 UTC
Labels: bug
